/**
 * Significados Curados — Pilar 5b · I Ching (F-219, F-220) · Hexagramas 33-64
 *
 * Sequência King Wen (Wilhelm/Baynes 1950). Cada hexagrama: nome canônico
 * PT-BR + 1 linha de essência. Profundidade completa (todas as linhas,
 * mutação) virá em F-220.
 *
 * Fontes (axioma 4 VISION §3):
 * - Wilhelm/Baynes, *The I Ching or Book of Changes* (1950).
 *
 * Princípios editoriais:
 * - PT-BR primeiro (Axioma 8).
 * - Cada `essencia` ≤22 palavras. Cada `pratica` 1 linha de UI.
 * - Citação obrigatória (Axioma 4).
 */
import type { SignificadoCurado } from './significados-curados';

export const PILAR_5_HEXAGRAMAS_33_64: SignificadoCurado[] = [
  {
    id: 33,
    pilar: 'iching',
    titulo: '33. A Retirada (Dun)',
    essencia: 'Recuo estratégico, preservação. A montanha sobre o céu.',
    missao: 'Recue quando preciso. Não é covardia — é sabedoria.',
    sombra: 'Fuga, isolamento, recuo prematuro.',
    pratica: 'Diga 1 "não" sagrado hoje. Saia de 1 ambiente que te esvazia.',
    conexao: 'Hexagrama 33 (P5) com Otua (P4) e Buscador (P1·7).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 34,
    pilar: 'iching',
    titulo: '34. O Poder do Grande (Da Zhuang)',
    essencia: 'Força em ascensão. O trovão que cresce. Energia bruta.',
    missao: 'Use a força com discernimento. Poder sem ética é violência.',
    sombra: 'Força bruta, autoritarismo, potência sem propósito.',
    pratica: 'Hoje, use 1 força sua (física, emocional, mental) com cuidado explícito.',
    conexao: 'Hexagrama 34 (P5) com Colérico (P3) e Áries (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 35,
    pilar: 'iching',
    titulo: '35. O Progresso (Jin)',
    essencia: 'Avanço, sol sobre a terra. Visibilidade e reconhecimento.',
    missao: 'Avance. Seja visto(a). O progresso pede presença pública.',
    sombra: 'Vaidade, exposição sem preparo, sucesso precoce.',
    pratica: 'Mostre 1 trabalho seu. Publique, compartilhe, apresente.',
    conexao: 'Hexagrama 35 (P5) com Corpo Radiante (P3·10) e Realizador (P1·8).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 36,
    pilar: 'iching',
    titulo: '36. O Escurecimento da Luz (Ming Yi)',
    essencia: 'Luz ferida. Perseguição do brilho. Tempo de proteção.',
    missao: 'Proteja a luz. Não brilhe onde será apagado(a). Recue.',
    sombra: 'Iluminação forçada, vitimismo luminoso.',
    pratica: 'Esconda 1 brilho seu hoje. Não precisa ser visto(a) o tempo todo.',
    conexao: 'Hexagrama 36 (P5) com Oyeku (P4) e Mente Negativa (P3·2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 37,
    pilar: 'iching',
    titulo: '37. A Família (Jia Ren)',
    essencia: 'Clareza nos papéis, lar, sustento. Estrutura íntima.',
    missao: 'Cuide do lar. Defina papéis com amor e clareza.',
    sombra: 'Disfunção familiar, papéis invertidos, sufocamento.',
    pratica: 'Faça 1 gesto doméstico hoje. Cozinhar, arrumar, ouvir. Em casa.',
    conexao: 'Hexagrama 37 (P5) com Câncer (P2) e Guardião (P1·6).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 38,
    pilar: 'iching',
    titulo: '38. A Oposição (Kui)',
    essencia: 'Divergência, polaridades. Dois olhares, mesmo céu.',
    missao: 'Honre o diferente. A oposição não é inimiga — é complementar.',
    sombra: 'Ruptura, polarização, conflito sem síntese.',
    pratica: 'Converse 5 min com quem pensa diferente de você. Escute o que puder.',
    conexao: 'Hexagrama 38 (P5) com Hexagrama 39 (P5) — par de opostos.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 39,
    pilar: 'iching',
    titulo: '39. O Obstáculo (Jian)',
    essencia: 'Dificuldade, água na montanha. Voltar para avançar.',
    missao: 'Contorne quando possível, atravesse quando inevitável.',
    sombra: 'Paralisia, vitimismo, regressão crônica.',
    pratica: 'Identifique 1 obstáculo seu. Pergunte: posso contornar? Devo atravessar?',
    conexao: 'Hexagrama 39 (P5) com Hexagrama 38 (P5) — solução por via complementar.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 40,
    pilar: 'iching',
    titulo: '40. A Libertação (Jie)',
    essencia: 'Desatar, absolvição. Tempo de solução. Fardo aliviado.',
    missao: 'Liberte. Solte. Volte ao caminho. O perdão começa em você.',
    sombra: 'Voltar à culpa, autoinfligir, não merecer.',
    pratica: 'Perdoe 1 pessoa ou a si mesmo(a) por 1 coisa específica. Em voz alta.',
    conexao: 'Hexagrama 40 (P5) com Ika (P4) e Libertador (P1·5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 41,
    pilar: 'iching',
    titulo: '41. A Diminuição (Sun)',
    essencia: 'Encolhimento, oferta. Diminuir para aumentar.',
    missao: 'Reduza. O que parece perda pode ser preparo.',
    sombra: 'Autodiminuição excessiva, perda sem sentido.',
    pratica: 'Corte 1 gasto ou hábito hoje. Sinta o espaço que abre.',
    conexao: 'Hexagrama 41 (P5) com Hexagrama 42 (P5) — par de opostos.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 42,
    pilar: 'iching',
    titulo: '42. O Aumento (Yi)',
    essencia: 'Crescimento, acréscimo. Tempo de expandir.',
    missao: 'Expanda. Aproveite o tempo de favor. Mas sem arrogância.',
    sombra: 'Crescimento sem raiz, expansão sem lastro.',
    pratica: 'Invista em 1 área sua de crescimento hoje. Tempo, dinheiro, atenção.',
    conexao: 'Hexagrama 42 (P5) com Realizador (P1·8) e Irosu (P4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 43,
    pilar: 'iching',
    titulo: '43. A Decisão (Guai)',
    essencia: 'Transbordar, decidir. Tempo de cortar e avançar.',
    missao: 'Decida. Saia do limbo. O aguardo se esgotou.',
    sombra: 'Decisão prematura, cortar sem motivo, impulsividade.',
    pratica: 'Tome 1 decisão importante. Sem hesitação. Confirme o que já sabe.',
    conexao: 'Hexagrama 43 (P5) com Owonrin (P4) e Libertador (P1·5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 44,
    pilar: 'iching',
    titulo: '44. O Encontrar (Gou)',
    essencia: 'Sedução, encontro com o oculto. Risco de ser pego.',
    missao: 'Cuidado com o que seduz. O brilho pode ser armadilha.',
    sombra: 'Ceder à tentação, confusão, encantamento.',
    pratica: 'Hoje, recuse 1 tentação específica. Pequena, mas específica.',
    conexao: 'Hexagrama 44 (P5) com Irete (P4) e Melancólico (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 45,
    pilar: 'iching',
    titulo: '45. A Colheita (Gathering)',
    essencia: 'Reunião, congregação. Suco da oferta. Colheita comunitária.',
    missao: 'Colha. Una. Mas o líder verdadeiro sabe também servir.',
    sombra: 'Centralismo, culto à personalidade, multidão cega.',
    pratica: 'Reúna 1 grupo pequeno para 1 propósito simples. Sem agenda oculta.',
    conexao: 'Hexagrama 45 (P5) com Humanista (P1·9) e Irosu (P4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 46,
    pilar: 'iching',
    titulo: '46. A Subida (Sheng)',
    essencia: 'Crescer, avançar, penetrar. Madeira sobre a terra.',
    missao: 'Suba. Reconheça. Avance sem perder a simplicidade.',
    sombra: 'Ambição desmedida, perder a raiz no caminho.',
    pratica: 'Dê 1 passo de ascensão hoje. Pode ser pequeno, mas consistente.',
    conexao: 'Hexagrama 46 (P5) com Pioneiro (P1·1) e Sagitário (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 47,
    pilar: 'iching',
    titulo: '47. O Esgotamento (Kun)',
    essencia: 'Lago seco, cansaço. Tempo de retiro e silêncio.',
    missao: 'Descanse. A exaustão tem mensagem. O corpo sabe.',
    sombra: 'Negação do limite, trabalhar até quebrar, apatia.',
    pratica: 'Durma 30 min a mais hoje. Permita-se parar.',
    conexao: 'Hexagrama 47 (P5) com Hexagrama 48 (P5) — par de opostos.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 48,
    pilar: 'iching',
    titulo: '48. O Poço (Jing)',
    essencia: 'Água que serve a todos. Fonte perene. O saber ancestral.',
    missao: 'Aprofunde. Sirva. O poço alimenta sem distinção.',
    sombra: 'Esgotamento do poço (recurso interno), serviço sem cuidado.',
    pratica: 'Beba água com presença hoje. Sinta o que cada gole nutre.',
    conexao: 'Hexagrama 48 (P5) com Otua (P4) e Buscador (P1·7).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 49,
    pilar: 'iching',
    titulo: '49. A Revolução (Ge)',
    essencia: 'Mudança radical. Fogo sobre o lago. Tempo de transformação.',
    missao: 'Mude. Não reforme — revolucione. O que serve de novo precisa nascer.',
    sombra: 'Revolução sem propósito, destruição por paixão.',
    pratica: 'Mude 1 hábito hoje. Não ajuste — troque. Outro, completamente outro.',
    conexao: 'Hexagrama 49 (P5) com Escorpião (P2) e Libertador (P1·5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 50,
    pilar: 'iching',
    titulo: '50. O Cachimbo (Ding)',
    essencia: 'Vaso sagrado, alimento espiritual. O que oferece sustento sutil.',
    missao: 'Ofereça. Sustente. A nutrição sutil vem do que você serve.',
    sombra: 'Vazio disfarçado de oferta, ritual sem conteúdo.',
    pratica: 'Ofereça 1 nutrição sutil hoje: música, silêncio, presença.',
    conexao: 'Hexagrama 50 (P5) com Irosu (P4) e Guardião (P1·6).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 51,
    pilar: 'iching',
    titulo: '51. O Trovão (Zhen)',
    essencia: 'O despertar, o choque que acorda. Início impulsivo e fecundo.',
    missao: 'Desperte. Assuste-se com o que precisa assustar. Acorde.',
    sombra: 'Trovão sem conteúdo, choque por choque.',
    pratica: 'Acorde sem o celular. 1 minuto de silêncio antes da tela.',
    conexao: 'Hexagrama 51 (P5) com Pioneiro (P1·1) e Áries (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 52,
    pilar: 'iching',
    titulo: '52. O Quietivo (Gen)',
    essencia: 'Montanha, quietude, parar. O tempo é dentro.',
    missao: 'Pare. Quietude. A montanha não se move para existir.',
    sombra: 'Estagnação, inércia, parar por medo.',
    pratica: 'Sente-se 15 min sem fazer nada. Sem celular, sem agenda, sem música.',
    conexao: 'Hexagrama 52 (P5) com Buscador (P1·7) e Mente Neutra (P3·4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 53,
    pilar: 'iching',
    titulo: '53. O Desenvolvimento Gradual (Jian)',
    essencia: 'Progresso lento, madeira sobre a montanha. O tempo amadurece.',
    missao: 'Avance devagar. A árvore não apressa a floresta.',
    sombra: 'Preguiça, lentidão disfarçada, medo de acelerar.',
    pratica: 'Avance 1% a mais em 1 projeto longo. Sem pressa, mas com constância.',
    conexao: 'Hexagrama 53 (P5) com Construtor (P1·4) e Touro (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 54,
    pilar: 'iching',
    titulo: '54. A Donzela (Gui Mei)',
    essencia: 'Casamento, aliança, presença feminina. O que se move com leveza.',
    missao: 'Alie-se. Busque parcerias com propósito. Mas sem perder a si.',
    sombra: 'Dependência, aliança sem verdade, fusão.',
    pratica: 'Renove 1 aliança ou promessa hoje. Pequena, mas consciente.',
    conexao: 'Hexagrama 54 (P5) com Libra (P2) e Diplomata (P1·2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 55,
    pilar: 'iching',
    titulo: '55. A Abundância (Feng)',
    essencia: 'Plenitude, auge, presença total. Mas efêmero.',
    missao: 'Aproveite. A abundância é passagem — não se agarra.',
    sombra: 'Apogeu que se eterniza, negação do declínio.',
    pratica: 'Reconheça 1 auge seu. Celebre. Mas saiba: passará.',
    conexao: 'Hexagrama 55 (P5) com Hexagrama 56 (P5) — par; Lua Cheia (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 56,
    pilar: 'iching',
    titulo: '56. O Andarilho (Lu)',
    essencia: 'Estrangeiro, passageiro, sem lugar fixo. Perspectiva.',
    missao: 'Não se fixe. A perspectiva vem de não estar totalmente em lugar nenhum.',
    sombra: 'Indisponibilidade, não pertencer como defesa.',
    pratica: 'Ande 1 caminho diferente hoje. Literal ou metaforicamente.',
    conexao: 'Hexagrama 56 (P5) com Sagitário (P2) e Libertador (P1·5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 57,
    pilar: 'iching',
    titulo: '57. O Suave (Xun)',
    essencia: 'Vento, suavidade, penetração. O que entra sem forçar.',
    missao: 'Suavize. A água vence a rocha não por força — por constância.',
    sombra: 'Passividade, indecisão, dissolver-se no ambiente.',
    pratica: 'Resolva 1 conflito com suavidade hoje. Escuta antes da fala.',
    conexao: 'Hexagrama 57 (P5) com Diplomata (P1·2) e Sanguíneo (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 58,
    pilar: 'iching',
    titulo: '58. O Alegre (Dui)',
    essencia: 'Lago, contentamento, troca. A alegria que se compartilha.',
    missao: 'Alegre-se. Compartilhe. A alegria dobra quando dividida.',
    sombra: 'Alegria superficial, contentamento como fuga.',
    pratica: 'Compartilhe 1 alegria genuína hoje. Conte a 1 pessoa, em voz alta.',
    conexao: 'Hexagrama 58 (P5) com Criador (P1·3) e Sanguíneo (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 59,
    pilar: 'iching',
    titulo: '59. A Dispersão (Huan)',
    essencia: 'Dissolução de barreiras. Vento sobre a água. Abrir o sistema.',
    missao: 'Abra. Permeie. O sistema se renova quando se deixa atravessar.',
    sombra: 'Dispersão, fragmentação, perder o centro.',
    pratica: 'Atravesse 1 barreira hoje. Converse com quem você evita.',
    conexao: 'Hexagrama 59 (P5) com Aquário (P2) e Libertador (P1·5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 60,
    pilar: 'iching',
    titulo: '60. A Limitação (Jie)',
    essencia: 'Demarcar, limitar, definir. O que estabelece fronteiras.',
    missao: 'Limite. Sem limite não há forma, não há cuidado, não há foco.',
    sombra: 'Restrição excessiva, contenção sem propósito.',
    pratica: 'Defina 1 limite claro hoje. Mantenha sem negociar.',
    conexao: 'Hexagrama 60 (P5) com Construtor (P1·4) e Capricórnio (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 61,
    pilar: 'iching',
    titulo: '61. A Verdade Interior (Zhong Fu)',
    essencia: 'Confiança no centro. Vento sobre o lago. Verdade silenciosa.',
    missao: 'Confie no centro. A verdade interna se manifesta sem esforço.',
    sombra: 'Ingênuo, confiante demais, ausência de discernimento.',
    pratica: 'Tome 1 decisão pelo centro hoje. Não pela opinião dos outros.',
    conexao: 'Hexagrama 61 (P5) com Iluminador (P1·11) e Hexagrama 10 (P5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 62,
    pilar: 'iching',
    titulo: '62. O Pequeno Excedente (Xiao Guo)',
    essencia: 'Pequeno demais para o peso. Trovão sobre a montanha. Cuidado.',
    missao: 'Atue pequeno. Excesso de ambição esmaga o que é leve.',
    sombra: 'Autodiminuição, medo de expandir.',
    pratica: 'Faça 1 coisa pequena, mas com excelência. Não busque o grande.',
    conexao: 'Hexagrama 62 (P5) com Virgem (P2) e Construtor (P1·4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 63,
    pilar: 'iching',
    titulo: '63. Depois da Conclusão (Ji Ji)',
    essencia: 'Depois da ordem, antes da desordem. Janela curta.',
    missao: 'Aja agora. A ordem estabelecida é passagem. Prepare o próximo ciclo.',
    sombra: 'Preguiça, achar que está tudo pronto, complacência.',
    pratica: 'Identifique 1 conquista sua. Já preparou o próximo passo?',
    conexao: 'Hexagrama 63 (P5) com Hexagrama 64 (P5) — par; Lua Minguante (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 64,
    pilar: 'iching',
    titulo: '64. Antes da Conclusão (Wei Ji)',
    essencia: 'Antes da ordem. Trovão sobre a água. O momento crítico.',
    missao: 'Vigie. Cuidado. Pequena falha agora derruba o que virá.',
    sombra: 'Negligência, crer que tudo está garantido.',
    pratica: 'Revise 1 detalhe importante hoje. A ordem se constrói nos detalhes.',
    conexao: 'Hexagrama 64 (P5) com Hexagrama 63 (P5) — par; Lua Nova (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
];
