/**
 * Significados Curados — Pilar 5a · I Ching (F-219, F-220) · Hexagramas 1-32
 *
 * Sequência King Wen (Wilhelm/Baynes 1950). Cada hexagrama: nome canônico
 * PT-BR + 1 linha de essência. Profundidade completa (todas as linhas,
 * mutação) virá em F-220.
 *
 * Fontes (axioma 4 VISION §3):
 * - Wilhelm/Baynes, *The I Ching or Book of Changes* (1950).
 *
 * Princípios editoriais:
 * - PT-BR primeiro (Axioma 8).
 * - Cada `essencia` ≤22 palavras. Cada `pratica` 1 linha de UI.
 * - Citação obrigatória (Axioma 4).
 */
import type { SignificadoCurado } from './significados-curados';

export const PILAR_5_HEXAGRAMAS_1_32: SignificadoCurado[] = [
  {
    id: 1,
    pilar: 'iching',
    titulo: '1. O Criador (Qian)',
    essencia: 'Pureza, força criadora, céu. Início absoluto. Liderança cósmica.',
    missao: 'Comece com integridade. A força que cria exige verdade.',
    sombra: 'Arrogância, força bruta, criar sem consciência.',
    pratica: 'Hoje, crie algo — uma frase, uma decisão, uma semente. Co-crie com o cosmos.',
    conexao: 'Hexagrama 1 (P5) com Pioneiro (P1·1) e Ogbe (P4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 2,
    pilar: 'iching',
    titulo: '2. O Receptivo (Kun)',
    essencia: 'Terra, acolhimento, devoção. A força que recebe e nutre.',
    missao: 'Receba. Sustente. Seja terra para outros recomeçarem.',
    sombra: 'Subserviência, passividade, dissolução no outro.',
    pratica: 'Acolha 1 pessoa ou ideia hoje sem corrigir, ensinar ou ajustar.',
    conexao: 'Hexagrama 2 (P5) com Guardião (P1·6) e Câncer (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 3,
    pilar: 'iching',
    titulo: '3. A Dificuldade Inicial (Zhun)',
    essencia: 'Início difícil, germinação. Força antes da forma.',
    missao: 'Persevere no começo. O caos inicial é solo fértil.',
    sombra: 'Confusão paralisante, desistência cedo demais.',
    pratica: 'Identifique 1 projeto em dificuldade inicial. Dê 1 passo, mesmo mínimo.',
    conexao: 'Hexagrama 3 (P5) com Pioneiro (P1·1) e Mente Negativa (P3·2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 4,
    pilar: 'iching',
    titulo: '4. A Insensatez Juvenil (Meng)',
    essencia: 'Aprendizado, inocência, discípulo. Porta de entrada do saber.',
    missao: 'Aprenda algo novo. Volte à postura de aluno. Humildade.',
    sombra: 'Ignorância confortável, recusa de mestre.',
    pratica: 'Peça ajuda 1 vez hoje. Aceite não saber.',
    conexao: 'Hexagrama 4 (P5) com Buscador (P1·7) e Mente Positiva (P3·3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 5,
    pilar: 'iching',
    titulo: '5. A Esperança (Xu)',
    essencia: 'Nutrição paciente, água que espera. Preparação serena.',
    missao: 'Espere o momento. Forçar é desperdiçar. Confie no tempo.',
    sombra: 'Inércia, passividade disfarçada de paciência.',
    pratica: 'Espere 24h antes de decidir algo. Só então decida.',
    conexao: 'Hexagrama 5 (P5) com Mente Neutra (P3·4) e Capricórnio (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 6,
    pilar: 'iching',
    titulo: '6. O Conflito (Song)',
    essencia: 'Disputa, tensão entre opostos. Aprender a conviver com o diferente.',
    missao: 'Confronte com justiça. Não fuja do conflito necessário.',
    sombra: 'Litígio, conflito por ego, guerra sem propósito.',
    pratica: 'Tenha 1 conversa difícil que você vem evitando. Com respeito, mas tenha.',
    conexao: 'Hexagrama 6 (P5) com Okanran (P4) e Colérico (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 7,
    pilar: 'iching',
    titulo: '7. O Exército (Shi)',
    essencia: 'Disciplina coletiva, ordem, comando. Força organizada.',
    missao: 'Organize. Estruture. Lidere com clareza de papéis.',
    sombra: 'Autoritarismo, militarismo, obediência cega.',
    pratica: 'Organize 1 espaço hoje. Mesa, agenda, projeto. Estrutura liberta.',
    conexao: 'Hexagrama 7 (P5) com Construtor (P1·4) e Obará (P4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 8,
    pilar: 'iching',
    titulo: '8. A Solidão (Bi)',
    essencia: 'União verdadeira exige individuação. Unir-se sem perder-se.',
    missao: 'Verifique: estou me unindo ou me dissolvendo?',
    sombra: 'Fusão, dependência, perder-se no coletivo.',
    pratica: 'Passe 1 hora sozinho(a) hoje. Só você consigo mesmo(a).',
    conexao: 'Hexagrama 8 (P5) com Diplomata (P1·2) e Mente Neutra (P3·4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 9,
    pilar: 'iching',
    titulo: '9. A Força Domesticadora (Xiao Chu)',
    essencia: 'Pequeno domínio, modéstia, freios. Suavidade que governa.',
    missao: 'Use força pequena, em momento certo. Vencem os flexíveis.',
    sombra: 'Timidez, autossabotagem, medo de crescer.',
    pratica: 'Avance 1 passo maior do que se sente pronto(a). Verifique o resultado.',
    conexao: 'Hexagrama 9 (P5) com Diplomata (P1·2) e Libra (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 10,
    pilar: 'iching',
    titulo: '10. O Passo do Javali (Lu)',
    essencia: 'Cuidado com a pose. Atitude superficial é risco real.',
    missao: 'Vá além da aparência. Aja com substância, não com forma.',
    sombra: 'Hipocrisia, performance, viver de imagem.',
    pratica: 'Pergunte-se: estou vivendo isso de verdade ou apenas parecendo?',
    conexao: 'Hexagrama 10 (P5) com Hexagrama 61 (P5) — verdade interna.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 11,
    pilar: 'iching',
    titulo: '11. A Paz (Tai)',
    essencia: 'Céu e terra em harmonia. Prosperidade. Colheita.',
    missao: 'Aproveite. A paz pede ação, não inércia. Use o tempo.',
    sombra: 'Preguiça, conformismo, paz que é estagnação.',
    pratica: 'Celebre 1 paz sua. Reconheça. Use o fôlego para 1 projeto.',
    conexao: 'Hexagrama 11 (P5) com Lua Cheia (P2) e Realizador (P1·8).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 12,
    pilar: 'iching',
    titulo: '12. O Estagnamento (Pi)',
    essencia: 'Céu e terra desconectados. Bloqueio. Estagnação.',
    missao: 'Espere. Não force. Quando o sistema trava, reverencie o tempo.',
    sombra: 'Depressão, inércia, desistência.',
    pratica: 'Reconheça 1 área estagnada. Sem pressão, apenas veja. O que ela pede?',
    conexao: 'Hexagrama 12 (P5) com Hexagrama 11 (P5) — par de opostos.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 13,
    pilar: 'iching',
    titulo: '13. A Comunhão (Tong Ren)',
    essencia: 'Pessoas em torno de um princípio. Comunidade de almas.',
    missao: 'Reúna quem vibra na mesma frequência. Sem máscaras.',
    sombra: 'Tribalismo, seita, comunidade que exclui.',
    pratica: 'Conecte-se a 1 comunidade alinhada com seus valores hoje.',
    conexao: 'Hexagrama 13 (P5) com Aquário (P2) e Diplomata (P1·2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 14,
    pilar: 'iching',
    titulo: '14. A Grande Posse (Da You)',
    essencia: 'Abundância, poder acumulado. Risco e oportunidade.',
    missao: 'Compartilhe. A grande posse exige grande responsabilidade.',
    sombra: 'Avareza, exibição, poder sem propósito.',
    pratica: 'Compartilhe 1 recurso seu (tempo, saber, dinheiro, atenção).',
    conexao: 'Hexagrama 14 (P5) com Realizador (P1·8) e Irosu (P4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 15,
    pilar: 'iching',
    titulo: '15. A Modéstia (Qian)',
    essencia: 'Humildade, simplicidade, discrição. O que é modesto prospera.',
    missao: 'Diminua. O que parece pequeno carrega a maior força.',
    sombra: 'Falsa modéstia, apagamento, esconder talento.',
    pratica: 'Reconheça 1 qualidade sua sem diminuir. Apenas nomeie.',
    conexao: 'Hexagrama 15 (P5) com Humanista (P1·9) e Mente Neutra (P3·4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 16,
    pilar: 'iching',
    titulo: '16. O Entusiasmo (Yu)',
    essencia: 'Alegria que move. Energia que se propaga sem forçar.',
    missao: 'Anime-se. A alegria genuína é contagiosa — use com propósito.',
    sombra: 'Euforia fugaz, animação sem fundamento.',
    pratica: 'Cultive 1 alegria simples hoje. Música, riso, dança, banho de sol.',
    conexao: 'Hexagrama 16 (P5) com Criador (P1·3) e Sanguíneo (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 17,
    pilar: 'iching',
    titulo: '17. O Acompanhamento (Sui)',
    essencia: 'Seguir e ser seguido. Adaptação inteligente.',
    missao: 'Acompanhe o que é maior. Adapte-se sem perder a si.',
    sombra: 'Subserviência, camaleão, seguir multidão.',
    pratica: 'Identifique quem você admira. Observe o que pode aprender.',
    conexao: 'Hexagrama 17 (P5) com Diplomata (P1·2) e Sanguíneo (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 18,
    pilar: 'iching',
    titulo: '18. A Obra que se Corrige (Gu)',
    essencia: 'Decadência, trabalho a fazer. Consertar antes que seja tarde.',
    missao: 'Repare. Volte ao que foi abandonado. Não finja que está tudo bem.',
    sombra: 'Negligência, negação, esperar crise em vez de prevenir.',
    pratica: 'Identifique 1 área da vida pedindo reparo. Dê 30 min a ela hoje.',
    conexao: 'Hexagrama 18 (P5) com Construtor (P1·4) e Virgem (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 19,
    pilar: 'iching',
    titulo: '19. A Aproximação (Lin)',
    essencia: 'Aproximar-se, presença que nutre. Grande em início.',
    missao: 'Aproxime-se. Mas saiba: o auge exige recuo consciente.',
    sombra: 'Apego, sucumbir ao outro, perder autonomia.',
    pratica: 'Esteja mais perto de 1 pessoa importante hoje. Escuta profunda.',
    conexao: 'Hexagrama 19 (P5) com Guardião (P1·6) e Câncer (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 20,
    pilar: 'iching',
    titulo: '20. A Contemplação (Guan)',
    essencia: 'Ver, observar, contemplar. Olhar que transforma.',
    missao: 'Observe. Saia do ruído. Contemple o que é maior.',
    sombra: 'Passividade, alheamento, observação como fuga.',
    pratica: 'Pare 10 min em lugar alto ou aberto. Olhe o horizonte. Não faça nada.',
    conexao: 'Hexagrama 20 (P5) com Buscador (P1·7) e Mente Neutra (P3·4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 21,
    pilar: 'iching',
    titulo: '21. A Mordedura que Quebra (Shi He)',
    essencia: 'Justiça que decide. Julgamento claro, sem ambiguidade.',
    missao: 'Decida. Julgue o que precisa ser julgado. Veredito claro.',
    sombra: 'Rigidez, crítica destrutiva, sentença sem misericórdia.',
    pratica: 'Tome 1 decisão judicial hoje (interna ou externa). Seja claro(a) e justo(a).',
    conexao: 'Hexagrama 21 (P5) com Obará (P4) e Capricórnio (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 22,
    pilar: 'iching',
    titulo: '22. A Graça (Bi)',
    essencia: 'Beleza, ornamento, forma. O que seduz precisa de substância.',
    missao: 'Decore com verdade. Beleza sem conteúdo é vazia.',
    sombra: 'Vaidade, forma sem essência, aparência.',
    pratica: 'Cuide de 1 detalhe estético hoje. Forma honrando o que ela veste.',
    conexao: 'Hexagrama 22 (P5) com Touro (P2) e Realizador (P1·8).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 23,
    pilar: 'iching',
    titulo: '23. A Desintegração (Bo)',
    essencia: 'A montanha desmorona. Fim de estrutura. Risco.',
    missao: 'Reconheça o fim. Não segure o que caiu. Volte ao essencial.',
    sombra: 'Negação, apego, reconstruir sem entender.',
    pratica: 'Identifique 1 estrutura sua desmoronando. Não conserte ainda. Apenas veja.',
    conexao: 'Hexagrama 23 (P5) com Ika (P4) e Lua Minguante (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 24,
    pilar: 'iching',
    titulo: '24. O Retorno (Fu)',
    essencia: 'Volta, renovação. O solstício de inverno. Início que volta.',
    missao: 'Retorne. Volte ao que é seu. Não reinvente, re-encontre.',
    sombra: 'Nostalgia, estagnação, voltar para evitar o novo.',
    pratica: 'Retome 1 prática antiga que você abandonou. 5 min. Só 5.',
    conexao: 'Hexagrama 24 (P5) com Lua Nova (P2) e Hexagrama 1 (P5).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 25,
    pilar: 'iching',
    titulo: '25. A Inocência (Wu Wang)',
    essencia: 'Pureza original, sem artifício. Verdade que se basta.',
    missao: 'Seja. Não finja. O que é verdadeiro é simples.',
    sombra: 'Ingênuo, inocente desprotegido, espontâneo sem ética.',
    pratica: 'Hoje, diga 1 verdade sem cálculo. Sem estratégia, sem cálculo.',
    conexao: 'Hexagrama 25 (P5) com Hexagrama 2 (P5) — par; com Iluminador (P1·11).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 26,
    pilar: 'iching',
    titulo: '26. A Força Domesticadora do Grande (Da Chu)',
    essencia: 'Acumular com moderação. Conter a abundância com disciplina.',
    missao: 'Domine. Contenha. Não queime a energia acumulada.',
    sombra: 'Acúmulo, repressão, contenção que sufoca.',
    pratica: 'Defina 1 limite claro hoje. Mantenha-o sem negociar.',
    conexao: 'Hexagrama 26 (P5) com Construtor (P1·4) e Obará (P4).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 27,
    pilar: 'iching',
    titulo: '27. A Boca (Yi)',
    essencia: 'Nutrição, fala, alimentação. O que entra e o que sai.',
    missao: 'Alimente-se bem. Fale o que precisa ser falado. Calcule o silêncio.',
    sombra: 'Gula, fala excessiva, má nutrição.',
    pratica: 'Faça 1 refeição em silêncio absoluto. Apenas coma. Apenas esteja.',
    conexao: 'Hexagrama 27 (P5) com Corpo Físico (P3·5) e Gêmeos (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 28,
    pilar: 'iching',
    titulo: '28. A Excesso (Da Guo)',
    essencia: 'Viga mestra vergada. Excesso de carga. Pressão extrema.',
    missao: 'Reconheça o peso. Sustente enquanto pode. Solte antes de quebrar.',
    sombra: 'Excesso crônico, sobrecarga, negação do limite.',
    pratica: 'Recuse 1 demanda que você aceitaria por incapacidade de dizer não.',
    conexao: 'Hexagrama 28 (P5) com Hexagrama 2 (P5) — risco sob sustentação.',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 29,
    pilar: 'iching',
    titulo: '29. O Abismo (Kan)',
    essencia: 'Água sobre água. Repetição do risco. Coragem para atravessar.',
    missao: 'Atravesse. Não há como contornar. A água ensina quem entra.',
    sombra: 'Medo paralisante, vitimismo, sucessão de crises.',
    pratica: 'Encare 1 medo pequeno hoje. Não o herói — apenas o encare.',
    conexao: 'Hexagrama 29 (P5) com Escorpião (P2) e Melancólico (P3).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 30,
    pilar: 'iching',
    titulo: '30. O Aderente (Li)',
    essencia: 'Fogo que brilha e queima. Clareza que une, mas pode ferir.',
    missao: 'Ilumine. Mas respeite o espaço. Nem tudo deve ser iluminado.',
    sombra: 'Intensidade excessiva, queimar para ser visto.',
    pratica: 'Diminua 1 luz hoje — tela, exposição, opinião. Note o que ganha.',
    conexao: 'Hexagrama 30 (P5) com Leão (P2) e Corpo Radiante (P3·10).',
    fonte: 'Wilhelm/Baynes 1950',
  },
  {
    id: 31,
    pilar: 'iching',
    titulo: '31. A Influência (Xian)',
    essencia: 'Atração, magnetismo, mútuo. Conectar com leveza.',
    missao: 'Aproxime. O que é magnético atrai. Não force.',
    sombra: 'Dependência, codependência, busca por validação.',
    pratica: 'Diga 1 elogio verdadeiro hoje. Sem objetivo. Só verdade.',
    conexao: 'Hexagrama 31 (P5) com Hexagrama 32 (P5) — par.',
    fonte: 'Wilhelm/Baynes 1950',
  } as SignificadoCurado,
  {
    id: 32,
    pilar: 'iching',
    titulo: '32. A Duração (Heng)',
    essencia: 'Continuidade, constância, permanência no tempo.',
    missao: 'Persevere. A duração constrói o que o entusiasmo começa.',
    sombra: 'Estagnação, medo de mudar, duração como tédio.',
    pratica: 'Mantenha 1 compromisso de longo prazo hoje. 1 ano de algo seu.',
    conexao: 'Hexagrama 32 (P5) com Construtor (P1·4) e Touro (P2).',
    fonte: 'Wilhelm/Baynes 1950',
  },
];
