// @ts-nocheck

// ika-meji-data.ts — Ika-Meji divination data (16 Principal Odu of Obeche/Ifa)

export interface IkaMejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const IKA_MEJI_DATA: IkaMejiOdu[] = [
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 1,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Plutão'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Touro',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Marrom', 'Verde', 'Preto'],
    offerings: ['Farinha de mandioca', 'Água de obí', 'Fumo', 'Aguardente'],
    ebos: ['Ebo de transformação', 'Ebo de cura'],
    taboos: ['Não comer carne podre', 'Não desperdiçar raízes'],
    strengths: ['Ancoragem', 'Persistência', 'Regeneração'],
    weaknesses: ['Estagnação', 'Rigidez'],
    health: ['Estômago', 'Intestinos', 'Fígado'],
    meanings: ['Terra', 'Raízes', 'Decomposição', 'Transformação'],
    ifaMessage: 'Ika transforma a matéria em vida nova, revelando que toda morte carrega semente de renascimento.',
  },
  {
    id: 'oyen',
    name: 'Oyen',
    portugueseName: 'Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro', 'Verde mar'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de paz interior', 'Ebo de cura emocional'],
    taboos: ['Não consumir sal em excesso', 'Não reter águas'],
    strengths: ['Intuição', 'Nutrição', 'Proteção'],
    weaknesses: ['Superproteção', 'Vulnerabilidade excessiva'],
    health: ['Útero', 'Seios', 'Estômago'],
    meanings: ['Água materna', 'Nutrição', 'Cuidado', 'Santuário'],
    ifaMessage: 'Oyen alimenta como a mãe terra, fornecendo sustenance e abrigo a todos os seres.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 3,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Sol'],
    sephirot: ['Geburah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Terça-feira',
    direction: 'Leste',
    colors: ['Vermelho', 'Laranja', 'Amarelo'],
    offerings: ['Palmeira', 'Mel', 'Frutos do mar'],
    ebos: ['Ebo de abertura de caminhos', 'Ebo de coragem'],
    taboos: ['Não matar sapo', 'Não hesitar'],
    strengths: ['Iniciativa', 'Coragem', 'Pioneirismo'],
    weaknesses: ['Impulsividade', 'Agressividade'],
    health: ['Cabeça', 'Olhos', 'Músculos'],
    meanings: ['Caminho aberto', 'Novo começo', 'Desbravamento'],
    ifaMessage: 'Ogunda abre trilhas onde não existem caminhos, revelando que toda jornada começa com um passo.',
  },
  {
    id: 'osai',
    name: 'Osai',
    portugueseName: 'Osai',
    order: 4,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Vênus', 'Mercúrio'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Libra',
    dayOfWeek: 'Sexta-feira',
    direction: 'Norte',
    colors: ['Rosa', 'Azul', 'Branco'],
    offerings: ['Flores', 'Perfume', 'Velas azuis'],
    ebos: ['Ebo de amor', 'Ebo de harmonia conjugal'],
    taboos: ['Não falar mentiras', 'Não discutir publicamente'],
    strengths: ['Equilíbrio', 'Beleza', 'Diplomacia'],
    weaknesses: ['Indecisão', 'Superficialidade'],
    health: ['Rins', 'Coluna lombar'],
    meanings: ['Amor', 'Harmonia', 'Parceria', 'Beleza'],
    ifaMessage: 'Osai ensina que o amor verdadeiro equilibra dar e receber em perfeita simetria.',
  },
  {
    id: 'ira',
    name: 'Ira',
    portugueseName: 'Ira',
    order: 5,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Tiphareth', 'Chesed'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Ouro', 'Amarelo', 'Laranja'],
    offerings: ['Mel', 'Frutas douradas', 'Velas douradas'],
    ebos: ['Ebo de prosperidade', 'Ebo de reconhecimento'],
    taboos: ['Não roubar', 'Não ser avarento'],
    strengths: ['Liderança', 'Generosidade', 'Confiança'],
    weaknesses: ['Arrogância', 'Orgulho exagerado'],
    health: ['Coração', 'Espinha', 'Olhos'],
    meanings: ['Luz solar', 'Prosperidade', 'Autoridade', 'Glória'],
    ifaMessage: 'Ira brilha como o sol do meio-dia, revelando que a verdadeira realeza serve ao povo.',
  },
  {
    id: 'wonrina',
    name: 'Wonrina',
    portugueseName: 'Wonrina',
    order: 6,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Marte'],
    sephirot: ['Hod', 'Geburah'],
    sign: 'Escorpião',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Vermelho escuro', 'Preto', 'Rubro'],
    offerings: ['Água preta', 'Carvão', 'Sangue de animal'],
    ebos: ['Ebo de proteção', 'Ebo de regeneração'],
    taboos: ['Não trair confiança', 'Não usar veneno'],
    strengths: ['Transformação', 'Regeneração', 'Segredos'],
    weaknesses: ['Vingança', 'Segredos destrutivos'],
    health: ['Órgãos sexuais', 'Bexiga'],
    meanings: ['Mistério', 'Regeneração', 'Sexualidade', 'Mortandade'],
    ifaMessage: 'Wonrina transforma dor em poder, revelando que a morte do ego é renascimento da alma.',
  },
  {
    id: 'irosun',
    name: 'Irosun',
    portugueseName: 'Irosun',
    order: 7,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Amarelo', 'Verde claro', 'Branco'],
    offerings: ['Farinha de trigo', 'Milho', 'Velas amarelas'],
    ebos: ['Ebo de limpeza espiritual', 'Ebo de iniciação'],
    taboos: ['Não comer porcaria', 'Não ser imundo'],
    strengths: ['Análise', 'Pureza', 'Discernimento'],
    weaknesses: ['Crítica excessiva', 'Perfeccionismo'],
    health: ['Intestinos', 'Baço'],
    meanings: ['Pureza', 'Iniciação', 'Mistério', 'Purificação'],
    ifaMessage: 'Irosun abre a porta do santuário, revelando que a purificação precede toda iniciação.',
  },
  {
    id: 'odina',
    name: 'Odina',
    portugueseName: 'Odina',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Saturno'],
    sephirot: ['Geburah', 'Malkuth'],
    sign: 'Capricórnio',
    dayOfWeek: 'Terça-feira',
    direction: 'Sul',
    colors: ['Preto', 'Cinza', 'Vermelho escuro'],
    offerings: ['Fumo', 'Aguardente', 'Galinha preta'],
    ebos: ['Ebo de proteção', 'Ebo contra inimigos'],
    taboos: ['Não fumar demais', 'Não brigar com superiores'],
    strengths: ['Resistência', 'Proteção', 'Firmeza'],
    weaknesses: ['Crueldade', 'Rigidez'],
    health: ['Ossos', 'Dentes', 'Pele'],
    meanings: ['Força', 'Proteção', 'Justiça', 'Limites'],
    ifaMessage: 'Odina ergue muros de proteção, revelando que a verdadeira força sabe quando dizer não.',
  },
  {
    id: 'kan',
    name: 'Kan',
    portugueseName: 'Kan',
    order: 9,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Lua', 'Júpiter'],
    sephirot: ['Yesod', 'Chesed'],
    sign: 'Peixes',
    dayOfWeek: 'Quinta-feira',
    direction: 'Nordeste',
    colors: ['Azul', 'Roxo', 'Branco'],
    offerings: ['Água mineral', 'Peixe', 'Velas azuis'],
    ebos: ['Ebo de fartura', 'Ebo de expansão'],
    taboos: ['Não desperdiçar comida', 'Não ter medo de água'],
    strengths: ['Abundância', 'Expansão', 'Sorte'],
    weaknesses: ['Excesso', 'Gula'],
    health: ['Pés', 'Lympháticos'],
    meanings: ['Abundância', 'Expansão', 'Liquidez', 'Conhecimento'],
    ifaMessage: 'Kan derrama bênçãos como a chuva, revelando que a abundância flui para quem sabe compartilhar.',
  },
  {
    id: 'oturupon',
    name: 'Oturupon',
    portugueseName: 'Oturupon',
    order: 10,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Sol'],
    sephirot: ['Tiphareth', 'Geburah'],
    sign: 'Áries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Branco', 'Ouro'],
    offerings: ['Carne grelhada', 'Vinho', 'Mel'],
    ebos: ['Ebo de vitória', 'Ebo de conquista'],
    taboos: ['Não fugir da batalha', 'Não abandonar parceiros'],
    strengths: ['Vitória', 'Conquista', 'Honra'],
    weaknesses: ['Garra', 'Arrogncia militar'],
    health: ['Cabeça', 'Coração'],
    meanings: ['Vitória', 'Guerra sagrada', 'Conquista', 'Honra'],
    ifaMessage: 'Oturupon conquista territórios desconhecidos, revelando que a honra se prova na ação.',
  },
  {
    id: 'metan',
    name: 'Metan',
    portugueseName: 'Metan',
    order: 11,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Saturno'],
    sephirot: ['Malkuth', 'Binah'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Marrom', 'Dourado'],
    offerings: ['Raízes', 'Tubérculos', 'Mel'],
    ebos: ['Ebo de estabilidade', 'Ebo de casamento'],
    taboos: ['Não comer seulho', 'Não abandonar família'],
    strengths: ['Fidelidade', 'Trabalho', 'Perseverança'],
    weaknesses: ['Teimosia', 'Materialismo'],
    health: ['Garganta', 'Pescoço'],
    meanings: ['Casamento', 'Aliança', 'Fidelidade', 'Trabalho'],
    ifaMessage: 'Metan une almas em casamento sagrado, revelando que o amor verdadeiro se prova no trabalho diário.',
  },
  {
    id: 'man',
    name: 'Man',
    portugueseName: 'Man',
    order: 12,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja', 'Branco'],
    offerings: ['Maçã', 'Nozes', 'Velas amarelas'],
    ebos: ['Ebo de inteligência', 'Ebo de negócios'],
    taboos: ['Não ser mentiroso', 'Não ser ladrão'],
    strengths: ['Inteligência', 'Comunicação', 'Versatilidade'],
    weaknesses: ['Inconsistência', 'Nervosismo'],
    health: ['Mãos', 'Braços', 'Pulmões'],
    meanings: ['Inteligência', 'Comunicação', 'Comércio', 'Mensageiro'],
    ifaMessage: 'Man voa como pássaro entre mundos, revelando que a mente conecta o que os olhos separam.',
  },
  {
    id: 'gba',
    name: 'Gba',
    portugueseName: 'Gba',
    order: 13,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Verde', 'Rosa'],
    offerings: ['Perfume', 'Flores', 'Velas rosas'],
    ebos: ['Ebo de amor', 'Ebo de fertilidade'],
    taboos: ['Não ter ciúmes', 'Não desperdiçar beleza'],
    strengths: ['Amor', 'Beleza', 'Arte'],
    weaknesses: ['Vaidade', 'Ciúmes'],
    health: ['Garganta', 'Rins'],
    meanings: ['Amor', 'Beleza', 'Fertilidade', 'Prazer'],
    ifaMessage: 'Gba embeleza o mundo com amor, revelando que a verdadeira riqueza é sentir-se amável.',
  },
  {
    id: 'shaki',
    name: 'Shaki',
    portugueseName: 'Shaki',
    order: 14,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Júpiter', 'Marte'],
    sephirot: ['Chesed', 'Geburah'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Nordeste',
    colors: ['Azul royal', 'Roxo', 'Dourado'],
    offerings: ['Vinho', 'Carne assada', 'Frutas'],
    ebos: ['Ebo de sabedoria', 'Ebo de longevidade'],
    taboos: ['Não jurar em vão', 'Não desonrar os mais velhos'],
    strengths: ['Sabedoria', 'Filosofia', 'Justiça'],
    weaknesses: ['Extravagância', 'Fanatismo'],
    health: ['Fígados', 'Coxas'],
    meanings: ['Sabedoria', 'Justiça', 'Lei sagrada', 'Filosofia'],
    ifaMessage: 'Shaki julga com sabedoria ancestral, revelando que a verdadeira justiça conhece a compaixão.',
  },
  {
    id: 'ola',
    name: 'Ola',
    portugueseName: 'Ola',
    order: 15,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Tiphareth', 'Chesed'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Ouro', 'Laranja', 'Amarelo'],
    offerings: ['Mel', 'Frutas douradas', 'Ouro'],
    ebos: ['Ebo de prosperidade', 'Ebo de sucesso'],
    taboos: ['Não ser preguiçoso', 'Não trapacear'],
    strengths: ['Prosperidade', 'Sucesso', 'Confiança'],
    weaknesses: ['Orgulho', 'Impaciência com lentidão'],
    health: ['Coração', 'Espinha'],
    meanings: ['Prosperidade', 'Sucesso', 'Saudação', 'Vitória'],
    ifaMessage: 'Ola irradia sucesso como o sol poente, revelando que a prosperidade é direito de quem trabalha.',
  },
  {
    id: 'oni',
    name: 'Oni',
    portugueseName: 'Oni',
    order: 16,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Lua'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Amarelo', 'Branco'],
    offerings: ['Frutas frescas', 'Velas verdes', 'Farinha'],
    ebos: ['Ebo de cura', 'Ebo de harmonia'],
    taboos: ['Não comer podríces', 'Não ser sujo'],
    strengths: ['Saúde', 'Limpeza', 'Serviço'],
    weaknesses: ['Preocupação excessiva', 'Crítica'],
    health: ['Todo o corpo', 'Sistema imunológico'],
    meanings: ['Saúde', 'Higiene', 'Serviço', 'Virtude'],
    ifaMessage: 'Oni purifica corpo e espírito, revelando que a saúde é o maior tesouro da existência.',
  },
];

export function getData(): IkaMejiOdu[] {
  return IKA_MEJI_DATA;
}

export default getData;
