// @ts-nocheck
// SKIP_LINT

// ikate-meji-data.ts — Ikate Meji (Double/Reflections) divination data for Ifa/Cabala system
// Associated orixá: Ikate (also known as Oxé or Oxaguiã)

export interface MejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_DATA: MejiOdu[] = [
  {
    id: 'ikate-ogbe',
    name: 'Ikate Ogbe',
    portugueseName: 'Ikate Ogbe',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Amarelo'],
    offerings: ['Dendê', 'Akará', 'Frutos do mar'],
    ebos: ['Ebo de vitória', 'Ebo de coragem'],
    taboos: ['Não matar sapo', 'Não mentir'],
    strengths: ['Vitória garantida', 'Iniciativa', 'Coragem'],
    weaknesses: ['Impaciência', 'Gula'],
    health: ['Coração', 'Cabeça'],
    meanings: ['Criação', 'Início', 'Abundância', 'Força vital'],
    ifaMessage: 'Ikate Ogbe representa a dupla luz do sol nascente, trazene inspiração e coragem para novos inícios.',
  },
  {
    id: 'ikate-oyen',
    name: 'Ikate Oyen',
    portugueseName: 'Ikate Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de paz', 'Ebo de longevidade'],
    taboos: ['Não consumir sal em excesso', 'Não derramar sangue'],
    strengths: ['Sabedoria', 'Paciência', 'Intuição profunda'],
    weaknesses: ['Melancolia', 'Excesso de sensibilidade'],
    health: ['Estômago', 'Útero'],
    meanings: ['Conhecimento', 'Sabedoria', 'Mistério', 'Profundidade'],
    ifaMessage: 'Ikate Oyen abre o livro da sabedoria lunar, revelando segredos ocultos através da reflexão nas águas.',
  },
  {
    id: 'ikate-ogunda',
    name: 'Ikate Ogunda',
    portugueseName: 'Ikate Ogunda',
    order: 3,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Mercúrio', 'Saturno'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja'],
    offerings: ['Cobre', 'Ferro', 'Milho'],
    ebos: ['Ebo de proteção', 'Ebo de comunicação'],
    taboos: ['Não usar armas', 'Não cortar árvores'],
    strengths: ['Comunicação', 'Inteligência', 'Versatilidade'],
    weaknesses: ['Inconstância', 'Nervosismo'],
    health: ['Pulmões', 'Mãos'],
    meanings: ['Ferramentas', 'Comunicação', 'Destino', 'Caminhos'],
    ifaMessage: 'Ikate Ogunda revela os caminhos duplos do destino, mostrando que cada ação tem múltiplas consequências.',
  },
  {
    id: 'ikate-oshe',
    name: 'Ikate Oshe',
    portugueseName: 'Ikate Oshe',
    order: 4,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Mel', 'Frutas maduras', 'Vinho doce'],
    ebos: ['Ebo de amor', 'Ebo de fertilidade'],
    taboos: ['Não ser infiel', 'Não comer sozinho'],
    strengths: ['Amor', 'Beleza', 'Abundância', 'Prazer'],
    weaknesses: ['Vaidade', 'Preguiça'],
    health: ['Garganta', 'Rins'],
    meanings: ['Amor', 'Prazer', 'Fertilidade', 'Beleza'],
    ifaMessage: 'Ikate Oshe representa a alegria dupla de viver, trazendo prosperidade e harmonia nas relações.',
  },
  {
    id: 'ikate-ika',
    name: 'Ikate Ika',
    portugueseName: 'Ikate Ika',
    order: 5,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Plutão', 'Netuno'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudoeste',
    colors: ['Preto', 'Roxo'],
    offerings: ['Água negra', 'Ervas escuras', 'Carvão'],
    ebos: ['Ebo de transformação', 'Ebo de limpeza'],
    taboos: ['Não enganar', 'Não usar veneno'],
    strengths: ['Transformação', 'Regeneração', 'Intuição'],
    weaknesses: ['Obsessão', 'Vingança'],
    health: ['Órgãos genitais', 'Intestinos'],
    meanings: ['Magia', 'Transformação', 'Segredos', 'Poder'],
    ifaMessage: 'Ikate Ika abre os portais duplos do mundo espiritual, revelando poderes ocultos da regeneração.',
  },
  {
    id: 'ikate-irosun',
    name: 'Ikate Irosun',
    portugueseName: 'Ikate Irosun',
    order: 6,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Tiphareth', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Nordeste',
    colors: ['Azul', 'Branco'],
    offerings: ['Frutas amarelas', 'Canjica', 'Flores azuis'],
    ebos: ['Ebo de proteção', 'Ebo de purificação'],
    taboos: ['Não ignorar avisos', 'Não comer carne crua'],
    strengths: ['Avisos', 'Proteção', 'Visão espiritual'],
    weaknesses: ['Medo', 'Ansiedade'],
    health: ['Olhos', 'Sangue'],
    meanings: ['Aviso', 'Proteção', 'Visão', 'Sangue'],
    ifaMessage: 'Ikate Irosun avisa sobre perigos ocultos, revelando segredos através de presságios duplos.',
  },
  {
    id: 'ikate-owonrin',
    name: 'Ikate Owonrin',
    portugueseName: 'Ikate Owonrin',
    order: 7,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Marte', 'Urano'],
    sephirot: ['Gevurah', 'Chesed'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Noroeste',
    colors: ['Cinza', 'Azul escuro'],
    offerings: ['Milho verde', 'Vento', 'Flores do campo'],
    ebos: ['Ebo de mudança', 'Ebo de libertação'],
    taboos: ['Não guardar objetos velhos', 'Não ser teimoso'],
    strengths: ['Mudança', 'Libertação', 'Movimento'],
    weaknesses: ['Inquietação', 'Impaciência'],
    health: ['Pulmões', 'Joelhos'],
    meanings: ['Mudança', 'Tempestade', 'Movimento', 'Liberdade'],
    ifaMessage: 'Ikate Owonrin traz ventos duplos de mudança e libertação, preparando para novos ciclos.',
  },
  {
    id: 'ikate-obara',
    name: 'Ikate Obara',
    portugueseName: 'Ikate Obara',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Júpiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphareth'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Sudeste',
    colors: ['Amarelo', 'Ouro'],
    offerings: ['Milho', 'Feijão', 'Frutas douradas'],
    ebos: ['Ebo de riqueza', 'Ebo de fartura'],
    taboos: ['Não contar planos antes', 'Não comer abóbora'],
    strengths: ['Riqueza', 'Fartura', 'Sabedoria'],
    weaknesses: ['Inveja', 'Teimosia'],
    health: ['Fígado', 'Coxas'],
    meanings: ['Riqueza', 'Fartura', 'Generosidade', 'Educação'],
    ifaMessage: 'Ikate Obara traz riqueza e fartura para aqueles que são generosos e estudiosos.',
  },
  {
    id: 'ikate-iron',
    name: 'Ikate Iron',
    portugueseName: 'Ikate Iron',
    order: 9,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Vênus'],
    sephirot: ['Malkuth', 'Netzach'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sudeste',
    colors: ['Marrom', 'Verde'],
    offerings: ['Raízes', 'Terra', 'Grãos'],
    ebos: ['Ebo de estabilidade', 'Ebo de saúde'],
    taboos: ['Não desperdiçar', 'Não ser ganancioso'],
    strengths: ['Fertilidade', 'Estabilidade', 'Praticidade'],
    weaknesses: ['Materialismo', 'Crítica excessiva'],
    health: ['Intestinos', 'Abdômen'],
    meanings: ['Terra', 'Fertilidade', 'Estabilidade', 'Trabalho'],
    ifaMessage: 'Ikate Iron representa a fertilidade da terra, trazendo abundância material e saúde.',
  },
  {
    id: 'ikate-odon',
    name: 'Ikate Odon',
    portugueseName: 'Ikate Odon',
    order: 10,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Urano'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Azul', 'Amarelo'],
    offerings: ['Água', 'Incienso', 'Flores'],
    ebos: ['Ebo de paz', 'Ebo de harmonia'],
    taboos: ['Não mentir', 'Não enganar'],
    strengths: ['Paz', 'Harmonia', 'Comunicação'],
    weaknesses: ['Superficialidade', 'Indecisão'],
    health: ['Pulmões', 'Braços'],
    meanings: ['Paz', 'Harmonia', 'Amizade', 'Verdade'],
    ifaMessage: 'Ikate Odon traz paz e harmonia, fortalecendo laços de amizade e verdade.',
  },
  {
    id: 'ikate-osa',
    name: 'Ikate Osa',
    portugueseName: 'Ikate Osa',
    order: 11,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Júpiter', 'Urano'],
    sephirot: ['Chesed', 'Hod'],
    sign: 'Peixes',
    dayOfWeek: 'Quinta-feira',
    direction: 'Nordeste',
    colors: ['Amarelo', 'Azul'],
    offerings: ['Pipoca', 'Efurom', 'Incienso'],
    ebos: ['Ebo de sabedoria', 'Ebo de evolução'],
    taboos: ['Não ser preguiçoso', 'Não fumar'],
    strengths: ['Sabedoria', 'Evolução', 'Adaptação'],
    weaknesses: ['Preguiça', 'Indolência'],
    health: ['Pés', 'Pernas'],
    meanings: ['Evolução', 'Adaptação', 'Sabedoria', 'Caminhada'],
    ifaMessage: 'Ikate Osa revela a caminhada dupla do destino, guiando através de obstáculos para a sabedoria.',
  },
  {
    id: 'ikate-osi',
    name: 'Ikate Osi',
    portugueseName: 'Ikate Osi',
    order: 12,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Marte', 'Sol'],
    sephirot: ['Gevurah', 'Tiphareth'],
    sign: 'Aries',
    dayOfWeek: 'Terça-feira',
    direction: 'Leste',
    colors: ['Vermelho', 'Branco'],
    offerings: ['Pimenta', 'Kolanuts', 'Gengibre'],
    ebos: ['Ebo de força', 'Ebo de firmeza'],
    taboos: ['Não usar faca', 'Não cortar cabelo'],
    strengths: ['Força', 'Determinação', 'Proteção'],
    weaknesses: ['Teimosia', 'Agressividade'],
    health: ['Cabeça', 'Sangues'],
    meanings: ['Força', 'Firmeza', 'Proteção', 'Justiça'],
    ifaMessage: 'Ikate Osi traz a dupla firmeza de propósito, protegendo contra inimigos e adversidades.',
  },
  {
    id: 'ikate-oyeku',
    name: 'Ikate Oyeku',
    portugueseName: 'Ikate Oyeku',
    order: 13,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Preto', 'Azul escuro'],
    offerings: ['Nozes', 'Água', 'Folhas escuras'],
    ebos: ['Ebo de escuridão', 'Ebo de mistério'],
    taboos: ['Não ter medo', 'Não duvidar'],
    strengths: ['Mistério', 'Ocultismo', 'Ancestralidade'],
    weaknesses: ['Medo', 'Pessimismo'],
    health: ['Psique', 'Nexos'],
    meanings: ['Escuridão', 'Mistério', 'Ocultismo', 'Ancestralidade'],
    ifaMessage: 'Ikate Oyeku abre os portais da noite, revelando segredos ancestrais através da reflexão.',
  },
  {
    id: 'ikate-oyon',
    name: 'Ikate Oyon',
    portugueseName: 'Ikate Oyon',
    order: 14,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Lua'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Touro',
    dayOfWeek: 'Segunda-feira',
    direction: 'Sul',
    colors: ['Verde', 'Branco'],
    offerings: ['Cabaça', 'Quiabo', 'Folhas sagradas'],
    ebos: ['Ebo de fartura', 'Ebo de saúde'],
    taboos: ['Não comer sozinho', 'Não ser avarento'],
    strengths: ['Abundância', 'Saúde', 'Fertilidade'],
    weaknesses: ['Avarícia', 'Inveja'],
    health: ['Útero', 'Ventr'],
    meanings: ['Abundância', 'Fartura', 'Saúde', 'Nascimento'],
    ifaMessage: 'Ikate Oyon abençoa a Fertility dupla, trazendo saúde e abundância para o lar.',
  },
  {
    id: 'ikate-ojon',
    name: 'Ikate Ojon',
    portugueseName: 'Ikate Ojon',
    order: 15,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Saturno', 'Marte'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Norte',
    colors: ['Azul', 'Branco'],
    offerings: ['Ferro', 'Colher de pau', 'Ouro'],
    ebos: ['Ebo de riqueza', 'Ebo de trabalho'],
    taboos: ['Não ser indolente', 'Não desperdiciar工具'],
    strengths: ['Trabalho', 'Riqueza', 'Disciplina'],
    weaknesses: [' Avareza', 'Rigidez'],
    health: ['Ossos', 'Joelhos'],
    meanings: ['Trabalho', 'Riqueza', 'Disciplina', 'Perseverança'],
    ifaMessage: 'Ikate Ojon trabalha com雙重 dedication, construindo riqueza através do esforço perseverante.',
  },
  {
    id: 'ikate-oxe',
    name: 'Ikate Oxe',
    portugueseName: 'Ikate Oxe',
    order: 16,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Tiphareth', 'Chesed'],
    sign: 'Leão',
    dayOfWeek: 'Sexta-feira',
    direction: 'Nordeste',
    colors: ['Vermelho', 'Ouro'],
    offerings: ['Pavão', 'Frango', 'Dendê'],
    ebos: ['Ebo de prosperidade', 'Ebo de honra'],
    taboos: ['Não desonrar pais', 'Não mentir sobre祖先'],
    strengths: ['Honra', 'Prosperidade', 'Liderança'],
    weaknesses: ['Orgulho', 'Arrogância'],
    health: ['Espinha', 'Olhos'],
    meanings: ['Honra', 'Prosperidade', 'Respeito', 'Ancestralidade'],
    ifaMessage: 'Ikate Oxe carrega a dupla honra dos ancestrais, trazendo prosperidade e respeito ao seu nome.',
  },
];

export function getData(): MejiOdu[] {
  return MEJI_DATA;
}
