// @ts-nocheck
// SKIP_LINT

/**
 * Megi Meji Data
 * Odu of golden double abundance, inner radiance, and the flow of prosperity
 * Represents the twin aspects of Megi's golden waters manifesting abundance
 */

// Megi Meji represents the double manifestation of golden waters
// where prosperity flows in balanced dual currents
// Governed by the golden light of inner radiance and outer abundance
// Element: Golden Water
// Represents wealth, beauty, self-worth, and the flow of abundance

export interface MegiMejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEGI_MEJI_DATA: MegiMejiOdu[] = [
  {
    id: 'megi-ros',
    name: 'Megi Ros',
    portugueseName: 'Megi Ros',
    order: 1,
    polarity: 'feminine',
    element: 'Agua Dourada',
    planets: ['Venus', 'Lua'],
    sephirot: ['Netzach', 'Hod', 'Yesod'],
    sign: 'Touros, Libra',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste',
    colors: ['Dourado', 'Rosa', 'Azul claro'],
    offerings: ['Mel dourado', 'Flores roses', 'Azeite doce', 'Frutas douradas'],
    ebos: ['Ebo de auto-estima', 'Ebo de abundancia'],
    taboos: ['Não desvalorizar a si mesmo', 'Não rejeitar prosperidade'],
    strengths: ['Valor proprio', 'Beleza interior', 'Prosperidade'],
    weaknesses: ['Vaidade', 'Materialismo'],
    health: ['Rins', 'Tireoide', 'Pele'],
    meanings: ['Abundancia dourada', 'Valor proprio', 'Beleza sagrada', 'Prosperidade'],
    ifaMessage: 'Megi Ros revela que a verdadeira beleza nace do reconhecimento do proprio valor, e que a prosperidade flui para quem sabe recebe-la com graia.',
  },
  {
    id: 'megi-da',
    name: 'Megi Da',
    portugueseName: 'Megi Da',
    order: 2,
    polarity: 'masculine',
    element: 'Terra Dourada',
    planets: ['Venus', 'Terra'],
    sephirot: ['Malkuth', 'Netzach'],
    sign: 'Touro, Capricornio',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Dourado', 'Marrom', 'Verde'],
    offerings: ['Mel', 'Frutos da terra', 'Raizes douradas', 'Farinha de mandioca'],
    ebos: ['Ebo de prosperidade', 'Ebo de fundamento'],
    taboos: ['Não desperdiçar recursos', 'Não rejeitar ofertas'],
    strengths: ['Prosperidade', 'Fundamento', 'Gratidao'],
    weaknesses: ['Avaricia', 'Apego'],
    health: ['Garganta', 'Pescoco', 'Ovarios'],
    meanings: ['Prosperidade', 'Gratidao', 'Fundamento', 'Abundancia terrestre'],
    ifaMessage: 'Megi Da ensina que a verdadeira riqueza se sustenta na terra do agradecimento, e que dar multiplica o que se recebe.',
  },
  {
    id: 'megi-se',
    name: 'Megi Se',
    portugueseName: 'Megi Se',
    order: 3,
    polarity: 'feminine',
    element: 'Ar Dourado',
    planets: ['Mercurio', 'Venus'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Gemeos, Aquario',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Dourado', 'Branco'],
    offerings: ['Mel dourado', 'Flores brancas', 'Azeite', 'Sementes'],
    ebos: ['Ebo de expansao', 'Ebo de circulacao'],
    taboos: ['Não reter o que deve circular', 'Não limitar a abundancia'],
    strengths: ['Circulacao', 'Expansao', 'Comunicao'],
    weaknesses: ['Dispersao', 'Inconstancia'],
    health: ['Pulmoes', 'Maos', 'Sistema nervoso'],
    meanings: ['Expansao', 'Circulacao', 'Luz dourada', 'Visao ampliada'],
    ifaMessage: 'Megi Se sopra como o vento dourado que carrega a prosperidade para todos os cantos, revelando que a abundancia multiplica quando compartilhada.',
  },
  {
    id: 'megi-kan',
    name: 'Megi Kan',
    portugueseName: 'Megi Kan',
    order: 4,
    polarity: 'masculine',
    element: 'Metal Dourado',
    planets: ['Venus', 'Marte'],
    sephirot: ['Netzach', 'Geburah'],
    sign: 'Escorpiao, Touro',
    dayOfWeek: 'Terca-feira',
    direction: 'Nordeste',
    colors: ['Dourado', 'Vermelho escuro', 'Cinza'],
    offerings: ['Ferro dourado', 'Mel', 'Fumo', 'Palmeira'],
    ebos: ['Ebo de poder', 'Ebo de protecao da abundancia'],
    taboos: ['Não desperdiçar prosperidade', 'Não permitir saque'],
    strengths: ['Poder', 'Protecao', 'Forca'],
    weaknesses: ['Rigidez', 'Ciumes'],
    health: ['Intestinos', 'Apendice', 'Musculos'],
    meanings: ['Poder', 'Forca', 'Protecao', 'Seguranca material'],
    ifaMessage: 'Megi Kan empunha o metal dourado que protege o tesouro, revelando que a verdadeira riqueza se defende com forca e proposito.',
  },
  {
    id: 'megi-rosi',
    name: 'Megi Rosi',
    portugueseName: 'Megi Rosi',
    order: 5,
    polarity: 'feminine',
    element: 'Agua Prateada',
    planets: ['Lua', 'Mercurio'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Cancer, Virgem',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Prata', 'Branco', 'Azul claro'],
    offerings: ['Agua de obi', 'Flores brancas', 'Mel', 'Sementes de prata'],
    ebos: ['Ebo de intuicao', 'Ebo de valorizacao'],
    taboos: ['Não ignorar a intuicao', 'Não desvalorizar insights'],
    strengths: ['Intuicao', 'Valorizacao', 'Discernimento'],
    weaknesses: ['Hipersensibilidade', 'Inseguranca'],
    health: ['Rins', 'Bexiga', 'Sistema imunologico'],
    meanings: ['Intuicao', 'Valorizacao', 'Consciencia', 'Prata lunar'],
    ifaMessage: 'Megi Rosi brilha como a lua prateada sobre as aguas douradas, revelando que o valor verdadeiro se enxerga com a luz da intuicao.',
  },
  {
    id: 'megi-oni',
    name: 'Megi Oni',
    portugueseName: 'Megi Oni',
    order: 6,
    polarity: 'masculine',
    element: 'Terra Dourada',
    planets: ['Terra', 'Sol'],
    sephirot: ['Malkuth', 'Tiphareth'],
    sign: 'Leao, Capricornio',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Laranja', 'Marrom'],
    offerings: ['Mel dourado', 'Frango', 'Milho', 'Azeite'],
    ebos: ['Ebo de lideranca', 'Ebo de abundancia real'],
    taboos: ['Não ser mesquinho', 'Não abandonar lideranca'],
    strengths: ['Lideranca', 'Generosidade', 'Nobreza'],
    weaknesses: ['Orgulho', 'Autoritarismo'],
    health: ['Coracao', 'Espinha', 'Olhos'],
    meanings: ['Lideranca', 'Realeza', 'Abundancia natural', 'Nobreza'],
    ifaMessage: 'Megi Oni coroado de ouro revela que a verdadeira realeza se mede pela generosidade do coracao, nao pela quantidade de ouro.',
  },
  {
    id: 'megi-te',
    name: 'Megi Te',
    portugueseName: 'Megi Te',
    order: 7,
    polarity: 'feminine',
    element: 'Agua Estrelada',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Peixes, Cancer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul escuro', 'Dourado', 'Prata'],
    offerings: ['Agua de obi', 'Estrelas do mar', 'Perolas', 'Flores noturnas'],
    ebos: ['Ebo de abundancia cósmica', 'Ebo de inspiracao'],
    taboos: ['Não ignorar sonhos', 'Não rejeitar inspiracao'],
    strengths: ['Inspiracao', 'Visao', 'Abundancia espiritual'],
    weaknesses: ['Sonho excessivo', 'Dissociacao'],
    health: ['Seios', 'Utero', 'Liquidos corporais'],
    meanings: ['Abundancia cósmica', 'Inspiracao', 'Visao espiritual', 'Estrelas douradas'],
    ifaMessage: 'Megi Te colecciona estrelas douradas do ceu, revelando que a verdadeira abundancia vem da conexao com o infinito.',
  },
  {
    id: 'megi-tura',
    name: 'Megi Tura',
    portugueseName: 'Megi Tura',
    order: 8,
    polarity: 'masculine',
    element: 'Fogo Dourado',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphareth', 'Netzach'],
    sign: 'Leao, Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Vermelho', 'Laranja'],
    offerings: ['Mel', 'Azeite', 'Velas douradas', 'Frango'],
    ebos: ['Ebo de prosperidade', 'Ebo de purificacao'],
    taboos: ['Não desperdiçar ouro', 'Não contaminar recursos'],
    strengths: ['Purificacao', 'Prosperidade', 'Vitalidade'],
    weaknesses: ['Impaciencia', 'Excesso'],
    health: ['Coracao', 'Sangue', 'Figado'],
    meanings: ['Purificacao', 'Prosperidade', 'Renovacao', 'Fogo dourado'],
    ifaMessage: 'Megi Tura arde com o fogo dourado que purifica e renova, revelando que a verdadeira riqueza se renova como o sol cada manha.',
  },
  {
    id: 'megi-rin',
    name: 'Megi Rin',
    portugueseName: 'Megi Rin',
    order: 9,
    polarity: 'feminine',
    element: 'Ar Dourado',
    planets: ['Venus', 'Jupiter'],
    sephirot: ['Netzach', 'Chesed'],
    sign: 'Sagitario, Libra',
    dayOfWeek: 'Quinta-feira',
    direction: 'Norte',
    colors: ['Dourado', 'Roxo', 'Azul'],
    offerings: ['Mel dourado', 'Uvas', 'Vinho doce', 'Flores'],
    ebos: ['Ebo de abundancia expansiva', 'Ebo de alegria'],
    taboos: ['Não ser tacanho', 'Não recusar abundancia'],
    strengths: ['Expansao', 'Alegria', 'Prosperidade generosa'],
    weaknesses: ['Excesso', 'Superficialidade'],
    health: ['Quadris', 'Coxas', 'Figado'],
    meanings: ['Expansao', 'Alegria', 'Abundancia alegre', 'Generosidade'],
    ifaMessage: 'Megi Rin gargalha com ouro, revelando que a abundancia alegre se multiplica e que a joie de vivre e a verdadeira riqueza.',
  },
  {
    id: 'megi-fun',
    name: 'Megi Fun',
    portugueseName: 'Megi Fun',
    order: 10,
    polarity: 'masculine',
    element: 'Terra Prateada',
    planets: ['Saturno', 'Lua'],
    sephirot: ['Binah', 'Malkuth'],
    sign: 'Capricornio, Cancer',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Prata', 'Marrom', 'Azul escuro'],
    offerings: ['Raizes prateadas', 'Terra', 'Agua de obi', 'Ferro'],
    ebos: ['Ebo de ancoragem', 'Ebo de protecao'],
    taboos: ['Não abandonar raizes', 'Não perder fundamento'],
    strengths: ['Ancoragem', 'Protecao', 'Estabilidade'],
    weaknesses: ['Rigidez', 'Medo'],
    health: ['Joelhos', 'Ossos', 'Dentes'],
    meanings: ['Ancoragem', 'Estabilidade', 'Fundamento prateado', 'Seguranca'],
    ifaMessage: 'Megi Fun ancora o ouro prateado na terra profunda, revelando que a verdadeira prosperidade se sustenta em fundamentos firmes.',
  },
  {
    id: 'megi-je',
    name: 'Megi Je',
    portugueseName: 'Megi Je',
    order: 11,
    polarity: 'feminine',
    element: 'Agua Solar',
    planets: ['Sol', 'Lua'],
    sephirot: ['Tiphareth', 'Yesod'],
    sign: 'Leao, Cancer',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Amarelo', 'Branco'],
    offerings: ['Mel dourado', 'Frutas solares', 'Azeite', 'Flores amarelas'],
    ebos: ['Ebo de iluminacao', 'Ebo de auto-estima plena'],
    taboos: ['Não se esconder', 'Não temer a luz'],
    strengths: ['Iluminacao', 'Confianca', 'Valor proprio'],
    weaknesses: ['Egocentrismo', 'Superficialidade'],
    health: ['Coracao', 'Ojos', 'Estomago'],
    meanings: ['Iluminacao', 'Confianca', 'Valor proprio', 'Sol dourado'],
    ifaMessage: 'Megi Je brilha como o sol dourado sobre as aguas, revelando que a verdadeira beleza interna se manifesta quando nos atrevemos a brilhar.',
  },
  {
    id: 'megi-roshi',
    name: 'Megi Roshi',
    portugueseName: 'Megi Roshi',
    order: 12,
    polarity: 'masculine',
    element: 'Metal Prateado',
    planets: ['Lua', 'Mercurio'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Gemeos, Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Prata', 'Branco', 'Amarelo claro'],
    offerings: ['Prata', 'Mel', 'Flores brancas', 'Azeite doce'],
    ebos: ['Ebo de comunicacao', 'Ebo de habilidades'],
    taboos: ['Não calar a verdade', 'Não subestimar habilidades'],
    strengths: ['Comunicacao', 'Habilidades', 'Versatilidade'],
    weaknesses: ['Nervosismo', 'Inconstancia'],
    health: ['Maos', 'Pulmoes', 'Bracos'],
    meanings: ['Comunicacao', 'Habilidades', 'Versatilidade', 'Metal prateado'],
    ifaMessage: 'Megi Roshi forja habilidades como prata reluzente, revelando que a verdadeira riqueza tambem se encontra nas capacidades do ser.',
  },
  {
    id: 'megi-tetu',
    name: 'Megi Tetu',
    portugueseName: 'Megi Tetu',
    order: 13,
    polarity: 'feminine',
    element: 'Agua Fluida',
    planets: ['Lua', 'Venus'],
    sephirot: ['Yesod', 'Netzach'],
    sign: 'Peixes, Touro',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Dourado', 'Verde agua'],
    offerings: ['Agua de obi', 'Perolas', 'Flores aquaticas', 'Mel'],
    ebos: ['Ebo de fluidez', 'Ebo de conexao emocional'],
    taboos: ['Não resistir o fluxo', 'Não bloquear emocoes'],
    strengths: ['Fluidez', 'Adaptabilidade', 'Conexao'],
    weaknesses: ['Dissolucao', 'Indecisao'],
    health: ['Rins', 'Linfatico', 'Pele'],
    meanings: ['Fluidez', 'Adaptabilidade', 'Abundancia fluente', 'Agua dourada'],
    ifaMessage: 'Megi Tetu flui como rio dourado, revelando que a prosperidade se manifesta mais facilmente quando nos entregamos ao fluxo da vida.',
  },
  {
    id: 'megi-pu',
    name: 'Megi Pu',
    portugueseName: 'Megi Pu',
    order: 14,
    polarity: 'masculine',
    element: 'Terra Fertile',
    planets: ['Terra', 'Venus'],
    sephirot: ['Malkuth', 'Netzach'],
    sign: 'Touro, Virgem',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Dourado', 'Marrom claro'],
    offerings: ['Frutas frescas', 'Mel', 'Raizes', 'Flores'],
    ebos: ['Ebo de fertilidade', 'Ebo de crescimento'],
    taboos: ['Não desperdiçar sementes', 'Não contaminar terra'],
    strengths: ['Fertilidade', 'Crescimento', 'Produtividade'],
    weaknesses: ['Avidez', 'Possessividade'],
    health: ['Abdomen', 'Intestinos', 'Sistema reprodutor'],
    meanings: ['Fertilidade', 'Crescimento', 'Abundancia natural', 'Terra fertile'],
    ifaMessage: 'Megi Pu semeia com mao generosa, revelando que a verdadeira abundancia nasce da terra fertile da generosidade.',
  },
  {
    id: 'megi-let',
    name: 'Megi Let',
    portugueseName: 'Megi Let',
    order: 15,
    polarity: 'feminine',
    element: 'Ar Estrelado',
    planets: ['Jupiter', 'Netuno'],
    sephirot: ['Chesed', 'Binah'],
    sign: 'Sagitario, Peixes',
    dayOfWeek: 'Quinta-feira',
    direction: 'Norte',
    colors: ['Roxo', 'Dourado', 'Azul profundo'],
    offerings: ['Mel', 'Vinho', 'Sangue de uva', 'Flores cosmicas'],
    ebos: ['Ebo de visao', 'Ebo de destino'],
    taboos: ['Não limitar o destino', 'Não impedir a visao'],
    strengths: ['Visao', 'Destino', 'Sabedoria'],
    weaknesses: ['Excesso de expansao', 'Perda de foco'],
    health: ['Mente', 'Quadrante superior direito', 'Figado'],
    meanings: ['Visao', 'Destino', 'Sabedoria oculta', 'Abundancia cosmica'],
    ifaMessage: 'Megi Let abre os olhos para os mysterios do destino, revelando que a verdadeira riqueza se encontra na visao do alma.',
  },
  {
    id: 'megi-otu',
    name: 'Megi Otu',
    portugueseName: 'Megi Otu',
    order: 16,
    polarity: 'masculine',
    element: 'Fogo Estelar',
    planets: ['Sol', 'Plutao'],
    sephirot: ['Tiphareth', 'Geburah'],
    sign: 'Leao, Escorpiao',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Vermelho', 'Preto'],
    offerings: ['Fogo ritual', 'Mel', 'Sangue', 'Incenso'],
    ebos: ['Ebo de transformacao', 'Ebo de poder maximo'],
    taboos: ['Não temer a transformacao', 'Não recusar o poder'],
    strengths: ['Transformacao', 'Poder', 'Renovacao maxima'],
    weaknesses: ['Destruicao', 'Fanatismo'],
    health: ['Coracao', 'Sangue', 'Articulacoes'],
    meanings: ['Transformacao', 'Poder maximo', 'Renovacao', 'Fogo estelar'],
    ifaMessage: 'Megi Otu incendeia com o poder estelar que transforma o chumbo em ouro, revelando que a verdadeira abundancia nasce da transformacao do ser.',
  },
];

export function getData(): MegiMejiOdu[] {
  return MEGI_MEJI_DATA;
}

export default getData;