// @ts-nocheck

// meji-data.ts — Meji (Double/Odu) divination data for Ifa/Cabala system

export interface MejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_DATA: MejiOdu[] = [
  {
    id: 'ogbe',
    name: 'Ogbe',
    portugueseName: 'Ogbe',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Amarelo'],
    offerings: ['Melk', 'Palmeira', 'Frutos do mar'],
    ebos: ['Ebo de dinheiro', 'Ebo de saúde'],
    taboos: ['Não matar sapo', 'Não mentir'],
    strengths: ['Vitória garantida', 'Iniciativa', 'Coragem'],
    weaknesses: ['Impaciência', 'Gula'],
    health: ['Coração', 'Cabeça'],
    meanings: ['Criação', 'Início', 'Abundância', 'Força vital'],
    ifaMessage: 'Ogbe Meji representa a dupla criação, o poder de manifestar realidades através da intenção pura.',
  },
  {
    id: 'oyen',
    name: 'Oyen',
    portugueseName: 'Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de paz', 'Ebo de longevidade'],
    taboos: ['Não consumir sal em excesso', 'Não derramar sangue'],
    strengths: ['Sabedoria', 'Paciência', 'Intuição profunda'],
    weaknesses: ['Melancolia', 'Excesso de sensibilidade'],
    health: ['Estômago', 'Útero'],
    meanings: ['Conhecimento', 'Sabedoria', 'Mistério', 'Profundidade'],
    ifaMessage: 'Oyen Meji abre o livro da sabedoria dupla, revelando segredos ocultos da mente divina.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 3,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Mercúrio', 'Saturno'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja'],
    offerings: ['Cobre', 'Ferro', 'Milho'],
    ebos: ['Ebo de proteção', 'Ebo de comunicação'],
    taboos: ['Não usar armas', 'Não cortar árvores'],
    strengths: ['Comunicação', 'Inteligência', 'Versatilidade'],
    weaknesses: ['Inconstância', 'Nervosismo'],
    health: ['Pulmões', 'Mãos'],
    meanings: ['Ferramentas', 'Comunicação', 'Destino', 'Caminhos'],
    ifaMessage: 'Ogunda Meji revela os caminhos duplos do destino, mostrando múltiplas possibilidades ao consulente.',
  },
  {
    id: 'oshe',
    name: 'Oshe',
    portugueseName: 'Oshe',
    order: 4,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Mel', 'Frutas maduras', 'Vinho doce'],
    ebos: ['Ebo de amor', 'Ebo de fertilidade'],
    taboos: ['Não ser infiel', 'Não comer sozinho'],
    strengths: ['Amor', 'Beleza', 'Abundância', 'Prazer'],
    weaknesses: ['Vaidade', 'Preguiça'],
    health: ['Garganta', 'Rins'],
    meanings: ['Amor', 'Prazer', 'Fertilidade', 'Beleza'],
    ifaMessage: 'Oshe Meji representa a alegria dupla de viver, trazendo prosperidade e harmonia nas relações.',
  },
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 5,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Plutão', 'Netuno'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudoeste',
    colors: ['Preto', 'Roxo'],
    offerings: ['Água negra', 'Ervas escuras', 'Carvão'],
    ebos: ['Ebo de transformação', 'Ebo de limpeza'],
    taboos: ['Não enganar', 'Não usar veneno'],
    strengths: ['Transformação', 'Regeneração', 'Intuição'],
    weaknesses: ['Obsessão', 'Vingança'],
    health: ['Órgãos genitais', 'Intestinos'],
    meanings: ['Magia', 'Transformação', 'Segredos', 'Poder'],
    ifaMessage: 'Ika Meji abre os portais duplos do mundo espiritual, revelando poderes ocultos da regeneração.',
  },
  {
    id: 'irosun',
    name: 'Irosun',
    portugueseName: 'Irosun',
    order: 6,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Tiphareth', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Nordeste',
    colors: ['Azul', 'Branco'],
    offerings: ['Frutas amarelas', 'Canjica', 'Flores azuis'],
    ebos: ['Ebo de proteção', 'Ebo de purificação'],
    taboos: ['Não ignorar avisos', 'Não comer carne crua'],
    strengths: ['Avisos', 'Proteção', 'Visão espiritual'],
    weaknesses: ['Medo', 'Ansiedade'],
    health: ['Olhos', 'Sangue'],
    meanings: ['Aviso', 'Proteção', 'Visão', 'Sangue'],
    ifaMessage: 'Irosun Meji avisa sobre perigos ocultos, revelando segredos através de presságios duplos.',
  },
  {
    id: 'owonrin',
    name: 'Owonrin',
    portugueseName: 'Owonrin',
    order: 7,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Marte', 'Urano'],
    sephirot: ['Gevurah', 'Chesed'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Noroeste',
    colors: ['Cinza', 'Azul escuro'],
    offerings: ['Milho verde', 'Vento', 'Flores do campo'],
    ebos: ['Ebo de mudança', 'Ebo de libertação'],
    taboos: ['Não guardar objetos velhos', 'Não ser teimoso'],
    strengths: ['Mudança', 'Libertação', 'Movimento'],
    weaknesses: ['Inquietação', 'Impaciência'],
    health: ['Pulmões', 'Joelhos'],
    meanings: ['Mudança', 'Tempestade', 'Movimento', 'Liberdade'],
    ifaMessage: 'Owonrin Meji traz ventos duplos de mudança e libertação, preparando para novos ciclos.',
  },
  {
    id: 'obara',
    name: 'Obara',
    portugueseName: 'Obara',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Júpiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphareth'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Sudeste',
    colors: ['Amarelo', 'Ouro'],
    offerings: ['Milho', 'Feijão', 'Frutas douradas'],
    ebos: ['Ebo de riqueza', 'Ebo de fartura'],
    taboos: ['Não contar planos antes', 'Não comer abóbora'],
    strengths: ['Riqueza', 'Fartura', 'Sabedoria'],
    weaknesses: ['Inveja', 'Teimosia'],
    health: ['Fígado', 'Coxas'],
    meanings: ['Riqueza', 'Fartura', 'Generosidade', 'Educação'],
    ifaMessage: 'Obara Meji traz riqueza e fartura duplas para aqueles que são generosos e estudiosos.',
  },
  {
    id: 'iron',
    name: 'Iron',
    portugueseName: 'Iron',
    order: 9,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Vênus'],
    sephirot: ['Malkuth', 'Netzach'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sudeste',
    colors: ['Marrom', 'Verde'],
    offerings: ['Raízes', 'Terra', 'Grãos'],
    ebos: ['Ebo de estabilidade', 'Ebo de saúde'],
    taboos: ['Não desperdiçar', 'Não ser ganancioso'],
    strengths: ['Fertilidade', 'Estabilidade', 'Praticidade'],
    weaknesses: ['Materialismo', 'Crítica excessiva'],
    health: ['Intestinos', 'Abdômen'],
    meanings: ['Terra', 'Fertilidade', 'Estabilidade', 'Trabalho'],
    ifaMessage: 'Iron Meji representa a fertilidade da terra dupla, trazendo abundância material e saúde.',
  },
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 10,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Gevurah', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Oeste',
    colors: ['Vermelho escuro', 'Preto'],
    offerings: ['Pimenta', 'Akp', 'Sangue de galinha'],
    ebos: ['Ebo de transformação', 'Ebo de magia'],
    taboos: ['Não guardar rancor', 'Não usar veneno'],
    strengths: ['Transformação', 'Regeneração', 'Poder'],
    weaknesses: ['Vingança', 'Obsessão'],
    health: ['Órgãos sexuais', 'Coluna'],
    meanings: ['Mistério', 'Transformação', 'Regeneração', 'Magia'],
    ifaMessage: 'Ika Meji abre os portais duplos do mundo espiritual, revelando poderes ocultos.',
  },
  {
    id: 'obara',
    name: 'Obara',
    portugueseName: 'Obara',
    order: 11,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Júpiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphareth'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja'],
    offerings: ['Milho', 'Feijão', 'Frutas douradas'],
    ebos: ['Ebo de riqueza', 'Ebo de fartura'],
    taboos: ['Não contar planos antes', 'Não comer abóbora'],
    strengths: ['Riqueza', 'Fartura', 'Sabedoria'],
    weaknesses: ['Inveja', 'Teimosia'],
    health: ['Fígado', 'Coxas'],
    meanings: ['Riqueza', 'Fartura', 'Generosidade', 'Educação'],
    ifaMessage: 'Obara Meji traz riqueza e fartura para aqueles que são generosos e estudiosos.',
  },
  {
    id: 'odon',
    name: 'Odon',
    portugueseName: 'Odon',
    order: 12,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Urano'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Azul', 'Amarelo'],
    offerings: ['Água', 'Incienso', 'Flores'],
    ebos: ['Ebo de paz', 'Ebo de harmonia'],
    taboos: ['Não mentir', 'Não enganar'],
    strengths: ['Paz', 'Harmonia', 'Comunicação'],
    weaknesses: ['Superficialidade', 'Indecisão'],
    health: ['Pulmões', 'Braços'],
    meanings: ['Paz', 'Harmonia', 'Amizade', 'Verdade'],
    ifaMessage: 'Odon Meji traz paz e harmonia дуальную, fortalecendo laços de amizade e verdade.',
  },
  {
    id: 'iron',
    name: 'Iron',
    portugueseName: 'Iron',
    order: 13,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Lua'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Touro',
    dayOfWeek: 'Segunda-feira',
    direction: 'Sul',
    colors: ['Verde', 'Marrom'],
    offerings: ['Raízes', 'Terra', 'Mel'],
    ebos: ['Ebo de prosperidade', 'Ebo de proteção'],
    taboos: ['Não ser preguiçoso', 'Não desperdiçar recursos'],
    strengths: ['Prosperidade', 'Proteção', 'Estabilidade'],
    weaknesses: ['Teimosia', 'Avidez'],
    health: ['Pescoço', 'Garganta'],
    meanings: ['Terra', 'Prosperidade', 'Proteção', 'Abundância'],
    ifaMessage: 'Iron Meji abençoa a terra com prosperidade dupla, protegendo e alimentando os filhos.',
  },
  {
    id: 'oshe',
    name: 'Oshe',
    portugueseName: 'Oshe',
    order: 14,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Libra',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste',
    colors: ['Rosa', 'Azul claro'],
    offerings: ['Mel', 'Flores', 'Perfume'],
    ebos: ['Ebo de amor', 'Ebo de reconciliação'],
    taboos: ['Não ser infiel', 'Não guardar ressentimento'],
    strengths: ['Amor', 'Beleza', 'Equilíbrio'],
    weaknesses: ['Vanidade', 'Superficialidade'],
    health: ['Rins', 'Lombar'],
    meanings: ['Amor', 'Beleza', 'Equilíbrio', 'Harmonia'],
    ifaMessage: 'Oshe Meji representa o amor duplo e a beleza interior, trazendo harmonia aos corações.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 15,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Mercúrio', 'Saturno'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Leste',
    colors: ['Amarelo', 'Azul'],
    offerings: ['Cobre', 'Ferro', 'Milho'],
    ebos: ['Ebo de proteção', 'Ebo de coragem'],
    taboos: ['Não usar armas', 'Não cortar árvores'],
    strengths: ['Comunicação', 'Inteligência', 'Coragem'],
    weaknesses: ['Inconstância', 'Nervosismo'],
    health: ['Estômago', 'Útero'],
    meanings: ['Ferramentas', 'Comunicação', 'Destino', 'Coragem'],
    ifaMessage: 'Ogunda Meji revela coragem дуальную, mostrando os caminhos勇敢 do destino.',
  },
  {
    id: 'oyen',
    name: 'Oyen',
    portugueseName: 'Oyen',
    order: 16,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Peixes',
    dayOfWeek: 'Segunda-feira',
    direction: 'Noroeste',
    colors: ['Azul', 'Prata'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de sabedoria', 'Ebo de espiritualidade'],
    taboos: ['Não consumir sal em excesso', 'Não derramar sangue'],
    strengths: ['Sabedoria', 'Intuição', 'Espiritualidade'],
    weaknesses: ['Melancolia', 'Excesso de sensibilidade'],
    health: ['Pés', 'Sistema linfático'],
    meanings: ['Conhecimento', 'Sabedoria', 'Mistério', 'Espiritualidade'],
    ifaMessage: 'Oyen Meji abre o livro da sabedoria dupla, revelando segredos ocultos do universo.',
  },
];

export function getData(): MejiOdu[] {
  return MEJI_DATA;
}