// @ts-nocheck
// SKIP_LINT

/**
 * Okanle Meji Data
 * Odu of the traveler's path, guidance through journeys, and divine protection
 * The guide who walks alongside, ensuring safe passage and blessed arrivals
 */

// Okanle Meji represents the divine guide who protects travelers
// where the path is illuminated and journeys are blessed with safe arrival
// Governed by the forces of movement, guidance, and sacred protection
// Element: Movement/Light
// Represents travel, protection, guidance, and the blessing of the journey

export interface OkanleMejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const OKANLE_MEJI_DATA: OkanleMejiOdu[] = [
  {
    id: 'okanle-ros',
    name: 'Okanle Ros',
    portugueseName: 'Okanle Ros',
    order: 1,
    polarity: 'feminine',
    element: 'Movimento',
    planets: ['Mercurio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Gemeos, Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Amarelo', 'Azul claro', 'Branco'],
    offerings: ['Flores amarelas', 'Sementes', 'Azeite doce', 'Frutas'],
    ebos: ['Ebo de protecao na viagem', 'Ebo de orientacao'],
    taboos: ['Nao partir sem bencao', 'Nao recusar companhia'],
    strengths: ['Orientacao', 'Comunicacao', 'Guia seguro'],
    weaknesses: ['Indecisao', 'Ansiedade de chegada'],
    health: ['Maos', 'Pulmoes', 'Joelhos'],
    meanings: ['Guia', 'Protecao', 'Orientacao', 'Caminho seguro'],
    ifaMessage: 'Okanle reveals the travelers path with light.',
  },
  {
    id: 'okanle-da',
    name: 'Okanle Da',
    portugueseName: 'Okanle Da',
    order: 2,
    polarity: 'masculine',
    element: 'Terra de Passagem',
    planets: ['Terra', 'Saturno'],
    sephirot: ['Malkuth', 'Binah'],
    sign: 'Capricornio, Touro',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Marrom', 'Verde', 'Amarelo'],
    offerings: ['Terra de cruzamento', 'Raizes', 'Frutos da jornada', 'Farinha'],
    ebos: ['Ebo de fundamento no caminho', 'Ebo de ancoragem'],
    taboos: ['Nao caminhar sobre terra sagrada sem respeito', 'Nao abandonar o caminho'],
    strengths: ['Fundamento', 'Estabilidade', 'Ancestralidade'],
    weaknesses: ['Rigidez', 'Medo de mudança'],
    health: ['Pes', 'Coluna', 'Ossos'],
    meanings: ['Passagem', 'Limiar', 'Transicao sagrada', 'Terra firme'],
    ifaMessage: 'Okanle Da teaches that every crossing point holds sacred power, and that the journey itself transforms the traveler.',
  },
  {
    id: 'okanle-se',
    name: 'Okanle Se',
    portugueseName: 'Okanle Se',
    order: 3,
    polarity: 'feminine',
    element: 'Ar da Visao',
    planets: ['Mercurio', 'Netuno'],
    sephirot: ['Hod', 'Chesed'],
    sign: 'Aquario, Gemeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Azul', 'Amarelo', 'Branco'],
    offerings: ['Vento捕捉', 'Flores', 'Azeite', 'Plumas brancas'],
    ebos: ['Ebo de visao ampliada', 'Ebo de perspectiva'],
    taboos: ['Nao limitar horizontes', 'Nao temer o desconhecido'],
    strengths: ['Visao', 'Expansao', 'Perspectiva'],
    weaknesses: ['Dispersao', 'Sonho excessivo'],
    health: ['Mente', 'Bracos', 'Sistema nervoso'],
    meanings: ['Visao ampliada', 'Horizonte', 'Perspectiva', 'Liberdade'],
    ifaMessage: 'Okanle Se lifts the veil between what is and what could be, revealing that the road ahead holds promise for those who dare to see.',
  },
  {
    id: 'okanle-kan',
    name: 'Okanle Kan',
    portugueseName: 'Okanle Kan',
    order: 4,
    polarity: 'masculine',
    element: 'Metal de Protecao',
    planets: ['Marte', 'Ferro'],
    sephirot: ['Geburah', 'Netzach'],
    sign: 'Escorpiao, Aries',
    dayOfWeek: 'Terca-feira',
    direction: 'Nordeste',
    colors: ['Cinza', 'Vermelho escuro', 'Preto'],
    offerings: ['Ferro', 'Fumo', 'Aguardente', 'Palmeira'],
    ebos: ['Ebo de protecao militar', 'Ebo de defesa'],
    taboos: ['Nao entrar em territorio hostil sem forca', 'Nao mostrar fraqueza'],
    strengths: ['Protecao', 'Forca', 'Defesa'],
    weaknesses: ['Paranoia', 'Agressividade'],
    health: ['Intestinos', 'Musculos', 'Figado'],
    meanings: ['Escudo', 'Defesa', 'Forca protetora', 'Barreira sagrada'],
    ifaMessage: 'Okanle Kan raises the shield of divine protection, revealing that the road is safe for those who walk with courage.',
  },
  {
    id: 'okanle-rosi',
    name: 'Okanle Rosi',
    portugueseName: 'Okanle Rosi',
    order: 5,
    polarity: 'feminine',
    element: 'Agua de Bencao',
    planets: ['Lua', 'Venus'],
    sephirot: ['Yesod', 'Netzach'],
    sign: 'Cancer, Libra',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Rosa', 'Prata'],
    offerings: ['Agua de flor', 'Mel', 'Flores roseiras', 'Perolas'],
    ebos: ['Ebo de chegada', 'Ebo de boa vinda'],
    taboos: ['Nao rejeitar a hospitalidade', 'Nao desvalorizar bencaos'],
    strengths: ['Hospitalidade', 'Bencao', 'Chegada segura'],
    weaknesses: ['Dependencia', 'Apego ao destino'],
    health: ['Seios', 'Estomago', 'Pele'],
    meanings: ['Chegada', 'Destino', 'Hospitalidade', 'Bencao'],
    ifaMessage: 'Okanle Rosi blesses the arrival, revealing that every journey finds its purpose when we open our hearts to welcome.',
  },
  {
    id: 'okanle-oni',
    name: 'Okanle Oni',
    portugueseName: 'Okanle Oni',
    order: 6,
    polarity: 'masculine',
    element: 'Fogo do Guia',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphareth', 'Geburah'],
    sign: 'Leao, Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Vermelho', 'Laranja'],
    offerings: ['Velas', 'Mel', 'Frango', 'Azeite'],
    ebos: ['Ebo de lideranca no caminho', 'Ebo de forca interior'],
    taboos: ['Nao seguir falso guia', 'Nao abandonar lideranca'],
    strengths: ['Lideranca', 'Forca interior', 'Navegacao'],
    weaknesses: ['Orgulho', 'Autocrata'],
    health: ['Coracao', 'Olhos', 'Cabeca'],
    meanings: ['Guia principal', 'Lideranca', 'Fogo interior', 'Visao clara'],
    ifaMessage: 'Okanle Oni burns with the fire of true guidance, revealing that authentic leadership illuminates the darkest paths.',
  },
  {
    id: 'okanle-te',
    name: 'Okanle Te',
    portugueseName: 'Okanle Te',
    order: 7,
    polarity: 'feminine',
    element: 'Agua Estrela',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Peixes, Cancer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul escuro', 'Prata', 'Branco'],
    offerings: ['Agua de obi', 'Estrelas do mar', 'Flores noturnas', 'Conchas'],
    ebos: ['Ebo de sonhos na estrada', 'Ebo de intuicao viajeira'],
    taboos: ['Nao ignorar sonhos profeticos', 'Nao recusar sinais'],
    strengths: ['Intuicao', 'Visao noturna', 'Conexao espiritual'],
    weaknesses: ['ilusao', 'Confusao'],
    health: ['Pés', 'Liquidos corporais', 'Sistema imunologico'],
    meanings: ['Orientacao celestial', 'Sinos', 'Guia das estrelas', 'Sabedoria noturna'],
    ifaMessage: 'Okanle Te navigates by starlight, revealing that the universe itself conspires to guide those who journey with open hearts.',
  },
  {
    id: 'okanle-tura',
    name: 'Okanle Tura',
    portugueseName: 'Okanle Tura',
    order: 8,
    polarity: 'masculine',
    element: 'Fogo de Purificacao',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphareth', 'Geburah'],
    sign: 'Leao, Sagitario',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Vermelho', 'Laranja claro'],
    offerings: ['Velas douradas', 'Incenso', 'Mel', 'Frango branco'],
    ebos: ['Ebo de purificacao da jornada', 'Ebo de renovaçao'],
    taboos: ['Nao carregar bagagem pesada', 'Nao temer o fogo purificador'],
    strengths: ['Purificacao', 'Renovacao', 'Libertacao'],
    weaknesses: ['Impaciencia', 'Destruicao necessaria'],
    health: ['Coracao', 'Sangue', 'Pulmoes'],
    meanings: ['Porta sagrada', 'Renovacao', 'Purificacao', 'Novo começo'],
    ifaMessage: 'Okanle Tura burns away what no longer serves, revealing that every journey ends with a transformed self stepping into new light.',
  },
  {
    id: 'okanle-rin',
    name: 'Okanle Rin',
    portugueseName: 'Okanle Rin',
    order: 9,
    polarity: 'feminine',
    element: 'Ar de Alegria',
    planets: ['Venus', 'Jupiter'],
    sephirot: ['Netzach', 'Chesed'],
    sign: 'Libra, Sagitario',
    dayOfWeek: 'Quinta-feira',
    direction: 'Norte',
    colors: ['Rosa', 'Azul claro', 'Dourado'],
    offerings: ['Flores', 'Frutas doces', 'Mel', 'Vinho suave'],
    ebos: ['Ebo de viagem alegre', 'Ebo de companheirismo'],
    taboos: ['Nao viajar triste', 'Nao recusar alegria compartilhada'],
    strengths: ['Alegria', 'Companheirismo', 'Socializacao'],
    weaknesses: ['Superficialidade', 'Escapatismo'],
    health: ['Pulmoes', 'Ombros', 'Torax'],
    meanings: ['Companhia', 'Alegria compartilhada', 'Amigos na estrada', 'Socializacao'],
    ifaMessage: 'Okanle Rin dances along the road, revealing that the journey becomes sacred when walked in fellowship with joyful hearts.',
  },
  {
    id: 'okanle-fun',
    name: 'Okanle Fun',
    portugueseName: 'Okanle Fun',
    order: 10,
    polarity: 'masculine',
    element: 'Terra Profunda',
    planets: ['Saturno', 'Terra'],
    sephirot: ['Malkuth', 'Binah'],
    sign: 'Capricornio, Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Marrom', 'Verde escuro', 'Preto'],
    offerings: ['Raizes', 'Terra sagrada', 'Pedras de caminho', 'Ferro'],
    ebos: ['Ebo de retorno', 'Ebo de casa de volta'],
    taboos: ['Nao esquecer a origem', 'Nao perder raizes'],
    strengths: ['Retorno', 'Memoria', 'Fundamento'],
    weaknesses: ['Rigidez', 'Nostalgia excessiva'],
    health: ['Joelhos', 'Ossos', 'Coluna'],
    meanings: ['Retorno', 'Casa', 'Origem', 'Raizes de caminhada'],
    ifaMessage: 'Okanle Fun remembers the path behind and ahead, revealing that true travelers carry their origins wherever they roam.',
  },
  {
    id: 'okanle-je',
    name: 'Okanle Je',
    portugueseName: 'Okanle Je',
    order: 11,
    polarity: 'feminine',
    element: 'Agua de Luz',
    planets: ['Sol', 'Lua'],
    sephirot: ['Tiphareth', 'Yesod'],
    sign: 'Leao, Cancer',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Azul claro', 'Branco'],
    offerings: ['Agua solar', 'Flores amarelas', 'Mel dourado', 'Perolas'],
    ebos: ['Ebo de iluminacao', 'Ebo de clareza mental'],
    taboos: ['Nao fechar os olhos ao caminho', 'Nao temer a luz'],
    strengths: ['Iluminacao', 'Clareza', 'Verdade'],
    weaknesses: ['Exposicao excessiva', 'Vulnerabilidade'],
    health: ['Olhos', 'Coracao', 'Sistema digestivos'],
    meanings: ['Visao clara', 'Verdade revelada', 'Luz do caminho', 'Claridade'],
    ifaMessage: 'Okanle Je illuminates the path with inner light, revealing that clarity comes to those who journey with honest hearts.',
  },
  {
    id: 'okanle-roshi',
    name: 'Okanle Roshi',
    portugueseName: 'Okanle Roshi',
    order: 12,
    polarity: 'masculine',
    element: 'Metal Sábio',
    planets: ['Mercurio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Gemeos, Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Cinza', 'Branco', 'Azul'],
    offerings: ['Ferro antigo', 'Sedas', 'Livros', 'Azeite'],
    ebos: ['Ebo de sabedoria viajante', 'Ebo de mestria'],
    taboos: ['Nao ignorar conselhos sabios', 'Nao recusar aprendizado'],
    strengths: ['Sabedoria', 'Aprendizado', 'Mestria'],
    weaknesses: ['Perfeccionismo', 'Distancia emocional'],
    health: ['Maos', 'Cerebro', 'Bracos'],
    meanings: ['Sabedoria', 'Mestria', 'Conhecimento ambulante', 'Educacao'],
    ifaMessage: 'Okanle Roshi carries the wisdom of ten thousand roads, revealing that true mastery comes from humble wandering.',
  },
  {
    id: 'okanle-she',
    name: 'Okanle She',
    portugueseName: 'Okanle She',
    order: 13,
    polarity: 'feminine',
    element: 'Ar de Harmonia',
    planets: ['Venus', 'Lua'],
    sephirot: ['Netzach', 'Yesod'],
    sign: 'Libra, Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste',
    colors: ['Rosa', 'Verde claro', 'Dourado'],
    offerings: ['Flores harmoniosas', 'Mel', 'Azeite doce', 'Sedas'],
    ebos: ['Ebo de paz na jornada', 'Ebo de harmonia'],
    taboos: ['Nao criar discurdia no caminho', 'Nao perturbar equilibrio'],
    strengths: ['Harmonia', 'Equilibrio', 'Paz'],
    weaknesses: ['Evasao', 'Compromisso excessivo'],
    health: ['Rins', 'Torax', 'Lombar'],
    meanings: ['Harmonia', 'Equilibrio', 'Paz', 'Balanca'],
    ifaMessage: 'Okanle She maintains balance on every road, revealing that true peace comes from harmonious movement through life.',
  },
  {
    id: 'okanle-na',
    name: 'Okanle Na',
    portugueseName: 'Okanle Na',
    order: 14,
    polarity: 'masculine',
    element: 'Terra de Sabedoria',
    planets: ['Terra', 'Mercurio'],
    sephirot: ['Malkuth', 'Hod'],
    sign: 'Virgem, Capricornio',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Marrom', 'Verde', 'Amarelo ocre'],
    offerings: ['Terra de cruzada', 'Raizes sabias', 'Frutos da terra', 'Sementes'],
    ebos: ['Ebo de conhecimento terrestre', 'Ebo de aprendizado'],
    taboos: ['Nao desrespeitar a terra mae', 'Nao ignorar liçoes do caminho'],
    strengths: ['Conhecimento', 'Pragmatismo', 'Enraizamento'],
    weaknesses: ['Materialismo', 'Ceticismo'],
    health: ['Estomago', 'Intestinos', 'Pele'],
    meanings: ['Conhecimento', 'Terra sagrada', 'Aprendizado pratico', 'Sabedoria terrestre'],
    ifaMessage: 'Okanle Na walks the earth with learned feet, revealing that wisdom grows deepest when rooted in humble soil.',
  },
  {
    id: 'okanle-teti',
    name: 'Okanle Teti',
    portugueseName: 'Okanle Teti',
    order: 15,
    polarity: 'feminine',
    element: 'Agua de Transicao',
    planets: ['Lua', 'Mercurio'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Cancer, Gemeos',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul claro', 'Prata', 'Verde agua'],
    offerings: ['Agua de cruzamento', 'Flores aquaticas', 'Perolas', 'Conchas'],
    ebos: ['Ebo de limiar', 'Ebo de mudanca'],
    taboos: ['Nao hesitar na fronteira', 'Nao temer o novo'],
    strengths: ['Transicao', 'Adaptacao', 'Fluidez'],
    weaknesses: ['Instabilidade', 'Medo de permanencia'],
    health: ['Liquidos corporais', 'Bexiga', 'Rins'],
    meanings: ['Transicao', 'Limiar', 'Mudanca', 'Fluxo'],
    ifaMessage: 'Okanle Teti flows between worlds with grace, revealing that transformation happens at the water edge of change.',
  },
  {
    id: 'okanle-turupon',
    name: 'Okanle Turupon',
    portugueseName: 'Okanle Turupon',
    order: 16,
    polarity: 'masculine',
    element: 'Fogo do Destino',
    planets: ['Marte', 'Saturno'],
    sephirot: ['Geburah', 'Binah'],
    sign: 'Escorpiao, Capricornio',
    dayOfWeek: 'Terca-feira',
    direction: 'Sul',
    colors: ['Preto', 'Vermelho escuro', 'Cinza'],
    offerings: ['Fumo forte', 'Aguardente', 'Ferro', 'Carvao'],
    ebos: ['Ebo de destino', 'Ebo de forca interior'],
    taboos: ['Nao fugir do destino', 'Nao temer a verdade'],
    strengths: ['Determinacao', 'Forca interior', 'Proposito'],
    weaknesses: ['Obsessao', 'Rigidez fatalista'],
    health: ['Osso', 'Dentes', 'Coluna'],
    meanings: ['Destino', 'Proposito', 'Fado', 'Forca inevitavel'],
    ifaMessage: 'Okanle Turupon walks toward destiny with unwavering steps, revealing that the road we must travel finds us long before we find it.',
  },
];

export function getData(): OkanleMejiOdu[] {
  return OKANLE_MEJI_DATA;
}

export default getData;