// @ts-nocheck

// osetura-meji-data.ts — Osetura Meji divination data (16 Principal Odu of Obeche/Ifa)

export interface OseturaMejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const OSETURA_MEJI_DATA: OseturaMejiOdu[] = [
  {
    id: 'osetura-ogbe',
    name: 'Osetura-Ogbe',
    portugueseName: 'Osetura-Ogbe',
    order: 1,
    polarity: 'masculine',
    element: 'Fire/Ether',
    planets: ['Sol', 'Mercúrio'],
    sephirot: ['Chokmah', 'Binah'],
    sign: 'Aries/Sagittarius',
    dayOfWeek: 'Domingo',
    direction: 'Leste/Nordeste',
    colors: ['Azul', 'Branco', 'Vermelho'],
    offerings: ['Obí', 'Flores brancas', 'Mel', 'Velas azuis'],
    ebos: ['Ebo de orientação', 'Ebo de decisões importantes'],
    taboos: ['Não tomar decisões precipitadas', 'Não ignorar sinais divinos'],
    strengths: ['Sabedoria divina', 'Discernimento', 'Orientação clara'],
    weaknesses: ['Indecisão crônica', 'Superstição excessiva'],
    health: ['Cabeça', 'Mente', 'Sistema nervoso'],
    meanings: ['Criação', 'Início', 'Sabedoria nos cruzamentos', 'Orientação divina'],
    ifaMessage: 'Osetura-Ogbe representa o poder de criar realidade através da sabedoria divine, mostrando que toda decisão é um ato de criação do destino.',
  },
  {
    id: 'osetura-oyen',
    name: 'Osetura-Oyen',
    portugueseName: 'Osetura-Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water/Ether',
    planets: ['Lua', 'Mercúrio'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Câncer/Capricorn',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste/Noroeste',
    colors: ['Branco', 'Azul claro', 'Roxo'],
    offerings: ['Flores brancas', 'Água de flor de laranja', 'Alfa-vaca', 'Velas roxas'],
    ebos: ['Ebo de sabedoria', 'Ebo de proteção nos cruzamentos'],
    taboos: ['Não ocultar informações importantes', 'Não agir sem consultar'],
    strengths: ['Intuição profunda', 'Sabedoria ancestral', 'Clareza mental'],
    weaknesses: ['Excesso de reflexão', 'Dúvida constante'],
    health: ['Mente', 'Estômago', 'Intuição'],
    meanings: ['Conhecimento', 'Sabedoria oculta', 'Mistérios revelados', 'Encruzilhadas'],
    ifaMessage: 'Osetura-Oyen abre a porta da sabedoria dupla nos cruzamentos da vida, revelando caminhos ocultos ao consulente.',
  },
  {
    id: 'osetura-ogunda',
    name: 'Osetura-Ogunda',
    portugueseName: 'Osetura-Ogunda',
    order: 3,
    polarity: 'masculine',
    element: 'Metal/Ether',
    planets: ['Mercúrio', 'Marte'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Gêmeos/Escorpião',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte/Nordeste',
    colors: ['Azul', 'Amarelo', 'Branco'],
    offerings: ['Obí', 'Ferro', 'Palha processional', 'Nozes de decisão'],
    ebos: ['Ebo de caminhos', 'Ebo de alinhamento de destino'],
    taboos: ['Não evitar decisões difíceis', 'Não cortar caminhos prematurely'],
    strengths: ['Comunicação divina', 'Escolhas acertadas', 'Alinhamento espiritual'],
    weaknesses: ['Medo das mudanças', 'Procrastinação'],
    health: ['Mãos', 'Braços', 'Sistema respiratório'],
    meanings: ['Destino', 'Escolhas', 'Cruzamentos', 'Alinhamento'],
    ifaMessage: 'Osetura-Ogunda revela os múltiplos caminhos do destino, mostrando que cada cruzamento é uma oportunidade de crescimento espiritual.',
  },
  {
    id: 'osetura-oshe',
    name: 'Osetura-Oshe',
    portugueseName: 'Osetura-Oshe',
    order: 4,
    polarity: 'feminine',
    element: 'Earth/Ether',
    planets: ['Vênus', 'Mercúrio'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Libra/Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste/Sudoeste',
    colors: ['Azul claro', 'Verde', 'Branco'],
    offerings: ['Flores', 'Mel', 'Alfa-vaca', 'Velas azuis claras'],
    ebos: ['Ebo de harmonia', 'Ebo de equilíbrio nas decisões'],
    taboos: ['Não forçar decisões', 'Não atuar com desequilíbrio'],
    strengths: ['Equilíbrio', 'Harmonia', 'Discernimento pacífico'],
    weaknesses: ['Indecisão por busca de perfeição', 'Evitar conflitos'],
    health: ['Rins', 'Coluna', 'Sistema digestivo'],
    meanings: ['Equilíbrio', 'Harmonia', 'Escolhas equilibradas', 'Beleza nos caminhos'],
    ifaMessage: 'Osetura-Oshe ensina que a sabedoria verdadeira está no equilíbrio entre ação e reflexão, harmonia nos cruzamentos.',
  },
  {
    id: 'osetura-irosun',
    name: 'Osetura-Irosun',
    portugueseName: 'Osetura-Irosun',
    order: 5,
    polarity: 'feminine',
    element: 'Fire/Ether',
    planets: ['Sol', 'Mercúrio'],
    sephirot: ['Tiphereth', 'Hod'],
    sign: 'Leão/Virgem',
    dayOfWeek: 'Domingo',
    direction: 'Centro/Nordeste',
    colors: ['Branco', 'Azul', 'Dourado'],
    offerings: ['Obí', 'Velas brancas', 'Farinha de mandioca', 'Mel'],
    ebos: ['Ebo de cura', 'Ebo de proteção cruzamentos'],
    taboos: ['Não ignorar necessidades espirituais', 'Não negligenciar saúde'],
    strengths: ['Proteção divina', 'Cura', 'Iluminação nos caminhos'],
    weaknesses: ['Excesso de preocupação', 'Ansiedade ante decisões'],
    health: ['Coração', 'Olhos', 'Sistema imunológico'],
    meanings: ['Proteção', 'Cura', 'Iluminação', 'Escolhas sagradas'],
    ifaMessage: 'Osetura-Irosun oferece proteção divina nos cruzamentos, iluminando caminhos obscurecidos pela dúvida e pelo medo.',
  },
  {
    id: 'osetura-odi',
    name: 'Osetura-Odi',
    portugueseName: 'Osetura-Odi',
    order: 6,
    polarity: 'masculine',
    element: 'Water/Ether',
    planets: ['Lua', 'Saturno'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Escorpião/Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Preto', 'Azul escuro'],
    offerings: ['Água', 'Velas pretas', 'Obí', 'Ervas de proteção'],
    ebos: ['Ebo de encruzilhada', 'Ebo de fortalecimento mental'],
    taboos: ['Não se render ao medo', 'Não evitar confrontos necessários'],
    strengths: ['Resistência', 'Força interior', 'Superação de obstáculos'],
    weaknesses: ['Pessimismo', 'Medo paralisante'],
    health: ['Genitais', 'Sistema excretor', 'Mente'],
    meanings: ['Resistência', 'Superação', 'Força nos cruzamentos sombrios'],
    ifaMessage: 'Osetura-Odi transforma cruzamentos sombrios em passagens de luz, mostrando que toda escuridão carrega o germe da sabedoria.',
  },
  {
    id: 'osetura-ossai',
    name: 'Osetura-Ossai',
    portugueseName: 'Osetura-Ossai',
    order: 7,
    polarity: 'feminine',
    element: 'Earth/Ether',
    planets: ['Vênus', 'Netuno'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Touro/Virgem',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul/Sudoeste',
    colors: ['Verde', 'Azul claro', 'Branco'],
    offerings: ['Frutas', 'Flores silvestres', 'Mel', 'Velas verdes'],
    ebos: ['Ebo de fartura', 'Ebo de prosperidade nos caminhos'],
    taboos: ['Não desperdiçar recursos', 'Não ser invejoso'],
    strengths: ['Prosperidade', 'Fertilidade', 'Abundância'],
    weaknesses: ['Ganância', 'Acomodação'],
    health: ['Garganta', 'Pescoço', 'Sistema hormonal'],
    meanings: ['Prosperidade', 'Fartura', 'Caminhos abundantes'],
    ifaMessage: 'Osetura-Ossai revela que cada cruzamento carrega sementes de abundância para quem sabe reconhecê-las.',
  },
  {
    id: 'osetura-oba',
    name: 'Osetura-Oba',
    portugueseName: 'Osetura-Oba',
    order: 8,
    polarity: 'feminine',
    element: 'Fire/Water',
    planets: ['Sol', 'Lua'],
    sephirot: ['Tiphereth', 'Malkuth'],
    sign: 'Leão/Câncer',
    dayOfWeek: 'Domingo',
    direction: 'Leste/Oeste',
    colors: ['Vermelho', 'Branco', 'Azul'],
    offerings: ['Pão', 'Velas vermelhas', 'Água sagrada', 'Flores brancas'],
    ebos: ['Ebo de lealdade', 'Ebo de proteção do lar'],
    taboos: ['Não traído confiança', 'Não abandonar compromissos'],
    strengths: ['Lealdade', 'Honradez', 'Proteção do círculo sagrado'],
    weaknesses: ['Rigidez', 'Dificuldade de perdoar'],
    health: ['Coração', 'Seios', 'Sistema circulatório'],
    meanings: ['Lealdade', 'Honra', 'Proteção sagrada', 'Escolhas corretas'],
    ifaMessage: 'Osetura-Oba ensina que a verdadeira sabedoria está em manter a lealdade aos compromissos divinos nos cruzamentos da vida.',
  },
  {
    id: 'osetura-oyeku',
    name: 'Osetura-Oyeku',
    portugueseName: 'Osetura-Oyeku',
    order: 9,
    polarity: 'masculine',
    element: 'Earth/Water',
    planets: ['Saturno', 'Plutão'],
    sephirot: ['Binah', 'Malkuth'],
    sign: 'Capricórnio/Escorpião',
    dayOfWeek: 'Sábado',
    direction: 'Sul',
    colors: ['Preto', 'Roxo', 'Branco'],
    offerings: ['Nozes escuras', 'Velas pretas', 'Obí', 'Ervas de proteção'],
    ebos: ['Ebo de transformação', 'Ebo de proteção contra negativity'],
    taboos: ['Não temer transformação', 'Não resistir a mudanças necessárias'],
    strengths: ['Transformação', 'Regeneração', 'Superação de provas'],
    weaknesses: ['Medo profundo', 'Resistência ao novo'],
    health: ['Ossos', 'Dentes', 'Sistema imune'],
    meanings: ['Transformação', 'Reinício', 'Passagem para novos caminhos'],
    ifaMessage: 'Osetura-Oyeku transforma o medo da mudança em sabedoria, revelando que todo cruzamento é uma oportunidade de renascimento.',
  },
  {
    id: 'osetura-inle',
    name: 'Osetura-Inle',
    portugueseName: 'Osetura-Inle',
    order: 10,
    polarity: 'masculine',
    element: 'Air/Ether',
    planets: ['Mercúrio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Gêmeos/Câncer',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Branco', 'Azul claro', 'Amarelo'],
    offerings: ['Peixe', 'Velas claras', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de saúde', 'Ebo de viagens seguras'],
    taboos: ['Não negligenciar saúde', 'Não viajar sem proteção'],
    strengths: ['Comunicação', 'Bilingüismo', 'Viagens espirituais'],
    weaknesses: ['Inconstância', 'Nervosismo'],
    health: ['Pulmões', 'Sistema respiratório', 'Articulações'],
    meanings: ['Saúde', 'Viagens', 'Comunicação clara', 'Escolhas móviles'],
    ifaMessage: 'Osetura-Inle abre caminhos para saúde e viagens seguras, mostrando que movimento e comunicação são sabedoria nos cruzamentos.',
  },
  {
    id: 'osetura-sawos',
    name: 'Osetura-Sawos',
    portugueseName: 'Osetura-Sawos',
    order: 11,
    polarity: 'feminine',
    element: 'Ether/Water',
    planets: ['Júpiter', 'Netuno'],
    sephirot: ['Chesed', 'Binah'],
    sign: 'Sagitário/Peixes',
    dayOfWeek: 'Quinta-feira',
    direction: 'Noroeste',
    colors: ['Azul', 'Roxo', 'Branco'],
    offerings: ['Frutos do mar', 'Velas azuis', 'Obí', 'Flores de lótus'],
    ebos: ['Ebo de expansão', 'Ebo de proteção espiritual'],
    taboos: ['Não limitar visão', 'Não rejeitar conhecimento'],
    strengths: ['Expansão', 'Sabedoria filosófica', 'Proteção ampla'],
    weaknesses: ['Excesso de idealismo', 'Dificuldade de concretização'],
    health: ['Fígado', 'Quadris', 'Sistema nervoso'],
    meanings: ['Expansão', 'Filosofia', 'Proteção ampla', 'Caminhos longos'],
    ifaMessage: 'Osetura-Sawos expande a consciência além dos cruzamentos imediatos, revelando horizontes mais amplos para decisões wiser.',
  },
  {
    id: 'osetura-beji',
    name: 'Osetura-Beji',
    portugueseName: 'Osetura-Beji',
    order: 12,
    polarity: 'feminine',
    element: 'Earth/Fire',
    planets: ['Terra', 'Sol'],
    sephirot: ['Malkuth', 'Tiphereth'],
    sign: 'Touro/Leão',
    dayOfWeek: 'Segunda-feira',
    direction: 'Centro',
    colors: ['Marrom', 'Branco', 'Azul'],
    offerings: ['Grãos', 'Velas marrons', 'Farinha', 'Mel'],
    ebos: ['Ebo de fertilidade', 'Ebo de estabilidade'],
    taboos: ['Não desrespeitar a terra', 'Não desperdiçar recursos'],
    strengths: ['Estabilidade', 'Fertilidade', 'Grounding'],
    weaknesses: ['Materialismo excessivo', 'Rigidez'],
    health: ['Pele', 'Ossos', 'Sistema digestivo'],
    meanings: ['Estabilidade', 'Fertilidade', 'Raízes', 'Escolhas fundamentadas'],
    ifaMessage: 'Osetura-Beji ancora a sabedoria nos cruzamentos, mostrando que decisões sábias precisam de fundamento estável.',
  },
  {
    id: 'osetura-ogbe-ogunda',
    name: 'Osetura-Ogbe-Ogunda',
    portugueseName: 'Osetura-Ogbe-Ogunda',
    order: 13,
    polarity: 'masculine',
    element: 'Fire/Metal',
    planets: ['Sol', 'Marte', 'Mercúrio'],
    sephirot: ['Chokmah', 'Gevurah', 'Hod'],
    sign: 'Aries/Escorpião',
    dayOfWeek: 'Domingo',
    direction: 'Leste/Norte',
    colors: ['Vermelho', 'Azul', 'Amarelo'],
    offerings: ['Obí', 'Ferro', 'Mel', 'Velas vermelhas e azuis'],
    ebos: ['Ebo de conquista', 'Ebo de alinhamento de destino'],
    taboos: ['Não agir com violência', 'Não forçar resultados'],
    strengths: ['Conquista', 'Vitória', 'Determinação aligned'],
    weaknesses: ['Impaciência', 'Agressividade'],
    health: ['Cabeça', 'Músculos', 'Articulações'],
    meanings: ['Conquista', 'Vitória', 'Destino manifesto', 'Cruzamento decisivo'],
    ifaMessage: 'Osetura-Ogbe-Ogunda representa a vitória nos cruzamentos do destino, onde a sabedoria encontra a determinação para criar realidade.',
  },
  {
    id: 'osetura-ogunda-ogbe',
    name: 'Osetura-Ogunda-Ogbe',
    portugueseName: 'Osetura-Ogunda-Ogbe',
    order: 14,
    polarity: 'masculine',
    element: 'Metal/Fire',
    planets: ['Marte', 'Mercúrio', 'Sol'],
    sephirot: ['Gevurah', 'Hod', 'Chokmah'],
    sign: 'Escorpião/Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte/Leste',
    colors: ['Azul', 'Vermelho', 'Branco'],
    offerings: ['Ferro', 'Obí', 'Nozes', 'Velas azuis e vermelhas'],
    ebos: ['Ebo de estratégia', 'Ebo de proteção em conflictos'],
    taboos: ['Não evitar confrontos necessários', 'Não agir sem estratégia'],
    strengths: ['Estratégia', 'Proteção', 'Comunicação de poder'],
    weaknesses: ['Conflito interno', 'Dúvida sobre capacidades'],
    health: ['Mãos', 'Cabeça', 'Sistema nervoso'],
    meanings: ['Estratégia', 'Proteção', 'Conflito resoluto', 'Caminho determinado'],
    ifaMessage: 'Osetura-Ogunda-Ogbe revela que a verdadeira força nos cruzamentos está na estratégia sábia, não na força bruta.',
  },
  {
    id: 'osetura-oye-ossen',
    name: 'Osetura-Oye-Ossen',
    portugueseName: 'Osetura-Oye-Ossen',
    order: 15,
    polarity: 'masculine',
    element: 'Air/Earth',
    planets: ['Mercúrio', 'Vênus', 'Terra'],
    sephirot: ['Hod', 'Netzach', 'Malkuth'],
    sign: 'Virgem/Libra',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sudeste',
    colors: ['Azul claro', 'Verde', 'Amarelo'],
    offerings: ['Frutas', 'Velas claras', 'Flores', 'Mel'],
    ebos: ['Ebo de comunicação', 'Ebo de relações harmoniosas'],
    taboos: ['Não omitir verdades importantes', 'Não silenciar sabedoria'],
    strengths: ['Comunicação clara', 'Relacionamentos harmoniosos', 'Discernimento'],
    weaknesses: ['Superficialidade', 'Indecisão em questões de princípio'],
    health: ['Braços', 'Pernas', 'Sistema digestivo'],
    meanings: ['Comunicação', 'Relacionamentos', 'Equilíbrio social', 'Escolhas colaborativas'],
    ifaMessage: 'Osetura-Oye-Ossen ensina que os melhores caminhos se revelam através do diálogo sagrado e da harmonia com outros.',
  },
  {
    id: 'osetura-ossen-beji',
    name: 'Osetura-Ossen-Beji',
    portugueseName: 'Osetura-Ossen-Beji',
    order: 16,
    polarity: 'masculine',
    element: 'Ether/Earth',
    planets: ['Netuno', 'Terra', 'Sol'],
    sephirot: ['Kether', 'Malkuth', 'Tiphereth'],
    sign: 'Peixes/Touro',
    dayOfWeek: 'Quinta-feira',
    direction: 'Norte/Sul',
    colors: ['Roxo', 'Marrom', 'Branco'],
    offerings: ['Obí', 'Grãos', 'Velas roxas', 'Flores brancas'],
    ebos: ['Ebo de transcendência', 'Ebo de embodiment espiritual'],
    taboos: ['Não negar espiritualidade', 'Não dissociar de realidade'],
    strengths: ['Transcendência', 'Sabedoria intuitiva', 'Conexão cósmica'],
    weaknesses: ['Dissociação', 'Excesso de fantasia'],
    health: ['Pés', 'Mente', 'Sistema imunológico'],
    meanings: ['Transcendência', 'Unificação', 'Sabedoria cósmica', 'Caminhos eternos'],
    ifaMessage: 'Osetura-Ossen-Beji representa a sabedoria suprema nos cruzamentos, onde o consulente acessa conhecimento que transcende o tempo e o espaço.',
  },
];

export function getData(): OseturaMejiOdu[] {
  return OSETURA_MEJI_DATA;
}