// @ts-nocheck
// SKIP_LINT

/**
 * Otura Meji Data
 * Odu of divine alignment, peace, and spiritual faith through doubled revelation
 * Represents the twin aspects of Otura's divine peace manifesting certainty
 */

// Otura Meji represents the double manifestation of divine alignment
// where peace flows in balanced dual currents of sacred certainty
// Governed by the purple light of spiritual peace and white light of divine purity
// Element: Spirit & Water
// Represents faith, peace, surrender, divine alignment, and spiritual certainty

export interface OturaMejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const OTURA_MEJI_DATA: OturaMejiOdu[] = [
  {
    id: 'otura-meji-ros',
    name: 'Otura Meji Ros',
    portugueseName: 'Otura Meji Ros',
    order: 1,
    polarity: 'feminine',
    element: 'Agua Espiritual',
    planets: ['Neptuno', 'Lua'],
    sephirot: ['Kether', 'Chokmah', 'Binah'],
    sign: 'Peixes, Cancer',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Roxo', 'Branco', 'Lavanda'],
    offerings: ['Agua de cheiro', 'Flores brancas', 'Veladoras roxas', 'Mel', 'Coco ralado', 'Alecrim'],
    ebos: ['Ebo de paz interior', 'Ebo de alinhamento divino'],
    taboos: ['Nao confiar na_vontade divina', 'Nao abandonar a_fé nos momentos dificeis'],
    strengths: ['Fé estabelecida', 'Paz interior', 'Alinhamento espiritual'],
    weaknesses: ['Ansiedade', 'Impaciência com o tempo divino'],
    health: ['Sistemas nervoso', 'Mente', 'Espirito'],
    meanings: ['Alinhamento divino', 'Paz interior', 'Fé certa', 'Confiança sagrada'],
    ifaMessage: 'Otura Meji Ros revela que a paz verdadeira nace da confiança absoluta na_vontade divina, e que o alinhamento espiritual e a recompensa para quem caminha com fé.',
  },
  {
    id: 'otura-meji-da',
    name: 'Otura Meji Da',
    portugueseName: 'Otura Meji Da',
    order: 2,
    polarity: 'masculine',
    element: 'Terra Espiritual',
    planets: ['Saturno', 'Terra'],
    sephirot: ['Malkuth', 'Chesed'],
    sign: 'Capricornio, Touro',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Roxo escuro', 'Branco', 'Prata'],
    offerings: ['Terra sagrada', 'Pedras quartz', 'Velas brancas', 'Amendoim', 'Fumo deerva'],
    ebos: ['Ebo de surrender', 'Ebo de aceitaçao'],
    taboos: ['Resistir ao_fuxo da_vida', 'Forçar situaçoes alem do tempo'],
    strengths: ['Aceitação', 'Surrender', 'Perseverança sagrada'],
    weaknesses: ['Passividade em_excesso', 'Abandono de responsabilidade'],
    health: ['Osso', 'Articulaçoes', 'Joelhos'],
    meanings: ['Surrender ao_sagrado', 'Aceitação do_caminho', 'Confiança no tempo divino'],
    ifaMessage: 'Otura Meji Da ensina que a verdadeira força está em saber quando agir e quando aguardar, aceitaando o_rítmo do cosmos com gracia e paciência.',
  },
  {
    id: 'otura-meji-logu',
    name: 'Otura Meji Logu',
    portugueseName: 'Otura Meji Logu',
    order: 3,
    polarity: 'feminine',
    element: 'Fogo Espiritual',
    planets: ['Sol', 'Jupiter'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Leão, Sagitário',
    dayOfWeek: 'Quarta-feira',
    direction: 'Leste',
    colors: ['Dourado', 'Roxo', 'Laranja'],
    offerings: ['Mel dourado', 'Canela', 'Sálvia', 'Velas douradas', 'Frutas还是比较复杂'],
    ebos: ['Ebo de coragem espiritual', 'Ebo de light interior'],
    taboos: ['Esconder a_verdade de_si_mesmo', 'Fingir paz que nao existe'],
    strengths: ['Luz interior', 'Coragem de ser verdadeiro', 'Iluminação'],
    weaknesses: ['Exposição em_excesso', 'Intensidade que quema'],
    health: ['Coração', 'Sangue', 'Energia vital'],
    meanings: ['Luz interior', 'Coragem espiritual', 'Iluminação da_alma', 'Verdade revelada'],
    ifaMessage: 'Otura Meji Logu brilha com a luz que vem de dentro, revelando que a verdadeira coragem e ser verdadeiro consigo mesmo e com o_divino, mesmo quando e_difícil.',
  },
  {
    id: 'otura-meji-texeira',
    name: 'Otura Meji Texeira',
    portugueseName: 'Otura Meji Texeira',
    order: 4,
    polarity: 'masculine',
    element: 'Ar Espiritual',
    planets: ['Mercurio', 'Venus'],
    sephirot: ['Netzach', 'Tiphareth'],
    sign: 'Gêmeos, Libra',
    dayOfWeek: 'Quarta-feira',
    direction: 'Oeste',
    colors: ['Azul claro', 'Roxo suave', 'Branco'],
    offerings: ['Incenso de sálvia', 'Flores de lavanda', 'Agua de flor', 'Pena de pomba'],
    ebos: ['Ebo de comunicaçao sagrada', 'Ebo de harmonização'],
    taboos: ['Bloquear a_comunicaçao com_o espirito', 'Ignorar os_sinais divinos'],
    strengths: ['Comunicação espiritual', 'Harmonização', 'Discernimento'],
    weaknesses: ['Indecisão', 'Superficialidade'],
    health: ['Pulmões', 'Membranas mucosas', 'Respiraçao'],
    meanings: ['Comunicaçao sagrada', 'Harmonização', 'Paz compartilhada', 'Discernimento divino'],
    ifaMessage: 'Otura Meji Texeira flutua nos ventos da comunicação sagrada, ensinando que a paz verdadeira se encontra quando ouvimos e somos ouvidos pelo universo.',
  },
  {
    id: 'otura-meji-aranha',
    name: 'Otura Meji Aranha',
    portugueseName: 'Otura Meji Aranha',
    order: 5,
    polarity: 'feminine',
    element: 'Teia Espiritual',
    planets: ['Lua', 'Mercurio'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Cancer, Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Centro',
    colors: ['Roxo', 'Preto', 'Escarlate'],
    offerings: ['Teia de aranha', 'Pedras obsidiana', 'Velas pretas', 'Sangue de galinha'],
    ebos: ['Ebo de destino', 'Ebo de misterio'],
    taboos: ['Romper teias do destino', 'Desrespectarancestrais'],
    strengths: ['Conexão com mistérios', 'Sabedoria oculta', 'Força de vontade'],
    weaknesses: ['Manipulação', 'Segredos em_excesso'],
    health: ['Sistema imune', 'Timo', 'Abdomem'],
    meanings: ['Destino tecido', 'Mistérios sagrados', 'Teia da_vida', 'Sabedoria oculta'],
    ifaMessage: 'Otura Meji Aranha tece os fios do destino com precisão sagrada, mostrando que cada conexao tem um propósito e cada teia uma razâo.',
  },
  {
    id: 'otura-meji-ossanha',
    name: 'Otura Meji Ossanha',
    portugueseName: 'Otura Meji Ossanha',
    order: 6,
    polarity: 'masculine',
    element: 'Terra Cura',
    planets: [' Terra', 'Marte'],
    sephirot: ['Malkuth', 'Gevurah'],
    sign: 'Touro, Aries',
    dayOfWeek: 'Quarta-feira',
    direction: 'Leste',
    colors: ['Verde', 'Marrom', 'Dourado'],
    offerings: ['Ervas verdes', 'Raizes de Y向她', 'Folhas de eucalipto', 'Terra vermelha'],
    ebos: ['Ebo de cura profunda', 'Ebo de reconciliaçao'],
    taboos: ['Usar plantas para_fins destrutivos', 'Envenenamento de qualquer forma'],
    strengths: ['Poder de cura', 'Reconciliaçao', 'Gentileza fuerte'],
    weaknesses: ['Culpa em_excesso', 'Sacrifício inutile'],
    health: ['Todo o_corpo', 'Sistema de healers', 'Sangramento'],
    meanings: ['Cura da_alma', 'Reconciliaçao', 'Plantas sagradas', '温柔却坚定'],
    ifaMessage: 'Otura Meji Ossanha traz a cura que vem da terra, mostrando que a reconciliaçao comself e com outros e o primeiro passo para a paz verdadeira.',
  },
  {
    id: 'otura-meji-ossaim',
    name: 'Otura Meji Ossaim',
    portugueseName: 'Otura Meji Ossaim',
    order: 7,
    polarity: 'feminine',
    element: 'Floresta Espiritual',
    planets: [' Venus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Verde escuro', 'Marrom', 'Amarelo selva'],
    offerings: ['Folhas de遍了', 'Rebentos frescos', 'Terra da_flroesta', 'Peças de животных'],
    ebos: ['Ebo de naturaleza', 'Ebo de conexao com_a terra'],
    taboos: ['Desmatamento', 'Destruiçao da naturea'],
    strengths: ['Conexão com natureza', 'Sabedoria herbal', 'Grounding'],
    weaknesses: ['Medo do mundo', 'Isolamento'],
    health: ['Figado', 'Vesícula', 'Músculos'],
    meanings: ['Sabedoria herbal', 'Conexão florestal', 'Grounding', 'Força da_terra'],
    ifaMessage: 'Otura Meji Ossaim sussurra nos ventos da floresta, ensinando que a paz se encontra na conexao com a terra e na simplicidade da_vida natural.',
  },
  {
    id: 'otura-meji-ogbe',
    name: 'Otura Meji Ogbe',
    portugueseName: 'Otura Meji Ogbe',
    order: 8,
    polarity: 'masculine',
    element: 'Inicio Espiritual',
    planets: ['Sol', 'Jupiter'],
    sephirot: ['Kether', 'Chokmah'],
    sign: 'Sagitário, Leão',
    dayOfWeek: 'Quarta-feira',
    direction: 'Leste',
    colors: ['Ouro', 'Azul royal', 'Branco'],
    offerings: ['Café torrado', 'Nozes', 'Fumo de ervas', 'Velas doradas'],
    ebos: ['Ebo de novos começos', 'Ebo de expansão'],
    taboos: ['Recusar oportunidades de crescimento', 'Fechar portas'],
    strengths: ['Iniciaçao', 'Expansão', 'Potencial infinito'],
    weaknesses: ['Impaciência', 'Ansiedade de começar'],
    health: ['Cabega', 'Mente expansiva', 'Sistema nervoso'],
    meanings: ['Novo começo', 'Iniciaçao sagrada', 'Expansão', 'Primeiro passo divino'],
    ifaMessage: 'Otura Meji Ogbe abre as portas do cosmos com a chiave da fé, mostrando que cada começo e uma oportunidade de alinhamento com o_divino.',
  },
  {
    id: 'otura-meji-ogunda',
    name: 'Otura Meji Ogunda',
    portugueseName: 'Otura Meji Ogunda',
    order: 9,
    polarity: 'feminine',
    element: 'Caos Espiritual',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Gevurah', 'Hod'],
    sign: 'Aries, Escorpião',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Vermelho', 'Preto', 'Roxo profundo'],
    offerings: ['Azeite vermelho', 'Ferro', 'Sangrar de propia mano', 'Velas vermelhas'],
    ebos: ['Ebo de transformaçao', 'Ebo de atravessar o_fogo'],
    taboos: ['Usar violencia', 'Destruiçao sem propósito'],
    strengths: ['Coragem em crise', 'Transformação', 'Sobrevivencia'],
    weaknesses: ['Destruiçao de relationships', 'Ma إدارة'],
    health: ['Sangue', 'Corpo físico', 'Força vital'],
    meanings: ['Transformação através do_fogo', 'Coragem em crise', 'Sobrevivência sagrada', 'Regeneração'],
    ifaMessage: 'Otura Meji Ogunda atravessa o caos com a certeza de que a destruição precede a criação, mostrando que a paz pode nascer do centro da tempestade.',
  },
  {
    id: 'otura-meji-osa',
    name: 'Otura Meji Osa',
    portugueseName: 'Otura Meji Osa',
    order: 10,
    polarity: 'masculine',
    element: 'Tempestade Espiritual',
    planets: ['Urano', 'Saturno'],
    sephirot: ['Binah', 'Chokmah'],
    sign: 'Aquário, Capricornio',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Azul electrico', 'Prata', 'Branco brilhante'],
    offerings: ['Para-raios miniatura', 'Agua de chuva', 'Sal marinho', 'Velas electricaz'],
    ebos: ['Ebo de mudança', 'Ebo de ruptura de padrões'],
    taboos: ['Resistir à mudança', 'Acomodar no_stagnation'],
    strengths: ['Mudança estrutural', 'Inovaçao', 'Libertação'],
    weaknesses: ['Destabilização em_excesso', 'Irregularidade'],
    health: ['Sistema nervoso', 'Mente', 'Articulaçõess'],
    meanings: ['Mudança inevitável', 'Liberdade através da_turbulência', 'Novo paradigma'],
    ifaMessage: 'Otura Meji Osa traz a tempestade que limpa o ar e rompe padrões velhos, mostrando que a paz verdadera veces require uma boa sacudida.',
  },
  {
    id: 'otura-meji-owonrin',
    name: 'Otura Meji Owonrin',
    portugueseName: 'Otura Meji Owonrin',
    order: 11,
    polarity: 'feminine',
    element: 'Maré Espiritual',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Kether'],
    sign: 'Cancer, Peixes',
    dayOfWeek: 'Quarta-feira',
    direction: 'Oeste',
    colors: ['Azul profundo', 'Escuro', 'Lunar branco'],
    offerings: ['Água do mar', 'Conchas', 'Pérolas', 'Velas azuis'],
    ebos: ['Ebo de fluxo', 'Ebo de aceitaçao do_rítmo'],
    taboos: ['Lutar contra a_correnteza', 'Ignorar rhythms naturais'],
    strengths: ['Adaptação', 'Fluidez', 'Conexão lunar'],
    weaknesses: ['Inconstância', 'Perda de 방향'],
    health: ['Sistemas corporais', 'Fluidos', 'Ciclo lunar'],
    meanings: ['Fluxo e refluxo', 'Aceitação do ritmo', 'Sabedoria lunar', 'Adaptaçao'],
    ifaMessage: 'Otura Meji Owonrin cavalga as ondas do destino com a graça de quem sabe que a maré sempre volta, ensinando a fluir com os ciclos.',
  },
  {
    id: 'otura-meji-odi',
    name: 'Otura Meji Odi',
    portugueseName: 'Otura Meji Odi',
    order: 12,
    polarity: 'masculine',
    element: 'Muro Espiritual',
    planets: ['Saturno', 'Marte'],
    sephirot: ['Tipareth', 'Gevurah'],
    sign: 'Escorpião, Capricornio',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Preto', 'Vermelho escuro', 'Ouro'],
    offerings: ['Feijões pretos', 'Carne seca', 'Velas pretas', 'Pedra protetora'],
    ebos: ['Ebo de proteçao', 'Ebo de limite sagrado'],
    taboos: ['Transgredir limites', 'Romper pactos'],
    strengths: ['Proteção', 'Fronteiras', 'Compromisso'],
    weaknesses: ['Rigidez', 'Paranoia'],
    health: ['Intestinos', 'Sistema excretor', 'Coluna'],
    meanings: ['Proteção sagrada', 'Limites necessários', 'Compromisso profundo', 'Força deguarda'],
    ifaMessage: 'Otura Meji Odi ergue muros de proteção ao redor da paz sagrada, mostrando que a verdadeira fé inclui saber o que proteger.',
  },
  {
    id: 'otura-meji-irosun',
    name: 'Otura Meji Irosun',
    portugueseName: 'Otura Meji Irosun',
    order: 13,
    polarity: 'feminine',
    element: 'Encruzilhada Espiritual',
    planets: ['Mercúrio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Virgem, Gêmeos',
    dayOfWeek: 'Domingo',
    direction: 'Centro',
    colors: ['Vermelho e preto', 'Marrom', 'Ouro antigo'],
    offerings: ['Milho moído', 'Dindinha', 'Kolanut', 'Velas de sebo'],
    ebos: ['Ebo de escolha correta', 'Ebo de crossroads'],
    taboos: ['Parar sem_verificar a_via', 'Ignorar prescientes'],
    strengths: ['Escolha sábia', 'Decisão rápido', 'Conexão ancestral'],
    weaknesses: ['Indecisão crônica', 'Mudar de camino demais'],
    health: ['Mente', 'Sistema digestvo', 'Nervos'],
    meanings: ['Encruzilhada de運命', 'Escolha sagrada', 'Decisão entrecruzada', 'Ancestral wisdom'],
    ifaMessage: 'Otura Meji Irosun marca as encruzilhadas do destino com sinais claros para quem tem fé para ver, mostrando que toda escolha tem um guia.',
  },
  {
    id: 'otura-meji-ozozun',
    name: 'Otura Meji Ozozun',
    portugueseName: 'Otura Meji Ozozun',
    order: 14,
    polarity: 'masculine',
    element: 'Veneno Espiritual',
    planets: ['Plutão', 'Marte'],
    sephirot: ['Gevurah', 'Din'],
    sign: 'Escorpião, Aries',
    dayOfWeek: 'Quarta-feira',
    direction: 'Leste',
    colors: ['Verde venenoso', 'Amarelo tóxico', 'Preto'],
    offerings: ['Veneno de cobra', 'Figado de animal', 'Ferro enferrujado', 'Alcool forte'],
    ebos: ['Ebo de desintoxicaçao', 'Ebo de proteçao contra veneno'],
    taboos: ['Usar veneno contra outros', 'Envenenar relaciones'],
    strengths: ['Desintoxicaçao', 'Transformação do_toxico em_tônico', 'Sobrevivencia'],
    weaknesses: ['Propensão a veneno', 'Destruiçao própria'],
    health: ['Figado', 'Rins', 'Sangue'],
    meanings: ['Veneno que cura', 'Desintoxicaçao', 'Transformação do sombra', 'Antídoto encontrado'],
    ifaMessage: 'Otura Meji Ozozun ensina que o mesmo veneno que destrói também pode curar quando preparado com intención e respeito, e que a paz requiere desintoxicação.',
  },
  {
    id: 'otura-meji-oyekun',
    name: 'Otura Meji Oyekun',
    portugueseName: 'Otura Meji Oyekun',
    order: 15,
    polarity: 'feminine',
    element: 'Noite Espiritual',
    planets: ['Saturno', 'Lua'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Capricornio, Cancer',
    dayOfWeek: 'Sábado',
    direction: 'Norte',
    colors: ['Preto profundo', 'Azul noite', 'Prata lunar'],
    offerings: ['Agua noturna', 'Flores noturnas', 'Te deboldo', 'Velas apagadas e_reacendidas'],
    ebos: ['Ebo de noite profunda', 'Ebo de transformaçao noturna'],
    taboos: ['Temer a_noite', 'Resistir ao sono'],
    strengths: ['Trabalho no escuro', 'Introspecção', 'Sabedoria noturna'],
    weaknesses: ['Isolamento noturno', 'Exaustão'],
    health: ['Glândulas pineal', 'Sonho', 'Melatonina'],
    meanings: ['Noite escura da_alma', 'Transformação no escuro', 'Sabedoria noturna', 'Retiro sagrado'],
    ifaMessage: 'Otura Meji Oyekun mergulha na noite escura para encontrar a luz que não pode ser vista de outro jeito, mostrando que a paz às vezes requiere pasar pela oscuridad.',
  },
  {
    id: 'otura-meji-oxossi',
    name: 'Otura Meji Oxossi',
    portugueseName: 'Otura Meji Oxossi',
    order: 16,
    polarity: 'masculine',
    element: 'Caça Espiritual',
    planets: ['Júpiter', 'Marte'],
    sephirot: ['Chesed', 'Gevurah'],
    sign: 'Sagitário, Aries',
    dayOfWeek: 'Quinta-feira',
    direction: 'Nordeste',
    colors: ['Verde caça', 'Azul rio', 'Marrom tierra'],
    ofertas: ['Caça살', 'Mel decaça', 'Flechas miniaturas', 'Flores de campo'],
    ebos: ['Ebo de perseguidor', 'Ebo de objetivo sagrado'],
    taboos: ['Desistir da_busca', 'Alcançar o_indevido'],
    strengths: ['Busca persistente', 'Determinação', 'Foco no_alvo'],
    weaknesses: ['Obsessão', 'Perseguição do_errado'],
    health: ['Musculatura', ' coluna ', 'Pernas'],
    meanings: ['Caça sagrada', 'Busca do conhecimento', 'Foco', 'Determinação'],
    ifaMessage: 'Otura Meji Oxossi caça nos territórios do espírito com a certeza de que a presa correta se revelará a quem persiste com intención.',
  },
  {
    id: 'otura-meji-xango',
    name: 'Otura Meji Xangô',
    portugueseName: 'Otura Meji Xangô',
    order: 17,
    polarity: 'masculine',
    element: 'Trovão Espiritual',
    planets: ['Marte', 'Júpiter'],
    sephirot: ['Gevurah', 'Chesed'],
    sign: 'Leão, Aries',
    dayOfWeek: 'Quarta-feira',
    direction: 'Noroeste',
    colors: ['Vermelho', 'Branco', 'Preto'],
    ofertas: ['Pão torrado', 'Frutas vermelhas', 'Pedras detrovão', 'Velas vermelha'],
    ebos: ['Ebo de justificado', 'Ebo de equilibrio'],
    taboos: ['Injustiça', 'Abuso de poder'],
    strengths: ['Justice', 'Equilibrio', 'Poder justificado'],
    weaknesses: ['Excesso de força', 'Luxúria por controle'],
    health: ['Ossos maxilares', 'Pulmões', 'Coração'],
    meanings: ['Justiça sagrada', 'Equilibrio de_forças', 'Trovão que restabelece', 'Ordem do caos'],
    ifaMessage: 'Otura Meji Xangô troveja com a justiça que restabelece o equilibrio, mostrando que a verdadeira paz às vezes requiere corregir o que está errado.',
  },
  {
    id: 'otura-meji-oxum',
    name: 'Otura Meji Oxum',
    portugueseName: 'Otura Meji Oxum',
    order: 18,
    polarity: 'feminine',
    element: 'Rio Espiritual',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Touro, Libra',
    dayOfWeek: 'Sábado',
    direction: 'Sul',
    colors: ['Azul ouro', 'Amarelo doce', 'Rosa'],
    ofertas: ['Mel', 'Flores douradas', 'Água dechocolate', 'Peças de bronze'],
    ebos: ['Ebo de prosperidade', 'Ebo de relacionamento'],
    taboos: ['Prostituir o talento', 'Desfecho econômico'],
    strengths: ['Prosperidade', 'Doçura de trato', 'Beleza interior'],
    weaknesses: ['Vaidade', 'Covardia emocional'],
    health: ['Pele', 'Tireoide', 'Rins'],
    meanings: ['Rio de prosperidade', 'Doçura', 'Beleza interior', 'Abastança doce'],
    ifaMessage: 'Otura Meji Oxum flui com a doçura que atrai prosperidade sem esforço, mostrando que a paz verdadeira incluye abundance com gracia.',
  },
  {
    id: 'otura-meji-orunmila',
    name: 'Otura Meji Orunmila',
    portugueseName: 'Otura Meji Orunmila',
    order: 19,
    polarity: 'masculine',
    element: 'Sabedoria Espiritual',
    planets: ['Mercury', 'Sol'],
    sephirot: ['Hod', 'Tiphareth'],
    sign: 'Gêmeos, Leão',
    dayOfWeek: 'Quarta-feira',
    direction: 'Leste',
    colors: ['Verde', 'Dourado', 'Branco'],
    ofertas: ['Kolanuts', 'Nozes de kola', 'Dindinha', 'Óleo de palma'],
    ebos: ['Ebo de sabduría', 'Ebo de conhecimento'],
    taboos: ['Mentiras espirit', 'Usurpação de conocimiento'],
    strengths: ['Sabedoria', 'Conhecimento dos presagios', 'ongue'],
    weaknesses: ['Arrogância intelectual', 'Covardia de_compartir'],
    health: ['Cérebro', 'Mente analítica', ' Nervos ópticos'],
    meanings: ['Sabedoria do Ifá', 'Conhecimento sagrado', 'ongue sagrada', 'Previsão'],
    ifaMessage: 'Otura Meji Orunmila oferece a sabedoria que vem da leitura correta dos sinais, mostrando que a paz se construye con conhecimento y não com ilusão.',
  },
  {
    id: 'otura-meji-oyansan',
    name: 'Otura Meji Oyansan',
    portugueseName: 'Otura Meji Oyansan',
    order: 20,
    polarity: 'feminine',
    element: 'Ferro Espiritual',
    planets: [' Marte', 'Terra'],
    sephirot: ['Gevurah', 'Malkuth'],
    sign: 'Aries',
    dayOfWeek: 'Terça-feira',
    direction: 'Norte',
    colors: ['Azul ferro', 'Laranja ferrugem', 'Preto'],
    ofertas: ['Ferro oxidado', 'Limalha', 'Azeite ferroso', 'Prego ritual'],
    ebos: ['Ebo de herramienta', 'Ebo de trabajo sagrado'],
    taboos: ['Preguiça', 'Destrui labor'],
    strengths: ['Trabalho', 'Força física', 'Resistência'],
    weaknesses: ['Violência', 'Força em_excesso'],
    health: ['Músculos', 'Sangue', 'Ferrro no_cuerpo'],
    meanings: ['Labor sagrado', 'Ferro que_constrói', 'Força de_trabalho', 'Resistência'],
    ifaMessage: 'Otura Meji Oyansan forja com ferro e trabalho, mostrando que a paz se construye com as mãos e a persistência, não tylko com a_fé passiva.',
  },
];

export function getData(): OturaMejiOdu[] {
  return OTURA_MEJI_DATA;
}

export default getData;
