/* prettier-ignore */
// @ts-nocheck
// SKIP_LINT

/**
 * Owonrin Meji Data Module
 * Meji (Double/Odu) divination data for Owonrin
 */

import type { MejiOdu } from './meji-data';

const OWONRIN_MEJI_DATA: MejiOdu[] = [
  {
    id: 'owonrin-ogbe',
    name: 'Owonrin Ogbe',
    portugueseName: 'Owonrin Ogbe',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Amarelo'],
    offerings: ['Mel', 'Cachaça', 'Pipa'],
    ebos: ['Ebo de cabeça', 'Ebo de clareza mental'],
    taboos: ['Não mentir para o Babalawo', 'Não recusar ajuda'],
    strengths: ['Visão clara', 'Determinação', 'Coragem'],
    weaknesses: ['Teimosia excessiva', 'Impaciência'],
    health: ['Cabeça', 'Olhos'],
    meanings: ['Poder da cabeça', 'Destino manifesto', 'Caça espiritual'],
    ifaMessage: 'Owonrin Ogbe representa o poder de conhecer a si mesmo e manifestar o destino através da intenção pura.',
  },
  {
    id: 'owonrin-oyen',
    name: 'Owonrin Oyen',
    portugueseName: 'Owonrin Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Farinha', 'Maçã', 'Água de coco'],
    ebos: ['Ebo de proteção', 'Ebo de sono reparador'],
    taboos: ['Não dormir tarde', 'Não negligenciar o Ori'],
    strengths: ['Intuição', 'Sensibilidade', 'Conhecimento interior'],
    weaknesses: ['Melancolia', 'Indecisão'],
    health: ['Mente', 'Sangue'],
    meanings: ['Intuição Kopf', 'Proteção sutil', 'Sabedoria interior'],
    ifaMessage: 'Owonrin Oyen revela o caminho da proteção através do autoconhecimento e da escuta interior.',
  },
  {
    id: 'owonrin-iwori',
    name: 'Owonrin Iwori',
    portugueseName: 'Owonrin Iwori',
    order: 3,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Terra'],
    sephirot: ['Hod', 'Malkuth'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Marrom', 'Verde escuro'],
    offerings: ['Fumo', 'Milho', 'Quiabo'],
    ebos: ['Ebo de paciência', 'Ebo de sabedoria'],
    taboos: ['Não ter pressa', 'Não desrespeitar os mais velhos'],
    strengths: ['Sabedoria', 'Paciência', 'Longevidade'],
    weaknesses: ['Rigidez', 'Pessimismo'],
    health: ['Joelhos', 'Ossos'],
    meanings: ['Experiência', 'Conselho', 'Luz da verdade'],
    ifaMessage: 'Owonrin Iwori ensina que a verdadeira sabedoria vem do tempo e da experiência acumulada.',
  },
  {
    id: 'owonrin-odi',
    name: 'Owonrin Odi',
    portugueseName: 'Owonrin Odi',
    order: 4,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Marte'],
    sephirot: ['Geburah', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Sul',
    colors: ['Preto', 'Vermelho escuro'],
    offerings: ['Pimenta', 'Dendê', 'Goiaba'],
    ebos: ['Ebo de inimigos', 'Ebo de proteção contra feitiçaria'],
    taboos: ['Não aceitar comida de estranhos', 'Não dormir em lugar desconhecido'],
    strengths:
['Discernimento', 'Proteção', 'Resistência'],
    weaknesses: ['Medo', 'Paranoia'],
    health: ['Vesícula', 'Fígado'],
    meanings: ['Mistério', 'Oculto revelado', 'Proteção contra mal'],
    ifaMessage: 'Owonrin Odi revela os segredos ocultos e protege contra as forças do mal.',
  },
  {
    id: 'owonrin-ossai',
    name: 'Owonrin Ossai',
    portugueseName: 'Owonrin Ossai',
    order: 5,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Júpiter'],
    sephirot: ['Tiferet', 'Chesed'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Nordeste',
    colors: ['Azul', 'Roxo'],
    offerings: ['Mandioca', 'Amendoim', 'Café'],
    ebos: ['Ebo de prosperidade', 'Ebo de viagem segura'],
    taboos: ['Não sair sem proteção', 'Não viajar sem motivo'],
    strengths: ['Comunicação', 'Viagem', 'Sorte'],
    weaknesses: ['Inconstância', 'Excesso de confiança'],
    health: ['Pulmões', 'Intestino'],
    meanings: ['Viagem', 'Comunicação', 'Expansão de consciência'],
    ifaMessage: 'Owonrin Ossai abre os caminhos da comunicação e da expansão espiritual.',
  },
  {
    id: 'owonrin-ixon',
    name: 'Owonrin Ixon',
    portugueseName: 'Owonrin Ixon',
    order: 6,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sudeste',
    colors: ['Verde', 'Rosa'],
    offerings: ['Flores', 'Vinho', 'Doce'],
    ebos: ['Ebo de amor', 'Ebo de reprodução'],
    taboos: ['Não recusar parceiro', 'Não matar animal'],
    strengths: ['Amor', 'Fertilidade', 'Beleza'],
    weaknesses: ['Ciúmes', 'Possessividade'],
    health: ['Garganta', 'Rins'],
    meanings: ['Amor', 'Criança', 'Alimentação'],
    ifaMessage: 'Owonrin Ixon abençoa o amor, a fertilidade e a criação de novas vida.',
  },
  {
    id: 'owonrin-pontosha',
    name: 'Owonrin Pontosha',
    portugueseName: 'Owonrin Pontosha',
    order: 7,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Sol', 'Mercúrio'],
    sephirot: ['Tiferet', 'Netzach'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Centro',
    colors: ['Laranja', 'Amarelo'],
    offerings: ['Manga', 'Melancia', 'Gema de ovo'],
    ebos: ['Ebo de alegria', 'Ebo de liderança'],
    taboos: ['Não ser avarento', 'Não humilhar outros'],
    strengths: ['Liderança', 'Generosidade', 'Confiança'],
    weaknesses: ['Orgulho', 'Desperdício'],
    health: ['Coração', 'Espinha'],
    meanings: ['Sol', 'Força vital', 'Realeza'],
    ifaMessage: 'Owonrin Pontosha ilumina o caminho com o poder do sol e da consciência desperta.',
  },
  {
    id: 'owonrin-oxexexu',
    name: 'Owonrin Oxexexu',
    portugueseName: 'Owonrin Oxexexu',
    order: 8,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Marte', 'Saturno'],
    sephirot: ['Geburah', 'Hod'],
    sign: 'Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Sul',
    colors: ['Preto', 'Vermelho'],
    offerings: ['Fumo preto', 'Cachimbo', 'Espelho'],
    ebos: ['Ebo contra feitiço', 'Ebo de limpeza'],
    taboos: ['Não fazer maldade', 'Não enganar'],
    strengths: ['Combate ao mal', 'Limpeza', 'Verdade'],
    weaknesses: ['Destruição', 'Confusão'],
    health: ['Intestino', 'Pele'],
    meanings: ['Eshu', 'Confusão', 'Limpeza'],
    ifaMessage: 'Owonrin Oxexexu comanda o poder de limpar e proteger contra energias negativas.',
  },
  {
    id: 'owonrin-obara',
    name: 'Owonrin Obara',
    portugueseName: 'Owonrin Obara',
    order: 9,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Terra', 'Júpiter'],
    sephirot: ['Chesed', 'Gevurah'],
    sign: 'Libra',
    dayOfWeek: 'Quinta-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Verde'],
    offerings: ['Pamonha', 'Milho verde', 'Pipoca'],
    ebos: ['Ebo de justiça', 'Ebo de equilíbrio'],
    taboos: ['Não roubar', 'Não ser parcial'],
    strengths: ['Justiça', 'Equilíbrio', 'Retidão'],
    weaknesses: ['Rigidez moral', 'Fanatismo'],
    health: ['Rins', 'Coluna'],
    meanings: ['Lei', 'Justiça', 'Conduta correta'],
    ifaMessage: 'Owonrin Obara estabelece a lei moral e a conduta reta para o buscadores.',
  },
  {
    id: 'owonrin-oyeku',
    name: 'Owonrin Oyeku',
    portugueseName: 'Owonrin Oyeku',
    order: 10,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Saturno', 'Lua'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Norte',
    colors: ['Preto', 'Cinza'],
    offerings: ['Cenoura', 'Beterraba', 'Fumo'],
    ebos: ['Ebo de morte', 'Ebo de transformação'],
    taboos: ['Não temer a morte', 'Não recusar mudança'],
    strengths: ['Transformação', 'Renovação', 'Libertação'],
    weaknesses: ['Medo', 'Trauma'],
    health: ['Baço', 'Pâncreas'],
    meanings: ['Morte', 'Transformação', 'Fim de ciclo'],
    ifaMessage: 'Owonrin Oyeku traz a transformação através da morte do ego e renovação da consciência.',
  },
  {
    id: 'owonrin-osa',
    name: 'Owonrin Osa',
    portugueseName: 'Owonrin Osa',
    order: 11,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Marte', 'Sol'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Amarelo', 'Laranja'],
    offerings: ['Melaço', 'Rapadura', 'Água'],
    ebos: ['Ebo de cura', 'Ebo de proteção'],
    taboos: ['Não ignorar sintomas', 'Não recusar tratamento'],
    strengths: ['Cura', 'Medicina', 'Conhecimento'],
    weaknesses: ['Doença crônica', 'Infecção'],
    health: ['Mãos', 'Pés'],
    meanings: ['Cura', 'Enfermidade', 'Medicina'],
    ifaMessage: 'Owonrin Osa ensina o caminho da cura e o conhecimento das doenças do corpo e da alma.',
  },
  {
    id: 'owonrin-ogunda',
    name: 'Owonrin Ogunda',
    portugueseName: 'Owonrin Ogunda',
    order: 12,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Geburah', 'Tiferet'],
    sign: 'Aries',
    dayOfWeek: 'Terça-feira',
    direction: 'Sul',
    colors: ['Vermelho', 'Marrom'],
    offerings: ['Faca', 'Espada', 'Alfarroba'],
    ebos: ['Ebo de guerra', 'Ebo de conflito'],
    taboos: ['Não iniciar briga', 'Não ser violento sem motivo'],
    strengths: ['Combate', 'Decisão', 'Ação'],
    weaknesses: ['Conflito desnecessário', 'Agressividade'],
    health: ['Cabeça', 'Cérebro'],
    meanings: ['Guerra', 'Decisão', 'Ação'],
    ifaMessage: 'Owonrin Ogunda traz a força para lutar e vencer as batalhas da vida.',
  },
  {
    id: 'owonrin-oses',
    name: 'Owonrin Oses',
    portugueseName: 'Owonrin Oses',
    order: 13,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Mercúrio', 'Vênus'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Amarelo', 'Branco'],
    offerings: ['Nozes', 'Amendoim', 'Castanha'],
    ebos: ['Ebo de paz', 'Ebo de harmonia'],
    taboos: ['Não discordar sem fundamento', 'Não ser superficial'],
    strengths: ['Harmonia', 'Paz', 'Equilíbrio'],
    weaknesses: ['Indecisão', 'Superficialidade'],
    health: ['Mente', 'Nervos'],
    meanings: ['Paz', 'Acordo', 'Reconciliação'],
    ifaMessage: 'Owonrin Oses traz a paz e a harmonia para os conflitos e dissensões.',
  },
  {
    id: 'owonrin-oin',
    name: 'Owonrin Oin',
    portugueseName: 'Owonrin Oin',
    order: 14,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Júpiter', 'Netuno'],
    sephirot: ['Chesed', 'Tiferet'],
    sign: 'Touro',
    dayOfWeek: 'Quinta-feira',
    direction: 'Noroeste',
    colors: ['Azul', 'Verde'],
    offerings: ['Fruta', 'Mel', 'Vinho'],
    ebos: ['Ebo de sorte', 'Ebo de graça'],
    taboos: ['Não desperdiçar', 'Não ser ingrato'],
    strengths: ['Sorte', 'Abundância', 'Gratidão'],
    weaknesses: ['Ganância', 'Avidez'],
    health: ['Estômago', 'Fígado'],
    meanings: ['Sorte', 'Fortuna', 'Graça'],
    ifaMessage: 'Owonrin Oin traz a sorte e a graça para os que seguem o caminho reto.',
  },
  {
    id: 'owonrin-ara',
    name: 'Owonrin Ara',
    portugueseName: 'Owonrin Ara',
    order: 15,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Malkuth'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Sul',
    colors: ['Azul', 'Branco'],
    offerings: ['Água', 'Leite', 'Farinha'],
    ebos: ['Ebo de união', 'Ebo de descendentes'],
    taboos: ['Não abandonar família', 'Não recusar casamento'],
    strengths: ['Família', 'Descendentes', 'União'],
    weaknesses: ['Brigas familiares', 'Ciúmes'],
    health: ['Útero', 'Seios'],
    meanings: ['Família', 'Descendência', 'União'],
    ifaMessage: 'Owonrin Ara abençoa a família e a continuidade da linhagem.',
  },
];

export function getData(): MejiOdu[] {
  return OWONRIN_MEJI_DATA;
}

function getOwonrinMejiById(id: string): MejiOdu | undefined {
  return OWONRIN_MEJI_DATA.find(m => m.id === id);
}

function getOwonrinMejiByOrder(order: number): MejiOdu | undefined {
  return OWONRIN_MEJI_DATA.find(m => m.order === order);
}

function getOwonrinMejiByElement(element: string): MejiOdu[] {
  return OWONRIN_MEJI_DATA.filter(m =>
    m.element.toLowerCase() === element.toLowerCase()
  );
}

function getOwonrinMejiByPolarity(polarity: 'masculine' | 'feminine'): MejiOdu[] {
  return OWONRIN_MEJI_DATA.filter(m => m.polarity === polarity);
}

export default { getData };