// @ts-nocheck

// Oyeku-Meji data — Odu of Transformation and Transmutation (16 Principal Odu of Obeche/Ifa)

export interface OyekuMejiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const OYEKU_MEJI_DATA: OyekuMejiOdu[] = [
  {
    id: 'oyeku',
    name: 'Oyeku',
    portugueseName: 'Oyeku',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Sol'],
    sephirot: ['Geburah', 'Tiphareth'],
    sign: 'Aries',
    dayOfWeek: 'Terca-feira',
    direction: 'Leste',
    colors: ['Vermelho', 'Laranja', 'Amarelo'],
    offerings: ['Palmeira', 'Mel', 'Frutos secos', 'Azeite'],
    ebos: ['Ebo de transformacao', 'Ebo de abertura de caminhos'],
    taboos: ['Nao desperdiçar recursos', 'Nao armazenar por medo'],
    strengths: ['Transmutacao', 'Coragem', 'Renovacao'],
    weaknesses: ['Impaciencia', 'Gastos excessivos'],
    health: ['Figado', 'Vesicula', 'Sangue'],
    meanings: ['Escassez', 'Transformacao', 'Transmutacao', 'Metamorfose'],
    ifaMessage: 'Oyeku revela que toda escuridao carrega a semente da luz, e que a escassez e apenas transformacao em progresso.',
  },
  {
    id: 'oyen',
    name: 'Oyen',
    portugueseName: 'Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Malkuth'],
    sign: 'Peixes',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul profundo', 'Verde escuro', 'Prata'],
    offerings: ['Agua de obi', 'Farinha de mandioca', 'Ervas aquaticas'],
    ebos: ['Ebo de fluidez', 'Ebo de aceitacao'],
    taboos: ['Nao resistir as mudancas', 'Nao acumular por escassez'],
    strengths: ['Adaptacao', 'Fluidez', 'Soltar'],
    weaknesses: ['Indecisao', 'Dissolucao'],
    health: ['Rins', 'Bexiga', 'Linfa'],
    meanings: ['Agua corrente', 'Fluxo', 'Liberacao', 'Desprendimento'],
    ifaMessage: 'Oyen ensina que a agua corrente nao se apega, e que soltar e tao poderoso quanto conquistar.',
  },
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 3,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Plutao'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Touro',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Marrom', 'Verde escuro', 'Preto'],
    offerings: ['Raizes', 'Terra', 'Frutos da terra'],
    ebos: ['Ebo de ancoragem', 'Ebo de raizes'],
    taboos: ['Nao abandonar a terra natal', 'Nao desprezar origens'],
    strengths: ['Ancoragem', 'Persistencia', 'Sobrevivencia'],
    weaknesses: ['Rigidez', 'Teimosia'],
    health: ['Osso', 'Dentes', 'Pele'],
    meanings: ['Raizes', 'Ancestralidade', 'Sobrevivencia', 'Riqueza subterranea'],
    ifaMessage: 'Ika mostra que a verdadeira riqueza nasce da terra escura, e que nossas raizes nos sustentam em toda transformacao.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 4,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Marte', 'Ferro'],
    sephirot: ['Geburah', 'Hod'],
    sign: 'Escorpiao',
    dayOfWeek: 'Terca-feira',
    direction: 'Nordeste',
    colors: ['Cinza', 'Ferro', 'Vermelho escuro'],
    offerings: ['Ferro', 'Fumo', 'Palmeira cortada'],
    ebos: ['Ebo de corte', 'Ebo de separacao'],
    taboos: ['Nao hesitar', 'Nao cortar lacos importantes'],
    strengths: ['Decisao', 'Acao', 'Corte preciso'],
    weaknesses: ['Impulsividade', 'Destruicao'],
    health: ['Intestinos', 'Apendice', 'Colon'],
    meanings: ['Corte', 'Separacao', 'Cirurgia', 'Decisao firme'],
    ifaMessage: 'Ogunda corta para reconstruir, separando o que impede o crescimento com precisao cirurgica.',
  },
  {
    id: 'osai',
    name: 'Osai',
    portugueseName: 'Osai',
    order: 5,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Venus', 'Mercurio'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Gemeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Azul claro', 'Branco'],
    offerings: ['Flores', 'Frutas tropicais', 'Azeite doce'],
    ebos: ['Ebo de harmonia', 'Ebo de reconciliacao'],
    taboos: ['Nao criar discurdia', 'Nao falar mal'],
    strengths: ['Harmonia', 'Comunicacao', 'Justica'],
    weaknesses: ['Inconstancia', 'Superficialidade'],
    health: ['Pulmoes', 'Bronquios', 'Maos'],
    meanings: ['Concordancia', 'Acordo', 'Harmonia', 'Resolucao'],
    ifaMessage: 'Osai ensina que o vento sopra onde quer, mas a harmonia se encontra no encontro dos opostos.',
  },
  {
    id: 'obara',
    name: 'Obara',
    portugueseName: 'Obara',
    order: 6,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Jupiter'],
    sephirot: ['Tiphareth', 'Chesed'],
    sign: 'Leao',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Ouro', 'Laranja', 'Vermelho'],
    offerings: ['Milho', 'Frango', 'Mel', 'Azeite'],
    ebos: ['Ebo de abundancia', 'Ebo de realeza'],
    taboos: ['Nao mentir', 'Nao desrespeitar anciãos'],
    strengths: ['Honestidade', 'Generosidade', 'Lideranca'],
    weaknesses: ['Orulho', 'Autoritarismo'],
    health: ['Coracao', 'Espinha', 'Olhos'],
    meanings: ['Leite', 'Maternidade', 'Educacao', 'Realeza'],
    ifaMessage: 'Obara e o sol que alimenta, a mae que ensina, revelando que a verdadeira realeza serve ao seu povo.',
  },
  {
    id: 'okanran',
    name: 'Okanran',
    portugueseName: 'Okanran',
    order: 7,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Lua'],
    sephirot: ['Malkuth', 'Binah'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Centro',
    colors: ['Verde', 'Marrom claro', 'Bege'],
    offerings: ['Raizes comestiveis', 'Frutas', 'Ervas'],
    ebos: ['Ebo de purificacao', 'Ebo de cura'],
    taboos: ['Nao contaminar', 'Nao desperdiçar'],
    strengths: ['Pureza', 'Discernimento', 'Servico'],
    weaknesses: ['Critica excessiva', 'Perfeccionismo'],
    health: ['Intestinos', 'Baço', 'Abdomen'],
    meanings: ['Flecha', 'Integridade', 'Pureza', 'Medicina'],
    ifaMessage: 'Okanran voa como flecha certeira, revelando que a integridade nos mantem no caminho reto.',
  },
  {
    id: 'ogbe',
    name: 'Ogbe',
    portugueseName: 'Ogbe',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutao'],
    sephirot: ['Geburah', 'Hod'],
    sign: 'Capricornio',
    dayOfWeek: 'Terca-feira',
    direction: 'Oeste',
    colors: ['Vermelho', 'Preto', 'Cinza'],
    offerings: ['Fumo', 'Palmeira', 'Aguardente'],
    ebos: ['Ebo de guerra', 'Ebo de protecao'],
    taboos: ['Nao iniciar conflitos', 'Nao ser covarde'],
    strengths: ['Forca', 'Vitoria', 'Conquista'],
    weaknesses: ['Agressividade', 'Conflito'],
    health: ['Musculos', 'Articulacoes', 'Pele'],
    meanings: ['Vitoria', 'Conquista', 'Guerra', 'Forca'],
    ifaMessage: 'Ogbe canta vitoria antes da batalha, porque a mente que vence ja derrotou o inimigo.',
  },
  {
    id: 'ossi',
    name: 'Ossi',
    portugueseName: 'Ossi',
    order: 9,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Venus'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Libra',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Rosa', 'Lilás'],
    offerings: ['Agua de flor', 'Sementes', 'Flores-doce'],
    ebos: ['Ebo de equilibrio', 'Ebo de justica'],
    taboos: ['Nao tomar partido', 'Nao ser parcial'],
    strengths: ['Equilibrio', 'Justica', 'Diplomacia'],
    weaknesses: ['Indecisao', 'Compromisso excessivo'],
    health: ['Rins', 'Tireoide', 'Lombar'],
    meanings: ['Peso', 'Balança', 'Equilibrio', 'Justica'],
    ifaMessage: 'Ossi e a balanca que pesa almas, revelando que toda acao tem peso igual na escala do destino.',
  },
  {
    id: 'wonu',
    name: 'Wonu',
    portugueseName: 'Wonu',
    order: 10,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Terra', 'Marte'],
    sephirot: ['Malkuth', 'Geburah'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Marrom', 'Ouro'],
    offerings: ['Frutos da terra', 'Mel', 'Raizes'],
    ebos: ['Ebo de fartura', 'Ebo de agradecimiento'],
    taboos: ['Nao recusar hospitalidade', 'Nao ser avarento'],
    strengths: ['Fertilidade', 'Abundancia', 'Generosidade'],
    weaknesses: ['Possessividade', 'Inveja'],
    health: ['Garganta', 'Pescoco', 'Ovarios'],
    meanings: ['Fartura', 'Abundancia', 'Celebracao', 'Partilha'],
    ifaMessage: 'Wonu ensina que a abundancia multiplica quando compartilhada, e seca quando acumulada por medo.',
  },
  {
    id: 'ros',
    name: 'Ros',
    portugueseName: 'Ros',
    order: 11,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Mercurio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Amarelo', 'Branco', 'Azul claro'],
    offerings: ['Flores brancas', 'Frutas', 'Azeite'],
    ebos: ['Ebo de sabedoria', 'Ebo de orientacao'],
    taboos: ['Nao aceitar orientacao', 'Nao desvalorizar conselhos'],
    strengths: ['Sabedoria', 'Orientacao', 'Comunicacao'],
    weaknesses: ['Manipulacao', 'Superficialidade'],
    health: ['Maos', 'Pulmoes', 'Sistema nervoso'],
    meanings: ['Sorte', 'Destino', 'Orientacao', 'Conselho'],
    ifaMessage: 'Ros sopra como o vento carregando mensagens, revelando que a sabedoria vem de ouvir antes de falar.',
  },
  {
    id: 'oton',
    name: 'Oton',
    portugueseName: 'Oton',
    order: 12,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Sol'],
    sephirot: ['Geburah', 'Tiphareth'],
    sign: 'Leao',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Laranja', 'Ouro'],
    offerings: ['Carne', 'Mel', 'Palmeira', 'Fumo'],
    ebos: ['Ebo de coragem', 'Ebo de protecao'],
    taboos: ['Nao ter medo', 'Nao retroceder'],
    strengths: ['Coragem', 'Forca', 'Protecao'],
    weaknesses: ['Rixa', 'Irritabilidade'],
    health: ['Coracao', 'Musculos', 'Cabeca'],
    meanings: ['Faca', 'Corte', 'Cirurgia', 'Valentia'],
    ifaMessage: 'Oton empunha a faca com proposito, cortando o que impede a cura com coragem inabalavel.',
  },
  {
    id: 'meyi',
    name: 'Meyi',
    portugueseName: 'Meyi',
    order: 13,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphareth', 'Geburah'],
    sign: 'Leao',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Ouro', 'Vermelho', 'Branco'],
    offerings: ['Frango branco', 'Milho', 'Azeite', 'Farinha'],
    ebos: ['Ebo de fogo sagrado', 'Ebo de renovacao'],
    taboos: ['Nao queimar oferendas incorretamente', 'Nao desrespeitar o fogo'],
    strengths: ['Renovacao', 'Purificacao', 'Poder'],
    weaknesses: ['Destruicao', 'Fanatismo'],
    health: ['Coracao', 'Sangue', 'Fogo interior'],
    meanings: ['Fogo', 'Renovacao', 'Purificacao', 'Sagrado'],
    ifaMessage: 'Meyi arde consumindo o que precisa morrer, para que o novo possa nascer das cinzas.',
  },
  {
    id: 'da',
    name: 'Da',
    portugueseName: 'Da',
    order: 14,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Terra', 'Saturno'],
    sephirot: ['Malkuth', 'Binah'],
    sign: 'Capricornio',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Marrom', 'Preto', 'Verde escuro'],
    offerings: ['Raizes', 'Terra', 'Agua'],
    ebos: ['Ebo de criacao', 'Ebo de fundamento'],
    taboos: ['Nao construir sobre areia', 'Nao mentir sobre fundacoes'],
    strengths: ['Criacao', 'Fundamento', 'Sabedoria'],
    weaknesses: ['Rigidez', 'Tradicao excessiva'],
    health: ['Cerebro', 'Medula', 'Coluna'],
    meanings: ['Criacao', 'Oraculo', 'Sabedoria ancestral', 'Fundamento'],
    ifaMessage: 'Da consulta os oraculos para criar alicerces firmes, revelando que toda sabedoria comeca na terra.',
  },
  {
    id: 'se',
    name: 'Se',
    portugueseName: 'Se',
    order: 15,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Mercurio', 'Netuno'],
    sephirot: ['Hod', 'Chesed'],
    sign: 'Aquario',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Azul', 'Prata', 'Branco'],
    offerings: ['Azeite', 'Flores', 'Frutas', 'Agua doce'],
    ebos: ['Ebo de expansao', 'Ebo de visao'],
    taboos: ['Nao limitar o visionario', 'Nao prender o vento'],
    strengths: ['Visao', 'Expansao', 'Liberdade'],
    weaknesses: ['Dispersao', 'Sonho excessivo'],
    health: ['Mente', 'Pes', 'Sistema nervoso'],
    meanings: ['Expansao', 'Visao', 'Liberdade', 'Sopro'],
    ifaMessage: 'Se sopra como o vento da mudanca, carregando-nos para alem dos horizontes conhecidos.',
  },
  {
    id: 'oyonu',
    name: 'Oyonu',
    portugueseName: 'Oyonu',
    order: 16,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Cancer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul marinho', 'Preto', 'Branco'],
    offerings: ['Agua de obi', 'Fumo', 'Flores noturnas'],
    ebos: ['Ebo de uniao', 'Ebo de transformacao'],
    taboos: ['Nao separar o que deve estar junto', 'Nao temer a transformacao'],
    strengths: ['Uniao', 'Transformacao', 'Integracao'],
    weaknesses: ['Fusao excessiva', 'Perda de limites'],
    health: ['Seios', 'Utero', 'Liquidos corporais'],
    meanings: ['Uniao', 'Integracao', 'Transformacao', 'Amor'],
    ifaMessage: 'Oyonu une o que foi separado, transformando inimigos em aliados atraves do poder do amor.',
  },
];

export function getData(): OyekuMejiOdu[] {
  return OYEKU_MEJI_DATA;
}

export default getData;