// ============================================================
// LIFE AREAS ENGINE - Data Definitions
// ============================================================
// Definição completa das 12 áreas da vida com todas as
// correlações: Astrologia, Numerologia, Odu, Orixá, Chakra, Elementos.
// Extraído do index.ts principal para manter arquivo focado.
// ============================================================

import type { LifeAreaId, LifeArea } from './types';

// ============================================================
// DEFINIÇÃO COMPLETA DAS 12 ÁREAS DA VIDA
// ============================================================

export const LIFE_AREAS: Record<LifeAreaId, LifeArea> = {
  // 1. PROPÓSITO DE VIDA
  proposito: {
    id: 'proposito',
    name: 'Propósito de Vida',
    nameEnglish: 'Life Purpose',
    description: 'Sua missão neste plano. O que você veio fazer e como contribuir para o coletivo.',
    emoji: '🌟',
    color: '#fbbf24',
    gradient: 'from-amber-500/20 to-yellow-500/10',
    icon: 'Compass',
    astrology: {
      planets: ['Sol', 'Júpiter', 'Netuno'],
      houses: [1, 9, 10, 12],
      signs: ['Leão', 'Sagitário', 'Peixes', 'Áries'],
      points: ['Nodo Norte', 'Meio do Céu (MC)', 'Sol'],
      aspects: ['Sol-MC', 'Sol-Netuno', 'Júpiter-Netuno'],
      keywords: ['missão', 'vocação', 'legado', 'sentido', 'chamado'],
      avoid: ['Terra'],
    },
    questions: [
      'O que te faz perder noção do tempo?',
      'Que legado você quer deixar?',
      'Se dinheiro não fosse problema, o que você faria?',
    ],
    practices: ['Meditação silenciosa', 'Journaling', 'Retiros espirituais', 'Estudo de filosofia'],
    crystals: ['Ametista', 'Quartzo transparente', 'Sugilita'],
    challenges: [],
    affirmations: [
      'Eu confio no chamado da minha alma.',
      'Minha missão revela cada passo.',
      'Eu sou guiado pela luz divina.',
    ],
  },

  // 2. CARREIRA / TRABALHO
  carreira: {
    id: 'carreira',
    name: 'Carreira & Trabalho',
    nameEnglish: 'Career & Work',
    description: 'Sua vocação profissional, ambições e contribuição social através do trabalho.',
    emoji: '💼',
    color: '#3b82f6',
    gradient: 'from-blue-500/20 to-cyan-500/10',
    icon: 'Briefcase',
    astrology: {
      planets: ['Sol', 'Saturno', 'Marte', 'Júpiter'],
      houses: [6, 10, 2],
      signs: ['Capricórnio', 'Áries', 'Leão', 'Virgem'],
      points: ['Meio do Céu (MC)', 'Sol', 'Saturno'],
      aspects: ['Sol-Saturno', 'Sol-MC', 'Marte-Saturno'],
      keywords: ['vocação', 'profissão', 'autoridade', 'disciplina'],
    },
    numerology: {
      lifePath: [1, 4, 8, 22],
      masterNumbers: [22],
      personalYear: [1, 4, 8],
      expression: [8, 22],
      keywords: ['realização', 'autoridade', 'conquista'],
    },
    odu: {
      primaryOdus: ['Ogbe', 'Irosun', 'Ofun'],
      favorableOdus: ['Iwori', 'Osa', 'Osetura'],
      avoidOdus: ['Owonrin'],
      eboSuggestions: ['Ebo de trabalho', 'Oferenda a Oxóssi'],
      keywords: ['realização', 'trabalho', 'profissão'],
    },
    orixa: {
      primary: ['Oxóssi', 'Oxum'],
      secondary: ['Ogum', 'Obaluaiê'],
      offerings: ['Flecha', 'Mel', 'Milho', 'Pinhão'],
      days: ['Quinta-feira', 'Terça-feira'],
      elements: ['Fogo', 'Ar'],
    },
    chakra: {
      primary: ['3º Plexo Solar'],
      balance: 'balanced',
      color: '#f59e0b',
      mantra: 'RAM',
    },
    element: {
      primary: 'Fogo',
      secondary: ['Ar'],
      favorable: ['Fogo', 'Ar'],
      avoid: ['Água em excesso'],
    },
    questions: [
      'Qual é sua vocação mais profunda?',
      'Como você quer ser lembrado pelo seu trabalho?',
      'Que contribuição social você quer fazer?',
    ],
    practices: [' networking', 'Estudo de mercado', 'Planejamento estratégico', 'Mentoria'],
    crystals: ['Cornalina', 'Ágata azul', 'Lápis-lazúli'],
    challenges: [],
    affirmations: [
      'Eu mereço sucesso e reconhecimento.',
      'Minha carreira está em perfeita expansão.',
      'Eu atraio oportunidades alinhadas com minha missão.',
    ],
  },

  // 3. FINANÇAS / DINHEIRO
  financas: {
    id: 'financas',
    name: 'Finanças & Abundância',
    nameEnglish: 'Finance & Abundance',
    description: 'Sua relação com dinheiro, prosperidade, recursos materiais e abundância.',
    emoji: '💰',
    color: '#10b981',
    gradient: 'from-emerald-500/20 to-green-500/10',
    icon: 'DollarSign',
    astrology: {
      planets: ['Vênus', 'Júpiter', 'Mercúrio'],
      houses: [2, 8, 11],
      signs: ['Touro', 'Libra', 'Sagitário', 'Capricórnio'],
      points: ['Vênus', 'Júpiter', 'Parte da Fortuna'],
      aspects: ['Vênus-Júpiter', 'Júpiter-Saturno', 'Sol-Parte da Fortuna'],
      keywords: ['prosperidade', 'recursos', 'valor próprio', 'fluxo'],
    },
    numerology: {
      lifePath: [4, 6, 8, 22, 33],
      masterNumbers: [22],
      personalYear: [4, 8],
      expression: [8, 22, 33],
      keywords: ['abundância', 'manifestação', 'valor'],
    },
    odu: {
      primaryOdus: ['Ofun', 'Irosun', 'Odi'],
      favorableOdus: ['Iwori', 'Osa', 'Osetura'],
      avoidOdus: ['Okanran', 'Owonrin'],
      eboSuggestions: ['Ebo de riqueza', 'Oferenda de Oxum'],
      keywords: ['riqueza', 'abundância', 'recursos'],
    },
    orixa: {
      primary: ['Oxum', 'Iemanjá'],
      secondary: ['Oxalá', 'Logunedé'],
      offerings: ['Mel', 'Diamantes', 'Ouro', 'Flores amarelas'],
      days: ['Domingo', 'Sexta-feira'],
      elements: ['Água', 'Terra'],
    },
    chakra: {
      primary: ['2º Sacro'],
      balance: 'balanced',
      color: '#10b981',
      mantra: 'VAM',
    },
    element: {
      primary: 'Terra',
      secondary: ['Água'],
      favorable: ['Terra', 'Água'],
      avoid: ['Fogo excessivo'],
    },
    questions: [
      'Qual é sua relação emocional com dinheiro?',
      'Você se sente merecedor de abundância?',
      'O que prosperidade significa para você?',
    ],
    practices: ['Controle financeiro', 'Investimentos', 'Visualização criativa', 'Gratidão diária'],
    crystals: ['Citrino', 'Pirita', 'Esmeralda', 'Aventurina verde'],
    challenges: [],
    affirmations: [
      'Eu sou um imã para abundância.',
      'O dinheiro flui para mim de fontes múltiplas.',
      'Eu uso a riqueza para servir ao bem maior.',
    ],
  },

  // 4. SAÚDE / CORPO / VITALIDADE
  saude: {
    id: 'saude',
    name: 'Saúde & Vitalidade',
    nameEnglish: 'Health & Vitality',
    description: 'Seu bem-estar físico, mental, emocional e energético. Sua relação com o corpo.',
    emoji: '🏥',
    color: '#ef4444',
    gradient: 'from-red-500/20 to-pink-500/10',
    icon: 'Heart',
    astrology: {
      planets: ['Sol', 'Marte', 'Lua'],
      houses: [1, 6, 8, 12],
      signs: ['Áries', 'Escorpião', 'Leão', 'Virgem'],
      points: ['Ascendente', 'Sol', 'Marte'],
      aspects: ['Sol-Ascendente', 'Sol-Lua', 'Marte-Ascendente'],
      keywords: ['vitalidade', 'energia', 'corpo', 'imunidade'],
    },
    numerology: {
      lifePath: [1, 3, 9],
      masterNumbers: [],
      personalYear: [1, 3],
      expression: [1, 3, 9],
      keywords: ['vitalidade', 'força', 'resistência'],
    },
    odu: {
      primaryOdus: ['Ofun', 'Ogbe', 'Ika'],
      favorableOdus: ['Irete', 'Odi', 'Osa'],
      avoidOdus: [],
      eboSuggestions: ['Ebo de saúde', 'Oferenda a Omolu'],
      keywords: ['saúde', 'corpo', 'vitalidade'],
    },
    orixa: {
      primary: ['Omolu', 'Nanã'],
      secondary: ['Oxum', 'Iansã'],
      offerings: ['Milho', 'Pipoca', 'Defumação', 'Ervas'],
      days: ['Segunda-feira', 'Terça-feira'],
      elements: ['Terra', 'Fogo'],
    },
    chakra: {
      primary: ['1º Básico', '3º Plexo Solar'],
      balance: 'balanced',
      color: '#ef4444',
      mantra: 'LAM',
    },
    element: {
      primary: 'Fogo',
      secondary: ['Terra'],
      favorable: ['Fogo', 'Terra'],
      avoid: ['Água em excesso'],
    },
    questions: [
      'Como você cuida do seu corpo?',
      'Que hábitos você precisa mudar?',
      'Como você gerencia seu estresse?',
    ],
    practices: ['Exercícios regulares', 'Alimentação consciente', 'Sono de qualidade', 'Cura energética'],
    crystals: ['Quartzo Verde', 'Cornalina', 'Granada', 'Olho de Tigre'],
    challenges: [],
    affirmations: [
      'Meu corpo é um templo sagrado.',
      'Eu tenho energia vital ilimitada.',
      'Cada célula do meu corpo irradia saúde.',
    ],
  },

  // 5. RELACIONAMENTOS / AMOR
  relacionamentos: {
    id: 'relacionamentos',
    name: 'Relacionamentos & Amor',
    nameEnglish: 'Relationships & Love',
    description: 'Sua capacidade de amar, parcerias, casamento e conexões afetivas profundas.',
    emoji: '💕',
    color: '#ec4899',
    gradient: 'from-pink-500/20 to-rose-500/10',
    icon: 'Heart',
    astrology: {
      planets: ['Vênus', 'Lua', 'Sol', 'Quíron'],
      houses: [4, 5, 7, 8],
      signs: ['Libra', 'Touro', 'Câncer', 'Peixes'],
      points: ['Descendente', 'Vênus', 'Lua', 'Quíron'],
      aspects: ['Vênus-Marte', 'Sol-Lua', 'Vênus-Descendente', 'Quíron-Vênus'],
      keywords: ['amor', 'parceria', 'intimidade', 'compaixão', 'cura emocional'],
    },
    numerology: {
      lifePath: [2, 6, 9],
      masterNumbers: [11],
      personalYear: [2, 6],
      expression: [2, 6, 9],
      keywords: ['união', 'harmonia', 'compaixão'],
    },
    odu: {
      primaryOdus: ['Irete', 'Odi', 'Ofun'],
      favorableOdus: ['Okana', 'Iwori', 'Obara'],
      avoidOdus: ['Okanran'],
      eboSuggestions: ['Ebo de amor', 'Oferenda a Oxum'],
      keywords: ['amor', 'parceria', 'casamento'],
    },
    orixa: {
      primary: ['Oxum', 'Iemanjá', 'Obaluaiê'],
      secondary: ['Oxalá', 'Nanã'],
      offerings: ['Mel', 'Rosa', 'Perfume', 'Velas cor-de-rosa'],
      days: ['Domingo', 'Sexta-feira'],
      elements: ['Água', 'Terra'],
    },
    chakra: {
      primary: ['4º Cardíaco'],
      balance: 'high',
      color: '#ec4899',
      mantra: 'YAM',
    },
    element: {
      primary: 'Água',
      secondary: ['Terra'],
      favorable: ['Água', 'Terra'],
      avoid: ['Fogo em excesso'],
    },
    questions: [
      'Como você se relaciona com seus партнёры passados?',
      'Que padrões repetitivos você percebe em seus relacionamentos?',
      'O que você precisa perdoar para amar plenamente?',
    ],
    practices: ['Terapia de casal', 'Comunicação não-violenta', 'Meditação a dois', 'Dance movement'],
    crystals: ['Quartzo rosa', 'Rodocrosita', 'Esmeralda', 'Rosa do deserto'],
    challenges: [],
    affirmations: [
      'Eu mereço amor profundo e saudável.',
      'Meus relacionamentos são fonte de paz.',
      'Eu abro meu coração para o amor genuíno.',
    ],
  },

  // 6. SEXUALIDADE / INTIMIDADE
  sexualidade: {
    id: 'sexualidade',
    name: 'Sexualidade & Prazer',
    nameEnglish: 'Sexuality & Pleasure',
    description: 'Sua energia criativa, sensual, libidinal e capacidade de prazer profundo.',
    emoji: '🌹',
    color: '#a855f7',
    gradient: 'from-purple-500/20 to-fuchsia-500/10',
    icon: 'Flame',
    astrology: {
      planets: ['Marte', 'Plutão', 'Vênus', 'Lilith'],
      houses: [5, 8, 12],
      signs: ['Escorpião', 'Leão', 'Áries', 'Touro'],
      points: ['Lilith (Preta e Branca)', 'Plutão', 'Marte', 'Nodo Sul'],
      aspects: ['Marte-Plutão', 'Vênus-Marte', 'Lilith-Sol', 'Plutão-Vênus'],
      keywords: ['prazer', 'desejo', 'transformação', 'tabu', 'sombra', 'instinto'],
    },
    numerology: {
      lifePath: [1, 5, 8, 11],
      masterNumbers: [11],
      personalYear: [1, 5],
      expression: [5, 8, 11],
      keywords: ['prazer', 'instinto', 'transformação'],
    },
    odu: {
      primaryOdus: ['Irete', 'Owonrin', 'Osa'],
      favorableOdus: ['Ogbe', 'Ika', 'Obara'],
      avoidOdus: ['Okanran'],
      eboSuggestions: ['Ebo de reconciliação', 'Limpezas com ervas'],
      keywords: ['prazer', 'transformação', 'sombra'],
    },
    orixa: {
      primary: ['Iansã', 'Oxum', 'Pomba-Gira'],
      secondary: ['Ogum', 'Exu'],
      offerings: ['Vermelho e rosa', 'Velas', 'Perfume', 'Espelho'],
      days: ['Quarta-feira', 'Terça-feira'],
      elements: ['Fogo', 'Água'],
    },
    chakra: {
      primary: ['2º Sacro'],
      balance: 'low',
      color: '#a855f7',
      mantra: 'VAM',
    },
    element: {
      primary: 'Fogo',
      secondary: ['Água'],
      favorable: ['Fogo', 'Água'],
      avoid: ['Terra excessiva'],
    },
    questions: [
      'Qual é sua relação com o prazer?',
      'Você se permite sentir desejo?',
      'Onde você reprime sua energia sexual?',
    ],
    practices: ['Movimento consciente', 'Tantra', 'Cura do chacra sacro', 'Dança'],
    crystals: ['Cornalina', 'Granada', 'Rubi', 'Crisocola'],
    challenges: [],
    affirmations: [
      'Eu honro minha energia sexual como sagrada.',
      'Eu mereço prazer e conexão profunda.',
      'Minha sensualidade é expressão da divindade.',
    ],
  },

  // 7. FAMÍLIA / RAÍZES
  familia: {
    id: 'familia',
    name: 'Família & Ancestrais',
    nameEnglish: 'Family & Roots',
    description: 'Sua linhagem, ancestralidade, base emocional e relações familiares.',
    emoji: '🏡',
    color: '#f97316',
    gradient: 'from-orange-500/20 to-amber-500/10',
    icon: 'Home',
    astrology: {
      planets: ['Lua', 'Saturno', 'Sol'],
      houses: [4, 10, 1],
      signs: ['Câncer', 'Capricórnio', 'Leão'],
      points: ['Fundo do Céu (IC)', 'Lua', 'Sol'],
      aspects: ['Sol-Lua', 'Sol-IC', 'Saturno-IC'],
      keywords: ['raízes', 'mãe', 'pai', 'ancestralidade', 'herança'],
    },
    numerology: {
      lifePath: [2, 4, 6, 9],
      masterNumbers: [],
      personalYear: [4, 6],
      expression: [4, 6],
      keywords: ['família', 'lar', 'ancestralidade'],
    },
    odu: {
      primaryOdus: ['Okana', 'Iwori', 'Obara'],
      favorableOdus: ['Ofun', 'Irete', 'Irosun'],
      avoidOdus: ['Owonrin'],
      eboSuggestions: ['Ebo de ancestralidade', 'Bori'],
      keywords: ['ancestralidade', 'família', 'raízes'],
    },
    orixa: {
      primary: ['Iemanjá', 'Oxum'],
      secondary: ['Nanã', 'Obaluaiê'],
      offerings: ['Sal', 'Alabaster', 'Flores brancas', 'Leite'],
      days: ['Sábado', 'Domingo'],
      elements: ['Água', 'Terra'],
    },
    chakra: {
      primary: ['1º Básico', '4º Cardíaco'],
      balance: 'balanced',
      color: '#f97316',
      mantra: 'LAM',
    },
    element: {
      primary: 'Terra',
      secondary: ['Água'],
      favorable: ['Terra', 'Água'],
      avoid: ['Fogo excessivo'],
    },
    questions: [
      'Que padrões familiares você herdou?',
      'Como você se relaciona com sua família de origem?',
      'Que tradição você quer criar para seus descendentes?',
    ],
    practices: ['Genealogia espiritual', 'Rituais ancestrais', 'Terapia familiar', 'Conexão com a terra'],
    crystals: ['Ágata branca', 'Howlita', 'Quartzo transparente', 'Pedra da lua'],
    challenges: [],
    affirmations: [
      'Eu honro minha família e meus ancestrais.',
      'Eu transformo padrões que não me servem.',
      'Sou grato(a) pelas minhas raízes.',
    ],
  },

  // 8. ESPIRITUALIDADE
  espiritualidade: {
    id: 'espiritualidade',
    name: 'Espiritualidade & Fé',
    nameEnglish: 'Spirituality & Faith',
    description: 'Sua conexão com o divino, fé, transcendência e propósito místico.',
    emoji: '🙏',
    color: '#8b5cf6',
    gradient: 'from-violet-500/20 to-indigo-500/10',
    icon: 'Sparkles',
    astrology: {
      planets: ['Netuno', 'Júpiter', 'Lua', 'Plutão'],
      houses: [9, 12, 4],
      signs: ['Peixes', 'Sagitário', 'Escorpião', 'Aquário'],
      points: ['Netuno', 'Júpiter', 'Nodo Sul', 'Lua'],
      aspects: ['Netuno-Plutão', 'Júpiter-Netuno', 'Sol-Netuno'],
      keywords: ['fé', 'transcendência', 'mística', 'devoção', 'intuição'],
    },
    numerology: {
      lifePath: [7, 9, 11, 22, 33],
      masterNumbers: [11, 22, 33],
      personalYear: [7, 11],
      expression: [7, 9, 11],
      keywords: ['intuição', 'sabedoria', 'mística'],
    },
    odu: {
      primaryOdus: ['Ofun', 'Oyeku', 'Irete'],
      favorableOdus: ['Irosun', 'Okana', 'Iwori'],
      avoidOdus: [],
      eboSuggestions: ['Bori', 'Akofá de Ori', 'Ritual de Ofá'],
      keywords: ['Ori', 'cabeça', 'destino espiritual'],
    },
    orixa: {
      primary: ['Oxalá', 'Iansã'],
      secondary: ['Orunmilá', 'Obaluaiê'],
      offerings: ['Pano branco', 'Mel', 'Frutas', 'Alecrim'],
      days: ['Domingo', 'Segunda-feira'],
      elements: ['Ar', 'Fogo'],
    },
    chakra: {
      primary: ['6º Frontal', '7º Coronário'],
      balance: 'low',
      color: '#8b5cf6',
      mantra: 'OM',
    },
    element: {
      primary: 'Ar',
      secondary: ['Fogo'],
      favorable: ['Ar', 'Fogo'],
      avoid: ['Terra em excesso'],
    },
    questions: [
      'Qual é sua prática espiritual?',
      'Como você cultiva sua fé?',
      'Que rituais fazem sentido para você?',
    ],
    practices: ['Meditação', 'Oração', 'Retiros', 'Estudo sagrado', 'Yoga'],
    crystals: ['Ametista', 'Quartzo transparente', 'Selenita', 'Larimar'],
    challenges: [],
    affirmations: [
      'Eu sou um ser de luz.',
      'Minha alma conhece seu caminho.',
      'Eu me abro para a sabedoria divina.',
    ],
  },

  // 9. CRIATIVIDADE / ARTE
  criatividade: {
    id: 'criatividade',
    name: 'Criatividade & Arte',
    nameEnglish: 'Creativity & Art',
    description: 'Sua capacidade criativa, expressão artística e originalidade.',
    emoji: '🎨',
    color: '#f59e0b',
    gradient: 'from-yellow-500/20 to-orange-500/10',
    icon: 'Palette',
    astrology: {
      planets: ['Sol', 'Vênus', 'Mercúrio', 'Urano'],
      houses: [3, 5, 11],
      signs: ['Leão', 'Aquário', 'Gêmeos', 'Libra'],
      points: ['Sol', 'Vênus', 'Mercúrio'],
      aspects: ['Sol-Urano', 'Vênus-Mercúrio', 'Sol-Mercúrio'],
      keywords: ['criação', 'arte', 'originalidade', 'expressão', 'talento'],
    },
    numerology: {
      lifePath: [3, 5, 7, 11],
      masterNumbers: [11],
      personalYear: [3, 5],
      expression: [3, 5, 11],
      keywords: ['inspiração', 'criação', 'talento'],
    },
    odu: {
      primaryOdus: ['Irosun', 'Ogbe', 'Iwori'],
      favorableOdus: ['Ika', 'Okana', 'Osa'],
      avoidOdus: ['Okanran'],
      eboSuggestions: ['Ebo de inspiração', 'Oferenda a Oxóssi'],
      keywords: ['criatividade', 'caça', 'inspiração'],
    },
    orixa: {
      primary: ['Oxóssi', 'Iansã'],
      secondary: ['Oxum', 'Oxalá'],
      offerings: ['Caça simbólica', 'Frutas', 'Mel'],
      days: ['Quinta-feira', 'Terça-feira'],
      elements: ['Ar', 'Fogo'],
    },
    chakra: {
      primary: ['2º Sacro', '5º Laríngeo'],
      balance: 'high',
      color: '#f59e0b',
      mantra: 'RAM',
    },
    element: {
      primary: 'Ar',
      secondary: ['Fogo'],
      favorable: ['Ar', 'Fogo'],
      avoid: ['Terra'],
    },
    questions: [
      'O que te inspira?',
      'Você se permite criar livremente?',
      'Como você expressa sua essência?',
    ],
    practices: ['Escrita criativa', 'Pintura', 'Música', 'Dança', 'Culinária'],
    crystals: ['Cornalina', 'Ágata de fogo', 'Topázio imperial'],
    challenges: [],
    affirmations: [
      'Eu sou um canal de criação divina.',
      'Minha expressão é única e necessária.',
      'Criatividade flui através de mim.',
    ],
  },

  // 10. AMIZADES / COMUNIDADE
  amizades: {
    id: 'amizades',
    name: 'Amizades & Comunidade',
    nameEnglish: 'Friendships & Community',
    description: 'Suas conexões sociais, grupos de pertencimento e círculos de amizade.',
    emoji: '🤝',
    color: '#06b6d4',
    gradient: 'from-cyan-500/20 to-blue-500/10',
    icon: 'Users',
    astrology: {
      planets: ['Urano', 'Mercúrio', 'Júpiter'],
      houses: [3, 7, 11],
      signs: ['Aquário', 'Gêmeos', 'Libra', 'Sagitário'],
      points: ['Urano', 'Mercúrio', 'Júpiter'],
      aspects: ['Mercúrio-Urano', 'Sol-Júpiter'],
      keywords: ['amizade', 'grupo', 'coletivo', 'rede', 'colaboração'],
    },
    numerology: {
      lifePath: [3, 5, 11],
      masterNumbers: [11],
      personalYear: [3, 11],
      expression: [3, 5, 11],
      keywords: ['sociabilidade', 'coletivo', 'troca'],
    },
    odu: {
      primaryOdus: ['Ogbe', 'Irosun', 'Ika'],
      favorableOdus: ['Iwori', 'Ofun', 'Osa'],
      avoidOdus: [],
      eboSuggestions: ['Ebo de amizade', 'Oferenda coletiva'],
      keywords: ['amizade', 'comunidade', 'socialização'],
    },
    orixa: {
      primary: ['Oxóssi', 'Iansã'],
      secondary: ['Oxum', 'Oxalá'],
      offerings: ['Frutas', 'Mel', 'Velas', 'Salgados'],
      days: ['Quinta-feira', 'Domingo'],
      elements: ['Ar', 'Fogo'],
    },
    chakra: {
      primary: ['4º Cardíaco', '5º Laríngeo'],
      balance: 'balanced',
      color: '#06b6d4',
      mantra: 'YAM',
    },
    element: {
      primary: 'Ar',
      secondary: ['Fogo'],
      favorable: ['Ar', 'Fogo'],
      avoid: ['Terra em excesso'],
    },
    questions: [
      'Quem são seus amigos mais verdadeiros?',
      'Como você contribui para sua comunidade?',
      'Que grupos você quer fazer parte?',
    ],
    practices: ['Voluntariado', 'Grupos de estudo', 'Atividades em grupo', 'Eventos sociais'],
    crystals: ['Ágata azul', 'Turquesa', 'Crisocola', 'Água marinha'],
    challenges: [],
    affirmations: [
      'Eu atraio amizades que me elevam.',
      'Sou uma bênção para minha comunidade.',
      'Eu tenho amigos que me celebram.',
    ],
  },

  // 11. CONHECIMENTO / ESTUDOS
  conhecimento: {
    id: 'conhecimento',
    name: 'Conhecimento & Sabedoria',
    nameEnglish: 'Knowledge & Wisdom',
    description: 'Sua busca por sabedoria, estudos superiores e compreensão do mundo.',
    emoji: '📚',
    color: '#6366f1',
    gradient: 'from-indigo-500/20 to-blue-500/10',
    icon: 'BookOpen',
    astrology: {
      planets: ['Mercúrio', 'Júpiter', 'Saturno', 'Netuno'],
      houses: [3, 9, 12],
      signs: ['Gêmeos', 'Sagitário', 'Aquário', 'Peixes'],
      points: ['Mercúrio', 'Júpiter'],
      aspects: ['Mercúrio-Júpiter', 'Júpiter-Netuno', 'Mercúrio-Saturno'],
      keywords: ['aprendizado', 'filosofia', 'sabedoria', 'ensino', 'pesquisa'],
    },
    numerology: {
      lifePath: [7, 9, 11, 22],
      masterNumbers: [11, 22],
      personalYear: [7, 9],
      expression: [7, 9, 11, 22],
      keywords: ['estudo', 'sabedoria', 'pesquisa'],
    },
    odu: {
      primaryOdus: ['Irosun', 'Ika', 'Ofun'],
      favorableOdus: ['Iwori', 'Osa', 'Ofun'],
      avoidOdus: [],
      eboSuggestions: ['Ebo de Ifá', 'Oferenda a Orunmilá'],
      keywords: ['sabedoria', 'Ifá', 'conhecimento'],
    },
    orixa: {
      primary: ['Orunmilá', 'Oxóssi'],
      secondary: ['Oxalá', 'Iansã'],
      offerings: ['Pano branco', 'Mel', 'Frutas', 'Livros'],
      days: ['Domingo', 'Quinta-feira'],
      elements: ['Ar', 'Fogo'],
    },
    chakra: {
      primary: ['5º Laríngeo', '6º Frontal'],
      balance: 'low',
      color: '#6366f1',
      mantra: 'HAM',
    },
    element: {
      primary: 'Ar',
      secondary: ['Fogo'],
      favorable: ['Ar', 'Fogo'],
      avoid: ['Água em excesso'],
    },
    questions: [
      'O que você quer aprender?',
      'Como você compartilha seu conhecimento?',
      'Que sabedoria você quer transmitir?',
    ],
    practices: ['Leitura', 'Estudos formais', 'Aulas', 'Pesquisa', 'Mentoria'],
    crystals: ['Lápis-lazúli', 'Azurita', 'Malaquita', 'Fluorita'],
    challenges: [],
    affirmations: [
      'Eu sou um student eterno.',
      'A sabedoria flui através de mim.',
      'Eu compartilho conhecimento com generosidade.',
    ],
  },

  // 12. AUTOCONHECIMENTO / SHADOW WORK
  autoconhecimento: {
    id: 'autoconhecimento',
    name: 'Autoconhecimento & Shadow Work',
    nameEnglish: 'Self-Knowledge & Shadow Work',
    description: 'Sua jornada de autoconhecimento, trabalho de sombra e integração da psique.',
    emoji: '🌑',
    color: '#9333ea',
    gradient: 'from-purple-500/20 to-violet-500/10',
    icon: 'Moon',
    astrology: {
      planets: ['Plutão', 'Saturno', 'Quíron', 'Lilith'],
      houses: [1, 4, 8, 12],
      signs: ['Escorpião', 'Peixes', 'Capricórnio', 'Virgem'],
      points: ['Quíron', 'Plutão', 'Lilith', 'Nodo Sul'],
      aspects: ['Sol-Plutão', 'Lua-Plutão', 'Quíron-Sol'],
      keywords: ['sombra', 'cura', 'transformação', 'integração', 'autenticidade'],
    },
    numerology: {
      lifePath: [4, 7, 9, 11, 22, 33],
      masterNumbers: [11, 22, 33],
      personalYear: [4, 7, 9],
      expression: [7, 9, 11],
      keywords: ['profundidade', 'cura', 'integração'],
    },
    odu: {
      primaryOdus: ['Owonrin', 'Irete', 'Oyeku'],
      favorableOdus: ['Ofun', 'Okana', 'Obara'],
      avoidOdus: [],
      eboSuggestions: ['Ebo de cabeça', 'Ritual de limpeza'],
      keywords: ['sombra', 'cura', 'Ori'],
    },
    orixa: {
      primary: ['Omolu', 'Nanã', 'Iansã'],
      secondary: ['Exu', 'Oxalá'],
      offerings: ['Milho', 'Pipoca', 'Lama', 'Defumação'],
      days: ['Segunda-feira', 'Terça-feira'],
      elements: ['Terra', 'Fogo'],
    },
    chakra: {
      primary: ['6º Frontal', '1º Básico'],
      balance: 'high',
      color: '#9333ea',
      mantra: 'AUM',
    },
    element: {
      primary: 'Fogo',
      secondary: ['Terra', 'Água'],
      favorable: ['Fogo', 'Água'],
      avoid: [],
    },
    questions: [
      'Que partes de si você ainda evita olhar?',
      'Como você se relaciona com suas sombras?',
      'O que seu corpo guarda de memórias antigas?',
    ],
    practices: ['Terapia', 'Journaling', 'Meditação profunda', 'Trabalho corporal', 'Astrologia terapêutica'],
    crystals: ['Obsidiana negra', 'Sugilita', 'Labradorita', 'Pedra Lua'],
    challenges: [],
    affirmations: [
      'Eu integro luz e sombra com amor.',
      'Cada ferida é uma porta para a cura.',
      'Eu me permito ser autêntico(a).',
    ],
  },
};
