// ============================================================
// READING ACTIONS - Cabala Dos Caminhos
// Cockpit Oracular - Mesa Real Reading Management
// ============================================================

import { prisma } from '@/lib/prisma';
import { z } from 'zod';

// Type for matrix data (Casa 1-36 mapping to Carta e Odu)
export interface MatrixData {
  [casa: number]: {
    carta: number;
    odu: number;
  };
}

// Schema for creating a reading
const createReadingSchema = z.object({
  clientId: z.string().min(1, 'clientId é obrigatório'),
  userId: z.string().min(1, 'userId é obrigatório'),
  matrixData: z.record(z.number(z.any())).optional(),
});

export type CreateReadingInput = z.infer<typeof createReadingSchema>;

// Status type
export type ReadingStatus = 'PENDING' | 'COMPLETED';

// ============================================================
// READING CRUD OPERATIONS
// ============================================================

/**
 * Creates a new Mesa Real reading
 */
export async function createReading(input: CreateReadingInput) {
  const data = createReadingSchema.parse(input);

  return prisma.reading.create({
    data: {
      clientId: data.clientId,
      userId: data.userId,
      matrixData: data.matrixData || {},
      status: 'PENDING',
    },
    include: {
      client: true,
    },
  });
}

/**
 * Gets a reading by ID
 */
export async function getReading(readingId: string) {
  return prisma.reading.findUnique({
    where: { id: readingId },
    include: {
      client: true,
      report: true,
    },
  });
}

/**
 * Gets readings by client ID
 */
export async function getReadingsByClient(clientId: string) {
  return prisma.reading.findMany({
    where: { clientId },
    include: {
      report: true,
    },
    orderBy: { createdAt: 'desc' },
  });
}

/**
 * Gets readings by user ID
 */
export async function getReadingsByUser(userId: string) {
  return prisma.reading.findMany({
    where: { userId },
    include: {
      client: true,
      report: true,
    },
    orderBy: { createdAt: 'desc' },
  });
}

/**
 * Updates matrix data for a reading (save current state)
 */
export async function updateMatrixData(
  readingId: string,
  matrixData: MatrixData
) {
  return prisma.reading.update({
    where: { id: readingId },
    data: {
      matrixData: matrixData as object,
    },
  });
}

/**
 * Updates reading status
 */
export async function updateReadingStatus(
  readingId: string,
  status: ReadingStatus
) {
  return prisma.reading.update({
    where: { id: readingId },
    data: { status },
  });
}

/**
 * Deletes a reading and its report
 */
export async function deleteReading(readingId: string) {
  return prisma.reading.delete({
    where: { id: readingId },
  });
}

// ============================================================
// REPORT OPERATIONS
// ============================================================

// Schema for creating/updating a report
const saveReportSchema = z.object({
  readingId: z.string().min(1, 'readingId é obrigatório'),
  content: z.record(z.unknown()),
  pdfUrl: z.string().url().optional().nullable(),
});

export type SaveReportInput = z.infer<typeof saveReportSchema>;

/**
 * Saves a report for a reading (generated by LLM)
 */
export async function saveReport(input: SaveReportInput) {
  const data = saveReportSchema.parse(input);

  // Upsert - update if exists, create if not
  return prisma.report.upsert({
    where: { readingId: data.readingId },
    create: {
      readingId: data.readingId,
      content: data.content as object,
      pdfUrl: data.pdfUrl,
    },
    update: {
      content: data.content as object,
      pdfUrl: data.pdfUrl,
    },
    include: {
      reading: {
        include: {
          client: true,
        },
      },
    },
  });
}

/**
 * Gets a report by reading ID
 */
export async function getReportByReading(readingId: string) {
  return prisma.report.findUnique({
    where: { readingId },
    include: {
      reading: {
        include: {
          client: true,
        },
      },
    },
  });
}

/**
 * Gets a report by ID
 */
async function getReport(reportId: string) {
  return prisma.report.findUnique({
    where: { id: reportId },
    include: {
      reading: {
        include: {
          client: true,
        },
      },
    },
  });
}
