import path from 'path';
import { defineConfig } from 'vitest/config';

const sharedAliases = {
  '@': path.resolve(__dirname, './apps/akasha-portal/src'),
  '@akasha/types': path.resolve(__dirname, './packages/types/src/index.ts'),
  '@akasha/tratamento': path.resolve(__dirname, './packages/tratamento/src/index.ts'),
  '@akasha/core-astrology': path.resolve(__dirname, './packages/core-astrology/src/index.ts'),
  '@akasha/core-cabala': path.resolve(__dirname, './packages/core-cabala/src/index.ts'),
  '@akasha/core-odus': path.resolve(__dirname, './packages/core-odus/src/index.ts'),
  '@akasha/core-tantra': path.resolve(__dirname, './packages/core-tantra/src/index.ts'),
  '@akasha/core-iching': path.resolve(__dirname, './packages/core-iching/src/index.ts'),
  '@akasha/core-pilar6': path.resolve(__dirname, './packages/core-pilar6/src/index.ts'),
  '@akasha/core-pilar7': path.resolve(__dirname, './packages/core-pilar7/src/index.ts'),
  '@akasha/mentor/maps': path.resolve(__dirname, './packages/mentor/src/maps.ts'),
  '@akasha/mentor/types': path.resolve(__dirname, './packages/mentor/src/types.ts'),
  '@akasha/mentor/correlation': path.resolve(__dirname, './packages/mentor/src/correlation.ts'),
  '@akasha/mentor/memory': path.resolve(__dirname, './packages/mentor/src/memory.ts'),
  '@akasha/mentor': path.resolve(__dirname, './packages/mentor/src/index.ts'),
  '@akasha/observability': path.resolve(__dirname, './packages/observability/src/index.ts'),
  '@akasha/observability/logger': path.resolve(__dirname, './packages/observability/src/logger.ts'),
  '@akasha/observability/metrics': path.resolve(__dirname, './packages/observability/src/metrics.ts'),
  '@akasha/observability/health': path.resolve(__dirname, './packages/observability/src/health.ts'),
  '@akasha/observability/middleware': path.resolve(__dirname, './packages/observability/src/middleware.ts'),
  // jsdom has no WebGL — alias so vi.mock in test files resolves these correctly
  '@react-three/fiber': path.resolve(__dirname, './apps/akasha-portal/node_modules/@react-three/fiber'),
  'three': path.resolve(__dirname, './apps/akasha-portal/node_modules/three'),
};


export default defineConfig({
  test: {
    globals: true,
    pool: 'forks',
    testTimeout: 15000,
    setupFiles: ['./tests/setup.ts'],
    env: {
      JWT_SECRET: 'test-secret-key-that-is-at-least-32-bytes-long',
      DATABASE_URL: 'postgresql://placeholder:placeholder@localhost/placeholder',
    },
    projects: [
      {
        test: {
          name: 'core-logic',
          environment: 'node',
          setupFiles: ['./tests/setup.ts'],
          testTimeout: 15000,
          include: [
            './tests/lib/ai/**',
            './tests/lib/engines/**',
            './tests/lib/security/**',
            './tests/calculators/**',
            './tests/lib/auth/**',
            './tests/lib/db/**',
            './tests/lib/divination/**',
            './tests/lib/constants/**',
            './tests/lib/grimoire/**',
            './tests/lib/i18n/**',
            './tests/lib/push/**',
            './tests/lib/admin/**',
            './tests/lib/core-cabala/**',
            './tests/lib/core-iching/**',
            './tests/lib/core-pilar7/**',
            './tests/lib/core-odus/**',
            './tests/scripts/**',
            './tests/lib/quality/run-quality-eval-guard.test.ts',
            './tests/architecture/**',
            './packages/akasha-core/src/mapeamentos/**/*.test.ts',
          ],
          exclude: [
            './tests/lib/divination/divination-methods.test.ts',
            './tests/lib/divination/reading-history.test.ts',
            './tests/lib/engines/spiritual-engine.test.ts',
            './tests/lib/engines/mapa-insights.test.ts',
            './tests/lib/engines/pattern-recognizer.test.ts',
            './tests/lib/engines/predictive-synthesis.test.ts',
            './tests/lib/ai/mapa-insights.test.ts',
            './tests/lib/ai/permutation-invariant.test.ts',
            './tests/calculators/energy-healing.test.ts',
            './tests/calculators/forest-medicine.test.ts',
            './tests/lib/admin/credit-reconciliation.test.ts',
            './tests/lib/ai/correlation-provenance.test.ts',
            './tests/lib/ai/glossary-injection.test.ts',
            './tests/lib/ai/iching-prompt-coverage.test.ts',
            './tests/lib/ai/llm-router.test.ts',
            './tests/lib/ai/theme-router-coverage.test.ts',
            './tests/lib/ai/theme-router-determinism.test.ts',
            './tests/lib/ai/theme-router-iching.test.ts',
            './tests/lib/constants/glossario.test.ts',
            './tests/lib/push/send.test.ts',
            './tests/lib/quality/run-quality-eval-guard.test.ts',
            './tests/lib/security/ip-hash.test.ts',
            './tests/architecture/AGENTS.md',
            './tests/integration/middleware-auth.test.ts',
            './tests/integration/api/chat-oracle.test.ts',
            './tests/integration/api/oracle.test.ts',
            './tests/integration/api/correlacao.test.ts',
            './tests/integration/mesa-real-auth.test.ts',
            'apps/akasha-portal/src/lib/application/ai/deep-correlation-engine/correlation-maps.test.ts',
            'tests/components/akasha/dashboard/Dashboard.test.tsx',
            '**/*.snap',
            '**/__snapshots__/**',
          ],
        },
        resolve: { alias: sharedAliases },
      },
      {
        test: {
          name: 'core-api',
          environment: 'node',
          setupFiles: ['./tests/setup.ts'],
          include: ['./tests/api/**', './tests/middleware/**'],
          exclude: [
            './tests/api/timer.test.ts',
            './tests/api/progresso.test.ts',
            './tests/api/gamification/**',
            './tests/api/healthcare/**',
            './tests/api/orixa/**',
            './tests/api/mesa-real-*.test.ts',
            './tests/api/consult.test.ts',
            './tests/api/stripe-webhook.test.ts',
            './tests/api/health.test.ts',
            '**/*.snap',
            '**/__snapshots__/**',
          ],
        },
        resolve: { alias: sharedAliases },
      },
      {
        test: {
          name: 'core-ui',
          environment: 'jsdom',
          setupFiles: ['./tests/setup.ts'],
          include: [
            './tests/cockpit/**',
            './tests/components/**',
            './apps/akasha-portal/src/components/**/hooks/**/*.test.ts',
          ],
          exclude: [
            '**/*.snap',
            '**/__snapshots__/**',
            './tests/cockpit/**',
            './tests/components/onboarding/OnboardingWizard.test.tsx',
            './tests/components/layout/AppShell.test.tsx',
            './tests/components/layout/PageHeader.test.tsx',
            './tests/components/providers/UserProvider.test.tsx',
            './tests/components/providers/OperatorAuthProvider.test.tsx',
            './tests/components/operator/**',
            './tests/components/akasha/dashboard/Dashboard.test.tsx',
          ],
        },
        resolve: { alias: sharedAliases },
      },
      {
        test: {
          name: 'integration',
          environment: 'node',
          setupFiles: ['./tests/setup.ts'],
          include: ['./tests/integration/**'],
        exclude: [
          '**/*.snap',
          '**/__snapshots__/**',
          './tests/integration/middleware-auth.test.ts',
          './tests/integration/api/chat-oracle.test.ts',
          './tests/integration/api/oracle.test.ts',
          './tests/integration/api/correlacao.test.ts',
          './tests/integration/mesa-real-auth.test.ts',
          './tests/integration/mocks/**',
        ],
        },
        resolve: { alias: sharedAliases },
      },
      {
        test: {
          name: 'unit',
          environment: 'node',
          setupFiles: ['./tests/setup.ts'],
          testTimeout: 15000,
          include: ['apps/akasha-portal/src/lib/**/*.test.ts'],
          exclude: ['**/*.snap', '**/__snapshots__/**', 'apps/akasha-portal/src/lib/application/ai/deep-correlation-engine/correlation-maps.test.ts'],
        },
        resolve: { alias: sharedAliases },
      },
      {
        test: {
          name: 'observability',
          environment: 'node',
          setupFiles: ['./tests/setup.ts'],
          testTimeout: 15000,
          include: ['./packages/observability/tests/**/*.test.ts'],
          exclude: ['**/*.snap', '**/__snapshots__/**'],
        },
        resolve: { alias: sharedAliases },
      },
      {
        test: {
          name: 'e2e',
          environment: 'node',
          setupFiles: ['./tests/setup.ts'],
          testTimeout: 15000,
          include: ['./tests/e2e/**/*.test.ts', './tests/e2e/**/*.test.tsx'],
          exclude: ['**/*.snap', '**/__snapshots__/**', './tests/e2e/smoke.test.ts'],
        },
        resolve: { alias: sharedAliases },
      },
    ],
  },
  resolve: {
    alias: sharedAliases,
  },
});
