// kundalini-v2-data.ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any
import type { KundaliniData } from '../kundalini-data';

export interface KundaliniV2Data extends KundaliniData {
  v2Features: {
    energyFlow: string[];
    meditationStages: string[];
    sacredGeometry: string[];
    mantras: string[];
    yantras: string[];
    activateSteps: string[];
  };
}

const kundaliniV2Data: KundaliniV2Data[] = [
  {
    id: 'v2-dormant',
    name: 'Kundalini Shakti V2',
    namePt: 'Kundalini Adormecida V2',
    nameEn: 'Dormant Kundalini V2',
    sanskrit: 'कुंडलिनी शक्ति',
    chakra: 'root',
    element: 'Fogo',
    location: 'Base da coluna vertebral',
    color: 'Amarelo-dourado',
    colorHex: '#FFD700',
    qualities: ['Potência', 'Energia latente', 'Força vital', 'Liberdade'],
    effects: ['Armazenamento de energia', 'Potencial adormecido', 'Reservatório de força'],
    symptoms: ['Inércia', 'Baixa energia', 'Bloqueios emocionais'],
    practices: ['Respiração básica', 'Posturas simples', 'Meditação inicial'],
    description: 'Enhanced Kundalini data with advanced v2 features for deeper spiritual practice.',
    descriptionPt: 'Dados Kundalini melhorados com recursos avançados v2 para prática espiritual mais profunda.',
    awakeningSigns: ['Sensação de calor na base da coluna', 'Formigamento', 'Fascinação espiritual'],
    sequence: 0,
    v2Features: {
      energyFlow: ['Canal central (Sushumna)', 'Canal Ida (energia lunar)', 'Canal Pingala (energia solar)'],
      meditationStages: ['Preparação', 'Aquecimento', 'Ativação básica', 'Estabilização'],
      sacredGeometry: ['Yantra triangular', 'Sri Yantra básico', 'Flor de vida'],
      mantras: ['LAM (raiz)', 'Om Gam Ganapataye Namaha', 'So Hum'],
      yantras: ['Triquetra básica', 'Yantra do Muladhara'],
      activateSteps: ['Grounding', 'Respiração', 'Visualização', 'Mantra', 'Silêncio'],
    },
  },
  {
    id: 'v2-root-chakra',
    name: 'Muladhara V2 activation',
    namePt: 'Ativação do Muladhara V2',
    nameEn: 'Root Chakra V2 Activation',
    sanskrit: 'मूलाधार',
    chakra: 'root',
    element: 'Terra',
    location: 'Base da coluna, entre o cóccix e o sacro',
    color: 'Vermelho',
    colorHex: '#FF0000',
    qualities: ['Sobrevivência', 'Segurança', 'Estabilidade', 'Conexão terrestre'],
    effects: ['Estabilização física', 'Sensação de enraizamento', 'Fortalecimento do corpo'],
    symptoms: ['Calor na base da coluna', 'Vibração nas pernas', 'Estabilidade emocional'],
    practices: ['Asanas de接地', 'Mantras LAM', 'Exercícios deaterramento'],
    description: 'Enhanced Root Chakra activation with v2 advanced techniques and sacred geometry.',
    descriptionPt: 'Ativação Aprimorada do Chakra Raiz com técnicas avançadas v2 e geometria sagrada.',
    awakeningSigns: ['Fortalecimento da coluna', 'Sensação de estabilidade', 'Conexão com a terra'],
    sequence: 1,
    v2Features: {
      energyFlow: ['Ascensão básica pelo canal central', 'Conexão Terra-Céu', 'Fluxo horizontal stabilizado'],
      meditationStages: ['Enraizamento profundo', 'Conexão elementar', 'Estabilização da serpente', 'Integração corpo-terra'],
      sacredGeometry: ['Yantra quadrado (Terra)', 'Círculo terrestre', 'Hexágono de estabilização'],
      mantras: ['LAM', 'Om Lam Muladharaya Namaha', 'Prithivi Bija'],
      yantras: ['Yantra Muladhara expandido', 'Yantra Terra Primordial', 'Elemento Terra Yantra'],
      activateSteps: ['Tocando a terra', 'Postura Muira', 'Respiração LAM', 'Visualização vermelha', 'Enraizamento total'],
    },
  },
  {
    id: 'v2-sacral-chakra',
    name: 'Svadhisthana V2 activation',
    namePt: 'Ativação do Svadhisthana V2',
    nameEn: 'Sacral Chakra V2 Activation',
    sanskrit: 'स्वाधिष्ठान',
    chakra: 'sacral',
    element: 'Água',
    location: 'Baixo abdômen, abaixo do umbigo',
    color: 'Laranja',
    colorHex: '#FF8000',
    qualities: ['Criatividade', 'Sexualidade', 'Fluidez', 'Liberdade emocional'],
    effects: ['Fluxo criativo', 'Liberação emocional', 'Vitalidade sexual'],
    symptoms: ['Sensação de ondas', 'Liberação de fluidos', 'Emoções intensificadas'],
    practices: ['Movimentos fluidos', 'Mantras VAM', 'Dance sagrada'],
    description: 'Enhanced Sacral Chakra with v2 water element flow and emotional release techniques.',
    descriptionPt: 'Chakra Sacral Aprimorado com fluxo de elemento água v2 e técnicas de liberação emocional.',
    awakeningSigns: ['Liberação criativa', 'Harmonização emocional', 'Fluidez nos movimentos'],
    sequence: 2,
    v2Features: {
      energyFlow: ['Fluxo ondulante', 'Ciclo lunar interno', 'Maré emocional'],
      meditationStages: ['Aceitação液态', 'Fluxo sem resistência', 'Transformação líquida', 'Purificação'],
      sacredGeometry: ['Yantra crescente (Lua)', 'Círculo de ondas', 'Lua crescente sagrada', 'Flor aquática'],
      mantras: ['VAM', 'Om Vam Svadhisthanaya Namaha', 'Jala Bija'],
      yantras: ['Yantra Svadhisthana expandido', 'Yantra Lua', 'Yantra água primordial'],
      activateSteps: ['Postura de água', 'Respiração VAM', 'Visualização ondas', 'Fluidez completa', 'Liberação emocional'],
    },
  },
  {
    id: 'v2-solar-plexus',
    name: 'Manipura V2 activation',
    namePt: 'Ativação do Plexo Solar V2',
    nameEn: 'Solar Plexus V2 Activation',
    sanskrit: 'मणिपूर',
    chakra: 'solar-plexus',
    element: 'Fogo',
    location: 'Epigástrio, área do estômago',
    color: 'Amarelo',
    colorHex: '#FFFF00',
    qualities: ['Poder pessoal', 'Vontade', 'Autoconfiança', 'Transformação'],
    effects: ['Fortificação do eu', 'Aumento dawill power', 'Transformação pessoal'],
    symptoms: ['Calor no plexo solar', 'Expansão do ego', 'Chamas internas'],
    practices: ['Pranayama intenso', 'Mantras RAM', 'Fogo interno meditation'],
    description: 'Enhanced Solar Plexus with v2 fire transformation and personal power awakening.',
    descriptionPt: 'Plexo Solar Aprimorado com transformação de fogo v2 e despertar de poder pessoal.',
    awakeningSigns: ['Poder pessoal aumentado', 'Confiança interior', 'Capacidade de transformação'],
    sequence: 3,
    v2Features: {
      energyFlow: ['Fogo ascendente', 'Agni (fogo interno)', 'Pranayama intensificado'],
      meditationStages: ['Ignição', 'Chama interior', 'Expansão do fogo', 'Transmutação'],
      sacredGeometry: ['Yantra triangular (Fogo)', 'Triângulo invertida', 'Lótus de fogo', 'Agni Yantra'],
      mantras: ['RAM', 'Om Ram Manipuraya Namaha', 'Agni Bija'],
      yantras: ['Yantra Manipura expandido', 'Yantra Fogo', 'Yantra Agni'],
      activateSteps: ['Postura de fogo', 'Respiração RAM', 'Visualização chamas', 'Capacitação interna', 'Expansão solar'],
    },
  },
  {
    id: 'v2-heart-chakra',
    name: 'Anahata V2 activation',
    namePt: 'Ativação do Anahata V2',
    nameEn: 'Heart Chakra V2 Activation',
    sanskrit: 'अनाहत',
    chakra: 'heart',
    element: 'Ar',
    location: 'Centro do peito',
    color: 'Verde',
    colorHex: '#00FF00',
    qualities: ['Amor incondicional', 'Compassão', 'Perdão', 'Conexão'],
    effects: ['Expansão do coração', 'Liberação do amor', 'Unificação interior'],
    symptoms: ['Abertura do peito', 'Sensação de expansão', 'Lágrimas de alegria'],
    practices: ['Meditação de amor', 'Mantras YAM', 'Prática do perdão'],
    description: 'Enhanced Heart Chakra with v2 unconditional love and emotional healing techniques.',
    descriptionPt: 'Chakra do Coração Aprimorado com amor incondicional v2 e técnicas de cura emocional.',
    awakeningSigns: ['Amor incondicional', 'Compassão profunda', 'Perdão total'],
    sequence: 4,
    v2Features: {
      energyFlow: ['Expansão radial', 'Amor incondicional', 'Fluxo de compaixão'],
      meditationStages: ['Abertura', 'Amor universal', 'Compaixão ativa', 'Perdão total'],
      sacredGeometry: ['Yantra hexagonal (Ar)', 'Hexagrama de Shiva-Shakti', 'Lótus de 12 pétalas', 'Anahata Yantra'],
      mantras: ['YAM', 'Om Yam Anahathaya Namaha', 'Vayu Bija'],
      yantras: ['Yantra Anahata expandido', 'Yantra Coração', 'Yantra compaixão'],
      activateSteps: ['Postura aberta', 'Respiração YAM', 'Visualização verde', 'Expansão do peito', 'Perdão completo'],
    },
  },
  {
    id: 'v2-throat-chakra',
    name: 'Vishuddha V2 activation',
    namePt: 'Ativação do Vishuddha V2',
    nameEn: 'Throat Chakra V2 Activation',
    sanskrit: 'विशुद्ध',
    chakra: 'throat',
    element: 'Éter',
    location: 'Garganta',
    color: 'Azul',
    colorHex: '#0000FF',
    qualities: ['Comunicação', 'Verdade', 'Expressão autêntica', 'Criação'],
    effects: ['Clareza de comunicação', 'Expressão verdadeira', 'Criação sagrada'],
    symptoms: ['Vibração na garganta', 'Clareza mental', 'Voz expandida'],
    practices: ['Canto sagrado', 'Mantras HAM', 'Expressão criativa'],
    description: 'Enhanced Throat Chakra with v2 sacred sound and authentic expression techniques.',
    descriptionPt: 'Chakra da Garganta Aprimorado com som sagrado v2 e técnicas de expressão autêntica.',
    awakeningSigns: ['Comunicação clara', 'Expressão autêntica', 'Conexão com a verdade'],
    sequence: 5,
    v2Features: {
      energyFlow: ['Vibração sonora', 'Resonânciaetheric', 'Comunicação cósmica'],
      meditationStages: ['Purificação verbal', 'Som primordial', 'Expressão auténtica', 'Criação sagrada'],
      sacredGeometry: ['Yantra circular (Éter)', 'Círculo de som na garganta', 'Saraswati Yantra', 'Mehru de som'],
      mantras: ['HAM', 'Om Ham Vishuddhanaya Namaha', 'Akasha Bija'],
      yantras: ['Yantra Vishuddha expandido', 'Yantra Éter', 'Yantra garganta', 'Yantra sonido'],
      activateSteps: ['Postura da garganta', 'Respiração HAM', 'Abertura vocal', 'Som primordial', 'Comunicação clara'],
    },
  },
  {
    id: 'v2-third-eye',
    name: 'Ajna V2 activation',
    namePt: 'Ativação do Ajna V2',
    nameEn: 'Third Eye V2 Activation',
    sanskrit: 'आज्ञा',
    chakra: 'third-eye',
    element: 'Luz',
    location: 'Entre as sobrancelhas',
    color: 'Índigo',
    colorHex: '#4B0082',
    qualities: ['Intuição', 'Visão interior', 'Sabedoria', 'Discernimento'],
    effects: ['Expansão da consciência', 'Percepção intuitiva', 'Visão clara'],
    symptoms: ['Pressão entre sobrancelhas', 'Visões', 'Clareza mental profunda'],
    practices: ['Meditação no terceiro olho', 'Mantras OM', 'Visualização avançada'],
    description: 'Enhanced Third Eye with v2 advanced intuition and inner vision techniques.',
    descriptionPt: 'Terceiro Olho Aprimorado com intuição avançada v2 e técnicas de visão interior.',
    awakeningSigns: ['Visão intuitiva', 'Percepção ampliada', 'Sabedoria interior'],
    sequence: 6,
    v2Features: {
      energyFlow: ['Foco frontal', 'Visão interna', 'Pranayama do terceiro olho'],
      meditationStages: ['Focalização', 'Intuição', 'Clareza', 'Visão expansiva', 'Siddhis awakening'],
      sacredGeometry: ['Yantra Ajna двуликий (2 pétalas)', 'Лотос双色 (duas cores)', 'Tatva Yantra', 'Ganky'],
      mantras: ['OM (Aum)', 'Om Om Ajnanaaya Namaha', 'Om Shani'],
      yantras: ['Yantra Ajna expandido', 'Yantra lumière (Luz)', 'Yantra terceiro olho'],
      activateSteps: ['Fechando os olhos', 'Foco no pontoentre sobrancelhas', 'Respiração OM', 'Visualização de luz', 'Intuição expansão'],
    },
  },
  {
    id: 'v2-crown-chakra',
    name: 'Sahasrara V2 activation',
    namePt: 'Ativação do Sahasrara V2',
    nameEn: 'Crown Chakra V2 Activation',
    sanskrit: 'सहस्रार',
    chakra: 'crown',
    element: 'Consciência',
    location: 'Topo da cabeça',
    color: 'Violeta',
    colorHex: '#8B00FF',
    qualities: ['Iluminação', 'União divina', 'Consciência cósmica', 'Transcendência'],
    effects: ['Expansão para o divino', 'Consciência cósmica', 'Libertação final'],
    symptoms: ['Sensação de abertura no topo', 'Luz dourada', 'Expansão infinita'],
    practices: ['Meditação de unidade', 'Mantras silêncio', 'Consciência sem objeto'],
    description: 'Enhanced Crown Chakra with v2 cosmic consciousness and divine union techniques.',
    descriptionPt: 'Chakra da Coroa Aprimorado com consciência cósmica v2 e técnicas de união divina.',
    awakeningSigns: ['Iluminação', 'União com o divino', 'Consciência cósmica'],
    sequence: 7,
    v2Features: {
      energyFlow: ['Descensão radial dorada', 'Sefirah keter', 'Consciência cósmica'],
      meditationStages: ['Sopro do silêncio', 'Vaziofúlfill', 'Unicidade', 'Consciência pura', 'Libertação final'],
      sacredGeometry: ['Yantra мандала (mil pétalas)', 'Sri Yantra completo', 'Тороидальный (Torus)', 'Sahasrara completo'],
      mantras: ['OM Мантра silêncio (Aum)', 'So Hum Sat Namam', 'Om Sat Chit Ananda'],
      yantras: ['Yantra Sahasrara completo', 'Yantra Coroa Divina', 'Yantra кетер', 'Crown Merkaba'],
      activateSteps: ['Sentar em silêncio', 'Postura céu aberto', 'Respiração sutil', 'Dissolução do ego', 'União cósmica'],
    },
  },
];

export function getData(): KundaliniV2Data[] {
  return kundaliniV2Data;
}
