// @ts-nocheck
 
// meji-osa-data.ts — Meji-Osa divination data (16 Principal Odu of Obeche/Ifa)

export interface MejiOsaData {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_OSA_DATA: MejiOsaData[] = [
  {
    id: 'meji-osa-001',
    name: 'Meji-Osa',
    portugueseName: 'Meji-Osa',
    order: 1,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Netuno'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Marrom'],
    offerings: ['Folhas de Osa', 'Água de rio', 'Milho'],
    ebos: ['Ebo de destino', 'Ebo de mudanca'],
    taboos: ['Nao caminhar sozinho na floresta', 'Nao cortar arvores sagradas'],
    strengths: ['Transformacao', 'Adaptabilidade', 'Forca espiritual'],
    weaknesses: ['Indecisao', 'Supersticao'],
    health: ['Figado', 'Rins'],
    meanings: ['Destino', 'Mudanca', 'Floresta', 'Mistério'],
    ifaMessage: 'Meji-Osa abre a porta da floresta sagrada, onde os destinos se entrelaçam e as forcas invisiveis governam.',
  },
  {
    id: 'meji-osa-002',
    name: 'Meji-Osa-Ogbe',
    portugueseName: 'Meji-Osa-Ogbe',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Venus'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Cancer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Prata'],
    offerings: [' leite', 'Flores brancas', 'Coco'],
    ebos: ['Ebo de protecao', 'Ebo de reconciliacao'],
    taboos: ['Nao consumir carne vermelha', 'Nao fazer barulho a noite'],
    strengths: ['Intuicao', 'Protecao', 'Sabedoria'],
    weaknesses: ['Excesso de cautela', 'Paranoia'],
    health: ['Estomago', 'Intestinos'],
    meanings: ['Floresta', 'Conhecimento oculto', 'Uniao dos opostos'],
    ifaMessage: 'Meji-Osa-Ogbe revela que a sabedoria da floresta protege aqueles que respeitam seus caminhos.',
  },
  {
    id: 'meji-osa-003',
    name: 'Meji-Osa-Oyeku',
    portugueseName: 'Meji-Osa-Oyeku',
    order: 3,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Gevurah'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Laranja'],
    offerings: ['Pimenta', 'Gengibre', 'Vinho de palma'],
    ebos: ['Ebo de vitoria', 'Ebo de forca'],
    taboos: ['Nao demonstrar fraqueza', 'Nao aceitar ajuda facilmente'],
    strengths: ['Coragem', 'Determinacao', 'Luta'],
    weaknesses: ['Agressividade', 'Imprudencia'],
    health: ['Cabeca', 'Olhos'],
    meanings: ['Luta', 'Perseveranca', 'Conquistar atraves do esfuerzo'],
    ifaMessage: 'Meji-Osa-Oyeku ensina que a batalha na floresta sagrada exige forca e persistencia.',
  },
  {
    id: 'meji-osa-004',
    name: 'Meji-Osa-Odi',
    portugueseName: 'Meji-Osa-Odi',
    order: 4,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Cancer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Agua de chuva', 'Flores do campo', 'Farinha de milho'],
    ebos: ['Ebo de reflexao', 'Ebo de verdade'],
    taboos: ['Nao mentir para si mesmo', 'Nao ignorar sinais'],
    strengths: ['Sabedoria', 'Discernimento', 'Paciencia'],
    weaknesses: ['Melancolia', 'Isolamento'],
    health: ['Coracao', 'Pulmoes'],
    meanings: ['Reflexao', 'Verdade oculta', 'Camino da sabedoria'],
    ifaMessage: 'Meji-Osa-Odi abre o livro dos segredos onde a verdade se revela lentamente.',
  },
  {
    id: 'meji-osa-005',
    name: 'Meji-Osa-Irosun',
    portugueseName: 'Meji-Osa-Irosun',
    order: 5,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Mercurio', 'Plutao'],
    sephirot: ['Hod', 'Netzach'],
    sign: 'Gemeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Ouro'],
    offerings: ['Ouro', 'Perfume', 'Incenso'],
    ebos: ['Ebo de advertncia', 'Ebo de purificacao'],
    taboos: ['Nao ignorar sonhos', 'Nao desconsiderar pressagios'],
    strengths: ['Visao', 'Advertncia', 'Protecao espiritual'],
    weaknesses: ['Receio excesivo', 'Duvida'],
    health: ['Bracos', 'Maos'],
    meanings: ['Advertncia', 'Vigilancia', 'Protecao contra perigos ocultos'],
    ifaMessage: 'Meji-Osa-Irosun advierte que os olhos da floresta veem tudo antes que aconteca.',
  },
  {
    id: 'meji-osa-006',
    name: 'Meji-Osa-Ogunda',
    portugueseName: 'Meji-Osa-Ogunda',
    order: 6,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Marte', 'Saturno'],
    sephirot: ['Gevurah', 'Hod'],
    sign: 'Escorpiao',
    dayOfWeek: 'Terca-feira',
    direction: 'Sul',
    colors: ['Preto', 'Vermelho escuro'],
    offerings: ['Ferro', 'Facas', 'Vinho fuerte'],
    ebos: ['Ebo de trabalho', 'Ebo de conquista'],
    taboos: ['Nao recusar missao', 'Nao abandonar batalha'],
    strengths: ['Acao', 'Forca', 'Destreza'],
    weaknesses: ['Impaciencia', 'Teimosia'],
    health: ['Osso', 'Sangre'],
    meanings: ['Acao', 'Feito heroico', 'Determinacao'],
    ifaMessage: 'Meji-Osa-Ogunda empunha a espada da floresta para cumprir a tarefa sagrada.',
  },
  {
    id: 'meji-osa-007',
    name: 'Meji-Osa-Ose',
    portugueseName: 'Meji-Osa-Ose',
    order: 7,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Venus'],
    sephirot: ['Tiphereth', 'Hod'],
    sign: 'Leao',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Laranja', 'Amarelo'],
    offerings: ['Frutas', 'Mel', 'Vinho doce'],
    ebos: ['Ebo de cura', 'Ebo de alegria'],
    taboos: ['Nao spread disease', 'Nao traer mal.'],
    strengths: ['Cura', 'Medicina', 'Alegría'],
    weaknesses: ['Exceso de confianza', 'Superficialidad'],
    health: ['Espalda', 'Espina'],
    meanings: ['Cura', 'Medicina sagrada', 'Alivio'],
    ifaMessage: 'Meji-Osa-Ose trae la curacion de la floresta para sanar lo que parece irreparable.',
  },
  {
    id: 'meji-osa-008',
    name: 'Meji-Osa-Oba',
    portugueseName: 'Meji-Osa-Oba',
    order: 8,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Venus', 'Jupiter'],
    sephirot: ['Netzach', 'Tiphereth'],
    sign: 'Libra',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Rosa'],
    offerings: ['Comida elaborada', 'Bebidas finas', 'Flores de laranjeira'],
    ebos: ['Ebo de lealtad', 'Ebo de servicio'],
    taboos: ['Nao trair confianza', 'Nao esquecer deveres'],
    strengths: ['Lealtad', 'Servicio', 'Nobleza'],
    weaknesses: ['Subordinacion excesiva', 'Falta de iniciativa'],
    health: ['Rinones', 'Vejiga'],
    meanings: ['Servicio', 'Lealtad', 'Camino del rei'],
    ifaMessage: 'Meji-Osa-Oba sirve al trono de la floresta con devocion y sabiduria.',
  },
  {
    id: 'meji-osa-009',
    name: 'Meji-Osa-Owonrin',
    portugueseName: 'Meji-Osa-Owonrin',
    order: 9,
    polarity: 'masculine',
    element: 'Wind',
    planets: ['Mercurio', 'Lua'],
    sephirot: ['Hod', 'Malkuth'],
    sign: 'Sagitario',
    dayOfWeek: 'Quinta-feira',
    direction: 'Norte',
    colors: ['Verde', 'Azul escuro'],
    offerings: ['Manteiga', 'Farinha', 'Agua corrente'],
    ebos: ['Ebo de viaje', 'Ebo de exploracao'],
    taboos: ['Nao quedarse quieto', 'Nao rechazar aventura'],
    strengths: ['Aventura', 'Exploracao', 'Libertad'],
    weaknesses: ['Inquietud', 'Fuga de responsabilidades'],
    health: ['Cadera', 'Piernas'],
    meanings: ['Viaje', 'Exploracion', 'Descubrimiento'],
    ifaMessage: 'Meji-Osa-Owonrin camina por los senderos de la floresta buscando nuevos horizontes.',
  },
  {
    id: 'meji-osa-010',
    name: 'Meji-Osa-Odaye',
    portugueseName: 'Meji-Osa-Odaye',
    order: 10,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Venus'],
    sephirot: ['Binah', 'Malkuth'],
    sign: 'Cancer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Sul',
    colors: ['Branco', 'Bege'],
    offerings: ['Farinha de mandioca', 'Agua de coco', 'Pao'],
    ebos: ['Ebo de comunidad', 'Ebo de integracao'],
    taboos: ['Nao excluir nadie', 'Nao dividir a comunidade'],
    strengths: ['unidad', 'comunidad', 'armonia'],
    weaknesses: ['Conformismo', 'Mediocridad'],
    health: ['Utero', 'Ovaras'],
    meanings: ['Unidad', 'Comunidad', 'Inclusion'],
    ifaMessage: 'Meji-Osa-Odaye reune a todos bajo el manto de la floresta sagrada.',
  },
  {
    id: 'meji-osa-011',
    name: 'Meji-Osa-Iwori',
    portugueseName: 'Meji-Osa-Iwori',
    order: 11,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Sol'],
    sephirot: ['Chokmah', 'Malkuth'],
    sign: 'Capricornio',
    dayOfWeek: 'Sabado',
    direction: 'Leste',
    colors: ['Marrom', 'Preto'],
    offerings: ['Vinho fuerte', 'Carne seca', 'Milho torrado'],
    ebos: ['Ebo de sabiduria', 'Ebo de respeite'],
    taboos: ['Nao des respeitar mayores', 'Nao burlar de tradicoes'],
    strengths: ['Sabiduria ancestral', 'Experiencia', 'Respeto'],
    weaknesses: ['Rigidez', 'Dificultad para cambiar'],
    health: ['Joelhos', 'Ossos'],
    meanings: ['Sabiduria', 'Experiencia', 'Camino del anciano'],
    ifaMessage: 'Meji-Osa-Iwori trae la sabiduria de los ancestros de la floresta.',
  },
  {
    id: 'meji-osa-012',
    name: 'Meji-Osa-Osa',
    portugueseName: 'Meji-Osa-Osa',
    order: 12,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Netuno', 'Plutao'],
    sephirot: ['Yesod', 'Malkuth'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Verde escuro', 'Amarelo escuro'],
    offerings: ['Raizes', 'Plantas medicinais', 'Cascas de arvore'],
    ebos: ['Ebo de misterio', 'Ebo de transformacao'],
    taboos: ['Nao revelar segredos', 'Nao confiar facilmente'],
    strengths: ['Misterio', 'Transformacao', 'Adaptacao'],
    weaknesses: ['Manipulacao', 'Segredos oscuros'],
    health: ['Intestinos', 'Pele'],
    meanings: ['Misterio', 'Transformacion', 'Lo oculto'],
    ifaMessage: 'Meji-Osa-Osa caminha entre as sombras da floresta onde tudo pode mudar.',
  },
  {
    id: 'meji-osa-013',
    name: 'Meji-Osa-Ika',
    portugueseName: 'Meji-Osa-Ika',
    order: 13,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Plutao', 'Lua'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Escorpiao',
    dayOfWeek: 'Terca-feira',
    direction: 'Oeste',
    colors: ['Preto', 'Vermelho'],
    offerings: ['sangue', 'Vinho escuro', 'Carne crua'],
    ebos: ['Ebo de purificacao', 'Ebo de limpieza'],
    taboos: ['Nao hacer dano', 'Nao usar veneno'],
    strengths: ['Purificacao', ' limpieza', 'Renovacao'],
    weaknesses: ['Revanche', 'Rancor'],
    health: ['Reproducao', 'Genitais'],
    meanings: ['Purificacao', 'Remocao de males', 'Limpieza'],
    ifaMessage: 'Meji-Osa-Ika limpia el cuerpo y el espiritu en las aguas sagradas de la floresta.',
  },
  {
    id: 'meji-osa-014',
    name: 'Meji-Osa-Oturupon',
    portugueseName: 'Meji-Osa-Oturupon',
    order: 14,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Gevurah', 'Chokmah'],
    sign: 'Leao',
    dayOfWeek: 'Domingo',
    direction: 'Norte',
    colors: ['Ouro', 'Vermelho'],
    offerings: ['Ouro', ' joias', 'Roupas finas'],
    ebos: ['Ebo de prosperidade', 'Ebo de abundancia'],
    taboos: ['Nao ser avarento', 'Nao guardar tudo para si'],
    strengths: ['Abundancia', 'Prosperidade', 'Generosidade'],
    weaknesses: ['Avaricia', 'Materialismo'],
    health: ['Coracao', 'Peito'],
    meanings: ['Abundancia', 'Prosperidade', 'Fecondidade'],
    ifaMessage: 'Meji-Osa-Oturupon abre las puertas de la abundancia en la floresta.',
  },
  {
    id: 'meji-osa-015',
    name: 'Meji-Osa-Otura',
    portugueseName: 'Meji-Osa-Otura',
    order: 15,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Jupiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphereth'],
    sign: 'Sagitario',
    dayOfWeek: 'Quinta-feira',
    direction: 'Leste',
    colors: ['Azul', 'Ouro'],
    offerings: ['Mel', 'Leite', 'Frutas douradas'],
    ebos: ['Ebo de clareza', 'Ebo de orientacao'],
    taboos: ['Nao perder esperanza', 'Nao ignorar a verdade'],
    strengths: ['clareza', 'orientacao', 'Vocao'],
    weaknesses: ['Exceso de idealismo', 'Desconexion'],
    health: ['Figado', 'Musculos'],
    meanings: [' clareza', 'Orientacao divina', 'Vocao'],
    ifaMessage: 'Meji-Osa-Otura ilumina el camino con la luz de la floresta sagrada.',
  },
  {
    id: 'meji-osa-016',
    name: 'Meji-Osa-Osa-Red',
    portugueseName: 'Meji-Osa-Osa-Red',
    order: 16,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutao'],
    sephirot: ['Gevurah', 'Netzach'],
    sign: 'Aries',
    dayOfWeek: 'Terca-feira',
    direction: 'Sul',
    colors: ['Vermelho', 'Laranja'],
    offerings: [' sangue fresco', 'Pimenta', 'Fogo'],
    ebos: ['Ebo de forca', 'Ebo de protecao'],
    taboos: ['Nao tener miedo', 'Nao huir del perigo'],
    strengths: ['forca', 'Poder', 'Coragem'],
    weaknesses: ['Violencia', 'Destruicao'],
    health: ['Cabeca', 'Sangue'],
    meanings: ['Forca', 'Poder', 'Protecao maxima'],
    ifaMessage: 'Meji-Osa-Osa-Red arde con la fuerza del fuego de la floresta.',
  },
];

export function getData(): MejiOsaData[] {
  return MEJI_OSA_DATA;
}