/**
 * prompts-t/astrologia.ts — 30 prompts for Astrologia
 *
 * Themes: moon sign, transits, lunar phase, ascendant, Mercury retrograde,
 *   Saturn return, nakshatra-adjacent concept (without co-opting)
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'astrologia';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const ASTROLOGIA_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Que fase lunar te acolhe hoje?', en: 'Which moon phase holds you today?', es: '¿Qué fase lunar te acoge hoy?' },
    { 'pt-BR': 'Olha a lua. Agradece em silêncio.', en: 'Look at the moon. Thank in silence.', es: 'Mira la luna. Agradece en silencio.', modality: 'ritual' }, 180),
  fp(2, 'sombra',
    { 'pt-BR': 'Que planeta retrógrado fala hoje em teu mapa?', en: 'Which retrograde planet speaks in your chart today?', es: '¿Qué planeta retrógrado habla hoy en tu carta?' },
    { 'pt-BR': 'Escreve o planeta. Medita sobre o tema dele.', en: 'Write the planet. Meditate on its theme.', es: 'Escribe el planeta. Medita sobre su tema.', modality: 'study' }, 300),
  fp(3, 'intencao',
    { 'pt-BR': 'Que signo lunar tu cultiva em teu corpo hoje?', en: 'Which moon sign do you cultivate in your body today?', es: '¿Qué signo lunar cultivas en tu cuerpo hoy?' },
    { 'pt-BR': 'Caminha 10 minutos sob a lua atual.', en: 'Walk 10 minutes under today\'s moon.', es: 'Camina 10 minutos bajo la luna de hoy.', modality: 'movement' }, 600),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes ao teu ascendente hoje?', en: 'What do you ask your ascendant today?', es: '¿Qué pides a tu ascendente hoy?' },
    { 'pt-BR': 'Senta 7 minutos. Olha pro leste.', en: 'Sit 7 minutes. Look to the east.', es: 'Siéntate 7 minutos. Mira al este.', modality: 'ritual' }, 420),
  fp(5, 'estudo',
    { 'pt-BR': 'Que aspecto te exige mais hoje?', en: 'Which aspect demands most from you today?', es: '¿Qué aspecto te exige más hoy?' },
    { 'pt-BR': 'Estuda o aspecto 5 minutos. Aplica a 1 caso.', en: 'Study the aspect 5 minutes. Apply to 1 case.', es: 'Estudia el aspecto 5 minutos. Aplícalo a 1 caso.', modality: 'study' }, 300),
  fp(6, 'acao',
    { 'pt-BR': 'Que ação te pede Mercúrio hoje?', en: 'Which action does Mercury ask today?', es: '¿Qué acción te pide Mercurio hoy?' },
    { 'pt-BR': 'Comunica 1 verdade. Clara e breve.', en: 'Communicate 1 truth. Clear and brief.', es: 'Comunica 1 verdad. Clara y breve.', modality: 'vocal' }, 180),
  fp(7, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu parar Saturno?', en: 'When did your body ask for Saturn\'s slow?', es: '¿Cuándo pidió tu cuerpo parar a Saturno?' },
    { 'pt-BR': 'Senta 20 minutos. Olha o tempo passar.', en: 'Sit 20 minutes. Watch time pass.', es: 'Siéntate 20 minutos. Mira pasar el tiempo.', modality: 'stillness' }, 900),
  fp(8, 'gratidao',
    { 'pt-BR': 'Que presente Venus traz hoje ao teu regente?', en: 'What gift does Venus bring to your ruler today?', es: '¿Qué regalo trae Venus a tu regente hoy?' },
    { 'pt-BR': 'Agradece. Cria algo bonito pequeno.', en: 'Give thanks. Create one small beautiful thing.', es: 'Agradece. Crea algo bello pequeño.', modality: 'movement' }, 240),
  fp(9, 'sombra',
    { 'pt-BR': 'Que casa te pede silêncio hoje?', en: 'Which house asks you for silence today?', es: '¿Qué casa te pide silencio hoy?' },
    { 'pt-BR': 'Escreve a casa. Lê o que ela governa.', en: 'Write the house. Read what it rules.', es: 'Escribe la casa. Lee lo que rige.', modality: 'study' }, 300),
  fp(10, 'intencao',
    { 'pt-BR': 'Que intenção tua Marte afina hoje?', en: 'Which intention does Mars sharpen today?', es: '¿Qué intención afina Marte hoy?' },
    { 'pt-BR': 'Define 1 intenção firme. Age rápido.', en: 'Define 1 firm intention. Act fast.', es: 'Define 1 intención firme. Actúa rápido.', modality: 'movement' }, 180),
  fp(11, 'oracao',
    { 'pt-BR': 'O que pedes a Júpiter hoje?', en: 'What do you ask Jupiter today?', es: '¿Qué pides a Júpiter hoy?' },
    { 'pt-BR': 'Abre braços. Pede expansão.', en: 'Open your arms. Ask for expansion.', es: 'Abre los brazos. Pide expansión.', modality: 'ritual' }, 180),
  fp(12, 'estudo',
    { 'pt-BR': 'Que trânsit hoje toca teu Sol?', en: 'Which transit today touches your Sun?', es: '¿Qué tránsito hoy toca tu Sol?' },
    { 'pt-BR': 'Lê sobre o trânsit 10 minutos.', en: 'Read about the transit 10 minutes.', es: 'Lee sobre el tránsito 10 minutos.', modality: 'study' }, 600),
  fp(13, 'acao',
    { 'pt-BR': 'Que vontade Marte te ajuda a cumprir hoje?', en: 'Which will does Mars help you fulfill today?', es: '¿Qué voluntad te ayuda a cumplir Marte hoy?' },
    { 'pt-BR': 'Toma 1 ação corajosa. Pequena.', en: 'Take 1 courageous action. Small.', es: 'Toma 1 acción valiente. Pequeña.', modality: 'movement' }, 180),
  fp(14, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu lua nova?', en: 'When did your body ask for new moon?', es: '¿Cuándo pidió tu cuerpo luna nueva?' },
    { 'pt-BR': 'Apaga luzes. Senta no escuro 10 min.', en: 'Turn off lights. Sit in the dark 10 min.', es: 'Apaga luces. Siéntate a oscuras 10 min.', modality: 'stillness' }, 600),
  fp(15, 'gratidao',
    { 'pt-BR': 'Que eclipse te marcou positivamente?', en: 'Which eclipse marked you positively?', es: '¿Qué eclipse te marcó positivamente?' },
    { 'pt-BR': 'Anota a data. Agradece o portal.', en: 'Note the date. Thank the portal.', es: 'Anota la fecha. Agradece el portal.', modality: 'study' }, 180),
  fp(16, 'sombra',
    { 'pt-BR': 'Que planeta te desafia mais?', en: 'Which planet challenges you most?', es: '¿Qué planeta te desafía más?' },
    { 'pt-BR': 'Escreve. Pede ajuda a esse arquétipo.', en: 'Write it. Ask that archetype for help.', es: 'Escríbelo. Pide ayuda a ese arquetipo.', modality: 'study' }, 240),
  fp(17, 'intencao',
    { 'pt-BR': 'Que retrogradação tua pede pausa?', en: 'Which retrograde of yours asks for pause?', es: '¿Qué retrogradación tuya pide pausa?' },
    { 'pt-BR': 'Não faz nada que não precise. Espera.', en: 'Don\'t do anything unnecessary. Wait.', es: 'No hagas nada innecesario. Espera.', modality: 'stillness' }, 180),
  fp(18, 'oracao',
    { 'pt-BR': 'O que pedes à lua cheia hoje?', en: 'What do you ask the full moon today?', es: '¿Qué pides a la luna llena hoy?' },
    { 'pt-BR': 'Olha a lua cheia 10 minutos. Pede em voz alta.', en: 'Look at the full moon 10 minutes. Ask aloud.', es: 'Mira la luna llena 10 minutos. Pide en voz alta.', modality: 'ritual' }, 600),
  fp(19, 'estudo',
    { 'pt-BR': 'Que nakshatra te chama atenção hoje?', en: 'Which star pattern calls your attention today?', es: '¿Qué nakshatra te llama la atención hoy?' },
    { 'pt-BR': 'Estuda o signo 5 minutos. Anota 1 qualidade.', en: 'Study the sign 5 minutes. Note 1 quality.', es: 'Estudia el signo 5 minutos. Anota 1 cualidad.', modality: 'study' }, 300),
  fp(20, 'acao',
    { 'pt-BR': 'Que Vênus te convida a amar hoje?', en: 'Which Venus invites you to love today?', es: '¿Qué Venus te invita a amar hoy?' },
    { 'pt-BR': 'Envia 1 mensagem de carinho verdadeira.', en: 'Send 1 message of true affection.', es: 'Envía 1 mensaje de cariño verdadero.', modality: 'vocal' }, 120),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu lua cheia descanso?', en: 'When did your body ask for full-moon rest?', es: '¿Cuándo pidió tu cuerpo descanso de luna llena?' },
    { 'pt-BR': 'Senta 15 minutos. Bebe chá quente.', en: 'Sit 15 minutes. Drink hot tea.', es: 'Siéntate 15 minutos. Bebe té caliente.', modality: 'stillness' }, 900),
  fp(22, 'gratidao',
    { 'pt-BR': 'Que signo te sustenta?', en: 'Which sign sustains you?', es: '¿Qué signo te sostiene?' },
    { 'pt-BR': 'Agradece ao signo. Em voz alta.', en: 'Thank the sign. Aloud.', es: 'Agradece al signo. En voz alta.', modality: 'vocal' }, 180),
  fp(23, 'sombra',
    { 'pt-BR': 'Que casa te causa mais dor?', en: 'Which house causes you the most pain?', es: '¿Qué casa te causa más dolor?' },
    { 'pt-BR': 'Escreve. Escreve o que tu aprende.', en: 'Write it. Write what you learn.', es: 'Escríbela. Escribe qué aprendes.', modality: 'study' }, 240),
  fp(24, 'intencao',
    { 'pt-BR': 'Que intenção tua netuno te afina hoje?', en: 'Which intention does Neptune refine today?', es: '¿Qué intención afina Neptuno hoy?' },
    { 'pt-BR': 'Escuta música. Define intenção suave.', en: 'Listen to music. Define a soft intention.', es: 'Escucha música. Define intención suave.', modality: 'stillness' }, 240),
  fp(25, 'oracao',
    { 'pt-BR': 'O que pedes a Urano hoje?', en: 'What do you ask Uranus today?', es: '¿Qué pides a Urano hoy?' },
    { 'pt-BR': 'Senta em silêncio. Pede mudança interna.', en: 'Sit in silence. Ask for inner change.', es: 'Siéntate en silencio. Pide cambio interno.', modality: 'ritual' }, 180),
  fp(26, 'estudo',
    { 'pt-BR': 'Que planeta regente tu ainda não estudou?', en: 'Which ruling planet have you not studied?', es: '¿Qué planeta regente no has estudiado?' },
    { 'pt-BR': 'Estuda ele hoje. 10 minutos.', en: 'Study it today. 10 minutes.', es: 'Estúdialo hoy. 10 minutos.', modality: 'study' }, 600),
  fp(27, 'acao',
    { 'pt-BR': 'Que parte do teu mapa pede ação hoje?', en: 'Which part of your chart asks for action today?', es: '¿Qué parte de tu carta pide acción hoy?' },
    { 'pt-BR': 'Age nessa direção. Pequeno passo.', en: 'Act in that direction. Small step.', es: 'Actúa en esa dirección. Pequeño paso.', modality: 'movement' }, 180),
  fp(28, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu Plutão?', en: 'When did your body ask for Pluto?', es: '¿Cuándo pidió tu cuerpo Plutón?' },
    { 'pt-BR': 'Senta 20 minutos. Deixa morrer 1 apego.', en: 'Sit 20 minutes. Let 1 attachment die.', es: 'Siéntate 20 minutos. Deja morir 1 apego.', modality: 'stillness' }, 900),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que alinhamento planetário te sustenta hoje?', en: 'Which planetary alignment sustains you today?', es: '¿Qué alineación planetaria te sostiene hoy?' },
    { 'pt-BR': 'Agradece ao céu. Olha pra cima.', en: 'Thank the sky. Look up.', es: 'Agradece al cielo. Mira arriba.', modality: 'ritual' }, 180),
  fp(30, 'sombra',
    { 'pt-BR': 'Que quadratura te esmaga hoje?', en: 'Which square crushes you today?', es: '¿Qué cuadratura te aplasta hoy?' },
    { 'pt-BR': 'Escreve. Pede ao aspecto uma saída.', en: 'Write it. Ask the aspect for an exit.', es: 'Escríbela. Pide al aspecto una salida.', modality: 'study' }, 240),
]);
