/**
 * prompts-t/cabala.ts — 30 prompts for Cabala
 *
 * Themes: Sefirot, Daat, daily psalm, Ana Bekoach, Shabat, mitzvah, neshamá
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'cabala';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const CABALA_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Que sefirá pulsa mais forte no teu peito hoje?', en: 'Which sefirah pulses strongest in your chest today?', es: '¿Qué sefirá pulsa más fuerte en tu pecho hoy?' },
    { 'pt-BR': 'Acende vela. Recita o nome da sefirá.', en: 'Light a candle. Recite the sefirah\'s name.', es: 'Enciende vela. Recita el nombre de la sefirá.', modality: 'ritual' }, 240),
  fp(2, 'sombra',
    { 'pt-BR': 'Que Klipá te aprisiona hoje?', en: 'Which Klipah imprisons you today?', es: '¿Qué Klipá te aprisiona hoy?' },
    { 'pt-BR': 'Nomeia a sombra. Reza o Ana Bekoach.', en: 'Name the shadow. Pray the Ana Bekoach.', es: 'Nombra la sombra. Reza el Ana Bekoach.', modality: 'ritual' }, 300),
  fp(3, 'intencao',
    { 'pt-BR': 'Que intenção tua pede alinhamento?', en: 'What intention of yours asks alignment?', es: '¿Qué intención tuya pide alineación?' },
    { 'pt-BR': 'Escreve. Pesa à luz de Netzach e Hod.', en: 'Write it. Weigh it through Netzach and Hod.', es: 'Escríbela. Pésala por Netzach y Hod.', modality: 'study' }, 300),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes a Ein Sof hoje?', en: 'What do you ask Ein Sof today?', es: '¿Qué pides a Ein Sof hoy?' },
    { 'pt-BR': 'Acende vela branca. Reza em hebraico se puderes.', en: 'Light a white candle. Pray in Hebrew if you can.', es: 'Enciende vela blanca. Reza en hebreo si puedes.', modality: 'ritual' }, 300),
  fp(5, 'estudo',
    { 'pt-BR': 'Qual teu salmo para hoje?', en: 'Which psalm is yours today?', es: '¿Qué salmo es tuyo hoy?' },
    { 'pt-BR': 'Lê 1 salmo em voz alta. Realça 1 frase.', en: 'Read 1 psalm aloud. Highlight 1 phrase.', es: 'Lee 1 salmo en voz alta. Destaca 1 frase.', modality: 'vocal' }, 300),
  fp(6, 'acao',
    { 'pt-BR': 'Que mitzvá simples tu podes fazer hoje?', en: 'Which simple mitzvah can you do today?', es: '¿Qué mitzvá simple puedes hacer hoy?' },
    { 'pt-BR': 'Escolhe uma. Executa sem presunção.', en: 'Pick one. Execute without presumption.', es: 'Elige una. Ejecuta sin presunción.', modality: 'movement' }, 180),
  fp(7, 'descanso',
    { 'pt-BR': 'Quando teu neshamá pediu quietude?', en: 'When did your soul ask for quietness?', es: '¿Cuándo pidió tu alma quietud?' },
    { 'pt-BR': 'Senta 20 minutos. Olha vela acesa.', en: 'Sit 20 minutes. Watch a lit candle.', es: 'Siéntate 20 minutos. Mira una vela encendida.', modality: 'stillness' }, 900),
  fp(8, 'gratidao',
    { 'pt-BR': 'Que dádiva do Shabat tu carrega?', en: 'Which Shabbat gift do you carry?', es: '¿Qué regalo del Shabat cargas?' },
    { 'pt-BR': 'Acende 2 velas. Reza o Kidush.', en: 'Light 2 candles. Pray the Kiddush.', es: 'Enciende 2 velas. Reza el Kidush.', modality: 'ritual' }, 240),
  fp(9, 'sombra',
    { 'pt-BR': 'Que nome teu tu esconde?', en: 'Which name of yours do you hide?', es: '¿Qué nombre tuyo escondes?' },
    { 'pt-BR': 'Escreve o nome. Reza por ele.', en: 'Write the name. Pray for it.', es: 'Escribe el nombre. Reza por él.', modality: 'study' }, 240),
  fp(10, 'intencao',
    { 'pt-BR': 'Que nome de Deus tu quer aprofundar hoje?', en: 'Which name of God do you want to deepen today?', es: '¿Qué nombre de Dios quieres profundizar hoy?' },
    { 'pt-BR': 'Recita 1 nome. Senta em silêncio.', en: 'Recite 1 name. Sit in silence.', es: 'Recita 1 nombre. Siéntate en silencio.', modality: 'study' }, 300),
  fp(11, 'oracao',
    { 'pt-BR': 'O que pedes a Chesed hoje?', en: 'What do you ask Chesed today?', es: '¿Qué pides a Chesed hoy?' },
    { 'pt-BR': 'Abre mão de uma coisa hoje. Em silêncio.', en: 'Let go of one thing today. Silently.', es: 'Suelta una cosa hoy. En silencio.', modality: 'ritual' }, 180),
  fp(12, 'estudo',
    { 'pt-BR': 'Que texto cabalístico tu pode ler em 5 min?', en: 'Which kabbalistic text can you read in 5 min?', es: '¿Qué texto cabalístico puedes leer en 5 min?' },
    { 'pt-BR': 'Abre o Zohar. Lê 1 página. Para.', en: 'Open the Zohar. Read 1 page. Stop.', es: 'Abre el Zohar. Lee 1 página. Para.', modality: 'study' }, 300),
  fp(13, 'acao',
    { 'pt-BR': 'Quem tu pode perdoar hoje em teu nome?', en: 'Who can you forgive in your name today?', es: '¿A quién puedes perdonar hoy en tu nombre?' },
    { 'pt-BR': 'Manda 1 mensagem de perdão. Breve.', en: 'Send 1 short forgiveness message.', es: 'Envía 1 mensaje breve de perdón.', modality: 'vocal' }, 180),
  fp(14, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu Shabat?', en: 'When did your body ask for Shabbat?', es: '¿Cuándo pidió tu cuerpo Shabat?' },
    { 'pt-BR': 'Desliga telas por 1 hora. Só.', en: 'Turn off screens for 1 hour. Just that.', es: 'Apaga pantallas 1 hora. Solo eso.', modality: 'stillness' }, 600),
  fp(15, 'gratidao',
    { 'pt-BR': 'Que milagre pequeno tu recebeu hoje?', en: 'Which small miracle did you receive today?', es: '¿Qué milagro pequeño recibiste hoy?' },
    { 'pt-BR': 'Agradece o Baruch Hashem. Em voz alta.', en: 'Thank Baruch Hashem. Aloud.', es: 'Agradece Baruch Hashem. En voz alta.', modality: 'vocal' }, 180),
  fp(16, 'sombra',
    { 'pt-BR': 'Que orgulho te separa dos outros hoje?', en: 'What pride separates you from others today?', es: '¿Qué orgullo te separa de los demás hoy?' },
    { 'pt-BR': 'Escreve o orgulho. Pede perdão.', en: 'Write the pride. Ask forgiveness.', es: 'Escribe el orgullo. Pide perdón.', modality: 'study' }, 240),
  fp(17, 'intencao',
    { 'pt-BR': 'Que reparação tu pode começar hoje?', en: 'Which repair (tikkun) can you begin today?', es: '¿Qué reparación (tikkun) puedes iniciar hoy?' },
    { 'pt-BR': 'Repara algo quebrado. Seja físico ou emocional.', en: 'Repair something broken. Physical or emotional.', es: 'Repara algo roto. Físico o emocional.', modality: 'movement' }, 240),
  fp(18, 'oracao',
    { 'pt-BR': 'O que pedes a Tiferet hoje?', en: 'What do you ask Tiferet today?', es: '¿Qué pides a Tiferet hoy?' },
    { 'pt-BR': 'Acende vela dourada. Pede equilíbrio.', en: 'Light a golden candle. Ask for balance.', es: 'Enciende vela dorada. Pide equilibrio.', modality: 'ritual' }, 240),
  fp(19, 'estudo',
    { 'pt-BR': 'Que letra hebraica fala ao teu dia hoje?', en: 'Which Hebrew letter speaks to your day today?', es: '¿Qué letra hebrea habla a tu día hoy?' },
    { 'pt-BR': 'Estuda 1 letra. Memoriza o som.', en: 'Study 1 letter. Memorize the sound.', es: 'Estudia 1 letra. Memoriza el sonido.', modality: 'study' }, 240),
  fp(20, 'acao',
    { 'pt-BR': 'Que tzedaká tu pode fazer hoje?', en: 'Which tzedakah can you give today?', es: '¿Qué tzedaká puedes hacer hoy?' },
    { 'pt-BR': 'Dá. Sem anônimo aparente.', en: 'Give. Without obvious anonymity.', es: 'Da. Sin anonimato aparente.', modality: 'movement' }, 120),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu niddah (pausa)?', en: 'When did your body ask for pause?', es: '¿Cuándo pidió tu cuerpo pausa?' },
    { 'pt-BR': 'Senta 15 minutos. Só olha a luz.', en: 'Sit 15 minutes. Just look at light.', es: 'Siéntate 15 minutos. Solo mira la luz.', modality: 'stillness' }, 900),
  fp(22, 'gratidao',
    { 'pt-BR': 'Que 7 verdades tu carregas?', en: 'Which 7 truths do you carry?', es: '¿Qué 7 verdades cargas?' },
    { 'pt-BR': 'Recita as 7 verdades em voz alta.', en: 'Recite the 7 truths aloud.', es: 'Recita las 7 verdades en voz alta.', modality: 'vocal' }, 240),
  fp(23, 'sombra',
    { 'pt-BR': 'Que medo te prende há 7 anos?', en: 'What fear has held you for 7 years?', es: '¿Qué miedo te atrapa desde hace 7 años?' },
    { 'pt-BR': 'Escreve. Reza 7 vezes o Shemá.', en: 'Write it. Pray the Shema 7 times.', es: 'Escríbelo. Reza el Shemá 7 veces.', modality: 'ritual' }, 300),
  fp(24, 'intencao',
    { 'pt-BR': 'Que escolha tua precisa de Daat?', en: 'Which choice of yours needs Daat?', es: '¿Qué elección tuya necesita Daat?' },
    { 'pt-BR': 'Para. Respira. Decide.', en: 'Pause. Breathe. Decide.', es: 'Para. Respira. Decide.', modality: 'stillness' }, 180),
  fp(25, 'oracao',
    { 'pt-BR': 'O que pedes a Yesod hoje?', en: 'What do you ask Yesod today?', es: '¿Qué pides a Yesod hoy?' },
    { 'pt-BR': 'Acende vela lilás. Pede fundação interna.', en: 'Light a lilac candle. Ask for inner foundation.', es: 'Enciende vela lila. Pide fundación interna.', modality: 'ritual' }, 240),
  fp(26, 'estudo',
    { 'pt-BR': 'Que trecho do Zohar fala hoje?', en: 'Which passage of the Zohar speaks today?', es: '¿Qué pasaje del Zohar habla hoy?' },
    { 'pt-BR': 'Abre 1 página aleatória. Lê devagar.', en: 'Open 1 random page. Read slowly.', es: 'Abre 1 página al azar. Lee despacio.', modality: 'study' }, 240),
  fp(27, 'acao',
    { 'pt-BR': 'Que bondade pequena tu pode oferecer hoje?', en: 'Which small kindness can you offer today?', es: '¿Qué bondad pequeña puedes ofrecer hoy?' },
    { 'pt-BR': 'Paga o café de alguém. Em silêncio.', en: 'Pay for someone\'s coffee. Silently.', es: 'Paga el café de alguien. En silencio.', modality: 'movement' }, 120),
  fp(28, 'descanso',
    { 'pt-BR': 'Quando teu nefesh pediu recolhimento?', en: 'When did your nefesh ask for retreat?', es: '¿Cuándo pidió tu nefesh recogimiento?' },
    { 'pt-BR': 'Senta 30 minutos em silêncio absoluto.', en: 'Sit 30 minutes in absolute silence.', es: 'Siéntate 30 minutos en silencio absoluto.', modality: 'stillness' }, 900),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que Shabat te sustentou essa semana?', en: 'Which Shabbat held you this week?', es: '¿Qué Shabat te sostuvo esta semana?' },
    { 'pt-BR': 'Liga pra alguém da tua congregação.', en: 'Call someone from your congregation.', es: 'Llama a alguien de tu congregación.', modality: 'vocal' }, 180),
  fp(30, 'sombra',
    { 'pt-BR': 'Que sombra te impede de receber?', en: 'Which shadow keeps you from receiving?', es: '¿Qué sombra te impide recibir?' },
    { 'pt-BR': 'Escreve. Pede a Chesed abertura.', en: 'Write it. Ask Chesed for openness.', es: 'Escríbela. Pide a Chesed apertura.', modality: 'study' }, 240),
]);
