/**
 * prompts-t/candomble.ts — 30 prompts for Candomblé
 *
 * Themes: orixás, axé, offerings, ancestors, terreiro, ebó, ritual cleanliness
 * Tag distribution: 4×7 + 2 → 5 gratitude, 5 shadow, 4 intention, 4 prayer,
 *   4 study, 4 action, 4 rest
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'candomble';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const CANDOMBLE_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Que orixá te acompanha desde o ventre?', en: 'Which orisha has accompanied you since the womb?', es: '¿Qué orisha te acompaña desde el vientre?' },
    { 'pt-BR': 'Acende vela branca. Reza o nome do orixá.', en: 'Light a white candle. Pray the orisha\'s name.', es: 'Enciende vela blanca. Reza el nombre del orisha.', modality: 'ritual' }, 240),
  fp(2, 'sombra',
    { 'pt-BR': 'Que preceito iorubá tu ainda não honrou?', en: 'Which Yoruba precept have you not yet honored?', es: '¿Qué precepto yoruba aún no honras?' },
    { 'pt-BR': 'Escreve o preceito. Medita sobre ele em silêncio.', en: 'Write the precept. Meditate on it silently.', es: 'Escribe el precepto. Medita en silencio.', modality: 'stillness' }, 300),
  fp(3, 'intencao',
    { 'pt-BR': 'Que oferenda simples tu pode fazer hoje?', en: 'What simple offering can you make today?', es: '¿Qué ofrenda simple puedes hacer hoy?' },
    { 'pt-BR': 'Coloca fruta fresca ou água na folha.', en: 'Place fresh fruit or water on a leaf.', es: 'Coloca fruta fresca o agua sobre una hoja.', modality: 'ritual' }, 180),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes aos teus egungun hoje?', en: 'What do you ask your ancestors today?', es: '¿Qué pides a tus ancestros hoy?' },
    { 'pt-BR': 'Senta. Bate 3 vezes no chão. Fala em voz alta.', en: 'Sit. Tap the ground 3 times. Speak aloud.', es: 'Siéntate. Golpea el suelo 3 veces. Habla en voz alta.', modality: 'ritual' }, 240),
  fp(5, 'estudo',
    { 'pt-BR': 'Qual qualidade de Oxalá tu quer cultivar hoje?', en: 'Which quality of Oxalá do you want to cultivate today?', es: '¿Qué cualidad de Oxalá quieres cultivar hoy?' },
    { 'pt-BR': 'Recita a qualidade. Repete 7 vezes no espelho.', en: 'Recite the quality. Repeat 7 times in the mirror.', es: 'Recita la cualidad. Repite 7 veces ante el espejo.', modality: 'vocal' }, 240),
  fp(6, 'acao',
    { 'pt-BR': 'Quem tu pode carregar hoje sem pedir nada?', en: 'Who can you carry today without asking anything?', es: '¿A quién puedes cargar hoy sin pedir nada?' },
    { 'pt-BR': 'Oferece algo concreto. Sem esperar elogio.', en: 'Offer something concrete. Without expecting praise.', es: 'Ofrece algo concreto. Sin esperar elogio.', modality: 'movement' }, 180),
  fp(7, 'descanso',
    { 'pt-BR': 'Quando teu corpo recebeu axé pela última vez?', en: 'When did your body last receive axé?', es: '¿Cuándo recibió axé tu cuerpo por última vez?' },
    { 'pt-BR': 'Toma banho de ervas. Ou escorre erva no corpo.', en: 'Take an herb bath. Or let herbs run down your body.', es: 'Toma baño de hierbas. O deja correr hierbas por el cuerpo.', modality: 'ritual' }, 900),
  fp(8, 'gratidao',
    { 'pt-BR': 'Quem te ensinou o caminho do axé?', en: 'Who taught you the path of axé?', es: '¿Quién te enseñó el camino del axé?' },
    { 'pt-BR': 'Liga ou escreve pra essa pessoa.', en: 'Call or write to that person.', es: 'Llama o escribe a esa persona.', modality: 'vocal' }, 180),
  fp(9, 'sombra',
    { 'pt-BR': 'O que tens escondido da tua comunidade?', en: 'What do you hide from your community?', es: '¿Qué escondes de tu comunidad?' },
    { 'pt-BR': 'Escreve o que escondes. Decide se quer revelar.', en: 'Write what you hide. Decide if you\'ll reveal.', es: 'Escribe qué escondes. Decide si revelarlo.', modality: 'study' }, 300),
  fp(10, 'intencao',
    { 'pt-BR': 'Que ebó interno tu precisa fazer?', en: 'Which internal ebó do you need to do?', es: '¿Qué ebó interno necesitas hacer?' },
    { 'pt-BR': 'Larga uma reclamação hoje. Em silêncio.', en: 'Drop one complaint today. Silently.', es: 'Suelta una queja hoy. En silencio.', modality: 'stillness' }, 180),
  fp(11, 'oracao',
    { 'pt-BR': 'O que pedes a Iemanjá?', en: 'What do you ask Yemanjá?', es: '¿Qué pides a Yemanjá?' },
    { 'pt-BR': 'Leva flor branca à beira do mar ou da água.', en: 'Bring a white flower to the sea or a body of water.', es: 'Lleva flor blanca al mar o a un cuerpo de agua.', modality: 'ritual' }, 300),
  fp(12, 'estudo',
    { 'pt-BR': 'Que fundamento tu pode aprofundar hoje?', en: 'Which fundamento can you deepen today?', es: '¿Qué fundamento puedes profundizar hoy?' },
    { 'pt-BR': 'Lê um ponto riscado. Decora 1 verso.', en: 'Read one cantiga. Memorize 1 verse.', es: 'Lee un punto. Memoriza 1 verso.', modality: 'study' }, 300),
  fp(13, 'acao',
    { 'pt-BR': 'Que axé tu pode oferecer ao próximo sem esperar?', en: 'What axé can you offer without expecting?', es: '¿Qué axé puedes ofrecer sin esperar?' },
    { 'pt-BR': 'Cozinha pra alguém que precisa. Em silêncio.', en: 'Cook for someone in need. Silently.', es: 'Cocina para alguien que necesita. En silencio.', modality: 'ritual' }, 360),
  fp(14, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu paíte?', en: 'When did your body ask for a cooling remedy?', es: '¿Cuándo pidió tu cuerpo paíte?' },
    { 'pt-BR': 'Toma banho morno. Senta em sombra por 20 minutos.', en: 'Take a warm bath. Sit in shade for 20 minutes.', es: 'Toma baño tibio. Siéntate en sombra 20 minutos.', modality: 'stillness' }, 900),
  fp(15, 'gratidao',
    { 'pt-BR': 'Que presente simples Iansã te deu hoje?', en: 'What simple gift did Iansã give you today?', es: '¿Qué regalo simple te dio Iansã hoy?' },
    { 'pt-BR': 'Agradece em voz alta. Acende vela vermelha.', en: 'Thank aloud. Light a red candle.', es: 'Agradece en voz alta. Enciende vela roja.', modality: 'ritual' }, 180),
  fp(16, 'sombra',
    { 'pt-BR': 'Que ira tu carrega que não é tua?', en: 'What anger do you carry that isn\'t yours?', es: '¿Qué ira cargas que no es tuya?' },
    { 'pt-BR': 'Nomeia a ira. Devolve simbolicamente ao chão.', en: 'Name the anger. Return it symbolically to the ground.', es: 'Nombra la ira. Devuélvela al suelo simbólicamente.', modality: 'stillness' }, 240),
  fp(17, 'intencao',
    { 'pt-BR': 'Que errante tu quer trazer pra casa?', en: 'Which errante do you want to bring home?', es: '¿Qué errante quieres traer a casa?' },
    { 'pt-BR': 'Acende vela. Reza pra cabeça da pessoa.', en: 'Light a candle. Pray for the person\'s head.', es: 'Enciende vela. Reza por la cabeza de la persona.', modality: 'ritual' }, 180),
  fp(18, 'oracao',
    { 'pt-BR': 'O que pedes a Ogum hoje?', en: 'What do you ask Ogum today?', es: '¿Qué pides a Ogum hoy?' },
    { 'pt-BR': 'Acende vela azul ou vermelha. Pede coragem.', en: 'Light a blue or red candle. Ask for courage.', es: 'Enciende vela azul o roja. Pide coraje.', modality: 'ritual' }, 180),
  fp(19, 'estudo',
    { 'pt-BR': 'Qual odu te ensinou mais sobre ti?', en: 'Which odu has taught you most about yourself?', es: '¿Qué odu te enseñó más sobre ti?' },
    { 'pt-BR': 'Recita o nome do odu. Pesa o que ele diz hoje.', en: 'Recite the odu\'s name. Weigh what it says today.', es: 'Recita el nombre del odu. Pesa lo que dice hoy.', modality: 'study' }, 240),
  fp(20, 'acao',
    { 'pt-BR': 'Que axé tu pode ofertar na tua casa hoje?', en: 'What axé can you offer in your home today?', es: '¿Qué axé puedes ofrecer en tu casa hoy?' },
    { 'pt-BR': 'Vassoureia a casa cantando um ponto.', en: 'Sweep the house singing a cantiga.', es: 'Barre la casa cantando un punto.', modality: 'ritual' }, 300),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando foi a última vez que sentaste numa terreira?', en: 'When did you last sit in a terreiro?', es: '¿Cuándo te sentaste por última vez en un terreiro?' },
    { 'pt-BR': 'Visita ou medita numa terreira por 15 minutos.', en: 'Visit or meditate in a terreiro for 15 minutes.', es: 'Visita o medita en un terreiro 15 minutos.', modality: 'stillness' }, 600),
  fp(22, 'gratidao',
    { 'pt-BR': 'Que ebó recebido tu ainda não agradeceu?', en: 'Which received ebó have you not yet thanked for?', es: '¿Qué ebó recibido aún no agradeces?' },
    { 'pt-BR': 'Acende vela na próxima lua cheia ou nova.', en: 'Light a candle at the next full or new moon.', es: 'Enciende vela en la próxima luna llena o nueva.', modality: 'ritual' }, 120),
  fp(23, 'sombra',
    { 'pt-BR': 'Que promessa feita ao teu orixá tu esqueceu?', en: 'Which promise to your orisha have you forgotten?', es: '¿Qué promesa a tu orisha olvidaste?' },
    { 'pt-BR': 'Escreve a promessa. Decide se vai cumprir.', en: 'Write the promise. Decide if you\'ll fulfill it.', es: 'Escribe la promesa. Decide si la cumplirás.', modality: 'study' }, 240),
  fp(24, 'intencao',
    { 'pt-BR': 'Que ebó tu pode fazer por ti hoje?', en: 'Which ebó can you do for yourself today?', es: '¿Qué ebó puedes hacer por ti hoy?' },
    { 'pt-BR': 'Larga um apego. Escreve o que solta.', en: 'Release one attachment. Write what you let go.', es: 'Suelta un apego. Escribe qué sueltas.', modality: 'study' }, 180),
  fp(25, 'oracao',
    { 'pt-BR': 'O que pedes a Oxum hoje?', en: 'What do you ask Oxum today?', es: '¿Qué pides a Oxum hoy?' },
    { 'pt-BR': 'Acende vela amarela. Reza com água limpa.', en: 'Light a yellow candle. Pray with clean water.', es: 'Enciende vela amarilla. Reza con agua limpia.', modality: 'ritual' }, 240),
  fp(26, 'estudo',
    { 'pt-BR': 'Que orixá tu conhece pouco e deveria?', en: 'Which orisha do you know little about and should?', es: '¿Qué orisha conoces poco y deberías?' },
    { 'pt-BR': 'Lê 5 minutos sobre ele. Anota 1 qualidade.', en: 'Read 5 minutes about it. Note 1 quality.', es: 'Lee 5 minutos sobre él. Anota 1 cualidad.', modality: 'study' }, 300),
  fp(27, 'acao',
    { 'pt-BR': 'Que cuidado tu pode oferecer ao teu corpo hoje?', en: 'What care can you offer your body today?', es: '¿Qué cuidado puedes ofrecer a tu cuerpo hoy?' },
    { 'pt-BR': 'Hidrata-te com folga. 8 copos d\'água.', en: 'Hydrate generously. 8 cups of water.', es: 'Hidrátate bien. 8 vasos de agua.', modality: 'ritual' }, 240),
  fp(28, 'descanso',
    { 'pt-BR': 'Quando foi a última vez que sentaste na varanda à noite?', en: 'When did you last sit on the porch at night?', es: '¿Cuándo te sentaste por última vez en el porche de noche?' },
    { 'pt-BR': 'Senta 15 minutos na varanda. Olha o céu.', en: 'Sit 15 minutes on the porch. Look at the sky.', es: 'Siéntate 15 minutos en el porche. Mira el cielo.', modality: 'stillness' }, 900),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que herança dos teus tu honra?', en: 'Which heritage from your ancestors do you honor?', es: '¿Qué herencia de tus ancestros honras?' },
    { 'pt-BR': 'Conta essa herança pra alguém mais jovem.', en: 'Share that heritage with someone younger.', es: 'Cuenta esa herencia a alguien más joven.', modality: 'vocal' }, 180),
  fp(30, 'sombra',
    { 'pt-BR': 'Que teimosia Iyá aponta em ti hoje?', en: 'Which stubbornness does Iyá point out in you today?', es: '¿Qué terquedad señala Iyá en ti hoy?' },
    { 'pt-BR': 'Escreve a teimosia. Pede ajuda ao teu maior.', en: 'Write the stubbornness. Ask your elder for help.', es: 'Escribe la terquedad. Pide ayuda a tu mayor.', modality: 'study' }, 240),
]);
