/**
 * prompts-t/cigano.ts — 30 prompts for Cigano (Romani folk spirituality)
 *
 * Themes: open road, signs, cards, leitura do dia, travel, family, music, dance
 * Tag distribution (30 = 4×7 + 2): gratitude×5, shadow×5, intention×4,
 *   prayer×4, study×4, action×4, rest×4
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'cigano';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const CIGANO_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Qual sinal de hoje, ainda pequeno, merece tua gratidão?', en: 'What small sign of today deserves your gratitude?', es: '¿Qué pequeña señal de hoy merece tu gratitud?' },
    { 'pt-BR': 'Anota o sinal em 3 linhas. Relê antes de dormir.', en: 'Write the sign in 3 lines. Re-read before sleep.', es: 'Anota la señal en 3 líneas. Relee antes de dormir.', modality: 'study' }, 200),
  fp(2, 'sombra',
    { 'pt-BR': 'Que carta ou símbolo te incomoda hoje — e por quê?', en: 'Which card or symbol unsettles you today — and why?', es: '¿Qué carta o símbolo te inquieta hoy — y por qué?' },
    { 'pt-BR': 'Escreve o incômodo em 1 frase. Senta em silêncio por 3 minutos.', en: 'Write the unease in 1 sentence. Sit in silence 3 minutes.', es: 'Escribe la inquietud en 1 frase. Siéntate en silencio 3 minutos.', modality: 'stillness' }, 240),
  fp(3, 'intencao',
    { 'pt-BR': 'A estrada aberta te chama pra onde hoje?', en: 'Where does the open road call you today?', es: '¿Hacia dónde te llama hoy el camino abierto?' },
    { 'pt-BR': 'Caminha 7 minutos sem destino fixo. Observa o primeiro sinal.', en: 'Walk 7 minutes without fixed destination. Notice the first sign.', es: 'Camina 7 minutos sin destino fijo. Observa la primera señal.', modality: 'movement' }, 420),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes ao viajante que te visita em sonho?', en: 'What do you ask the traveler who visits you in dreams?', es: '¿Qué pides al viajero que te visita en sueños?' },
    { 'pt-BR': 'Acende uma vela dourada. Reza em voz alta.', en: 'Light a golden candle. Pray aloud.', es: 'Enciende una vela dorada. Reza en voz alta.', modality: 'ritual' }, 300),
  fp(5, 'estudo',
    { 'pt-BR': 'Qual carta do baralho cigano representa tua pergunta silenciosa hoje?', en: 'Which Lenormand card holds your silent question today?', es: '¿Qué carta del tarot gitano sostiene tu pregunta silenciosa hoy?' },
    { 'pt-BR': 'Saca uma carta. Lê o significado clássico + o reverso.', en: 'Draw one card. Read classical meaning + reverse.', es: 'Saca una carta. Lee significado clásico + reverso.', modality: 'study' }, 300),
  fp(6, 'acao',
    { 'pt-BR': 'Quem precisa ouvir tua verdade hoje — com doçura?', en: 'Who needs to hear your truth today — with kindness?', es: '¿Quién necesita escuchar tu verdad hoy — con dulzura?' },
    { 'pt-BR': 'Envia uma mensagem curta, sem apagar.', en: 'Send one short message, don\'t delete it.', es: 'Envía un mensaje corto, sin borrar.', modality: 'vocal' }, 120),
  fp(7, 'descanso',
    { 'pt-BR': 'Onde tua alma cigana repousa quando ninguém vê?', en: 'Where does your Roma soul rest when no one sees?', es: '¿Dónde descansa tu alma gitana cuando nadie ve?' },
    { 'pt-BR': 'Deita 15 minutos. Escuta uma música cigana baixinha.', en: 'Lie down 15 minutes. Play a quiet Roma song.', es: 'Acuéstate 15 minutos. Pon una canción gitana baja.', modality: 'stillness' }, 900),
  fp(8, 'gratidao',
    { 'pt-BR': 'Qual laço do clã merece tua louvação hoje?', en: 'Which clan bond merits your praise today?', es: '¿Qué lazo del clan merece tu alabanza hoy?' },
    { 'pt-BR': 'Liga pra um familiar mais velho. Escuta primeiro.', en: 'Call an elder relative. Listen first.', es: 'Llama a un familiar mayor. Escucha primero.', modality: 'vocal' }, 300),
  fp(9, 'sombra',
    { 'pt-BR': 'Que promessa antiga tu carrega sem fechar?', en: 'What old promise do you carry unclosed?', es: '¿Qué promesa antigua cargas sin cerrar?' },
    { 'pt-BR': 'Escreve o que falta pra fechar. Põe data simbólica.', en: 'Write what\'s missing to close. Set a symbolic date.', es: 'Escribe qué falta para cerrar. Pon fecha simbólica.', modality: 'study' }, 300),
  fp(10, 'intencao',
    { 'pt-BR': 'Se o vento te levasse hoje, pra onde irias sem medo?', en: 'If the wind carried you today, where would you go without fear?', es: 'Si el viento te llevara hoy, ¿adónde irías sin miedo?' },
    { 'pt-BR': 'Olha um mapa aberto. Para o dedo. Observa a cidade.', en: 'Open a map. Hover your finger. Notice the city.', es: 'Mira un mapa abierto. Detén el dedo. Observa la ciudad.', modality: 'study' }, 240),
  fp(11, 'oracao',
    { 'pt-BR': 'Qual santo popular conversa com teu coração cigano?', en: 'Which folk saint dialogues with your Roma heart?', es: '¿Qué santo popular dialoga con tu corazón gitano?' },
    { 'pt-BR': 'Reza um pai-nosso em intenção do santo. Acende vela azul.', en: 'Pray an Our Father in the saint\'s intention. Light a blue candle.', es: 'Reza un padrenuestro por la intención del santo. Enciende vela azul.', modality: 'ritual' }, 300),
  fp(12, 'estudo',
    { 'pt-BR': 'O que o número 7 diz sobre teu passo de hoje?', en: 'What does the number 7 say about your step today?', es: '¿Qué dice el número 7 sobre tu paso de hoy?' },
    { 'pt-BR': 'Recita 7 coisas que fizeste ontem em voz alta.', en: 'Recite 7 things you did yesterday, aloud.', es: 'Recita 7 cosas que hiciste ayer en voz alta.', modality: 'vocal' }, 300),
  fp(13, 'acao',
    { 'pt-BR': 'Quem precisa de tua mão hoje, sem esperar nada?', en: 'Who needs your hand today, expecting nothing?', es: '¿Quién necesita tu mano hoy, sin esperar nada?' },
    { 'pt-BR': 'Leva comida ou uma palavra pra essa pessoa.', en: 'Bring food or a word to that person.', es: 'Lleva comida o una palabra a esa persona.', modality: 'movement' }, 240),
  fp(14, 'descanso',
    { 'pt-BR': 'Onde descansa teu corpo cigano quando a música para?', en: 'Where does your Roma body rest when the music stops?', es: '¿Dónde descansa tu cuerpo gitano cuando la música para?' },
    { 'pt-BR': 'Senta com chá quente. Olha pela janela por 5 minutos.', en: 'Sit with hot tea. Look out the window 5 minutes.', es: 'Siéntate con té caliente. Mira por la ventana 5 minutos.', modality: 'stillness' }, 360),
  fp(15, 'gratidao',
    { 'pt-BR': 'Quem te ensinou a ler o mundo sem escrita?', en: 'Who taught you to read the world without writing?', es: '¿Quién te enseñó a leer el mundo sin escritura?' },
    { 'pt-BR': 'Fecha os olhos. Vê essa pessoa. Agradece em silêncio.', en: 'Close your eyes. See that person. Thank in silence.', es: 'Cierra los ojos. Ve a esa persona. Agradece en silencio.', modality: 'stillness' }, 180),
  fp(16, 'sombra',
    { 'pt-BR': 'Que caminho andas fugindo — e qual o custo?', en: 'Which path do you keep avoiding — and what\'s the cost?', es: '¿Qué camino sigues evitando — y cuál es el costo?' },
    { 'pt-BR': 'Escreve o custo em 1 palavra. Respira fundo 4 vezes.', en: 'Write the cost in 1 word. Breathe deeply 4 times.', es: 'Escribe el costo en 1 palabra. Respira profundo 4 veces.', modality: 'stillness' }, 240),
  fp(17, 'intencao',
    { 'pt-BR': 'Que história tua merece ser contada em voz alta hoje?', en: 'What story of yours deserves to be told aloud today?', es: '¿Qué historia tuya merece ser contada en voz alta hoy?' },
    { 'pt-BR': 'Conta um trecho a alguém de confiança. Sem corrigir.', en: 'Tell a passage to someone you trust. Don\'t correct.', es: 'Cuenta un trecho a alguien de confianza. Sin corregir.', modality: 'vocal' }, 300),
  fp(18, 'oracao',
    { 'pt-BR': 'Que proteção pedes pra estrada que vem?', en: 'What protection do you ask for the road ahead?', es: '¿Qué protección pides para el camino que viene?' },
    { 'pt-BR': 'Amarra um fio vermelho no pulso. Reza 3 vezes.', en: 'Tie a red thread on your wrist. Pray 3 times.', es: 'Ata un hilo rojo en la muñeca. Reza 3 veces.', modality: 'ritual' }, 180),
  fp(19, 'estudo',
    { 'pt-BR': 'Qual frase cigana tua avó repetiria agora?', en: 'Which Roma phrase would your grandmother repeat now?', es: '¿Qué frase gitana repetiría tu abuela ahora?' },
    { 'pt-BR': 'Memoriza a frase e repete ao acordar amanhã.', en: 'Memorize the phrase and repeat it on waking tomorrow.', es: 'Memoriza la frase y repítela al despertar mañana.', modality: 'study' }, 240),
  fp(20, 'acao',
    { 'pt-BR': 'Que dancinha solta teu quadril hoje?', en: 'Which little dance loosens your hips today?', es: '¿Qué bailecito afloja tu cadera hoy?' },
    { 'pt-BR': 'Dança 5 minutos com música cigana.', en: 'Dance 5 minutes with Roma music.', es: 'Baila 5 minutos con música gitana.', modality: 'movement' }, 300),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando foi a última vez que sentaste sem fazer nada?', en: 'When was the last time you sat doing nothing?', es: '¿Cuándo fue la última vez que te sentaste sin hacer nada?' },
    { 'pt-BR': 'Marca no calendário 30 minutos hoje.', en: 'Mark 30 minutes today on the calendar.', es: 'Marca 30 minutos hoy en el calendario.', modality: 'stillness' }, 600),
  fp(22, 'gratidao',
    { 'pt-BR': 'Qual prato te reconecta com a casa?', en: 'Which dish reconnects you with home?', es: '¿Qué plato te reconecta con la casa?' },
    { 'pt-BR': 'Cozinha algo simples. Divide se possível.', en: 'Cook something simple. Share if possible.', es: 'Cocina algo simple. Comparte si puedes.', modality: 'ritual' }, 480),
  fp(23, 'sombra',
    { 'pt-BR': 'Que verdade tens medo de contar pra ti mesmo?', en: 'What truth are you afraid to tell yourself?', es: '¿Qué verdad temes decirte a ti mismo?' },
    { 'pt-BR': 'Olha no espelho. Fala em voz alta.', en: 'Look in the mirror. Speak aloud.', es: 'Mira al espejo. Habla en voz alta.', modality: 'vocal' }, 180),
  fp(24, 'intencao',
    { 'pt-BR': 'O que queres cultivar nos próximos 30 dias?', en: 'What do you want to cultivate in the next 30 days?', es: '¿Qué quieres cultivar en los próximos 30 días?' },
    { 'pt-BR': 'Escreve em papel pardo. Dobra. Põe em lugar alto.', en: 'Write on brown paper. Fold. Place high.', es: 'Escribe en papel marrón. Dobla. Pon en lugar alto.', modality: 'ritual' }, 240),
  fp(25, 'oracao',
    { 'pt-BR': 'Agradece pelo que ainda não veio?', en: 'Can you thank for what hasn\'t arrived yet?', es: '¿Puedes agradecer por lo que aún no llega?' },
    { 'pt-BR': 'Senta. Inspira 4. Expira 4. Repete 7 vezes.', en: 'Sit. Inhale 4. Exhale 4. Repeat 7 times.', es: 'Siéntate. Inhala 4. Exhala 4. Repite 7 veces.', modality: 'stillness' }, 240),
  fp(26, 'estudo',
    { 'pt-BR': 'Que história cigana tu nunca contou?', en: 'What Roma story have you never told?', es: '¿Qué historia gitana nunca has contado?' },
    { 'pt-BR': 'Escreve o título. Toca o tema 2 minutos.', en: 'Write the title. Touch the theme 2 minutes.', es: 'Escribe el título. Toca el tema 2 minutos.', modality: 'study' }, 180),
  fp(27, 'acao',
    { 'pt-BR': 'Que festa cigana tu poderias animar hoje?', en: 'Which Roma festivity could you brighten today?', es: '¿Qué fiesta gitana podrías animar hoy?' },
    { 'pt-BR': 'Manda música cigana pra alguém que aprecia.', en: 'Send Roma music to someone who\'d appreciate it.', es: 'Envía música gitana a alguien que aprecie.', modality: 'movement' }, 120),
  fp(28, 'descanso',
    { 'pt-BR': 'Tua cigana interior já descansou hoje?', en: 'Has your inner Roma rested today?', es: '¿Tu gitana interior ya descansó hoy?' },
    { 'pt-BR': 'Tira os sapatos 5 minutos. Sente o chão.', en: 'Take off your shoes 5 minutes. Feel the ground.', es: 'Quítate los zapatos 5 minutos. Siente el suelo.', modality: 'stillness' }, 300),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que sorriso te salvaria hoje?', en: 'What smile would save you today?', es: '¿Qué sonrisa te salvaría hoy?' },
    { 'pt-BR': 'Tira foto mental. Preserva.', en: 'Take a mental photo. Preserve it.', es: 'Toma foto mental. Presérvala.', modality: 'study' }, 60),
  fp(30, 'sombra',
    { 'pt-BR': 'O que tens carregado de quem não está mais?', en: 'What do you carry from those no longer here?', es: '¿Qué cargas de quienes ya no están?' },
    { 'pt-BR': 'Escreve 3 nomes. Beija um papel por eles.', en: 'Write 3 names. Kiss a paper for them.', es: 'Escribe 3 nombres. Besa un papel por ellos.', modality: 'ritual' }, 240),
]);
