/**
 * prompts-t/ifa.ts — 30 prompts for Ifá
 *
 * Themes: Odus, merindilogun, odu of the day, Orunmila, babalaô, ikín, ori
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'ifa';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const IFA_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Que odu marcou teu nascimento?', en: 'Which odu marks your birth?', es: '¿Qué odu marca tu nacimiento?' },
    { 'pt-BR': 'Recita o nome do odu. Agradece em voz alta.', en: 'Recite the odu\'s name. Thank aloud.', es: 'Recita el nombre del odu. Agradece en voz alta.', modality: 'vocal' }, 240),
  fp(2, 'sombra',
    { 'pt-BR': 'Que ebó iorubá tu tem resistido?', en: 'Which Yoruba ebó have you resisted?', es: '¿Qué ebó yoruba has resistido?' },
    { 'pt-BR': 'Escreve. Pede conselho ao babalaô.', en: 'Write it. Ask a babalaô for counsel.', es: 'Escríbelo. Pide consejo al babalaô.', modality: 'study' }, 300),
  fp(3, 'intencao',
    { 'pt-BR': 'Que oferenda tu pode fazer hoje?', en: 'Which offering can you make today?', es: '¿Qué ofrenda puedes hacer hoy?' },
    { 'pt-BR': 'Oferece fruta ou água. Em silêncio.', en: 'Offer fruit or water. Silently.', es: 'Ofrece fruta o agua. En silencio.', modality: 'ritual' }, 180),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes a Orunmila hoje?', en: 'What do you ask Orunmila today?', es: '¿Qué pides a Orunmila hoy?' },
    { 'pt-BR': 'Reza 7 ikín. Pede clareza no que veio confuso.', en: 'Pray 7 ikín. Ask for clarity on what is confused.', es: 'Reza 7 ikín. Pide claridad en lo confuso.', modality: 'ritual' }, 300),
  fp(5, 'estudo',
    { 'pt-BR': 'Qualità de Exu-Ara tu quer cultivar hoje?', en: 'Which quality do you want to cultivate today?', es: '¿Qué cualidad de Exu-Ara quieres cultivar hoy?' },
    { 'pt-BR': 'Recita. Escreve 1 aplicação prática.', en: 'Recite. Write 1 practical application.', es: 'Recítala. Escribe 1 aplicación práctica.', modality: 'study' }, 300),
  fp(6, 'acao',
    { 'pt-BR': 'Que decisão iorubá tu podes tomar hoje?', en: 'Which Yoruba decision can you make today?', es: '¿Qué decisión yoruba puedes tomar hoy?' },
    { 'pt-BR': 'Joga 4 ikín. Honra o que veio.', en: 'Cast 4 ikín. Honor what came.', es: 'Tira 4 ikín. Honra lo que salió.', modality: 'ritual' }, 240),
  fp(7, 'descanso',
    { 'pt-BR': 'Quando o teu ifá pediu descanso?', en: 'When did your ifá ask for rest?', es: '¿Cuándo pidió descanso tu ifá?' },
    { 'pt-BR': 'Senta 10 minutos em silêncio absoluto.', en: 'Sit 10 minutes in absolute silence.', es: 'Siéntate 10 minutos en silencio absoluto.', modality: 'stillness' }, 600),
  fp(8, 'gratidao',
    { 'pt-BR': 'Quem te ensinou o caminho do odu?', en: 'Who taught you the odu path?', es: '¿Quién te enseñó el camino del odu?' },
    { 'pt-BR': 'Oferece fruta à pessoa. Ou reza por ela.', en: 'Offer fruit to the person. Or pray for them.', es: 'Ofrece fruta a la persona. O reza por ella.', modality: 'ritual' }, 180),
  fp(9, 'sombra',
    { 'pt-BR': 'Que apego a um passado iorubá te prende?', en: 'Which attachment to a Yoruba past binds you?', es: '¿Qué apego a un pasado yoruba te atrapa?' },
    { 'pt-BR': 'Nomeia. Reza um odu de libertação.', en: 'Name it. Pray an odu of liberation.', es: 'Nómbralo. Reza un odu de liberación.', modality: 'ritual' }, 300),
  fp(10, 'intencao',
    { 'pt-BR': 'Que oferenda mínima tu pode fazer pelo teu ori?', en: 'Which minimum offering can you make for your ori?', es: '¿Qué ofrenda mínima puedes hacer por tu ori?' },
    { 'pt-BR': 'Banho de ervas frescas. 5 minutos.', en: 'Herbal bath. 5 minutes.', es: 'Baño de hierbas frescas. 5 minutos.', modality: 'ritual' }, 300),
  fp(11, 'oracao',
    { 'pt-BR': 'O que pedes a Eégún hoje?', en: 'What do you ask the ancestors today?', es: '¿Qué pides a Eégún hoy?' },
    { 'pt-BR': 'Acende vela branca. Reza em voz alta.', en: 'Light a white candle. Pray aloud.', es: 'Enciende vela blanca. Reza en voz alta.', modality: 'ritual' }, 240),
  fp(12, 'estudo',
    { 'pt-BR': 'Que odu tu nunca consultou?', en: 'Which odu have you never consulted?', es: '¿Qué odu nunca consultaste?' },
    { 'pt-BR': 'Lê o odu. Aplica a 1 decisão tua.', en: 'Read the odu. Apply to 1 decision of yours.', es: 'Lee el odu. Aplícalo a 1 decisión tuya.', modality: 'study' }, 300),
  fp(13, 'acao',
    { 'pt-BR': 'Que ebó tu pode fazer por alguém hoje?', en: 'Which ebó can you make for someone today?', es: '¿Qué ebó puedes hacer por alguien hoy?' },
    { 'pt-BR': 'Cozinha algo. Leva à pessoa.', en: 'Cook something. Bring it to the person.', es: 'Cocina algo. Llévalo a la persona.', modality: 'ritual' }, 360),
  fp(14, 'descanso',
    { 'pt-BR': 'Quando teu ori pediu silêncio?', en: 'When did your ori ask for silence?', es: '¿Cuándo pidió silencio tu ori?' },
    { 'pt-BR': 'Senta. Olha pra água. 15 minutos.', en: 'Sit. Look at water. 15 minutes.', es: 'Siéntate. Mira el agua. 15 minutos.', modality: 'stillness' }, 900),
  fp(15, 'gratidao',
    { 'pt-BR': 'O que Orunmila te revelou?', en: 'What has Orunmila revealed to you?', es: '¿Qué te reveló Orunmila?' },
    { 'pt-BR': 'Escreve a revelação. Agradece.', en: 'Write the revelation. Give thanks.', es: 'Escribe la revelación. Agradece.', modality: 'study' }, 240),
  fp(16, 'sombra',
    { 'pt-BR': 'Que orgulho te impede de pedir ikín?', en: 'What pride stops you from asking ikín?', es: '¿Qué orgullo te impide pedir ikín?' },
    { 'pt-BR': 'Escreve o orgulho. Pede conselhos a um maior.', en: 'Write the pride. Ask an elder for counsel.', es: 'Escribe el orgullo. Pide consejo a un mayor.', modality: 'study' }, 240),
  fp(17, 'intencao',
    { 'pt-BR': 'Que ebó grande tu está protelando?', en: 'Which major ebó have you been postponing?', es: '¿Qué ebó mayor estás postergando?' },
    { 'pt-BR': 'Escreve. Coloca data na próxima lua cheia.', en: 'Write it. Set a date for the next full moon.', es: 'Escríbelo. Pon fecha en la próxima luna llena.', modality: 'study' }, 240),
  fp(18, 'oracao',
    { 'pt-BR': 'O que pedes a Obatalá hoje?', en: 'What do you ask Obatalá today?', es: '¿Qué pides a Obatalá hoy?' },
    { 'pt-BR': 'Acende vela branca. Reza com calma.', en: 'Light a white candle. Pray calmly.', es: 'Enciende vela blanca. Reza con calma.', modality: 'ritual' }, 240),
  fp(19, 'estudo',
    { 'pt-BR': 'Qual odu fala ao teu momento?', en: 'Which odu speaks to your moment?', es: '¿Qué odu habla a tu momento?' },
    { 'pt-BR': 'Recita seu nome. Medita.', en: 'Recite its name. Meditate.', es: 'Recita su nombre. Medita.', modality: 'study' }, 300),
  fp(20, 'acao',
    { 'pt-BR': 'Que caminho tu está adiando por medo?', en: 'Which path are you delaying out of fear?', es: '¿Qué camino estás postergando por miedo?' },
    { 'pt-BR': 'Dá 1 passo concreto. Pequeno.', en: 'Take 1 concrete step. Small.', es: 'Da 1 paso concreto. Pequeño.', modality: 'movement' }, 240),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu ebó de esfriamento?', en: 'When did your body ask for cooling ebó?', es: '¿Cuándo pidió tu cuerpo ebó de enfriamiento?' },
    { 'pt-BR': 'Toma banho morno. Bebe água calma.', en: 'Take a warm bath. Drink calm water.', es: 'Toma baño tibio. Bebe agua en calma.', modality: 'ritual' }, 600),
  fp(22, 'gratidao',
    { 'pt-BR': 'Que ebó feito tu recebeu com paz?', en: 'Which made ebó did you receive with peace?', es: '¿Qué ebó hecho recibiste con paz?' },
    { 'pt-BR': 'Acende vela. Reza pelo babalaô.', en: 'Light a candle. Pray for the babalaô.', es: 'Enciende vela. Reza por el babalaô.', modality: 'ritual' }, 180),
  fp(23, 'sombra',
    { 'pt-BR': 'Que palavra dura tu disse e não reparou?', en: 'Which harsh word did you say and not repair?', es: '¿Qué palabra dura dijiste y no arreglaste?' },
    { 'pt-BR': 'Escreve. Pede perdão em voz alta.', en: 'Write it. Ask forgiveness aloud.', es: 'Escríbela. Pide perdón en voz alta.', modality: 'vocal' }, 240),
  fp(24, 'intencao',
    { 'pt-BR': 'Que ebó silencioso tu pode iniciar?', en: 'Which silent ebó can you begin?', es: '¿Qué ebó silencioso puedes empezar?' },
    { 'pt-BR': 'Larga uma mágoa por escrito. Queima em sigilo.', en: 'Drop a grudge on paper. Burn in secret.', es: 'Suelta un rencor por escrito. Quema en secreto.', modality: 'ritual' }, 240),
  fp(25, 'oracao',
    { 'pt-BR': 'O que pedes a Shangô hoje?', en: 'What do you ask Shangô today?', es: '¿Qué pides a Shangô hoy?' },
    { 'pt-BR': 'Acende vela vermelha e branca. Pede justiça.', en: 'Light a red and white candle. Ask for justice.', es: 'Enciende vela roja y blanca. Pide justicia.', modality: 'ritual' }, 240),
  fp(26, 'estudo',
    { 'pt-BR': 'O que tu sabe sobre o odu que te rege?', en: 'What do you know about your ruling odu?', es: '¿Qué sabes del odu que te rige?' },
    { 'pt-BR': 'Recita os 16 odus principais. Hoje 4.', en: 'Recite the main 16 odus. Today 4.', es: 'Recita los 16 odus principales. Hoy 4.', modality: 'study' }, 240),
  fp(27, 'acao',
    { 'pt-BR': 'Que justiça tu pode fazer sem barulho?', en: 'Which justice can you do without noise?', es: '¿Qué justicia puedes hacer sin ruido?' },
    { 'pt-BR': 'Defende alguém em silêncio. Sem plateia.', en: 'Defend someone silently. Without audience.', es: 'Defiende a alguien en silencio. Sin público.', modality: 'movement' }, 180),
  fp(28, 'descanso',
    { 'pt-BR': 'Quando teu ori pediu paíte?', en: 'When did your ori ask for cooling remedy?', es: '¿Cuándo pidió tu ori paíte?' },
    { 'pt-BR': 'Senta na sombra por 20 minutos.', en: 'Sit in shade for 20 minutes.', es: 'Siéntate en la sombra 20 minutos.', modality: 'stillness' }, 900),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que caminho odu te mostrou?', en: 'Which path has the odu shown you?', es: '¿Qué camino te mostró el odu?' },
    { 'pt-BR': 'Escreve. Canta o odu em voz alta.', en: 'Write it. Sing the odu aloud.', es: 'Escríbelo. Canta el odu en voz alta.', modality: 'vocal' }, 180),
  fp(30, 'sombra',
    { 'pt-BR': 'Que segredo teu orí pediu pra soltar?', en: 'Which secret did your head ask you to drop?', es: '¿Qué secreto pidió tu ori que soltaras?' },
    { 'pt-BR': 'Escreve. Decide se quer confiar.', en: 'Write it. Decide if you\'ll trust someone.', es: 'Escríbelo. Decide si confiar.', modality: 'study' }, 240),
]);
