/**
 * prompts-t/tantra.ts — 30 prompts for Tantra
 *
 * Themes: prana, bandhas, kundalini, mudras, mantras, breath, agni,
 *   sexual energy as sacred, chakra work (without co-opting other lineages)
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'tantra';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const TANTRA_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Que prana teu corpo recebeu hoje?', en: 'Which prana did your body receive today?', es: '¿Qué prana recibió tu cuerpo hoy?' },
    { 'pt-BR': 'Respiração profunda 4-7-8. Agradece após.', en: 'Deep breathing 4-7-8. Thank after.', es: 'Respiración profunda 4-7-8. Agradece después.', modality: 'stillness' }, 180),
  fp(2, 'sombra',
    { 'pt-BR': 'Que apego material te prende hoje?', en: 'Which material attachment binds you today?', es: '¿Qué apego material te atrapa hoy?' },
    { 'pt-BR': 'Escreve. Olha pro objeto. Respiração consciente.', en: 'Write. Look at the object. Conscious breath.', es: 'Escríbelo. Mira el objeto. Respiración consciente.', modality: 'study' }, 240),
  fp(3, 'intencao',
    { 'pt-BR': 'Que kula tua quer despertar hoje?', en: 'Which kula wants to wake today?', es: '¿Qué kula quiere despertar hoy?' },
    { 'pt-BR': 'Medita 10 minutos no centro escolhido.', en: 'Meditate 10 minutes on the chosen center.', es: 'Medita 10 minutos en el centro elegido.', modality: 'stillness' }, 600),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes a Shiva hoje?', en: 'What do you ask Shiva today?', es: '¿Qué pides a Shiva hoy?' },
    { 'pt-BR': 'Canta o mantra Om Namah Shivaya 11 vezes.', en: 'Chant Om Namah Shivaya 11 times.', es: 'Canta el mantra Om Namah Shivaya 11 veces.', modality: 'vocal' }, 300),
  fp(5, 'estudo',
    { 'pt-BR': 'Que sutra fala hoje ao teu caminho?', en: 'Which sutra speaks to your path today?', es: '¿Qué sutra habla hoy a tu camino?' },
    { 'pt-BR': 'Abre 1 sutra. Lê 5 parágrafos. Para.', en: 'Open 1 sutra. Read 5 paragraphs. Stop.', es: 'Abre 1 sutra. Lee 5 párrafos. Para.', modality: 'study' }, 300),
  fp(6, 'acao',
    { 'pt-BR': 'Que bandha tu pratica hoje?', en: 'Which bandha do you practice today?', es: '¿Qué bandha practicas hoy?' },
    { 'pt-BR': 'Pratica mula bandha 3 minutos.', en: 'Practice mula bandha 3 minutes.', es: 'Practica mula bandha 3 minutos.', modality: 'movement' }, 240),
  fp(7, 'descanso',
    { 'pt-BR': 'Quando teu agni pediu brisa?', en: 'When did your agni ask for breeze?', es: '¿Cuándo pidió tu agni brisa?' },
    { 'pt-BR': 'Senta em jejum parcial. 4 horas.', en: 'Sit in partial fast. 4 hours.', es: 'Siéntate en ayuno parcial. 4 horas.', modality: 'stillness' }, 600),
  fp(8, 'gratidao',
    { 'pt-BR': 'Que rosto sagrado iluminou tua consciência hoje?', en: 'Which sacred face lit your consciousness today?', es: '¿Qué rostro sagrado iluminó tu conciencia hoy?' },
    { 'pt-BR': 'Acende vela. Reza o nome de Shakti.', en: 'Light a candle. Pray Shakti\'s name.', es: 'Enciende vela. Reza el nombre de Shakti.', modality: 'ritual' }, 240),
  fp(9, 'sombra',
    { 'pt-BR': 'Que medo bloqueia teu muladhara?', en: 'What fear blocks your muladhara?', es: '¿Qué miedo bloquea tu muladhara?' },
    { 'pt-BR': 'Escreve. Medita no centro. Solta.', en: 'Write. Meditate on the center. Release.', es: 'Escríbelo. Medita en el centro. Suelta.', modality: 'stillness' }, 300),
  fp(10, 'intencao',
    { 'pt-BR': 'Que chakra quer abrir hoje?', en: 'Which chakra wants to open today?', es: '¿Qué chakra quiere abrir hoy?' },
    { 'pt-BR': 'Meditação 15 minutos no chakra. Som + respiração.', en: 'Meditate 15 minutes on the chakra. Sound + breath.', es: 'Meditación 15 minutos en el chakra. Sonido + respiración.', modality: 'stillness' }, 900),
  fp(11, 'oracao',
    { 'pt-BR': 'O que pedes a Ganesh hoje?', en: 'What do you ask Ganesh today?', es: '¿Qué pides a Ganesh hoy?' },
    { 'pt-BR': 'Canta o mantra Om Gam Ganapataye 9 vezes.', en: 'Chant Om Gam Ganapataye 9 times.', es: 'Canta el mantra Om Gam Ganapataye 9 veces.', modality: 'vocal' }, 240),
  fp(12, 'estudo',
    { 'pt-BR': 'Que yantra tu pode traçar hoje?', en: 'Which yantra can you draw today?', es: '¿Qué yantra puedes trazar hoy?' },
    { 'pt-BR': 'Desenha um yantra simples. Medita sobre ele.', en: 'Draw a simple yantra. Meditate on it.', es: 'Dibuja un yantra simple. Medita sobre él.', modality: 'study' }, 300),
  fp(13, 'acao',
    { 'pt-BR': 'Que mudra tu pratica hoje?', en: 'Which mudra do you practice today?', es: '¿Qué mudra practicas hoy?' },
    { 'pt-BR': 'Pratica gyan mudra por 11 minutos.', en: 'Practice gyan mudra for 11 minutes.', es: 'Practica gyan mudra 11 minutos.', modality: 'movement' }, 720),
  fp(14, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu nidra?', en: 'When did your body ask for nidra?', es: '¿Cuándo pidió tu cuerpo nidra?' },
    { 'pt-BR': 'Deita 20 minutos em yoga nidra guiado.', en: 'Lie down 20 minutes in guided yoga nidra.', es: 'Acuéstate 20 minutos en yoga nidra guiada.', modality: 'stillness' }, 900),
  fp(15, 'gratidao',
    { 'pt-BR': 'Que energia criativa te atravessou?', en: 'Which creative energy passed through you?', es: '¿Qué energía creativa te atravesó?' },
    { 'pt-BR': 'Cria 1 coisa pequena. Em silêncio.', en: 'Create 1 small thing. Silently.', es: 'Crea 1 cosa pequeña. En silencio.', modality: 'movement' }, 240),
  fp(16, 'sombra',
    { 'pt-BR': 'Que raiva teu segundo chakra segura?', en: 'Which anger does your second chakra hold?', es: '¿Qué rabia guarda tu segundo chakra?' },
    { 'pt-BR': 'Escreve. Respira no centro. Solta.', en: 'Write. Breathe into the center. Release.', es: 'Escríbela. Respira en el centro. Suelta.', modality: 'study' }, 240),
  fp(17, 'intencao',
    { 'pt-BR': 'Que intenção tua pede mais fogo?', en: 'Which intention of yours asks for more fire?', es: '¿Qué intención tuya pide más fuego?' },
    { 'pt-BR': 'Defina 1 micro-ação corajosa. Executa.', en: 'Define 1 micro-courageous action. Execute.', es: 'Define 1 microacción valiente. Ejecuta.', modality: 'movement' }, 180),
  fp(18, 'oracao',
    { 'pt-BR': 'O que pedes a Lakshmi hoje?', en: 'What do you ask Lakshmi today?', es: '¿Qué pides a Lakshmi hoy?' },
    { 'pt-BR': 'Canta o mantra Om Shrim Maha 21 vezes.', en: 'Chant Om Shrim Maha 21 times.', es: 'Canta el mantra Om Shrim Maha 21 veces.', modality: 'vocal' }, 420),
  fp(19, 'estudo',
    { 'pt-BR': 'Que kundalini experiencia tu pode nomear?', en: 'Which kundalini experience can you name?', es: '¿Qué experiencia kundalini puedes nombrar?' },
    { 'pt-BR': 'Escreve o que sentiste. Pede discernimento.', en: 'Write what you felt. Ask for discernment.', es: 'Escribe qué sentiste. Pide discernimiento.', modality: 'study' }, 240),
  fp(20, 'acao',
    { 'pt-BR': 'Que relacionamento teu pede presença hoje?', en: 'Which relationship of yours asks for presence today?', es: '¿Qué relación tuya pide presencia hoy?' },
    { 'pt-BR': 'Senta com alguém. Olha. Escuta.', en: 'Sit with someone. Look. Listen.', es: 'Siéntate con alguien. Mira. Escucha.', modality: 'stillness' }, 240),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando teu terceiro olho pediu escurecer?', en: 'When did your third eye ask to darken?', es: '¿Cuándo pidió tu tercer ojo oscurecer?' },
    { 'pt-BR': 'Vende 1 sentido. Senta 15 minutos.', en: 'Cover 1 sense. Sit 15 minutes.', es: 'Cubre 1 sentido. Siéntate 15 minutos.', modality: 'stillness' }, 900),
  fp(22, 'gratidao',
    { 'pt-BR': 'Que bênção tua passou despercebida hoje?', en: 'Which blessing of yours went unnoticed today?', es: '¿Qué bendición tuya pasó desapercibida hoy?' },
    { 'pt-BR': 'Escreve. Agradece. Em voz alta.', en: 'Write. Thank. Aloud.', es: 'Escríbela. Agradece. En voz alta.', modality: 'vocal' }, 240),
  fp(23, 'sombra',
    { 'pt-BR': 'Que mente crítica te interrompe?', en: 'Which critical mind interrupts you?', es: '¿Qué mente crítica te interrumpe?' },
    { 'pt-BR': 'Escreve. Medita 10 minutos em silêncio.', en: 'Write. Meditate 10 minutes in silence.', es: 'Escríbela. Medita 10 minutos en silencio.', modality: 'stillness' }, 240),
  fp(24, 'intencao',
    { 'pt-BR': 'Que energia sexual podes honrar hoje?', en: 'Which sexual energy can you honor today?', es: '¿Qué energía sexual puedes honrar hoy?' },
    { 'pt-BR': 'Honra teu corpo. Respiração consciente.', en: 'Honor your body. Conscious breath.', es: 'Honra tu cuerpo. Respiración consciente.', modality: 'stillness' }, 240),
  fp(25, 'oracao',
    { 'pt-BR': 'O que pedes a Sarasvati hoje?', en: 'What do you ask Sarasvati today?', es: '¿Qué pides a Sarasvati hoy?' },
    { 'pt-BR': 'Canta o mantra Om Aim Sarasvatyai 11 vezes.', en: 'Chant Om Aim Sarasvatyai 11 times.', es: 'Canta el mantra Om Aim Sarasvatyai 11 veces.', modality: 'vocal' }, 240),
  fp(26, 'estudo',
    { 'pt-BR': 'Que tantra tu pode ler hoje?', en: 'Which tantra can you read today?', es: '¿Qué tantra puedes leer hoy?' },
    { 'pt-BR': 'Lê 3 páginas de um tantra clássico.', en: 'Read 3 pages from a classic tantra.', es: 'Lee 3 páginas de un tantra clásico.', modality: 'study' }, 360),
  fp(27, 'acao',
    { 'pt-BR': 'Que verdade tua te custa dizer hoje?', en: 'Which truth costs you to tell today?', es: '¿Qué verdad tuya te cuesta decir hoy?' },
    { 'pt-BR': 'Diz a verdade. Com compaixão.', en: 'Speak the truth. With compassion.', es: 'Di la verdad. Con compasión.', modality: 'vocal' }, 180),
  fp(28, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu silêncio sensual?', en: 'When did your body ask for sensual silence?', es: '¿Cuándo pidió tu cuerpo silencio sensual?' },
    { 'pt-BR': 'Banho quente. Toque lento. Em ti.', en: 'Hot bath. Slow touch. On yourself.', es: 'Baño caliente. Toque lento. Sobre ti.', modality: 'ritual' }, 900),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que corpo teu te serve hoje?', en: 'Which body of yours serves you today?', es: '¿Qué cuerpo tuyo te sirve hoy?' },
    { 'pt-BR': 'Agradece aos teus membros. Beija-os.', en: 'Thank your limbs. Kiss them.', es: 'Agradece a tus miembros. Bésalos.', modality: 'ritual' }, 180),
  fp(30, 'sombra',
    { 'pt-BR': 'Que apego a um mestre te prende?', en: 'Which attachment to a master binds you?', es: '¿Qué apego a un maestro te atrapa?' },
    { 'pt-BR': 'Escreve. Pede ao mestre interno.', en: 'Write. Ask the inner master.', es: 'Escríbelo. Pide al maestro interno.', modality: 'study' }, 240),
]);
