/**
 * prompts-t/umbanda.ts — 30 prompts for Umbanda
 *
 * Themes: guias (Preto-Velho, Caboclo, Baiana, Exu), sessão, caridade,
 *   terreiro, prayer, charity work
 */
import {
  type DailyPrompt,
  type PromptTag,
  type LocalizedText,
  type LocalizedAction,
  frozenPrompt,
} from './types.ts';
import type { Tradicao } from './types.ts';

const T: Tradicao = 'umbanda';

function fp(idx: number, tag: PromptTag, text: LocalizedText, action: LocalizedAction, dur: number = 180): DailyPrompt {
  return frozenPrompt(T, idx, tag, text, action, dur);
}

export const UMBANDA_PROMPTS: ReadonlyArray<DailyPrompt> = Object.freeze([
  fp(1, 'gratidao',
    { 'pt-BR': 'Qual guia te visita mais silencioso hoje?', en: 'Which guide visits you most silently today?', es: '¿Qué guía te visita más silencioso hoy?' },
    { 'pt-BR': 'Acende vela. Pede licença em voz alta.', en: 'Light a candle. Ask for permission aloud.', es: 'Enciende vela. Pide permiso en voz alta.', modality: 'ritual' }, 240),
  fp(2, 'sombra',
    { 'pt-BR': 'Que baixa-intenção tu carrega escondido?', en: 'Which low intention do you carry hidden?', es: '¿Qué mala intención cargas escondida?' },
    { 'pt-BR': 'Escreve. Decide se quer largar.', en: 'Write it. Decide if you\'ll release it.', es: 'Escríbelo. Decide si soltarlo.', modality: 'study' }, 300),
  fp(3, 'intencao',
    { 'pt-BR': 'Que caridade tu pode fazer hoje sem esperar nada?', en: 'Which charity can you do today expecting nothing?', es: '¿Qué caridad puedes hacer hoy sin esperar nada?' },
    { 'pt-BR': 'Escolhe uma ação. Executa. Não conta a ninguém.', en: 'Pick one action. Execute. Tell no one.', es: 'Elige una acción. Ejecuta. No cuentes a nadie.', modality: 'movement' }, 360),
  fp(4, 'oracao',
    { 'pt-BR': 'O que pedes a Preto-Velho hoje?', en: 'What do you ask Preto-Velho today?', es: '¿Qué pides a Preto-Velho hoy?' },
    { 'pt-BR': 'Acende vela preta ou branca. Reza devagar.', en: 'Light a black or white candle. Pray slowly.', es: 'Enciende vela negra o blanca. Reza despacio.', modality: 'ritual' }, 240),
  fp(5, 'estudo',
    { 'pt-BR': 'Qual ponto riscado tu poderia aprender hoje?', en: 'Which cantiga could you learn today?', es: '¿Qué ponto podrías aprender hoy?' },
    { 'pt-BR': 'Canta um ponto novo pra alguém mais velho.', en: 'Sing a new cantiga for an elder.', es: 'Canta un punto nuevo a un mayor.', modality: 'study' }, 300),
  fp(6, 'acao',
    { 'pt-BR': 'Quem tu precisa atender hoje em primeiro lugar?', en: 'Who do you need to attend to first today?', es: '¿A quién necesitas atender primero hoy?' },
    { 'pt-BR': 'Coloca essa pessoa na agenda primeiro.', en: 'Put that person first on your schedule.', es: 'Pon a esa persona primero en tu agenda.', modality: 'movement' }, 120),
  fp(7, 'descanso',
    { 'pt-BR': 'Quando teu corpo pediu descaso?', en: 'When did your body ask for rest?', es: '¿Cuándo pidió tu cuerpo descanso?' },
    { 'pt-BR': 'Para 10 minutos. Coloca as mãos no coração.', en: 'Pause 10 minutes. Place hands on your heart.', es: 'Para 10 minutos. Pon las manos en el corazón.', modality: 'stillness' }, 600),
  fp(8, 'gratidao',
    { 'pt-BR': 'Quem te apontou a luz nos dias difíceis?', en: 'Who pointed you to the light on hard days?', es: '¿Quién te señaló la luz en días difíciles?' },
    { 'pt-BR': 'Agradece em silêncio. Visualiza o rosto.', en: 'Thank silently. Visualize the face.', es: 'Agradece en silencio. Visualiza el rostro.', modality: 'stillness' }, 180),
  fp(9, 'sombra',
    { 'pt-BR': 'Que medo te impede de servir hoje?', en: 'What fear keeps you from serving today?', es: '¿Qué miedo te impide de servir hoy?' },
    { 'pt-BR': 'Nomeia o medo. Reza 7 vezes uma oração tua.', en: 'Name the fear. Pray 7 times with your own prayer.', es: 'Nombra el miedo. Reza 7 veces con tu propia oración.', modality: 'vocal' }, 300),
  fp(10, 'intencao',
    { 'pt-BR': 'Que linha da umbanda tu quer aprofundar?', en: 'Which umbanda line do you want to deepen?', es: '¿Qué línea de umbanda quieres profundizar?' },
    { 'pt-BR': 'Lê 1 página de um livro da linha. Hoje.', en: 'Read 1 page from a line book. Today.', es: 'Lee 1 página de un libro de la línea. Hoy.', modality: 'study' }, 240),
  fp(11, 'oracao',
    { 'pt-BR': 'O que pedes a Caboclo hoje?', en: 'What do you ask Caboclo today?', es: '¿Qué pides al Caboclo hoy?' },
    { 'pt-BR': 'Acende vela verde. Fala em voz alta.', en: 'Light a green candle. Speak aloud.', es: 'Enciende vela verde. Habla en voz alta.', modality: 'ritual' }, 180),
  fp(12, 'estudo',
    { 'pt-BR': 'O que tu sabe sobre a tua linha de batismo?', en: 'What do you know about your baptism line?', es: '¿Qué sabes de tu línea de bautismo?' },
    { 'pt-BR': 'Escreve 3 verdades. Pesa onde tens dúvida.', en: 'Write 3 truths. Weigh where you doubt.', es: 'Escribe 3 verdades. Pesa dónde dudas.', modality: 'study' }, 240),
  fp(13, 'acao',
    { 'pt-BR': 'Que medium dos teus precisa ser ouvido hoje?', en: 'Which medium of yours needs to be heard today?', es: '¿Qué médium tuyo necesita ser escuchado hoy?' },
    { 'pt-BR': 'Liga ou escreve. Oferece tempo de presença.', en: 'Call or write. Offer presence time.', es: 'Llama o escribe. Ofrece tiempo de presencia.', modality: 'vocal' }, 240),
  fp(14, 'descanso',
    { 'pt-BR': 'Quando foi a última vez que sentaste em terreiro?', en: 'When did you last sit in a terreiro?', es: '¿Cuándo te sentaste por última vez en terreiro?' },
    { 'pt-BR': 'Assiste um giro ou gira no YouTube.', en: 'Watch a session or gira on YouTube.', es: 'Mira una sesión o gira en YouTube.', modality: 'stillness' }, 600),
  fp(15, 'gratidao',
    { 'pt-BR': 'Que cura inesperada tu recebeu?', en: 'What unexpected healing have you received?', es: '¿Qué sanación inesperada has recibido?' },
    { 'pt-BR': 'Acende vela pra quem te curou.', en: 'Light a candle for who healed you.', es: 'Enciende vela por quien te sanó.', modality: 'ritual' }, 180),
  fp(16, 'sombra',
    { 'pt-BR': 'Que vaidade te cerca perigosamente?', en: 'What vanity sits dangerously near you?', es: '¿Qué vanidad te acecha peligrosamente?' },
    { 'pt-BR': 'Escreve 1 vaidade. Pede a um guia a correção.', en: 'Write 1 vanity. Ask a guide for correction.', es: 'Escribe 1 vanidad. Pide a una guía la corrección.', modality: 'study' }, 300),
  fp(17, 'intencao',
    { 'pt-BR': 'Que trabalho espiritual tu podes começar hoje?', en: 'Which spiritual work can you start today?', es: '¿Qué trabajo espiritual puedes iniciar hoy?' },
    { 'pt-BR': 'Define 1 passo concreto. Coloca no papel.', en: 'Define 1 concrete step. Write it down.', es: 'Define 1 paso concreto. Anótalo.', modality: 'study' }, 180),
  fp(18, 'oracao',
    { 'pt-BR': 'O que pedes a Baiana hoje?', en: 'What do you ask Baiana today?', es: '¿Qué pides a Baiana hoy?' },
    { 'pt-BR': 'Acende vela rosa. Fala devagar.', en: 'Light a pink candle. Speak slowly.', es: 'Enciende vela rosa. Habla despacio.', modality: 'ritual' }, 180),
  fp(19, 'estudo',
    { 'pt-BR': 'Que entidade tu conhece pouco?', en: 'Which entity do you know little about?', es: '¿Qué entidad conoces poco?' },
    { 'pt-BR': 'Procura 1 história dela. Lê em voz alta.', en: 'Find 1 story. Read aloud.', es: 'Busca 1 historia. Léela en voz alta.', modality: 'vocal' }, 300),
  fp(20, 'acao',
    { 'pt-BR': 'Quem pode te ajudar hoje se tu pedir?', en: 'Who can help you today if you ask?', es: '¿Quién puede ayudarte hoy si lo pides?' },
    { 'pt-BR': 'Pede ajuda concreta. Sem vergonha.', en: 'Ask for concrete help. Without shame.', es: 'Pide ayuda concreta. Sin vergüenza.', modality: 'vocal' }, 120),
  fp(21, 'descanso',
    { 'pt-BR': 'Quando foi a última vez que riste por dentro?', en: 'When did you last laugh inside recently?', es: '¿Cuándo fue la última vez que reíste por dentro?' },
    { 'pt-BR': 'Telefona alguém que te faça rir.', en: 'Call someone who makes you laugh.', es: 'Llama a alguien que te haga reír.', modality: 'vocal' }, 240),
  fp(22, 'gratidao',
    { 'pt-BR': 'O que tu aprendeste com a tua dor?', en: 'What have you learned from your pain?', es: '¿Qué aprendiste de tu dolor?' },
    { 'pt-BR': 'Escreve a lição. Agradece a dor.', en: 'Write the lesson. Thank the pain.', es: 'Escribe la lección. Agradece al dolor.', modality: 'study' }, 240),
  fp(23, 'sombra',
    { 'pt-BR': 'Que culpa te prende ainda?', en: 'Which guilt still binds you?', es: '¿Qué culpa te atrapa aún?' },
    { 'pt-BR': 'Nomeia. Reza. Pede perdão ao teu guia.', en: 'Name it. Pray. Ask your guide for forgiveness.', es: 'Nómbrala. Reza. Pide perdón a tu guía.', modality: 'ritual' }, 240),
  fp(24, 'intencao',
    { 'pt-BR': 'Que oferenda silenciosa tu pode fazer hoje?', en: 'Which silent offering can you make today?', es: '¿Qué ofrenda silenciosa puedes hacer hoy?' },
    { 'pt-BR': 'Coloca flor ou fruta em lugar sagrado.', en: 'Place a flower or fruit in a sacred place.', es: 'Coloca flor o fruta en lugar sagrado.', modality: 'ritual' }, 240),
  fp(25, 'oracao',
    { 'pt-BR': 'O que pedes a Exu hoje?', en: 'What do you ask Exu today?', es: '¿Qué pides a Exu hoy?' },
    { 'pt-BR': 'Acende vela vermelha e preta. Pede firmeza.', en: 'Light a red and black candle. Ask for firmness.', es: 'Enciende vela roja y negra. Pide firmeza.', modality: 'ritual' }, 180),
  fp(26, 'estudo',
    { 'pt-BR': 'O que distingue caridade de troca?', en: 'What distinguishes charity from exchange?', es: '¿Qué distingue la caridad del intercambio?' },
    { 'pt-BR': 'Escreve 1 exemplo. Medita 3 minutos.', en: 'Write 1 example. Meditate 3 minutes.', es: 'Escribe 1 ejemplo. Medita 3 minutos.', modality: 'study' }, 240),
  fp(27, 'acao',
    { 'pt-BR': 'Que terreiro tu pode visitar ou apoiar hoje?', en: 'Which terreiro can you visit or support today?', es: '¿Qué terreiro puedes visitar o apoyar hoy?' },
    { 'pt-BR': 'Envia uma mensagem de gratidão.', en: 'Send a gratitude message.', es: 'Envía un mensaje de gratitud.', modality: 'vocal' }, 180),
  fp(28, 'descanso',
    { 'pt-BR': 'Quando foi a última vez que paraste pra ouvir música?', en: 'When did you last stop to listen to music?', es: '¿Cuándo paraste a escuchar música?' },
    { 'pt-BR': 'Coloca um ponto riscado. Fecha os olhos. 15 min.', en: 'Play a cantiga. Close your eyes. 15 min.', es: 'Pon un punto. Cierra los ojos. 15 min.', modality: 'stillness' }, 900),
  fp(29, 'gratidao',
    { 'pt-BR': 'Que defesa tu pediu e recebeu?', en: 'Which defense did you ask for and receive?', es: '¿Qué defensa pediste y recibiste?' },
    { 'pt-BR': 'Vai até a firma do teu guia. Agradece em voz alta.', en: 'Go to your guide\'s signature. Thank aloud.', es: 'Ve a la firma de tu guía. Agradece en voz alta.', modality: 'ritual' }, 180),
  fp(30, 'sombra',
    { 'pt-BR': 'Que promessa antiga com terreiro tu esqueceu?', en: 'Which old promise with a terreiro have you forgotten?', es: '¿Qué promesa antigua con terreiro olvidaste?' },
    { 'pt-BR': 'Escreve. Decide se quer honrar. Avisa.', en: 'Write it. Decide if you\'ll honor it. Tell someone.', es: 'Escríbela. Decide si honrar. Avisa.', modality: 'study' }, 240),
]);
