/**
 * Cosmic Data - Dados Cósmicos
 * Dados astrológicos e cósmicos fundamentais
 */

export interface CosmicData {
  id: string;
  nome: string;
  nomeIngles: string;
  categoria: 'planeta' | 'signo' | 'casa' | 'aspecto' | 'sefira';
  elemento: string;
  qualidade: string;
  polaridade: 'yang' | 'yin' | 'neutral';
  simbolo: string;
  cor: string;
  frequencia: number;
  interpretacao: string;
}

export const COSMIC_DATA: CosmicData[] = [
  {
    id: 'sol',
    nome: 'Sol',
    nomeIngles: 'Sun',
    categoria: 'planeta',
    elemento: 'Ouro',
    qualidade: 'Cardeal',
    polaridade: 'yang',
    simbolo: '☉',
    cor: '#FFD700',
    frequencia: 528,
    interpretacao: 'Centro do sistema, representa o Self, propósito de vida e vitalidade.',
  },
  {
    id: 'lua',
    nome: 'Lua',
    nomeIngles: 'Moon',
    categoria: 'planeta',
    elemento: 'Prata',
    qualidade: 'Mutável',
    polaridade: 'yin',
    simbolo: '☽',
    cor: '#C0C0C0',
    frequencia: 417,
    interpretacao: 'Rege emoções, inconsciente, hábitos e necesidades de segurança.',
  },
  {
    id: 'mercurio',
    nome: 'Mercúrio',
    nomeIngles: 'Mercury',
    categoria: 'planeta',
    elemento: 'Mercúrio',
    qualidade: 'Mutável',
    polaridade: 'neutral',
    simbolo: '☿',
    cor: '#CCCCCC',
    frequencia: 741,
    interpretacao: 'Comunicação, análise, comércio e viagens curtas.',
  },
  {
    id: 'venus',
    nome: 'Vênus',
    nomeIngles: 'Venus',
    categoria: 'planeta',
    elemento: 'Cobre',
    qualidade: 'Fixo',
    polaridade: 'yin',
    simbolo: '♀',
    cor: '#E6B800',
    frequencia: 639,
    interpretacao: 'Amor, beleza, harmonia e valores pessoais.',
  },
  {
    id: 'marte',
    nome: 'Marte',
    nomeIngles: 'Mars',
    categoria: 'planeta',
    elemento: 'Ferro',
    qualidade: 'Cardeal',
    polaridade: 'yang',
    simbolo: '♂',
    cor: '#FF4444',
    frequencia: 432,
    interpretacao: 'Energia, ação, desejo e coragem.',
  },
  {
    id: 'jupiter',
    nome: 'Júpiter',
    nomeIngles: 'Jupiter',
    categoria: 'planeta',
    elemento: 'Estanho',
    qualidade: 'Mutável',
    polaridade: 'yang',
    simbolo: '♃',
    cor: '#DAA520',
    frequencia: 396,
    interpretacao: 'Expansão, sabedoria, abundância e oportunidades.',
  },
  {
    id: 'saturno',
    nome: 'Saturno',
    nomeIngles: 'Saturn',
    categoria: 'planeta',
    elemento: 'Chumbo',
    qualidade: 'Fixo',
    polaridade: 'yin',
    simbolo: '♄',
    cor: '#708090',
    frequencia: 285,
    interpretacao: 'Estrutura, disciplina, limites e karima cósmica.',
  },
  {
    id: 'urano',
    nome: 'Urano',
    nomeIngles: 'Uranus',
    categoria: 'planeta',
    elemento: 'Urânio',
    qualidade: 'Cardeal',
    polaridade: 'yang',
    simbolo: '♅',
    cor: '#40E0D0',
    frequencia: 639,
    interpretacao: 'Inovação, liberdade, sudden change and awakening.',
  },
  {
    id: 'netuno',
    nome: 'Netuno',
    nomeIngles: 'Neptune',
    categoria: 'planeta',
    elemento: 'Plutônio',
    qualidade: 'Mutável',
    polaridade: 'yin',
    simbolo: '♆',
    cor: '#4169E1',
    frequencia: 396,
    interpretacao: 'Transcendência, intuição, sonhos e dissolução de límites.',
  },
  {
    id: 'plutao',
    nome: 'Plutão',
    nomeIngles: 'Pluto',
    categoria: 'planeta',
    elemento: 'Plutônio',
    qualidade: 'Cardeal',
    polaridade: 'yang',
    simbolo: '♇',
    cor: '#8B008B',
    frequencia: 432,
    interpretacao: 'Transformação profunda, regeneração e poder pessoal.',
  },
  {
    id: 'aries',
    nome: 'Áries',
    nomeIngles: 'Aries',
    categoria: 'signo',
    elemento: 'Fogo',
    qualidade: 'Cardeal',
    polaridade: 'yang',
    simbolo: '♈',
    cor: '#FF0000',
    frequencia: 432,
    interpretacao: 'Iniciativa, pioneirismo e coragem de liderança.',
  },
  {
    id: 'touro',
    nome: 'Touro',
    nomeIngles: 'Taurus',
    categoria: 'signo',
    elemento: 'Terra',
    qualidade: 'Fixo',
    polaridade: 'yin',
    simbolo: '♉',
    cor: '#00FF00',
    frequencia: 528,
    interpretacao: 'Estabilidade, sensualidade e construção de valores.',
  },
  {
    id: 'gemeos',
    nome: 'Gêmeos',
    nomeIngles: 'Gemini',
    categoria: 'signo',
    elemento: 'Ar',
    qualidade: 'Mutável',
    polaridade: 'neutral',
    simbolo: '♊',
    cor: '#FFFF00',
    frequencia: 639,
    interpretacao: 'Comunicação, dualidade e integração de opostos.',
  },
  {
    id: 'cancer',
    nome: 'Câncer',
    nomeIngles: 'Cancer',
    categoria: 'signo',
    elemento: 'Água',
    qualidade: 'Cardeal',
    polaridade: 'yin',
    simbolo: '♋',
    cor: '#FFFFFF',
    frequencia: 417,
    interpretacao: 'Nutrição, emocionalidade e proteção do núcleo familiar.',
  },
  {
    id: 'leao',
    nome: 'Leão',
    nomeIngles: 'Leo',
    categoria: 'signo',
    elemento: 'Fogo',
    qualidade: 'Fixo',
    polaridade: 'yang',
    simbolo: '♌',
    cor: '#FFA500',
    frequencia: 528,
    interpretacao: 'Expressão criativa, orgulho e generosidade solar.',
  },
  {
    id: 'virgem',
    nome: 'Virgem',
    nomeIngles: 'Virgo',
    categoria: 'signo',
    elemento: 'Terra',
    qualidade: 'Mutável',
    polaridade: 'yin',
    simbolo: '♍',
    cor: '#8B4513',
    frequencia: 741,
    interpretacao: 'Análise, serviço e perfeição através da discriminação.',
  },
  {
    id: 'libra',
    nome: 'Libra',
    nomeIngles: 'Libra',
    categoria: 'signo',
    elemento: 'Ar',
    qualidade: 'Cardeal',
    polaridade: 'yin',
    simbolo: '♎',
    cor: '#FFC0CB',
    frequencia: 639,
    interpretacao: 'Harmonia, justicia e integração de relaciones.',
  },
  {
    id: 'escorpiao',
    nome: 'Escorpião',
    nomeIngles: 'Scorpio',
    categoria: 'signo',
    elemento: 'Água',
    qualidade: 'Fixo',
    polaridade: 'yin',
    simbolo: '♏',
    cor: '#800000',
    frequencia: 432,
    interpretacao: 'Transformação, intensidade e penetração nos mistérios.',
  },
  {
    id: 'sagitario',
    nome: 'Sagitário',
    nomeIngles: 'Sagittarius',
    categoria: 'signo',
    elemento: 'Fogo',
    qualidade: 'Mutável',
    polaridade: 'yang',
    simbolo: '♐',
    cor: '#0000FF',
    frequencia: 396,
    interpretacao: 'Expansão, filosofia e busca por verdades transcendentais.',
  },
  {
    id: 'capricornio',
    nome: 'Capricórnio',
    nomeIngles: 'Capricorn',
    categoria: 'signo',
    elemento: 'Terra',
    qualidade: 'Cardeal',
    polaridade: 'yin',
    simbolo: '♑',
    cor: '#404040',
    frequencia: 285,
    interpretacao: 'Ambição, estrutura e Ascensão através da disciplina.',
  },
  {
    id: 'aquario',
    nome: 'Aquário',
    nomeIngles: 'Aquarius',
    categoria: 'signo',
    elemento: 'Ar',
    qualidade: 'Fixo',
    polaridade: 'yang',
    simbolo: '♒',
    cor: '#00CED1',
    frequencia: 639,
    interpretacao: 'Humanitarismo, inovação e liberdade além das convenções.',
  },
  {
    id: 'peixes',
    nome: 'Peixes',
    nomeIngles: 'Pisces',
    categoria: 'signo',
    elemento: 'Água',
    qualidade: 'Mutável',
    polaridade: 'yin',
    simbolo: '♓',
    cor: '#0000FF',
    frequencia: 417,
    interpretacao: 'Unificação, compaixão e dissolução dos límites do ego.',
  },
  {
    id: 'kether',
    nome: 'Kether',
    nomeIngles: 'Kether',
    categoria: 'sefira',
    elemento: 'Nenhum',
    qualidade: 'Primeiro',
    polaridade: 'neutral',
    simbolo: 'כתר',
    cor: '#FFFFFF',
    frequencia: 963,
    interpretacao: 'Corona, vontade divina e unidade primordial.',
  },
  {
    id: 'chokmah',
    nome: 'Chokmah',
    nomeIngles: 'Chokmah',
    categoria: 'sefira',
    elemento: 'Ain Soph',
    qualidade: 'Segundo',
    polaridade: 'yang',
    simbolo: 'חכמה',
    cor: '#00FFFF',
    frequencia: 852,
    interpretacao: 'Sabedoria, força dinâmica e princípio masculino cósmico.',
  },
  {
    id: 'binah',
    nome: 'Binah',
    nomeIngles: 'Binah',
    categoria: 'sefira',
    elemento: 'Ain Soph',
    qualidade: 'Terceiro',
    polaridade: 'yin',
    simbolo: 'בינה',
    cor: '#000000',
    frequencia: 741,
    interpretacao: 'Compreensão, limitação estruturante e princípio feminino cósmico.',
  },
];

export function getData(): CosmicData[] {
  return [...COSMIC_DATA];
}