export const meta = { name: 'fase-20-mfa', description: 'Fase 20: MFA/TOTP para Operators ADMIN' };

const PROJECT_CONTEXT = [
  'PROJETO: Cabala dos Caminhos - sistema B2B de leituras oraculares',
  'BRANCH ATUAL: claude/docs-refactor-alignment-FOUqN',
  'ULTIMO COMMIT: 4f991274 chore(hardening): Fase 18 - rate limits + security headers + cleanup',
  'WORKING DIR: /home/skynet/cabala-dos-caminhos',
  '',
  'ESTADO ATUAL (Fases 1-18 completas):',
  '- Auth: JWT access 15min + refresh 30d com rotacao (Fase 15)',
  '- OperatorSession com hash SHA-256, revokedAt, type=ACCESS|REFRESH',
  '- Server-side auth gate (Fase 14/17) em cockpit + dashboard/mesa-real + clientes',
  '- Rate limits: login 5/15min, register 3/h, refresh 30/min (Fase 18)',
  '- UI de gestao de sessoes ativas (Fase 16)',
  '- 233/233 testes auth passando, 9706 totais',
].join('\n');

const PHASE_20_PROMPT = [
  PROJECT_CONTEXT,
  '',
  'FASE 20: MFA / TOTP PARA OPERATORS ADMIN',
  '',
  'OBJETIVO: Implementar TOTP (RFC 6238) como segundo fator para Operators com role ADMIN. Operators normais (role=OPERATOR) NAO exigem MFA (escopo desta fase).',
  '',
  'DECISOES JA TOMADAS:',
  '- Apenas Operators com role=ADMIN precisam ativar MFA (opt-in)',
  '- TOTP via app autenticador (Google Authenticator, Authy, 1Password) - 6 digitos, 30s',
  '- Secret TOTP armazenado hasheado no DB (aes-256-gcm ou similar)',
  '- 10 recovery codes single-use gerados no setup, hasheados (bcrypt) no DB',
  '- Setup flow: POST /api/operator/auth/mfa/setup (gera secret + QR + recovery codes) → POST /api/operator/auth/mfa/verify-setup { code }',
  '- Login flow: se operator tem MFA ativo, apos senha OK retornar 200 { mfaRequired: true, mfaToken: short-lived-jwt } → POST /api/operator/auth/mfa/verify { mfaToken, code }',
  '- mfaToken: JWT 5min dedicado, type=mfa-challenge, single-use',
  '- Rota POST /api/operator/auth/mfa/disable { password } (desabilita MFA)',
  '- Schema: novo model OperatorMfa { operatorId (unique), secretEncrypted, enabled, recoveryCodesHash (string[]), createdAt, updatedAt }',
  '- Migration nova: add_operator_mfa',
  '',
  'ARQUIVOS A CRIAR/MODIFICAR:',
  '- prisma/schema.prisma - adicionar model OperatorMfa',
  '- prisma/migrations/<ts>_add_operator_mfa/migration.sql - nova',
  '- src/lib/auth/operator-totp.ts - TOTP secret gen, encrypt/decrypt, code verify, recovery codes',
  '- src/lib/auth/operator-mfa.ts - setup, verify, disable, isEnabled',
  '- src/app/api/operator/auth/login/route.ts - detectar MFA, retornar mfaRequired',
  '- src/app/api/operator/auth/mfa/setup/route.ts - NOVO POST (ADMIN only)',
  '- src/app/api/operator/auth/mfa/verify-setup/route.ts - NOVO POST (valida primeiro codigo)',
  '- src/app/api/operator/auth/mfa/verify/route.ts - NOVO POST (challenge: mfaToken + code)',
  '- src/app/api/operator/auth/mfa/disable/route.ts - NOVO POST (re-autentica com senha)',
  '- src/app/api/operator/auth/mfa/recovery-code/route.ts - NOVO POST (usa recovery code em vez de TOTP)',
  '- src/lib/auth/operator-jwt.ts - adicionar signMfaChallengeToken / verifyMfaChallengeToken',
  '- src/app/operator/mfa-setup/page.tsx - NOVA pagina de setup',
  '- src/app/operator/login/page.tsx - integrar step 2 (codigo MFA)',
  '- tests/lib/auth/operator-totp.test.ts - TOTP secret gen, encrypt/decrypt, code verify',
  '- tests/lib/auth/operator-mfa.test.ts - setup, verify, disable, recovery',
  '- tests/api/operator-auth-mfa.test.ts - integracao das rotas',
  '',
  'DEPENDENCIAS:',
  '- Adicionar: `npm install otpauth qrcode` (lib de TOTP + QR code)',
  '- Usar crypto nativo (node:crypto) para AES-256-GCM do secret',
  '- bcrypt para recovery codes (ja existe)',
  '',
  'VERIFICACAO:',
  '- npx tsc --noEmit - 0 erros',
  '- npx vitest run tests/lib/auth tests/api/operator-auth - todos passando',
  '- 17+ testes novos cobrindo: secret gen, encrypt/decrypt, code verify, setup flow, verify flow, recovery codes, disable flow',
  '- Edge cases: code expirado, code reuse, recovery code reuse, TOTP drift de 30s',
  '- Build OK (pode ter pre-existing quebrado)',
  '',
  'NAO MODIFICAR (canonicos):',
  '- src/lib/lenormand/mesa-real.ts',
  '- src/lib/constants/lenormand-cards.ts',
  '- src/lib/auth/operator-jwt.ts (apenas ADICIONAR funcoes, nao modificar as existentes)',
  '',
  'WORKFLOW DE COMMIT (igual Fases 15-18):',
  '1. npm install otpauth qrcode (commit separado deps)',
  '2. git add <apenas arquivos da Fase 20>',
  '3. git commit -m "feat(auth): Fase 20 - MFA/TOTP para Operators ADMIN" com detalhes',
  '4. git stash push -m "lint-Fase20"',
  '5. git pull --rebase origin claude/docs-refactor-alignment-FOUqN',
  '6. git stash pop',
  '7. git push origin claude/docs-refactor-alignment-FOUqN',
  '8. Criar memory/cycle-XXX.md com resumo',
  '9. Atualizar MEMORY.md com a entrada',
  '',
  'SAIDA ESPERADA:',
  '- Resumo 1-2 paragrafos do que foi feito',
  '- Lista de commits (SHA + titulo)',
  '- Contagem de tests passing (com delta vs antes)',
  '- Lista de dependencias adicionadas',
  '- Quaisquer issues encontrados',
  '- Status final do push',
].join('\n');

log('Iniciando Fase 20 - MFA/TOTP para Operators ADMIN');

const surveyResult = await agent(
  [
    'Voce e um agente de survey read-only para a Fase 20 do Cabala dos Caminhos.',
    '',
    PROJECT_CONTEXT,
    '',
    'TAREFAS:',
    '1. Confirmar a ausencia da lib `otpauth` no package.json (npm ls otpauth).',
    '2. Verificar se ja existe algum campo de MFA no Operator schema (nao deveria).',
    '3. Confirmar arquivos existentes: src/lib/auth/operator-{jwt,session,sessions}.ts (estrutura do codigo).',
    '4. Verificar que operator-jwt.ts tem apenas as funcoes sign/verify/cookie - sem conflito com o que vou ADICIONAR (signMfaChallengeToken, verifyMfaChallengeToken).',
    '',
    'NAO modifique nada. Use Read, Grep, Bash apenas. Retorne 1 paragrafo de survey.',
  ].join('\n'),
  { label: 'Survey Fase 20', phase: 'Survey', agentType: 'Explore' }
);
log('Survey concluido.');

const phase20Result = await agent(PHASE_20_PROMPT, {
  label: 'Fase 20: MFA/TOTP',
  phase: 'Fase 20: MFA/TOTP',
  agentType: 'general-purpose',
});
log('Fase 20 concluida.');

return { survey: surveyResult, fase20: phase20Result };
