const __workflow = true; export const meta = {
  name: 'cabala-fases-15-18',
  description: 'Orquestra Fases 15-18: refresh tokens, UI sessoes, audit auth, hard final',
  phases: [
    { title: 'Survey' },
    { title: 'Fase 15: Refresh tokens' },
    { title: 'Fase 16: UI de sessoes' },
    { title: 'Fase 17: Audit auth' },
    { title: 'Fase 18: Hard final' },
    { title: 'Verificacao final' },
  ],
};

const PROJECT_CONTEXT = [
  'PROJETO: Cabala dos Caminhos - sistema B2B de leituras oraculares',
  'BRANCH ATUAL: claude/docs-refactor-alignment-FOUqN',
  'ULTIMO COMMIT: 9b9b5999 refactor(ui): Fase 14b - polish cockpit, api routes, oracle cards',
  'WORKING DIR: /home/skynet/cabala-dos-caminhos',
  '',
  'ESTADO ATUAL:',
  '- Fases 1-14 completas (ver memory/cycle-{101..122}.md)',
  '- Auth Operator: JWT em cookie httpOnly cockpit_session (HS256, 7d)',
  '- Operator.sessions (Fase 13): hash SHA-256, revokedAt, ipAddress, userAgent',
  '- Server-side auth gate (Fase 14) no /cockpit/page.tsx',
  '- /api/operator/auth/* com createSession/revokeSession/isSessionActive',
  '- 4 rotas: login, logout, register, me',
  '',
  'CONVENCOES DO PROJETO:',
  '- Single-access token atual (Fase 8 decisao). Refresh tokens sao Fase 15.',
  "- 'use client' no topo de componentes client",
  "- 'use server' para Server Actions",
  '- Tenant isolation: client-side guard + server-side guard',
  '- pnpm + Next 16 + React 19 + Prisma 7',
  '- Testes: vitest com mocks de prisma',
  '- Auth: src/lib/auth/operator-{jwt,session,sessions}.ts',
  '',
  'NAO MODIFICAR (canonicos):',
  '- src/lib/lenormand/mesa-real.ts (Doc 16)',
  '- src/lib/constants/lenormand-cards.ts (Doc 15/16 AD-02)',
  '- prisma/schema.prisma (excleto adicoes da Fase 15)',
  '',
  'WORKFLOW POR FASE:',
  '1. Implementar (codigo + types + tests)',
  '2. Validar (typecheck + tests)',
  '3. Commit com mensagem descritiva',
  '4. Stash lint, pull rebase, pop, push',
  '5. Atualizar memory (memory/cycle-NNN.md + MEMORY.md)',
  '',
  'SAIDA ESPERADA DE CADA AGENT:',
  '- Resumo de 1-2 paragrafos do que foi feito',
  '- Lista de commits feitos',
  '- Lista de testes passing',
  '- Quaisquer issues encontrados',
].join('\n');

const PHASE_15_PROMPT = [
  PROJECT_CONTEXT,
  '',
  'FASE 15: REFRESH TOKENS',
  '',
  'OBJETIVO: Implementar par access (15min) + refresh (30d) com rotacao.',
  '',
  'DECISOES JA TOMADAS:',
  '- Single-token atual e access de 15min (nao 7d)',
  "- Refresh token em cookie separado httpOnly 'cockpit_refresh' (30d)",
  '- Rotacao: cada refresh emite novo access E novo refresh; revoga o anterior',
  '- Deteccao de reuso: se um refresh revogado for usado, revoga TODAS as sessoes do operator',
  "- JWT shape: { sub, role, type: 'access' | 'refresh' }",
  '- Schema: estender OperatorSession com type, refreshExpiresAt',
  '- Migration nova: add_refresh_to_operator_sessions',
  '',
  'ARQUIVOS A MODIFICAR:',
  '- prisma/schema.prisma - adicionar campos em OperatorSession',
  '- prisma/migrations/<ts>_add_refresh_to_operator_sessions/ - migration nova',
  '- src/lib/auth/operator-jwt.ts - signOperatorAccessToken, signOperatorRefreshToken, verifyOperatorToken (com type check)',
  '- src/lib/auth/operator-sessions.ts - createRefreshSession, rotateRefreshToken, detectRefreshReuse',
  '- src/app/api/operator/auth/login/route.ts - emitir access+refresh, setar 2 cookies',
  '- src/app/api/operator/auth/refresh/route.ts - NOVO endpoint POST que rotaciona',
  '- src/app/api/operator/auth/logout/route.ts - revogar refresh tambem',
  '- src/app/api/operator/auth/me/route.ts - so aceita access, nao refresh',
  '- tests/* - testes para novo flow',
  '',
  'VERIFICACAO:',
  '- typecheck: 0 erros',
  '- Testes do novo flow: rotacionar OK, detectar reuso, revogar todas em reuso',
  '- Testes antigos (Fases 7+8+13+14) continuam passando',
  '',
  'SAIDA:',
  '- Lista dos commits feitos',
  '- Resumo: 1-2 paragrafos do que foi implementado',
  '- Lista de tests passing (com contagem)',
  '- Quaisquer issues encontrados',
  '- Status do push',
].join('\n');

const PHASE_16_PROMPT = [
  PROJECT_CONTEXT,
  '',
  'FASE 16: UI DE SESSOES ATIVAS',
  '',
  'OBJETIVO: Operator pode ver e revogar suas sessoes ativas (sair de outros dispositivos).',
  '',
  'DECISOES JA TOMADAS:',
  '- API: GET /api/operator/auth/sessions (lista sessoes ativas)',
  '- API: DELETE /api/operator/auth/sessions/[id] (revoga 1 sessao)',
  '- API: POST /api/operator/auth/sessions/revoke-all (revoga todas)',
  '- UI: nova secao "Sessoes Ativas" no CockpitHeader (modal ou drawer)',
  '- Cada sessao mostra: device, IP, localizacao (best-effort), ultima atividade, "Sair"',
  '- Botao "Sair de Todos os Outros Dispositivos"',
  '- Sem refresh tokens: usar OperatorSession.revokedAt para listar',
  '',
  'ARQUIVOS A MODIFICAR:',
  '- src/app/api/operator/auth/sessions/route.ts - NOVO GET',
  '- src/app/api/operator/auth/sessions/[id]/route.ts - NOVO DELETE',
  '- src/app/api/operator/auth/sessions/revoke-all/route.ts - NOVO POST',
  '- src/components/operator/SessionsList.tsx - NOVO componente (modal/drawer)',
  '- src/components/cockpit/CockpitHeader.tsx - adicionar botao "Sessoes"',
  '- tests/* - testes para novos endpoints e componente',
  '',
  'VERIFICACAO:',
  '- typecheck: 0 erros',
  '- Tests dos novos endpoints: list, delete, revoke-all, edge cases',
  '- Build passa',
  '',
  'SAIDA:',
  '- Commits feitos',
  '- Resumo 1-2 paragrafos',
  '- Tests passing (com contagem)',
  '- Issues encontrados',
  '- Status do push',
].join('\n');

const PHASE_17_PROMPT = [
  PROJECT_CONTEXT,
  '',
  'FASE 17: AUDIT AUTH EM TODAS AS PAGINAS OPERATOR',
  '',
  'OBJETIVO: Garantir que TODAS as paginas e rotas Operator-related tem server-side auth gate (defense in depth).',
  '',
  'ESCOPO:',
  '- src/app/cockpit/* - JA tem gate (Fase 14) OK',
  '- src/app/dashboard/mesa-real/* - verificar',
  '- src/app/operator/* - login/register sao publicas (correto)',
  '- src/app/dashboard/oraculo/* - verificar se e Operator',
  '- src/app/api/operator/* - JA tem requireOperator OK',
  '- src/app/api/mesa-real/* - JA tem requireOperator OK',
  '- src/app/api/consult/* - JA tem requireOperator OK',
  '',
  'TAREFAS:',
  '1. Auditar todas as src/app/**/page.tsx e route.ts',
  '2. Para paginas Operator-related sem server-side gate: ADICIONAR',
  '3. Para API routes Operator-related sem requireOperator: ADICIONAR',
  '4. Para paginas B2C (dashboard de User), documentar que usam SupabaseProvider (separado, fora de escopo)',
  '5. Criar um teste E2E smoke: GET /cockpit sem cookie -> 302 ou redirect',
  '6. Criar um helper reutilizavel: requireOperatorPage() para Server Components (se ja nao existir)',
  '',
  'VERIFICACAO:',
  '- typecheck: 0 erros',
  '- Build passa',
  '- Audit script rodado e 0 unprotected Operator pages',
  '- Tests dos helpers',
  '',
  'SAIDA:',
  '- Commits feitos',
  '- Tabela de paginas auditadas: status, action',
  '- Tests passing',
  '- Issues',
  '- Status do push',
].join('\n');

const PHASE_18_PROMPT = [
  PROJECT_CONTEXT,
  '',
  'FASE 18: HARD FINAL + CLEANUP',
  '',
  'OBJETIVO: Production hardening + limpeza de debitos pre-existentes.',
  '',
  'ESCOPO:',
  'A) RATE LIMITING em auth:',
  '   - src/app/api/operator/auth/login/route.ts: 5 attempts / 15min por IP',
  '   - src/app/api/operator/auth/register/route.ts: 3 / hour por IP',
  '   - src/app/api/operator/auth/refresh/route.ts: 30 / min por IP',
  '   - Usar Redis (ja existe @/lib/redis)',
  '',
  'B) SECURITY HEADERS:',
  '   - Verificar middleware.ts adiciona: HSTS, X-Content-Type-Options, X-Frame-Options',
  '   - CSP para rotas API (strict)',
  '   - X-Rate-Limit-* headers nas respostas',
  '',
  'C) LIMPEZA:',
  '   - Remover arquivos nao usados (tests/lib/auth-jwt/* se confirmado morto)',
  '   - Atualizar PROGRESS.md (criar se nao existir)',
  '   - Documentar workflow de fases no AGENTS.md ou novo arquivo',
  '',
  'D) METRICAS:',
  '   - Rodar npm run test:run e contar',
  '   - Rodar npm run build',
  '   - Gerar summary em memory/cycle-123.md',
  '',
  'VERIFICACAO:',
  '- typecheck: 0 erros',
  '- Build OK',
  '- Tests OK',
  '- Rate limits testados',
  '',
  'SAIDA:',
  '- Commits feitos',
  '- Tabela de melhoras aplicadas',
  '- Metricas finais (tests count, build size)',
  '- Tests passing',
  '- Issues',
  '- Status do push',
].join('\n');

log('Iniciando Fases 15-18 do Cabala dos Caminhos (orquestrado por workflow)');

phase('Survey');
const surveyResult = await agent(
  [
    'Voce e um agente de survey read-only. Faca exploracao rapida do estado atual do projeto Cabala dos Caminhos.',
    '',
    PROJECT_CONTEXT,
    '',
    'TAREFAS:',
    '1. Leia o estado atual da branch (git log -10, git status)',
    '2. Verifique os arquivos de auth em src/lib/auth/ e src/app/api/operator/',
    '3. Verifique o estado do /cockpit/page.tsx (server-side gate?)',
    '4. Identifique paginas Operator-related em src/app/ e se tem server-side gate',
    '5. Verifique cobertura de auth em src/app/api/* routes',
    '6. Identifique blockers ou debitos pre-existentes',
    '',
    'RETORNE um resumo curto com:',
    '- currentPhase: estado atual (qual fase esta em andamento)',
    '- operatorAuthFiles: lista de arquivos de auth',
    '- cockpitPageState: tem server-side gate? sim/nao/parcial',
    '- protectedPages: paginas que precisam de auth (lista)',
    '- apiAuthCoverage: % de API routes com requireOperator',
    '- blockers: lista de issues que bloqueiam Fases 15-18',
    '- recommendedFases: lista priorizada de Fases 15-20 com scope e estimatedFiles',
    '',
    'NAO modifique arquivos. Use Read, Grep, Bash apenas.',
  ].join('\n'),
  { label: 'Survey estado', phase: 'Survey', agentType: 'Explore' }
);
log('Survey concluido.');

phase('Fase 15: Refresh tokens');
const phase15Result = await agent(PHASE_15_PROMPT, {
  label: 'Fase 15: Refresh tokens',
  phase: 'Fase 15: Refresh tokens',
  agentType: 'general-purpose',
});
log('Fase 15 concluida.');

phase('Fase 16: UI de sessoes');
const phase16Result = await agent(PHASE_16_PROMPT, {
  label: 'Fase 16: UI sessoes',
  phase: 'Fase 16: UI de sessoes',
  agentType: 'general-purpose',
});
log('Fase 16 concluida.');

phase('Fase 17: Audit auth');
const phase17Result = await agent(PHASE_17_PROMPT, {
  label: 'Fase 17: Audit auth',
  phase: 'Fase 17: Audit auth',
  agentType: 'general-purpose',
});
log('Fase 17 concluida.');

phase('Fase 18: Hard final');
const phase18Result = await agent(PHASE_18_PROMPT, {
  label: 'Fase 18: Hard final',
  phase: 'Fase 18: Hard final',
  agentType: 'general-purpose',
});
log('Fase 18 concluida.');

phase('Verificacao final');
const finalCheck = await agent(
  [
    'Voce e o verificador final. Rode os testes e o build completos, confirme que nada quebrou.',
    '',
    PROJECT_CONTEXT,
    '',
    'TAREFAS:',
    '1. cd /home/skynet/cabala-dos-caminhos',
    '2. Rodar: npx tsc --noEmit 2>&1 | tail -5',
    '3. Rodar: npx vitest run --reporter=dot 2>&1 | tail -10',
    '4. Rodar: npm run build 2>&1 | tail -20',
    '5. git log --oneline -15',
    '6. git status',
    '',
    'RETORNE um summary estruturado:',
    '- typecheck: pass/fail',
    '- tests: pass count / fail count / total',
    '- build: pass/fail',
    '- branch state: ahead/behind/clean',
    '- 5 commits mais recentes com o que cada um fez',
    '',
    'NAO modifique nada. Apenas rode os comandos e reporte.',
  ].join('\n'),
  { label: 'Verificacao final', phase: 'Verificacao final', agentType: 'Explore' }
);
log('Verificacao final concluida.');

log('Workflow completo. Fases 15-18 executadas.');

return {
  survey: surveyResult,
  phase15: phase15Result,
  phase16: phase16Result,
  phase17: phase17Result,
  phase18: phase18Result,
  finalCheck,
};
