// @ts-nocheck
/* eslint-disable */
// meji-iyonu-data.ts — Meji-Iyonu divination data (16 Principal Odu of Obeche/Ifa)

export interface MejiIyonuOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_IYONU_DATA: MejiIyonuOdu[] = [
  {
    id: 'ogbe',
    name: 'Ogbe',
    portugueseName: 'Ogbe',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Amarelo'],
    offerings: ['Melk', 'Palmeira', 'Frutos do mar'],
    ebos: ['Ebo de dinheiro', 'Ebo de saúde'],
    taboos: ['Não matar sapo', 'Não mentir'],
    strengths: ['Vitória garantida', 'Iniciativa', 'Coragem'],
    weaknesses: ['Impaciência', 'Gula'],
    health: ['Coração', 'Cabeça'],
    meanings: ['Criação', 'Início', 'Abundância', 'Força vital'],
    ifaMessage: 'Ogbe divide a água em dois, representando o poder de criar através da oposição.',
  },
  {
    id: 'oyen',
    name: 'Oyen',
    portugueseName: 'Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de paz', 'Ebo de longevidade'],
    taboos: ['Não consumir sal em excesso', 'Não derramar sangue'],
    strengths: ['Sabedoria', 'Paciência', 'Intuição profunda'],
    weaknesses: ['Melancolia', 'Excesso de sensibilidade'],
    health: ['Estômago', 'Útero'],
    meanings: ['Conhecimento', 'Sabedoria', 'Mistério', 'Profundidade'],
    ifaMessage: 'Oyen abre o livro da sabedoria, revelando segredos ocultos.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 3,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Mercúrio', 'Saturno'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja'],
    offerings: ['Cobre', 'Ferro', 'Milho'],
    ebos: ['Ebo de proteção', 'Ebo de comunicação'],
    taboos: ['Não usar armas', 'Não cortar árvores'],
    strengths: ['Comunicação', 'Inteligência', 'Versatilidade'],
    weaknesses: ['Inconstância', 'Nervosismo'],
    health: ['Pulmões', 'Mãos'],
    meanings: ['Ferramentas', 'Comunicação', 'Destino', 'Caminhos'],
    ifaMessage: 'Ogunda revela os caminhos e destinos disponíveis ao consulente.',
  },
  {
    id: 'oshe',
    name: 'Oshe',
    portugueseName: 'Oshe',
    order: 4,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Mel', 'Frutas maduras', 'Vinho doce'],
    ebos: ['Ebo de amor', 'Ebo de fertilidade'],
    taboos: ['Não ser infiel', 'Não comer sozinho'],
    strengths: ['Amor', 'Beleza', 'Abundância', 'Prazer'],
    weaknesses: ['Vaidade', 'Preguiça'],
    health: ['Garganta', 'Rins'],
    meanings: ['Amor', 'Prazer', 'Fertilidade', 'Beleza'],
    ifaMessage: 'Oshe representa o amor e a alegria de viver, trazendo欢乐 e prosperidade.',
  },
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 5,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Plutão', 'Netuno'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudoeste',
    colors: ['Preto', 'Roxo'],
    offerings: ['Água negra', 'Ervas escuras', 'Carvão'],
    ebos: ['Ebo de transformação', 'Ebo de limpeza'],
    taboos: ['Não enganar', 'Não usar veneno'],
    strengths: ['Transformação', 'Regeneração', 'Intuição'],
    weaknesses: ['Obsessão', 'Vingança'],
    health: ['Órgãos genitais', 'Intestinos'],
    meanings: ['Magia', 'Transformação', 'Segredos', 'Poder'],
    ifaMessage: 'Ika revela o poder da transformação através da feitiçaria e da regeneração.',
  },
  {
    id: 'irosun',
    name: 'Irosun',
    portugueseName: 'Irosun',
    order: 6,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Tiphareth', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Nordeste',
    colors: ['Azul', 'Branco'],
    offerings: ['Frutas amarelas', 'Canjica', 'Flores azuis'],
    ebos: ['Ebo de proteção', 'Ebo de purificação'],
    taboos: ['Não ignorar avisos', 'Não comer carne crua'],
    strengths: ['Avisos', 'Proteção', 'Visão espiritual'],
    weaknesses: ['Medo', 'Ansiedade'],
    health: ['Olhos', 'Sangue'],
    meanings: ['Aviso', 'Proteção', 'Visão', 'Sangue'],
    ifaMessage: 'Irosun avisa sobre perigos e revela segredos através de sonhos e presságios.',
  },
  {
    id: 'owonrin',
    name: 'Owonrin',
    portugueseName: 'Owonrin',
    order: 7,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Marte', 'Urano'],
    sephirot: ['Gevurah', 'Chesed'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Noroeste',
    colors: ['Cinza', 'Azul escuro'],
    offerings: ['Milho verde', 'Vento', 'Flores do campo'],
    ebos: ['Ebo de mudança', 'Ebo de libertação'],
    taboos: ['Não guardar objetos velhos', 'Não ser teimoso'],
    strengths: ['Mudança', 'Libertação', 'Movimento'],
    weaknesses: ['Inquietação', 'Impaciência'],
    health: ['Pulmões', 'Joelhos'],
    meanings: ['Mudança', 'Tempestade', 'Movimento', 'Liberdade'],
    ifaMessage: 'Owonrin traz ventos de mudança e libertação, preparando para novos ciclos.',
  },
  {
    id: 'obara',
    name: 'Obara',
    portugueseName: 'Obara',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Júpiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphareth'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Sudeste',
    colors: ['Amarelo', 'Ouro'],
    offerings: ['Milho', 'Feijão', 'Frutas douradas'],
    ebos: ['Ebo de riqueza', 'Ebo de fartura'],
    taboos: ['Não contar planos antes', 'Não comer abóbora'],
    strengths: ['Riqueza', 'Fartura', 'Sabedoria'],
    weaknesses: ['Inveja', 'Teimosia'],
    health: ['Fígado', 'Coxas'],
    meanings: ['Riqueza', 'Fartura', 'Generosidade', 'Educação'],
    ifaMessage: 'Obara traz riqueza e fartura para aqueles que são generosos e estudiosos.',
  },
  {
    id: 'oni',
    name: 'Oni',
    portugueseName: 'Oni',
    order: 9,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Saturno'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Wednesday',
    direction: 'Centro',
    colors: ['Marrom', 'Verde escuro'],
    offerings: ['Raízes', 'Inhame', 'Terra'],
    ebos: ['Ebo de terra', 'Ebo de fundação'],
    taboos: ['Não duvidar de si', 'Não cavar buracos'],
    strengths: ['Estabilidade', 'Fundação', 'Raízes'],
    weaknesses: ['Teimosia', 'Rigidez'],
    health: ['Intestinos', 'Pé'],
    meanings: ['Terra', 'Estabilidade', 'Raízes', 'Ancestralidade'],
    ifaMessage: 'Oni representa a terra e a estabilidade, ancorando o consulente em suas raízes.',
  },
  {
    id: 'ogbe-ogunda',
    name: 'Ogbe Ogunda',
    portugueseName: 'Ogbe Ogunda',
    order: 10,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte', 'Mercúrio'],
    sephirot: ['Chokmah', 'Hod', 'Gevurah'],
    sign: 'Aries/Gêmeos',
    dayOfWeek: 'Domingo',
    direction: 'Leste-Norte',
    colors: ['Vermelho', 'Amarelo', 'Laranja'],
    offerings: ['Ferro', 'Melk', 'Cobre'],
    ebos: ['Ebo de vitória', 'Ebo de coragem'],
    taboos: ['Não fugir de batalhas', 'Não ser covarde'],
    strengths: ['Vitória', 'Coragem', 'Determinação'],
    weaknesses: ['Agressividade', 'Impaciência'],
    health: ['Cabeça', 'Mãos', 'Pulmões'],
    meanings: ['Vitória', 'Combate', 'Determinação', 'Força'],
    ifaMessage: 'Ogbe Ogunda combina criação e destino, garantindo vitória nos empreendimentos.',
  },
  {
    id: 'oyeku-meji',
    name: 'Oyeku Meji',
    portugueseName: 'Oyeku Meji',
    order: 11,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno', 'Plutão'],
    sephirot: ['Binah', 'Yesod', 'Hod'],
    sign: 'Câncer/Escorpião',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste-Sudoeste',
    colors: ['Preto', 'Azul escuro', 'Branco'],
    offerings: ['Água', 'Ervas escuras', 'Flores brancas'],
    ebos: ['Ebo de renovação', 'Ebo de proteção'],
    taboos: ['Não resistir mudanças', 'Não ignorar intuição'],
    strengths: ['Renovação', 'Transformação', 'Profundidade'],
    weaknesses: ['Melancolia', 'Segredos'],
    health: ['Estômago', 'Órgãos genitais'],
    meanings: ['Renovação', 'Segredos', 'Transformação', 'Mistério'],
    ifaMessage: 'Oyeku Meji traz renovação profunda através do fim de ciclos e revelações ocultas.',
  },
  {
    id: 'iwori-meji',
    name: 'Iwori Meji',
    portugueseName: 'Iwori Meji',
    order: 12,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Sol', 'Júpiter'],
    sephirot: ['Gevurah', 'Chokmah', 'Tiphareth'],
    sign: 'Escorpião/Sagitário',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudoeste-Nordeste',
    colors: ['Vermelho', 'Azul', 'Amarelo'],
    offerings: ['Cobre', 'Ferro', 'Frutas'],
    ebos: ['Ebo de conhecimento', 'Ebo de batalha'],
    taboos: ['Não ser precipitado', 'Não ignorar conselhos'],
    strengths: ['Conhecimento', 'Batalha', 'Determinação'],
    weaknesses: ['Orgulho', 'Imprudência'],
    health: ['Sexto chakra', 'Fígado'],
    meanings: ['Conhecimento', 'Batalha', 'Força', 'Sabedoria'],
    ifaMessage: 'Iwori Meji traz o poder do conhecimento guerreiro e da sabedoria Batalhadora.',
  },
  {
    id: 'odi-meji',
    name: 'Odi Meji',
    portugueseName: 'Odi Meji',
    order: 13,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Saturno', 'Plutão'],
    sephirot: ['Malkuth', 'Yesod', 'Binah'],
    sign: 'Virgem/Escorpião',
    dayOfWeek: 'Quarta-feira',
    direction: 'Centro-Sudoeste',
    colors: ['Preto', 'Marrom', 'Verde'],
    offerings: ['Raízes', 'Terra', 'Carvão'],
    ebos: ['Ebo de proteção', 'Ebo de encerramento'],
    taboos: ['Não ignorar sinais', 'Não cavar fundo'],
    strengths: ['Proteção', 'Encerramento', 'Mistério'],
    weaknesses: ['Teimosia', 'Segredos'],
    health: ['Intestinos', 'Útero'],
    meanings: ['Mistério', 'Encerramento', 'Proteção', 'Ocultismo'],
    ifaMessage: 'Odi Meji revela o oculto e protege contra malefícios através do encerramento de ciclos.',
  },
  {
    id: 'irosun-meji',
    name: 'Irosun Meji',
    portugueseName: 'Irosun Meji',
    order: 14,
    polarity: 'feminine',
    element: 'Fire',
    planets: ['Sol', 'Lua', 'Júpiter'],
    sephirot: ['Tiphareth', 'Chesed', 'Hod'],
    sign: 'Leão/Câncer',
    dayOfWeek: 'Domingo',
    direction: 'Nordeste-Leste',
    colors: ['Azul', 'Branco', 'Amarelo'],
    offerings: ['Canjica', 'Frutas', 'Flores azuis'],
    ebos: ['Ebo de proteção', 'Ebo de prosperidade'],
    taboos: ['Não ignorar avisos', 'Não ser ingrato'],
    strengths: ['Proteção', 'Prosperidade', 'Avisos'],
    weaknesses: ['Ansiedade', 'Medo'],
    health: ['Olhos', 'Coração'],
    meanings: ['Proteção', 'Prosperidade', 'Avisos', 'Visão'],
    ifaMessage: 'Irosun Meji traz proteção poderosa e prosperidade através de avisos e orientação espiritual.',
  },
  {
    id: 'owonrin-meji',
    name: 'Owonrin Meji',
    portugueseName: 'Owonrin Meji',
    order: 15,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Marte', 'Urano', 'Saturno'],
    sephirot: ['Gevurah', 'Hod', 'Binah'],
    sign: 'Aquário/Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Noroeste-Oeste',
    colors: ['Cinza', 'Azul escuro', 'Preto'],
    offerings: ['Vento', 'Milho', 'Folhas'],
    ebos: ['Ebo de mudança', 'Ebo de libertação'],
    taboos: ['Não resistir mudança', 'Não guardar velhos'],
    strengths: ['Mudança', 'Libertação', 'Adaptação'],
    weaknesses: ['Inquietação', 'Impaciência'],
    health: ['Pulmões', 'Joelhos'],
    meanings: ['Mudança', 'Libertação', 'Tempestade', 'Renovação'],
    ifaMessage: 'Owonrin Meji traz mudança radical e libertação através de transformações tempestuosas.',
  },
  {
    id: 'obara-meji',
    name: 'Obara Meji',
    portugueseName: 'Obara Meji',
    order: 16,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Júpiter', 'Sol', 'Marte'],
    sephirot: ['Chesed', 'Tiphareth', 'Gevurah'],
    sign: 'Sagitário/Leão',
    dayOfWeek: 'Quinta-feira',
    direction: 'Sudeste-Leste',
    colors: ['Amarelo', 'Ouro', 'Laranja'],
    offerings: ['Milho', 'Feijão', 'Frutas douradas'],
    ebos: ['Ebo de riqueza', 'Ebo de fartura', 'Ebo de proteção'],
    taboos: ['Não ser invejoso', 'Não ser arrogante'],
    strengths: ['Riqueza', 'Fartura', 'Generosidade'],
    weaknesses: ['Orgulho', 'Inveja'],
    health: ['Fígado', 'Coração', 'Coxas'],
    meanings: ['Riqueza', 'Fartura', 'Generosidade', 'Proteção'],
    ifaMessage: 'Obara Meji traz riqueza, fartura e proteção para aqueles que praticam generosidade e gratidão.',
  },
];

export function getData(): MejiIyonuOdu[] {
  return MEJI_IYONU_DATA;
}