// @ts-nocheck
/* eslint-disable */
// meji-ika-data.ts — Meji-Ika divination data (16 Principal Odu of Obeche/Ifa)

export interface MejiIkaOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_IKA_DATA: MejiIkaOdu[] = [
  {
    id: 'meji-ika-1',
    name: 'Meji-Ika-I',
    portugueseName: 'Meji-Ika-I',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Amarelo', 'Branco'],
    offerings: ['Melk', 'Palmeira', 'Frutos do mar', 'Ògọ̀rùn-Ọ̀pẹ̀'],
    ebos: ['Ebo de dinheiro', 'Ebo de saúde', 'Ebo de proteção'],
    taboos: ['Não matar sapo', 'Não mentir', 'Não consumir álcool'],
    strengths: ['Vitória garantida', 'Iniciativa', 'Coragem', 'Poder de destruição do mal'],
    weaknesses: ['Impaciência', 'Gula', 'Orgulho'],
    health: ['Coração', 'Cabeça', 'Visão'],
    meanings: ['Criação', 'Início', 'Abundância', 'Força vital', 'Purificação'],
    ifaMessage: 'Meji-Ika divide a água em dois, purificando o consulente através da oposição sagrada.',
  },
  {
    id: 'meji-ika-2',
    name: 'Meji-Ika-II',
    portugueseName: 'Meji-Ika-II',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro', 'Verde'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas', 'Ọ̀pẹ̀-nla'],
    ebos: ['Ebo de paz', 'Ebo de longevidade', 'Ebo de fertilidade'],
    taboos: ['Não consumir sal em excesso', 'Não derramar sangue', 'Não visitar lugares escuros'],
    strengths: ['Sabedoria', 'Paciência', 'Intuição profunda', 'Capacidade de regeneração'],
    weaknesses: ['Melancolia', 'Excesso de sensibilidade', 'Tendência à solidão'],
    health: ['Estômago', 'Útero', 'Sistema linfático'],
    meanings: ['Conhecimento', 'Sabedoria', 'Mistério', 'Profundidade', 'Renovação'],
    ifaMessage: 'Meji-Ika abre o livro da sabedoria, revelando segredos ocultos para a cura.',
  },
  {
    id: 'meji-ika-3',
    name: 'Meji-Ika-III',
    portugueseName: 'Meji-Ika-III',
    order: 3,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Mercúrio', 'Saturno'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja', 'Azul'],
    offerings: ['Cobre', 'Ferro', 'Milho', 'Ìgbẹ̀-Ọ̀run'],
    ebos: ['Ebo de proteção', 'Ebo de comunicação', 'Ebo de negócios'],
    taboos: ['Não usar armas', 'Não cortar árvores', 'Não guardar ressentimentos'],
    strengths: ['Comunicação', 'Inteligência', 'Versatilidade', 'Resistência física'],
    weaknesses: ['Inconstância', 'Nervosismo', 'Superficialidade'],
    health: ['Pulmões', 'Mãos', 'Sistema nervoso'],
    meanings: ['Ferramentas', 'Comunicação', 'Destino', 'Caminhos', 'Transformação'],
    ifaMessage: 'Meji-Ika forja novas armas para o consulente, transformando obstáculos em oportunidades.',
  },
  {
    id: 'meji-ika-4',
    name: 'Meji-Ika-IV',
    portugueseName: 'Meji-Ika-IV',
    order: 4,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa', 'Marrom'],
    offerings: ['Frutas', 'Meli', 'Pepela', 'Ẹ̀jì-Ọ̀run'],
    ebos: ['Ebo de amor', 'Ebo de prosperidade', 'Ebo de casamento'],
    taboos: ['Não desperdiçar comida', 'Não roubar', 'Não trair parceiros'],
    strengths: ['Beleza', 'Amor', 'Abundância', 'Estabilidade material'],
    weaknesses: ['Materialismo', 'Ciúme', 'Possessividade'],
    health: ['Garganta', 'Pescoço', 'Sistema digestivo'],
    meanings: ['Amor', 'Beleza', 'Fertilidade', 'Prosperidade', 'Harmonia conjugal'],
    ifaMessage: 'Meji-Ika abençoa a terra com fertilidade, trazendo abundância ao consulente.',
  },
  {
    id: 'meji-ika-5',
    name: 'Meji-Ika-V',
    portugueseName: 'Meji-Ika-V',
    order: 5,
    polarity: 'masculine',
    element: 'Wood',
    planets: ['Júpiter', 'Marte'],
    sephirot: ['Chesed', 'Gevurah'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Noroeste',
    colors: ['Azul escuro', 'Roxo', 'Dourado'],
    offerings: ['Vinho de palma', 'Cabrito', 'Ìkọ̀-Ọ̀run'],
    ebos: ['Ebo de justiça', 'Ebo de expiação', 'Ebo de sabedoria'],
    taboos: ['Não praticar feitiçaria maléfica', 'Não jurar falsamente', 'Não desrespeitar elders'],
    strengths: ['Justiça', 'Disciplina', 'Fé', 'Crescimento espiritual'],
    weaknesses: ['Rigor excessivo', 'Dogmatismo', 'Intolerância'],
    health: ['Fígado', 'Coxas', 'Músculos'],
    meanings: ['Lei', 'Justiça', 'Expansão', 'Fé', 'Oráculo'],
    ifaMessage: 'Meji-Ika revela a lei divina, mostrando ao consulente o caminho da retidão.',
  },
  {
    id: 'meji-ika-6',
    name: 'Meji-Ika-VI',
    portugueseName: 'Meji-Ika-VI',
    order: 6,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Plutão'],
    sephirot: ['Hod', ' Netzach'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudeste',
    colors: ['Preto', 'Vermelho sangue', 'Escarlate'],
    offerings: ['Ògọ̀rùn', 'Àdámọ́', 'Ẹ̀jì-Ìkọ̀'],
    ebos: ['Ebo de purificação', 'Ebo de transformação', 'Ebo de morte e renascimento'],
    taboos: ['Não mentir', 'Não esconder a verdade', 'Não ter medo de mudanças'],
    strengths: ['Transformação', 'Regeneração', 'Intensidade', 'Poder de cicatrização'],
    weaknesses: ['Vingança', 'Obsessão', 'Segredos destrutivos'],
    health: ['Órgãos reprodutivos', 'Coluna', 'Medula espinhal'],
    meanings: ['Morte e renascimento', 'Transformação', 'Segredos', 'Poder de cura'],
    ifaMessage: 'Meji-Ika oferece a morte ritual e o renascimento, purificando a alma do consulente.',
  },
  {
    id: 'meji-ika-7',
    name: 'Meji-Ika-VII',
    portugueseName: 'Meji-Ika-VII',
    order: 7,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tipheret', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Centro',
    colors: ['Ouro', 'Laranja', 'Amarelo solar'],
    offerings: ['Mel', 'Cabrito branco', 'Ọ̀pẹ̀-tòpẹ̀', 'Ìwé-Ọ̀run'],
    ebos: ['Ebo de realeza', 'Ebo de liderança', 'Ebo de saúde do coração'],
    taboos: ['Não ser covarde', 'Não abandonar família', 'Não ser egoísta'],
    strengths: ['Liderança', 'Coraçãopio', 'Criatividade', 'Generosidade real'],
    weaknesses: ['Arrogância', 'Desperdício', 'Autocomplacência'],
    health: ['Coração', 'Olhos', 'Espinha dorsal'],
    meanings: ['Realeza', 'Coração', 'Criatividade', 'Liderança', 'Espiritualidade solar'],
    ifaMessage: 'Meji-Ika coroa o consulente com luz solar, iluminando seu caminho de volta ao Ṣọ̀run.',
  },
  {
    id: 'meji-ika-8',
    name: 'Meji-Ika-VIII',
    portugueseName: 'Meji-Ika-VIII',
    order: 8,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Saturno'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Nordeste',
    colors: ['Marrom', 'Bege', 'Verde musgo'],
    offerings: ['Mandioca', 'Feijão', 'Ọ̀bùn-Ọ̀run', 'Ìrẹ̀kẹ̀-Ọ̀run'],
    ebos: ['Ebo de serviço', 'Ebo de pureza', 'Ebo de desapegomaterial'],
    taboos: ['Não ser preguiçoso', 'Não kriticar severamente', 'Não négligenciar saúde'],
    strengths: ['Pureza', 'Serviço', 'Análise', 'Dedicação ao trabalho'],
    weaknesses: ['Crítica excessiva', 'Perfeccionismo', 'Ansiedade'],
    health: ['Intestinos', 'Baço', 'Sistema imunológico'],
    meanings: ['Serviço', 'Pureza', 'Trabalho', 'Saúde', 'Modéstia'],
    ifaMessage: 'Meji-Ika purifica o consulente através do trabalho sagrado e do serviço aos outros.',
  },
  {
    id: 'meji-ika-9',
    name: 'Meji-Ika-IX',
    portugueseName: 'Meji-Ika-IX',
    order: 9,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Urano'],
    sephirot: ['Hod', 'Chesed'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Leste-Nordeste',
    colors: ['Azul eléctrico', 'Prata', 'Ciano'],
    offerings: ['Água corrente', '金属片', 'Ìbonná-Ọ̀run'],
    ebos: ['Ebo de liberdade', 'Ebo de inovação', 'Ebo de pensamiento livre'],
    taboos: ['Não apoiar tirania', 'Não ser conformista', 'Não abandonar ideais'],
    strengths: ['Libertação', 'Inovação', 'Humanitarismo', 'Originalidade'],
    weaknesses: ['Rebeldia destructiva', 'Friagem emocional', 'Irregularidade'],
    health: ['Tornozelos', 'Cãibras', 'Sistema circulatório periférico'],
    meanings: ['Libertação', 'Inovação', 'Humanitarismo', 'Renovação social', 'Liberdade'],
    ifaMessage: 'Meji-Ika traz a chuva de liberdade, libertando o consulente das cadenas da ignorância.',
  },
  {
    id: 'meji-ika-10',
    name: 'Meji-Ika-X',
    portugueseName: 'Meji-Ika-X',
    order: 10,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Vênus', 'Netuno'],
    sephirot: ['Netzach', 'Binah'],
    sign: 'Peixes',
    dayOfWeek: 'Quinta-feira',
    direction: 'Oeste-Sudoeste',
    colors: ['Verde-mar', 'Lavanda', 'Turquesa'],
    offerings: ['Peixe fresco', 'Crostáceos', 'Ọ̀run-Ọ̀pẹ̀', 'Ẹ̀gbá-Ìyá'],
    ebos: ['Ebo de compaixão', 'Ebo de sonhos', 'Ebo de dissolução de ego'],
    taboos: ['Não ser cruel', 'Não fugir da realidade', 'Não se perder em ilusões'],
    strengths: ['Compaixão', 'Intuição', 'S.user sensitividade', 'Conexão espiritual'],
    weaknesses: ['Codependência', 'Vulnerabilidade ao engano', 'Dissipação de energia'],
    health: ['Pés', 'Sangue', 'Sistema imune'],
    meanings: ['Compaixão', 'Sonhos', 'Unidade com o divino', 'Sacrifício', 'Transcendência'],
    ifaMessage: 'Meji-Ika dissolve os limites do ego, levando o consulente a experiências místicas de persatuan com Olodumare.',
  },
  {
    id: 'meji-ika-11',
    name: 'Meji-Ika-XI',
    portugueseName: 'Meji-Ika-XI',
    order: 11,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Gevurah', 'Hod'],
    sign: 'Áries',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudeste',
    colors: ['Vermelho escuro', 'Carmesim', 'Preto'],
    offerings: ['Ejaculado', 'pimenta', 'Àgbà-Ọ̀run'],
    ebos: ['Ebo de guerra', 'Ebo de conquista', 'Ebo de superação de inimigos'],
    taboos: ['Não atacar primeiro', 'Não usar violência sem causa', 'Não ser agressivo sem justifica'],
    strengths: ['Coragem', 'Estratégia', 'Determinação', 'Poder marcial'],
    weaknesses: ['Agressividade', 'Impaciência para vitórias', 'Tendência a conflitos'],
    health: ['Cabeça', 'Músculos', 'Adrenais'],
    meanings: ['Guerra santa', 'Conquista', 'Vitória sobre inimigos', 'Força de vontade', 'Proteção'],
    ifaMessage: 'Meji-Ika empunha a espada da guerra santa, protegendo o consulente contra todo mal.',
  },
  {
    id: 'meji-ika-12',
    name: 'Meji-Ika-XII',
    portugueseName: 'Meji-Ika-XII',
    order: 12,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Lua', 'Terra'],
    sephirot: ['Binah', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Segunda-feira',
    direction: 'Sudoeste',
    colors: ['Verde', 'Ocre', 'Rosa pálido'],
    offerings: ['Frutas da terra', 'Mandioca cozida', 'Ọ̀pẹ̀-Ọ̀run', 'Ẹ̀jì-Ọbùn'],
    ebos: ['Ebo de estabilidade', 'Ebo de casamento', 'Ebo de maternidade'],
    taboos: ['Não abandonar a terra', 'Não desperdiçar recursos', 'Não ser inconstante em compromissos'],
    strengths: ['Estabilidade', 'Fertilidade', 'Resiliência', ' connections with ancestors'],
    weaknesses: ['Carácter possessivo', 'Rigidez', 'Medo de mudanças'],
    health: ['Pescoço', 'Garganta', 'Órgãos reprodutivos femininos'],
    meanings: ['Terra', 'Estabilidade', 'Fertilidade', 'Maternidade', 'Abundância terrena'],
    ifaMessage: 'Meji-Ika conecta o consulente à terra ancestral, fortalecendo seus vínculos com Èsṹ.',
  },
  {
    id: 'meji-ika-13',
    name: 'Meji-Ika-XIII',
    portugueseName: 'Meji-Ika-XIII',
    order: 13,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Júpiter'],
    sephirot: ['Hod', 'Chesed'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte-Nordeste',
    colors: ['Amarelo claro', 'Azul claro', 'Branco'],
    offerings: ['Livros', 'Plumas', 'Ìkọ̀-Lára', 'Ọ̀pẹ̀-Mẹ́ta'],
    ebos: ['Ebo de aprendizado', 'Ebo de comunicação', 'Ebo de viagens curtas'],
    taboos: ['Não Spread mentiras', 'Não ser superficial', 'Não evitar leitura'],
    strengths: ['Aprendizado', 'Comunicação', 'Adaptabilidade', 'Curiosidade intelectual'],
    weaknesses: ['Inconsistência', 'Nervosismo', 'Dificuldade em专注'],
    health: ['Braços', 'Mãos', 'Pulmões'],
    meanings: ['Aprendizado', 'Comunicação', 'Irmandade', 'Viajens', 'Conhecimento'],
    ifaMessage: 'Meji-Ika abre os olhos do consulente para a luz do conhecimento, revelando caminhos de sabedoria.',
  },
  {
    id: 'meji-ika-14',
    name: 'Meji-Ika-XIV',
    portugueseName: 'Meji-Ika-XIV',
    order: 14,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Netzach', 'Binah'],
    sign: 'Libra',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste-Noroeste',
    colors: ['Rosa', 'Azul suave', 'Dourado pálido'],
    offerings: ['Flores', 'Perfumes', 'Ọ̀pẹ̀-Ọ̀run', 'Ẹ̀gbá-Ọ̀run'],
    ebos: ['Ebo de harmonia', 'Ebo de casamento', 'Ebo de relaciones'],
    taboos: ['Não ser injusto', 'Não tomar partido em conflitos', 'Não descuidar da aparência'],
    strengths: ['Equilíbrio', 'Beleza', 'Diplomacia', 'Senso de justiça'],
    weaknesses: ['Indecisão', 'Superficialidade', 'Conflito internal'],
    health: ['Rins', 'Bexiga', 'Lumbar'],
    meanings: ['Harmonia', 'Equilíbrio', 'Beleza', 'Relaciones', 'Parceria'],
    ifaMessage: 'Meji-Ika traz o peso da perfect equilíbrio, harmonizando as relaciones do consulente.',
  },
  {
    id: 'meji-ika-15',
    name: 'Meji-Ika-XV',
    portugueseName: 'Meji-Ika-XV',
    order: 15,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Plutão', 'Sol'],
    sephirot: ['Tipheret', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Centro-Este',
    colors: ['Ouro', 'Branco', 'Vermelho'],
    offerings: ['Leite', 'Mel', 'Ọ̀pẹ̀-Yọ́', 'Ẹ̀jì-Tòró'],
    ebos: ['Ebo de alinhamento', 'Ebo de propósito', 'Ebo de autoestima'],
    taboos: ['Não se humilhar sem causa', 'Não esconder talentos', 'Não ser conformista com a mediocridade'],
    strengths: ['Propósito divino', 'Autoestima', 'Criatividade', 'Liderança inspirada'],
    weaknesses: ['Ego Inflado', 'Arrogância espiritual', 'Desprezo pelos fracos'],
    health: ['Coração', 'Espinha', 'Olhos'],
    meanings: ['Alinhamento', 'Propósito', 'Autoestima', 'Criatividade', 'Luz interior'],
    ifaMessage: 'Meji-Ika alinha o consulente com seu destino sagrado, awakênando sua luz interior para o trabalho de Orí.',
  },
  {
    id: 'meji-ika-16',
    name: 'Meji-Ika-XVI',
    portugueseName: 'Meji-Ika-XVI',
    order: 16,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Saturno', 'Terra'],
    sephirot: ['Malkuth', 'Yesod'],
    sign: 'Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Sul-Sudeste',
    colors: ['Preto', 'Marrom escuro', 'Cinza'],
    offerings: ['Pedras', 'Terra', 'Ọ̀pẹ̀-Ọ̀gbẹ́', 'Ìkọ̀-Ọ̀run'],
    ebos: ['Ebo deardeur', 'Ebo de tradição', 'Ebo de estruturação'],
    taboos: ['Não abandonar ancestrais', 'Não quebrar juramentos', 'Não desrespeitar estruturas'],
    strengths: ['Disciplina', 'Tradição', 'Estruturação', 'Responsabilidad'],
    weaknesses: ['Rigidez', 'Pessimismo', 'Medo do fracasso'],
    health: ['Joelhos', 'Dentes', 'Ossos'],
    meanings: ['Tradição', 'Disciplina', 'Estrutura', 'Responsabilidad', 'Conclusão'],
    ifaMessage: 'Meji-Ika conclui o ciclo, oferecendo ao consulente a sabedoría dos anciões para construir sobre terreno sólido.',
  },
];

export function getData(): MejiIkaOdu[] {
  return MEJI_IKA_DATA;
}
