// @ts-nocheck
 
// meji-iwori-data.ts — Meji-Iwori divination data (16 Principal Odu of Obeche/Ifa)

export interface MejiIworiOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_IWORI_DATA: MejiIworiOdu[] = [
  {
    id: 'iwori',
    name: 'Iwori',
    portugueseName: 'Iwori',
    order: 1,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Sol', 'Saturno'],
    sephirot: ['Chokmah', 'Binah'],
    sign: 'Escorpião',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Marrom'],
    offerings: ['Milho', 'Farinha de mandioca', 'Agua'],
    ebos: ['Ebo de sabedoria', 'Ebo de longevidade'],
    taboos: ['Não mentir aos ancestrais', 'Não desonrar os mais velhos'],
    strengths: ['Sabedoria ancestral', 'Conhecimento profundo', 'Respeito'],
    weaknesses: ['Teimosia', 'Rigidez mental'],
    health: ['Cérebro', 'Coluna'],
    meanings: ['Sabedoria', 'Ancestralidade', 'Tradição', 'Conhecimento'],
    ifaMessage: 'Iwori traz a sabedoria dos ancestrais, revelando que o conhecimento verdadeiro vem da tradição.',
  },
  {
    id: 'iworiyen',
    name: 'Iworiyen',
    portugueseName: 'Iworiyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Peixes',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Prata'],
    offerings: ['Agua do mar', 'Flores brancas', 'Leite'],
    ebos: ['Ebo de paz interior', 'Ebo de intuicao'],
    taboos: ['Não ignorar pressentimentos', 'Não rejeitar sonhos'],
    strengths: ['Intuicao profunda', 'Conexão espiritual', 'Sensibilidade'],
    weaknesses: ['Excessiva sensibilidade', 'Confusao mental'],
    health: ['Glândulas', 'Sistema linfatico'],
    meanings: ['Intuicao', 'Sonhos', 'Profundidade', 'Misterio'],
    ifaMessage: 'Iworiyen abre os olhos da alma, revelando verdades atraves dos sonhos e da intuicao.',
  },
  {
    id: 'iworiodi',
    name: 'Iworiodi',
    portugueseName: 'Iworiodi',
    order: 3,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphereth', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Norte',
    colors: ['Dourado', 'Laranja'],
    offerings: ['Mel', 'Cafe torrado', 'Frango'],
    ebos: ['Ebo de coragem', 'Ebo de honra'],
    taboos: ['Não ser covarde', 'Não esconder a verdade'],
    strengths: ['Coragem', 'Honra', 'Liderança natural'],
    weaknesses: ['Orgulho', 'Importunância'],
    health: ['Coração', 'Olhos'],
    meanings: ['Honra', 'Coragem', 'Luz', 'Realeza interior'],
    ifaMessage: 'Iworiodi brilha como o sol, trazendo coragem para enfrentar qualquer desafio.',
  },
  {
    id: 'iworioshe',
    name: 'Iworioshe',
    portugueseName: 'Iworioshe',
    order: 4,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Mel', 'Frutas maduras', 'Flores'],
    ebos: ['Ebo de amor', 'Ebo de harmonia familiar'],
    taboos: ['Não ser infiel', 'Não abandonar a familia'],
    strengths: ['Amor profundo', 'Lealdade', 'Beleza interior'],
    weaknesses: ['Ciúme', ' possessividade'],
    health: ['Garganta', 'Coracao'],
    meanings: ['Amor', 'Familia', 'Harmonia', 'Beleza'],
    ifaMessage: 'Iworioshe ensina que o amor verdadeiro fortalece os laços familiares e traz paz.',
  },
  {
    id: 'iworika',
    name: 'Iworika',
    portugueseName: 'Iworika',
    order: 5,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutao'],
    sephirot: ['Gevurah', 'Hod'],
    sign: 'Escorpiao',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudeste',
    colors: ['Vermelho escuro', 'Roxo'],
    offerings: ['Pimenta', 'Vinho tinto', 'Sangue de galinha'],
    ebos: ['Ebo de transformação', 'Ebo de proteção'],
    taboos: ['Não guardar rancor', 'Não usar magia para o mal'],
    strengths: ['Transformação', 'Poder curativo', 'Mistério'],
    weaknesses: ['Vingança', 'Segredos perigosos'],
    health: ['Órgãos sexuais', 'Coluna'],
    meanings: ['Mistério', 'Transformação', 'Magia', 'Poder'],
    ifaMessage: 'Iworika revela os segredos da transformação, mostrando que toda crise traz renascimento.',
  },
  {
    id: 'iworiobua',
    name: 'Iworiobua',
    portugueseName: 'Iworiobua',
    order: 6,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Lua', 'Vênus'],
    sephirot: ['Yesod', 'Netzach'],
    sign: 'Libra',
    dayOfWeek: 'Domingo',
    direction: 'Oeste',
    colors: ['Azul', 'Prata'],
    offerings: ['Agua', 'Perfume', 'Sândalo'],
    ebos: ['Ebo de justiça', 'Ebo de reconciliação'],
    taboos: ['Não ser hipócrita', 'Não fraudar'],
    strengths: ['Equilíbrio', 'Justiça', 'Diplomacia'],
    weaknesses: ['Indecisão', 'Superficialidade'],
    health: ['Intestinos', 'Rins'],
    meanings: ['Equilíbrio', 'Justiça', 'Harmonia', 'Lei'],
    ifaMessage: 'Iworiobua pesa as ações com justiça, buscando harmonia entre luz e sombra.',
  },
  {
    id: 'iworioron',
    name: 'Iworioron',
    portugueseName: 'Iworioron',
    order: 7,
    polarity: 'masculine',
    element: 'Wood',
    planets: ['Júpiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphereth'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Noroeste',
    colors: ['Azul royal', 'Dourado'],
    offerings: ['Cravo', 'Incienso', 'Frango'],
    ebos: ['Ebo de prosperidade', 'Ebo de sabedoria'],
    taboos: ['Não explorar os mais fracos', 'Não recusar conhecimento'],
    strengths: ['Filosofia', 'Abundância', 'Generosidade'],
    weaknesses: ['Excesso de confiança', 'Imprudência'],
    health: ['Fígado', 'Coxas'],
    meanings: ['Sorte', 'Filosofia', 'Abundância', 'Sabedoria'],
    ifaMessage: 'Iworioron traz a bênção do conhecimento, expandindo a mente para novas verdades.',
  },
  {
    id: 'iworiodi',
    name: 'Iworiodi',
    portugueseName: 'Iworiodi',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphereth', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Norte',
    colors: ['Dourado', 'Laranja'],
    offerings: ['Mel', 'Ouro', 'Coroa'],
    ebos: ['Ebo de realeza', 'Ebo de poder'],
    taboos: ['Não ser covarde', 'Não desonrar a família'],
    strengths: ['Liderança', 'Coragem', 'Nobreza'],
    weaknesses: ['Orgulho', 'Tirania'],
    health: ['Coração', 'Olhos'],
    meanings: ['Realeza', 'Poder', 'Honra', 'Luz'],
    ifaMessage: 'Iworiodi ilumina como o sol, trazendo poder real e sabedoria verdadeira.',
  },
  {
    id: 'iworiire',
    name: 'Iworiire',
    portugueseName: 'Iworiire',
    order: 9,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Frutas', 'Mel', 'Vinho'],
    ebos: ['Ebo de paz', 'Ebo de bênção'],
    taboos: ['Não falar mal', 'Não ser ingrato'],
    strengths: ['Paz', 'Bênção', 'Gratidão'],
    weaknesses: ['Suscetibilidade', 'Dependência'],
    health: ['Pescoço', 'Garganta'],
    meanings: ['Bênção', 'Paz', 'Gratidão', 'Harmonia'],
    ifaMessage: 'Iworiire traz paz e bênçãos, mas requer gratidão e humildade constante.',
  },
  {
    id: 'iworioshi',
    name: 'Iworioshi',
    portugueseName: 'Iworioshi',
    order: 10,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Marte'],
    sephirot: ['Gevurah', 'Malkuth'],
    sign: 'Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Sul',
    colors: ['Preto', 'Marrom'],
    offerings: ['Cachorro', 'Eti', 'Pimenta'],
    ebos: ['Ebo de proteção', 'Ebo de disciplina'],
    taboos: ['Não abandonar', 'Não ser traidor'],
    strengths: ['Lealdade', 'Disciplina', 'Proteção'],
    weaknesses: ['Rigidez', 'Crueldade'],
    health: ['Ossos', 'Joelhos'],
    meanings: ['Força', 'Proteção', 'Guerra', 'Disciplina'],
    ifaMessage: 'Iworioshi representa a disciplina de ferro e a lealdade inabalável aos seus.',
  },
  {
    id: 'iworikana',
    name: 'Iworikana',
    portugueseName: 'Iworikana',
    order: 11,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Saturno', 'Netuno'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Leste',
    colors: ['Azul escuro', 'Prata'],
    offerings: ['Agua salgada', 'Carvão', 'Cera'],
    ebos: ['Ebo de encerramento', 'Ebo de revelação'],
    taboos: ['Não revelar segredos', 'Não desobedecer'],
    strengths: ['Mistério', 'Conhecimento oculto', 'Sabedoria profunda'],
    weaknesses: ['Prisão', 'Segredos que prendem'],
    health: ['Cérebro', 'Sistema nervoso'],
    meanings: ['Prisão', 'Mistério', 'Segredo', 'Cativeiro'],
    ifaMessage: 'Iworikana revela prisões espirituais e os segredos ancestrais que as prendem.',
  },
  {
    id: 'iworima',
    name: 'Iworima',
    portugueseName: 'Iworima',
    order: 12,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Gevurah', 'Chokmah'],
    sign: 'Áries',
    dayOfWeek: 'Terça-feira',
    direction: 'Nordeste',
    colors: ['Vermelho', 'Escarlate'],
    offerings: ['Sangue', 'Pimenta', 'Armas'],
    ebos: ['Ebo de guerra', 'Ebo de conquista'],
    taboos: ['Não recuar', 'Não temer'],
    strengths: ['Conquista', 'Vitória militar', 'Bravura'],
    weaknesses: ['Agressividade', 'Imprudência'],
    health: ['Cabeça', 'Nariz'],
    meanings: ['Guerra', 'Conquista', 'Vitória', 'Batalha'],
    ifaMessage: 'Iworima canta o hino da batalha, prometendo vitória aos sabios e corajosos.',
  },
  {
    id: 'iworiton',
    name: 'Iworiton',
    portugueseName: 'Iworiton',
    order: 13,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Peixes',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Ciano'],
    offerings: ['Agua do mar', 'Peixes', 'Sal'],
    ebos: ['Ebo de limpeza', 'Ebo de purificação'],
    taboos: ['Não poluir', 'Não mentir na água'],
    strengths: ['Purificação', 'Movimento', 'Adaptação'],
    weaknesses: ['Inundação', 'Afogamento'],
    health: ['Pés', 'Sistema imunológico'],
    meanings: ['Água', 'Movimento', 'Purificação', 'Mudança'],
    ifaMessage: 'Iworiton flui como água, lavando impurezas e trazendo renovação espiritual.',
  },
  {
    id: 'iworiluon',
    name: 'Iworiluon',
    portugueseName: 'Iworiluon',
    order: 14,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Vênus'],
    sephirot: ['Malkuth', 'Netzach'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Centro',
    colors: ['Marrom', 'Verde escuro'],
    offerings: ['Raízes', 'Terra', 'Melão'],
    ebos: ['Ebo de terra', 'Ebo de fundamento'],
    taboos: ['Não desrespeitar a terra', 'Não desperdiçar comida'],
    strengths: ['Fundamento', 'Praticidade', 'Conexão terrena'],
    weaknesses: ['Materialismo', 'Escassez'],
    health: ['Intestinos', 'Pele'],
    meanings: ['Terra', 'Trabalho', 'Realidade', 'Humildade'],
    ifaMessage: 'Iworiluon ensina que a verdadeira sabedoria está no trabalho honesto e na conexão com a terra.',
  },
  {
    id: 'iworikun',
    name: 'Iworikun',
    portugueseName: 'Iworikun',
    order: 15,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Chokmah', 'Tiphereth'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Norte',
    colors: ['Dourado', 'Amarelo'],
    offerings: ['Mel', 'Frango assado', 'Coroa de flores'],
    ebos: ['Ebo de alegria', 'Ebo de recebimento'],
    taboos: ['Não recusar presente', 'Não ser mesquinho'],
    strengths: ['Felicidade', 'Recebimento', 'Celebração'],
    weaknesses: ['Excesso', 'Superficialidade'],
    health: ['Coração', 'Estômago'],
    meanings: ['Alegria', 'Presente', 'Celebração', 'Recebimento'],
    ifaMessage: 'Iworikun traz alegria e boas novas, prometendo sabedoria e felicidade.',
  },
  {
    id: 'iworituo',
    name: 'Iworituo',
    portugueseName: 'Iworituo',
    order: 16,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Mercúrio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Cinza', 'Branco'],
    offerings: ['Farinha', 'Agua', 'Ovelha branca'],
    ebos: ['Ebo de morte', 'Ebo de fim'],
    taboos: ['Não celebrar morte', 'Não tocar defuntos'],
    strengths: ['Transição', 'Finalização', 'Libertação'],
    weaknesses: ['Morte', 'Perda', 'Tristeza'],
    health: ['Pulmões', 'Sistema respiratório'],
    meanings: ['Morte', 'Fim', 'Transição', 'Libertação'],
    ifaMessage: 'Iworituo encerra ciclos com sabedoria, trazendo fim necessário para novo começo.',
  },
];

export function getData(): MejiIworiOdu[] {
  return MEJI_IWORI_DATA;
}
