// Hatha data

export interface HathaPractice {
  id: string;
  name: string;
  namePt: string;
  type: 'hatha';
  category: 'asana' | 'pranayama' | 'kriya' | 'mudra' | 'bandha';
  description: string;
  descriptionPt: string;
  duration: number;
  durationUnit: 'minutes' | 'seconds' | 'minutes_per_side';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  benefits: string[];
  precautions: string[];
  location: string;
  locationPt: string;
  sefirot: string[];
  qualities: string[];
  score: number;
}

const data: HathaPractice[] = [
  {
    id: 'mountain-pose',
    name: 'Tadasana',
    namePt: 'Postura da Montanha',
    type: 'hatha',
    category: 'asana',
    description: 'Foundational standing pose that establishes alignment and body awareness.',
    descriptionPt: 'Postura fundamental em pé que estabelece alinhamento e consciência corporal.',
    duration: 1,
    durationUnit: 'minutes',
    difficulty: 'beginner',
    benefits: ['Improves posture', 'Strengthens legs', 'Grounds energy'],
    precautions: ['Stand near support if dizzy', 'Keep weight evenly distributed'],
    location: 'Full body standing',
    locationPt: 'Corpo inteiro em pé',
    sefirot: ['Malkuth'],
    qualities: ['Grounding', 'Stability', 'Presence'],
    score: 3,
  },
  {
    id: 'warrior-1',
    name: 'Virabhadrasana I',
    namePt: 'Guerreiro I',
    type: 'hatha',
    category: 'asana',
    description: 'Powerful standing pose that builds strength and focus while opening the chest.',
    descriptionPt: 'Postura em pé poderosa que constrói força e foco enquanto abre o peito.',
    duration: 1,
    durationUnit: 'minutes_per_side',
    difficulty: 'beginner',
    benefits: ['Strengthens legs', 'Opens hips', 'Builds focus'],
    precautions: ['Avoid high blood pressure', 'Knee over ankle'],
    location: 'Lower body / Chest',
    locationPt: 'Corpo inferior / Peito',
    sefirot: ['Malkuth', 'Netzach'],
    qualities: ['Strength', 'Courage', 'Expansion'],
    score: 5,
  },
  {
    id: 'tree-pose',
    name: 'Vrksasana',
    namePt: 'Postura da Árvore',
    type: 'hatha',
    category: 'asana',
    description: 'Balancing pose that cultivates concentration and steadiness.',
    descriptionPt: 'Postura de equilíbrio que cultiva concentração e firmeza.',
    duration: 1,
    durationUnit: 'minutes_per_side',
    difficulty: 'beginner',
    benefits: ['Improves balance', 'Strengthens ankles', 'Enhances focus'],
    precautions: ['Use wall support if needed', 'Avoid on slippery surface'],
    location: 'Standing leg / Core',
    locationPt: 'Perna de apoio / Centro',
    sefirot: ['Malkuth', 'Yesod'],
    qualities: ['Balance', 'Rootedness', 'Poise'],
    score: 4,
  },
  {
    id: 'cobra-pose',
    name: 'Bhujangasana',
    namePt: 'Postura da Cobra',
    type: 'hatha',
    category: 'asana',
    description: 'Gentle backbend that strengthens the spine and opens the heart.',
    descriptionPt: 'Curva suave para trás que fortalece a coluna e abre o coração.',
    duration: 1,
    durationUnit: 'minutes_per_side',
    difficulty: 'beginner',
    benefits: ['Strengthens back', 'Opens chest', 'Relieves stress'],
    precautions: ['Keep lower ribs grounded', 'Avoid if pregnant'],
    location: 'Spine / Chest',
    locationPt: 'Coluna / Peito',
    sefirot: ['Tiphereth'],
    qualities: ['Opening', 'Heart', 'Courage'],
    score: 4,
  },
  {
    id: 'downward-dog',
    name: 'Adho Mukha Svanasana',
    namePt: 'Cão Olhando para Baixo',
    type: 'hatha',
    category: 'asana',
    description: 'Inverted pose that stretches the entire body while building strength.',
    descriptionPt: 'Postura invertida que alonga todo o corpo enquanto constrói força.',
    duration: 1,
    durationUnit: 'minutes',
    difficulty: 'beginner',
    benefits: ['Stretches hamstrings', 'Strengthens arms', 'Calms mind'],
    precautions: ['Bend knees if tight hamstrings', 'Avoid with wrist injury'],
    location: 'Full body stretch',
    locationPt: 'Alongamento total do corpo',
    sefirot: ['Malkuth', 'Tiphereth'],
    qualities: ['Extension', 'Rejuvenation', 'Inversion'],
    score: 5,
  },
  {
    id: 'corpse-pose',
    name: 'Savasana',
    namePt: 'Postura do Cadáver',
    type: 'hatha',
    category: 'asana',
    description: 'Final relaxation pose that integrates the practice and promotes deep rest.',
    descriptionPt: 'Postura de relaxamento final que integra a prática e promove descanso profundo.',
    duration: 10,
    durationUnit: 'minutes',
    difficulty: 'beginner',
    benefits: ['Reduces stress', 'Integrates practice', 'Promotes healing'],
    precautions: ['Stay warm', 'Use support under knees if needed'],
    location: 'Full body supine',
    locationPt: 'Corpo inteiro deitado',
    sefirot: ['Malkuth', 'Tiphereth', 'Kether'],
    qualities: ['Relaxation', 'Integration', 'Surrender'],
    score: 8,
  },
  {
    id: 'victorious-breath',
    name: 'Ujjayi Pranayama',
    namePt: 'Pranayama Vitorioso',
    type: 'hatha',
    category: 'pranayama',
    description: 'Ocean-sounding breath that heats the body and calms the mind.',
    descriptionPt: 'Respiração com som de oceano que aquece o corpo e acalma a mente.',
    duration: 5,
    durationUnit: 'minutes',
    difficulty: 'beginner',
    benefits: ['Calms nervous system', 'Builds internal heat', 'Improves focus'],
    precautions: ['Start gradually', 'Avoid if hyperventilating'],
    location: 'Throat / Full breath',
    locationPt: 'Garganta / Respiração completa',
    sefirot: ['Vishuddha', 'Ajna'],
    qualities: ['Heat', 'Focus', 'Meditation'],
    score: 6,
  },
  {
    id: 'alternate-nostril',
    name: 'Nadi Shodhana',
    namePt: 'Purificação dos Canais',
    type: 'hatha',
    category: 'pranayama',
    description: 'Balancing pranayama that harmonizes ida and pingala nadis.',
    descriptionPt: 'Pranayama equilibrador que harmoniza os nadis ida e pingala.',
    duration: 5,
    durationUnit: 'minutes',
    difficulty: 'intermediate',
    benefits: ['Balances energy', 'Calms mind', 'Prepares for meditation'],
    precautions: ['Keep breath smooth', 'Avoid forcing retention'],
    location: 'Full body / Energy channels',
    locationPt: 'Corpo inteiro / Canais de energia',
    sefirot: ['Yesod', 'Tiphereth'],
    qualities: ['Balance', 'Harmony', 'Purity'],
    score: 7,
  },
  {
    id: 'boat-pose',
    name: 'Navasana',
    namePt: 'Postura do Barco',
    type: 'hatha',
    category: 'asana',
    description: 'Core-strengthening pose that builds abdominal power and balance.',
    descriptionPt: 'Postura fortalecedora do centro que constrói poder abdominal e equilíbrio.',
    duration: 1,
    durationUnit: 'minutes',
    difficulty: 'intermediate',
    benefits: ['Strengthens core', 'Improves balance', 'Stimulates digestion'],
    precautions: ['Avoid with back injury', 'Keep chest lifted'],
    location: 'Core / Hip flexors',
    locationPt: 'Centro / Flexores do quadril',
    sefirot: ['Malkuth', 'Hod'],
    qualities: ['Strength', 'Core', 'Determination'],
    score: 5,
  },
  {
    id: 'lotus-pose',
    name: 'Padmasana',
    namePt: 'Postura da Lótus',
    type: 'hatha',
    category: 'asana',
    description: 'Classic meditation pose that promotes stability and elevated states.',
    descriptionPt: 'Postura clássica de meditação que promove estabilidade e estados elevados.',
    duration: 15,
    durationUnit: 'minutes',
    difficulty: 'advanced',
    benefits: ['Promotes straight spine', 'Calms mind', 'Traditional meditation seat'],
    precautions: ['Open hips gradually', 'Use support under knees if needed'],
    location: 'Hips / Spine',
    locationPt: 'Quadril / Coluna',
    sefirot: ['Sahasrara', 'Tiphereth'],
    qualities: ['Stability', 'Meditation', 'Sacred posture'],
    score: 9,
  },
];

export function getData(): HathaPractice[] {
  return data;
}