// @ts-nocheck
 
// meji-oni-data.ts — Meji-Oni divination data (16 Principal Odu of Obeche/Ifa)

export interface MejiOniOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_ONI_DATA: MejiOniOdu[] = [
  {
    id: 'oni',
    name: 'Oni',
    portugueseName: 'Oni',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Netzach'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Laranja'],
    offerings: ['Pimenta', 'Gengibre', 'Azeite de dendê'],
    ebos: ['Ebo de vitória', 'Ebo de força'],
    taboos: ['Não desistir dos objetivos', 'Não ter covardia'],
    strengths: ['Determinação', 'Liderança', 'Poder de ação'],
    weaknesses: ['Orgulho excessivo', 'Agressividade'],
    health: ['Cabeça', 'Músculos'],
    meanings: ['Força', 'Coragem', 'Ação', 'Iniciativa'],
    ifaMessage: 'Oni carrega o bastão do poder, abrindo caminho através de todos os obstáculos.',
  },
  {
    id: 'ire',
    name: 'Ire',
    portugueseName: 'Ire',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Vênus'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Oeste',
    colors: ['Rosa', 'Verde claro'],
    offerings: ['Mel', 'Leite', 'Flores perfumadas'],
    ebos: ['Ebo de paz', 'Ebo de harmonia'],
    taboos: ['Não falar mal dos outros', 'Não guardar rancor'],
    strengths: ['Amor', 'Beleza', 'Paz interior'],
    weaknesses: ['Preguiça', 'Materialismo'],
    health: ['Garganta', 'Pele'],
    meanings: ['Bênção', 'Paz', 'Harmonia', 'Contentamento'],
    ifaMessage: 'Ire traz a água fresca da serenidade, apagando toda sede espiritual.',
  },
  {
    id: 'ogi',
    name: 'Ogi',
    portugueseName: 'Ogi',
    order: 3,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Júpiter'],
    sephirot: ['Hod', ' Chesed'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Branco'],
    offerings: ['Frutas secas', 'Nozes', 'Aveia'],
    ebos: ['Ebo de comunicação', 'Ebo de sabedoria'],
    taboos: ['Não mentir', 'Não caluniar'],
    strengths: ['Inteligência', 'Comunicação', 'Versatilidade'],
    weaknesses: ['Nervosismo', 'Inconsistência'],
    health: ['Pulmões', 'Mãos'],
    meanings: ['Transmissão', 'Sabedoria', 'Oratória', 'Comércio'],
    ifaMessage: 'Ogi sopra o vento da eloquência, levando palavras de poder a todos os cantos.',
  },
  {
    id: 'ogbe-oyen',
    name: 'Ogbe-Oyen',
    portugueseName: 'Ogbe-Oyen',
    order: 4,
    polarity: 'masculine',
    element: 'Fire-Water',
    planets: ['Sol', 'Lua'],
    sephirot: ['Chokmah', 'Binah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Ouro', 'Azul escuro'],
    offerings: ['Café', 'Azeite', 'Coco ralado'],
    ebos: ['Ebo de prosperidade', 'Ebo de proteção'],
    taboos: ['Não descuidar dos compromissos', 'Não fazer promessas vazias'],
    strengths: ['Equilíbrio', 'Discernimento', 'Abundância'],
    weaknesses: ['Conflitos internos', 'Indecisão'],
    health: ['Coração', 'Rins'],
    meanings: ['Decisão', 'Equilíbrio', 'Abundância', 'Proteção'],
    ifaMessage: 'Ogbe-Oyen une o fogo e a água em harmonia, criando estabilidade através dos opostos.',
  },
  {
    id: 'ogboni',
    name: 'Ogboni',
    portugueseName: 'Ogboni',
    order: 5,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Terra'],
    sephirot: [' Malkuth', 'Yesod'],
    sign: 'Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Sul',
    colors: ['Marrom', 'Preto'],
    offerings: ['Terra', 'Raízes', 'Cascas'],
    ebos: ['Ebo de sabedoria ancestral', 'Ebo de根基'],
    taboos: ['Não desrespeitar os idosos', 'Não quebrar juramentos'],
    strengths: ['Sabedoria dos ancestrais', 'Resiliência', 'Firmeza'],
    weaknesses: ['Teimosia', 'Rigidez'],
    health: ['Ossos', 'Joelhos'],
    meanings: ['Conhecimento profundo', 'Raízes', 'Tradição', 'Firmeza'],
    ifaMessage: 'Ogboni planta a semente da sabedoria antiga nas terras férteis da consciência.',
  },
  {
    id: 'ejife',
    name: 'Ejife',
    portugueseName: 'Ejife',
    order: 6,
    polarity: 'feminine',
    element: 'Earth-Water',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sudoeste',
    colors: ['Verde', 'Bege'],
    offerings: ['Grãos', 'Legumes', 'Mel'],
    ebos: ['Ebo de saúde', 'Ebo de trabalho'],
    taboos: ['Não desperdiçar recursos', 'Não ser indolente'],
    strengths: ['Serviço', 'Pureza', 'Devoção'],
    weaknesses: ['Crítica excessiva', 'Perfeccionismo'],
    health: ['Intestinos', 'Baço'],
    meanings: ['Serviço', 'Pureza', 'Higiene', 'Devoção'],
    ifaMessage: 'Ejife tece o tapete da purificação, varrendo toda impureza do caminho.',
  },
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 7,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Netuno', 'Lua'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Oeste',
    colors: ['Preto', 'Roxo'],
    offerings: ['Aguardente', 'Goma arábica', 'Tinta'],
    ebos: ['Ebo de transformação', 'Ebo de mistério'],
    taboos: ['Não revelar segredos', 'Não trair confiança'],
    strengths: ['Transformação', 'Intuição profunda', 'Coragem'],
    weaknesses: ['Vingança', 'Segredos destrutivos'],
    health: ['Órgãos sexuais', 'Bexiga'],
    meanings: ['Mistério', 'Transformação', 'Regeneração', 'Segredos'],
    ifaMessage: 'Ika remove a pele antiga, revelando a serpente da renovação escondida por baixo.',
  },
  {
    id: 'oturupon',
    name: 'Oturupon',
    portugueseName: 'Oturupon',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Júpiter'],
    sephirot: ['Geburah', 'Chesed'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Nordeste',
    colors: ['Azul royal', 'Dourado'],
    offerings: ['Vinho', 'Carne assada', 'Especiarias'],
    ebos: ['Ebo de sorte', 'Ebo de viagem'],
    taboos: ['Não ser hipócrita', 'Não viajar sozinho'],
    strengths: ['Sorte', 'Expansão', 'Filosofia'],
    weaknesses: ['Excesso de confiança', 'Imprudência'],
    health: ['Fígado', 'Quadril'],
    meanings: ['Sorte', 'Viagem', 'Expansão', 'Filosofia'],
    ifaMessage: 'Oturupon aponta a flecha da sorte além das sete montanhas da incerteza.',
  },
  {
    id: 'obara',
    name: 'Obara',
    portugueseName: 'Obara',
    order: 9,
    polarity: 'masculine',
    element: 'Fire-Earth',
    planets: ['Sol', 'Saturno'],
    sephirot: ['Tiphereth', 'Malkuth'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Sul',
    colors: ['Amarelo', 'Marrom'],
    offerings: ['Milho', 'Farinha de trigo', 'Manteiga'],
    ebos: ['Ebo de casamento', 'Ebo de lealdade'],
    taboos: ['Não ser infiel', 'Não quebrar promessas'],
    strengths: ['Honra', 'Lealdade', 'Nobreza'],
    weaknesses: ['Rigidez moral', 'Orgulho'],
    health: ['Coração', 'Costas'],
    meanings: ['Honra', 'Lealdade', 'Casamento', 'Nobreza'],
    ifaMessage: 'Obara estende a mão da aliança sagrada, selando pactos de sangue e amor.',
  },
  {
    id: 'okanrin',
    name: 'Okanrin',
    portugueseName: 'Okanrin',
    order: 10,
    polarity: 'feminine',
    element: 'Air-Water',
    planets: ['Lua', 'Mercúrio'],
    sephirot: ['Yesod', 'Hod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul claro', 'Prata'],
    offerings: ['Água', 'Ervas', 'Areia do mar'],
    ebos: ['Ebo de proteção', 'Ebo de clarividência'],
    taboos: ['Não consultar falsos oráculos', 'Não abusar de bebidas'],
    strengths: ['Clarividência', 'Sensibilidade', 'Memória'],
    weaknesses: ['Instabilidade emocional', 'Confusão mental'],
    health: ['Estômago', 'Mente'],
    meanings: ['Visão', 'Memória', 'Sensibilidade', 'Mundo espiritual'],
    ifaMessage: 'Okanrin abre o terceiro olho, permitindo ver através das águas da ilusão.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 11,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Marte', 'Mercúrio'],
    sephirot: ['Geburah', 'Hod'],
    sign: 'Áries',
    dayOfWeek: 'Terça-feira',
    direction: 'Norte',
    colors: ['Vermelho', 'Amarelo'],
    offerings: ['Pimenta', 'Fogo', 'Ferro'],
    ebos: ['Ebo de guerra', 'Ebo de proteção'],
    taboos: ['Não iniciar conflitos desnecessários', 'Não usar violência'],
    strengths: ['Coragem', 'Estratégia', 'Comunicação de guerra'],
    weaknesses: ['Guerra desnecessária', 'Palavras ferinas'],
    health: ['Cabeça', 'Braços'],
    meanings: ['Guerra', 'Ferramentas', 'Mensagem', 'Estratégia'],
    ifaMessage: 'Ogunda empunha a espada da palavra certa, cortando mentiras e descobrindo a verdade.',
  },
  {
    id: 'osa',
    name: 'Osa',
    portugueseName: 'Osa',
    order: 12,
    polarity: 'feminine',
    element: 'Water-Earth',
    planets: ['Venus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sudeste',
    colors: ['Verde', 'Rosa'],
    offerings: ['Manga', 'Banana', 'Frutas tropicais'],
    ebos: ['Ebo de estabilidade', 'Ebo de negócios'],
    taboos: ['Não desperdiçar comida', 'Não ter preguiça'],
    strengths: ['Estabilidade', 'Prosperidade', 'Prazer'],
    weaknesses: ['Avidez', 'Inércia'],
    health: ['Garganta', 'Pescoço'],
    meanings: ['Estabilidade', 'Prosperidade', 'Prazer', 'Boa sorte'],
    ifaMessage: 'Osa abre a porta da abundância, convidando o fluxo de bênçãos materiais.',
  },
  {
    id: 'iyonu',
    name: 'Iyonu',
    portugueseName: 'Iyonu',
    order: 13,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Lua', 'Terra'],
    sephirot: ['Binah', 'Malkuth'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Marrom claro'],
    offerings: ['Leite', 'Mingau', 'Pão'],
    ebos: ['Ebo de nutrição', 'Ebo de família'],
    taboos: ['Não abandonar os necessitados', 'Não ser mesquinho'],
    strengths: ['Nutrição', 'Maternidade', 'Generosidade'],
    weaknesses: ['Abuso maternal', 'Excesso de preocupação'],
    health: ['Útero', 'Seios'],
    meanings: ['Nutrição', 'Maternidade', 'Caridade', 'Abundância'],
    ifaMessage: 'Iyonu alimenta o filho do mundo inteiro, sustentando toda vida com seu leite cósmico.',
  },
  {
    id: 'rosun',
    name: 'Rosun',
    portugueseName: 'Rosun',
    order: 14,
    polarity: 'masculine',
    element: 'Fire-Air',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Chokmah', 'Tiphereth'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Dourado', 'Laranja'],
    offerings: ['Azeite', 'Mel', 'Cravo-da-índia'],
    ebos: ['Ebo de sucesso', 'Ebo de consagração'],
    taboos: ['Não ser arrogante na vitória', 'Não menosprezar os outros'],
    strengths: ['Majestade', 'Sucesso', 'Reconhecimento'],
    weaknesses: ['Arrogância', 'Luxúria'],
    health: ['Coração', 'Olhos'],
    meanings: ['Majestade', 'Sucesso', 'Vitória', 'Reconhecimento'],
    ifaMessage: 'Rosun recebe a coroa do triunfo, brilhando como o sol do meio-dia.',
  },
  {
    id: 'ofun',
    name: 'Ofún',
    portugueseName: 'Ofún',
    order: 15,
    polarity: 'masculine',
    element: 'Air',
    planets: ['Mercúrio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Livros', 'Tinta', 'Papel'],
    ebos: ['Ebo de conhecimento', 'Ebo de escrever destino'],
    taboos: ['Não guardar segredos nocivos', 'Não falsear documentos'],
    strengths: ['Conhecimento', 'Escrita', 'Mídia'],
    weaknesses: ['Fofoca', 'Documentos falsos'],
    health: ['Mãos', 'Pulmões'],
    meanings: ['Conhecimento', 'Escrita', 'Magia', 'Destino'],
    ifaMessage: 'Ofún escreve o destino na palma da mão, revelando o que foi ocultado.',
  },
  {
    id: 'owonrin',
    name: 'Owonrin',
    portugueseName: 'Owonrin',
    order: 16,
    polarity: 'masculine',
    element: 'Air-Water',
    planets: ['Saturno', 'Netuno'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Sudeste',
    colors: ['Azul escuro', 'Branco'],
    offerings: ['Petróleo', 'Sal', 'Velas brancas'],
    ebos: ['Ebo de chuva', 'Ebo de renovação'],
    taboos: ['Não contaminar águas', 'Não desperdiciar'],
    strengths: ['Chuva', 'Renovação', 'Purificação'],
    weaknesses: ['Inundação', 'Destruição'],
    health: ['Articulações', 'Sistema nervoso'],
    meanings: ['Tempestade', 'Renovação', 'Regeneração', 'Ciclos'],
    ifaMessage: 'Owonrin traz a chuva purificadora, lavando a terra e renovando toda vida.',
  },
];

export function getData(): MejiOniOdu[] {
  return MEJI_ONI_DATA;
}