[migrationLock]
lockVersion = 2

[[actions]]
action = "drop_enum"
enum_name = "UserRole"

[[actions]]
action = "create_enum"
enum_name = "OperatorRole"
values = ["OPERATOR", "ADMIN"]

[[actions]]
action = "alter_column"
table = "operators"
column = "role"
type = "\"OperatorRole\""
