// ============================================================================
// Recording + Replay — Wave 39 (Video + Streaming 6/8)
// ============================================================================
// Auto-record every live event, transcode to VOD, generate thumbnail,
// auto-chapter markers, publish to /library after the event.
//
// LGPD Art. 7, 18, 37 — recording consent:
//   • Host must opt-in (recording toggle in event creation form)
//   • Viewer banner: "Este evento está sendo gravado" with link to privacy
//   • Attendees can request deletion of their Q&A / chat messages
//     (the video itself is the host's IP — not deletable per host's choice)
//
// The recording pipeline:
//   Live HLS  →  Concat to single MP4  →  Upload to S3
//                                              ↓
//                            Thumbnail at midpoint (FFmpeg seek)
//                                              ↓
//                            Auto-chapters from highlight markers
//                                              ↓
//                            Whisper PT-BR captions (background)
//                                              ↓
//                            Publish to Library (visible to RSVP-only)
//
// ============================================================================

/**
 * Auto-chapter marker — derived from chat highlight detection.
 * Stored as part of the VOD manifest so the player can render skip links.
 */
export interface AutoChapter {
  readonly id: string;
  readonly title: string;
  /** Seconds from start of recording. */
  readonly offset: number;
  /** Auto-generated by chat velocity (true) vs manual host marker (false). */
  readonly auto: boolean;
  /** Reason for chapter (e.g. "Burst: 8 msgs in 5s"). */
  readonly reason?: string;
}

/**
 * Metadata describing a recorded event in the library.
 * Owned by the host — they decide if/when it goes public.
 */
export interface RecordedEvent {
  readonly id: string;
  readonly originalEventId: string;
  readonly title: string;
  readonly facilitator: string;
  readonly tradicao?: string;
  readonly duration: number; // seconds
  readonly cdnVideoId: string;
  readonly thumbnailUrl: string;
  readonly captionsUrl?: string;
  readonly chapters: readonly AutoChapter[];
  readonly visibility: 'private' | 'rsvp-only' | 'public';
  readonly createdAt: string; // ISO
  /** LGPD consent given by host for recording (LGPD Art. 7). */
  readonly lgpdConsent: true;
  /** Allow community members to add to watch history / progress. */
  readonly progressTrackingEnabled: boolean;
}

export interface RecordingRequest {
  readonly eventId: string;
  readonly hostId: string;
  readonly title: string;
  readonly tradicao?: string;
  readonly hlsManifestUrl: string;
  readonly lgpdConsent: true;
  readonly publishPolicy: 'auto-publish' | 'review-then-publish' | 'private';
}

/**
 * Generate the FFmpeg seek command to extract a thumbnail at the
 * midpoint of the recording.
 */
export function buildThumbnailExtractCommand(
  hlsManifestUrl: string,
  outputUrl: string,
  durationHint: number,
): readonly string[] {
  // Seek to 50% with -ss BEFORE -i for fast seek (keyframe-based).
  // Use additional -ss after -i for fine adjustment.
  const midpoint = Math.max(2, Math.floor(durationHint / 2));
  return Object.freeze([
    '-ss', String(midpoint),
    '-i', hlsManifestUrl,
    '-vframes', '1',
    '-vf', 'scale=1280:-2',
    '-q:v', '2',
    '-f', 'image2',
    outputUrl,
  ]);
}

/**
 * Compose auto-chapter markers from a list of chat highlights.
 * Adjacent markers (within 90s of each other) are merged so we don't
 * create a chapter per message burst.
 */
export function buildAutoChapters(
  highlights: readonly { ts: number; reason: string }[],
  totalDurationSeconds: number,
): readonly AutoChapter[] {
  if (highlights.length === 0) return Object.freeze([]);
  // Merge adjacent highlights.
  const sorted = [...highlights].sort((a, b) => a.ts - b.ts);
  const merged: { ts: number; reason: string; count: number }[] = [];
  for (const h of sorted) {
    const prev = merged[merged.length - 1];
    if (prev && h.ts - prev.ts < 90_000) {
      prev.count += 1;
      prev.ts = Math.floor((prev.ts + h.ts) / 2);
    } else {
      merged.push({ ts: h.ts, reason: h.reason, count: 1 });
    }
  }
  const chapters: AutoChapter[] = merged.map((m, idx) => ({
    id: `ch-${idx}-${m.ts}`,
    title:
      m.count > 1
        ? `Momento marcante (${m.count}×)`
        : 'Momento marcante',
    offset: Math.floor(m.ts / 1000),
    auto: true as const,
    reason: m.reason,
  }));
  // Ensure first chapter at 0s and last at duration.
  if (!chapters.length || chapters[0]!.offset > 0) {
    chapters.unshift({
      id: `ch-0-intro`,
      title: 'Abertura',
      offset: 0,
      auto: true,
    });
  }
  if (chapters[chapters.length - 1]!.offset < totalDurationSeconds - 10) {
    chapters.push({
      id: `ch-${chapters.length}-close`,
      title: 'Encerramento',
      offset: totalDurationSeconds,
      auto: true,
    });
  }
  return Object.freeze(chapters);
}

/**
 * LGPD deletion handler — scrub a viewer's chat/Q&A messages from the
 * recorded VOD chapter metadata and the chat archive.
 *
 * Per LGPD Art. 18, V (elimination) — the user has the right to demand
 * removal of their own personal data. We must scrub:
 *   • Chat messages with their handle
 *   • Q&A questions with their handle
 *   • Reactions (handle replaced with "Anônimo")
 *
 * Note: the VOD video itself is NOT scrubbed (it's the host's IP).
 */
export interface LgpdScrubRequest {
  readonly userId: string;
  readonly eventId: string;
  readonly scope: 'chat' | 'qa' | 'reactions' | 'all';
  readonly reason?: string;
}

export interface LgpdScrubResult {
  readonly scrubbedMessages: number;
  readonly scrubbedReactions: number;
  readonly scrubbedQa: number;
  readonly recordedAt: string;
}

export function buildScrubResult(): LgpdScrubResult {
  return Object.freeze({
    scrubbedMessages: 0,
    scrubbedReactions: 0,
    scrubbedQa: 0,
    recordedAt: new Date().toISOString(),
  });
}

/** Default thumbnail dimensions — used in <Library> cards. */
export const THUMBNAIL_WIDTH = 1280;
export const THUMBNAIL_HEIGHT = 720;
/** Minimum recording duration to be eligible for library publish. */
export const MIN_PUBLISH_DURATION_S = 120;
