// @ts-nocheck
 
// meji-ogbe-data.ts — Meji-Ogbe divination data (16 Principal Odu of Obeche/Ifa)

export interface MejiOgbeOdu {
  id: string;
  name: string;
  portugueseName: string;
  order: number;
  polarity: 'masculine' | 'feminine';
  element: string;
  planets: string[];
  sephirot: string[];
  sign: string;
  dayOfWeek: string;
  direction: string;
  colors: string[];
  offerings: string[];
  ebos: string[];
  taboos: string[];
  strengths: string[];
  weaknesses: string[];
  health: string[];
  meanings: string[];
  ifaMessage: string;
}

const MEJI_OGBE_DATA: MejiOgbeOdu[] = [
  {
    id: 'ogbe',
    name: 'Ogbe',
    portugueseName: 'Ogbe',
    order: 1,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Chokmah', 'Hod'],
    sign: 'Aries',
    dayOfWeek: 'Domingo',
    direction: 'Leste',
    colors: ['Vermelho', 'Amarelo'],
    offerings: ['Melk', 'Palmeira', 'Frutos do mar'],
    ebos: ['Ebo de dinheiro', 'Ebo de saúde'],
    taboos: ['Não matar sapo', 'Não mentir'],
    strengths: ['Vitória garantida', 'Iniciativa', 'Coragem'],
    weaknesses: ['Impaciência', 'Gula'],
    health: ['Coração', 'Cabeça'],
    meanings: ['Criação', 'Início', 'Abundância', 'Força vital'],
    ifaMessage: 'Ogbe divide a água em dois, representando o poder de criar através da oposição.',
  },
  {
    id: 'oyen',
    name: 'Oyen',
    portugueseName: 'Oyen',
    order: 2,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Binah', 'Yesod'],
    sign: 'Câncer',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Branco', 'Azul claro'],
    offerings: ['Farinha de mandioca', 'Água de coco', 'Flores brancas'],
    ebos: ['Ebo de paz', 'Ebo de longevidade'],
    taboos: ['Não consumir sal em excesso', 'Não derramar sangue'],
    strengths: ['Sabedoria', 'Paciência', 'Intuição profunda'],
    weaknesses: ['Melancolia', 'Excesso de sensibilidade'],
    health: ['Estômago', 'Útero'],
    meanings: ['Conhecimento', 'Sabedoria', 'Mistério', 'Profundidade'],
    ifaMessage: 'Oyen abre o livro da sabedoria, revelando segredos ocultos.',
  },
  {
    id: 'ogunda',
    name: 'Ogunda',
    portugueseName: 'Ogunda',
    order: 3,
    polarity: 'masculine',
    element: 'Metal',
    planets: ['Mercúrio', 'Saturno'],
    sephirot: ['Hod', 'Gevurah'],
    sign: 'Gêmeos',
    dayOfWeek: 'Quarta-feira',
    direction: 'Norte',
    colors: ['Amarelo', 'Laranja'],
    offerings: ['Cobre', 'Ferro', 'Milho'],
    ebos: ['Ebo de proteção', 'Ebo de comunicação'],
    taboos: ['Não usar armas', 'Não cortar árvores'],
    strengths: ['Comunicação', 'Inteligência', 'Versatilidade'],
    weaknesses: ['Inconstância', 'Nervosismo'],
    health: ['Pulmões', 'Mãos'],
    meanings: ['Ferramentas', 'Comunicação', 'Destino', 'Caminhos'],
    ifaMessage: 'Ogunda revela os caminhos e destinos disponíveis ao consulente.',
  },
  {
    id: 'oshe',
    name: 'Oshe',
    portugueseName: 'Oshe',
    order: 4,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Vênus', 'Terra'],
    sephirot: ['Netzach', 'Malkuth'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Mel', 'Frutas maduras', 'Vinho doce'],
    ebos: ['Ebo de amor', 'Ebo de fertilidade'],
    taboos: ['Não ser infiel', 'Não comer sozinho'],
    strengths: ['Amor', 'Beleza', 'Abundância', 'Prazer'],
    weaknesses: ['Vaidade', 'Preguiça'],
    health: ['Garganta', 'Rins'],
    meanings: ['Amor', 'Prazer', 'Fertilidade', 'Beleza'],
    ifaMessage: 'Oshe representa o amor e a alegria de viver, trazendo欢乐 e prosperidade.',
  },
  {
    id: 'ika',
    name: 'Ika',
    portugueseName: 'Ika',
    order: 5,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Gevurah', 'Hod'],
    sign: 'Escorpião',
    dayOfWeek: 'Terça-feira',
    direction: 'Sudeste',
    colors: ['Vermelho escuro', 'Roxo'],
    offerings: ['Pimenta', 'Akp', 'Sangue de galinha'],
    ebos: ['Ebo de transformação', 'Ebo de justiça'],
    taboos: ['Não guardar rancor', 'Não usar veneno'],
    strengths: ['Transformação', 'Regeneração', 'Poder'],
    weaknesses: ['Vingança', 'Obsessão'],
    health: ['Órgãos sexuais', 'Coluna'],
    meanings: ['Mistério', 'Transformação', 'Regeneração', 'Magia'],
    ifaMessage: 'Ika abre os portais do mundo espiritual, revelando poderes ocultos.',
  },
  {
    id: 'obua',
    name: 'Obua',
    portugueseName: 'Obua',
    order: 6,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Lua', 'Vênus'],
    sephirot: ['Yesod', 'Netzach'],
    sign: 'Libra',
    dayOfWeek: 'Domingo',
    direction: 'Oeste',
    colors: ['Azul', 'Prata'],
    offerings: ['Água', 'Perfume', 'Sândalo'],
    ebos: ['Ebo de reconciliação', 'Ebo de justiça'],
    taboos: ['Não fraudar', 'Não ser hipócrita'],
    strengths: ['Equilíbrio', 'Justiça', 'Diplomacia'],
    weaknesses: ['Indecisão', 'Superficialidade'],
    health: ['Intestinos', 'Bexiga'],
    meanings: ['Equilíbrio', 'Justiça', 'Harmonia', 'Lei'],
    ifaMessage: 'Obua pesa o coração do consulente, buscando equilíbrio entre luz e sombra.',
  },
  {
    id: 'oron',
    name: 'Oron',
    portugueseName: 'Oron',
    order: 7,
    polarity: 'masculine',
    element: 'Wood',
    planets: ['Júpiter', 'Sol'],
    sephirot: ['Chesed', 'Tiphereth'],
    sign: 'Sagitário',
    dayOfWeek: 'Quinta-feira',
    direction: 'Noroeste',
    colors: ['Azul royal', 'Dourado'],
    offerings: ['Cravo', 'Incienso', 'Frango'],
    ebos: ['Ebo de prosperidade', 'Ebo de sabedoria'],
    taboos: ['Não explorar os pobres', 'Não recusar客人'],
    strengths: ['Filosofia', 'Abundância', 'Generosidade'],
    weaknesses: ['Excesso de confiança', 'Imprudência'],
    health: ['Fígado', 'Coxas'],
    meanings: ['Sorte', 'Filosofia', 'Abundância', 'Generosidade'],
    ifaMessage: 'Oron traz a bênção do céu,prometendo prosperidade e boa sorte.',
  },
  {
    id: 'odi',
    name: 'Odi',
    portugueseName: 'Odi',
    order: 8,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Marte'],
    sephirot: ['Tiphereth', 'Gevurah'],
    sign: 'Leão',
    dayOfWeek: 'Domingo',
    direction: 'Norte',
    colors: ['Dourado', 'Laranja'],
    offerings: ['Mel', 'Ouro', 'Coroa'],
    ebos: ['Ebo de realeza', 'Ebo de poder'],
    taboos: ['Não ser covarde', 'Não desonrar a família'],
    strengths: ['Liderança', 'Coragem', 'Nobreza'],
    weaknesses: ['Orgulho', 'Tirania'],
    health: ['Coração', 'Olhos'],
    meanings: ['Realeza', 'Poder', 'Honra', 'Luz'],
    ifaMessage: 'Odi ilumina como o sol, trazendo poder real e光彩.',
  },
  {
    id: 'ire',
    name: 'Ire',
    portugueseName: 'Ire',
    order: 9,
    polarity: 'feminine',
    element: 'Water',
    planets: ['Vênus', 'Lua'],
    sephirot: ['Netzach', 'Hod'],
    sign: 'Touro',
    dayOfWeek: 'Sexta-feira',
    direction: 'Sul',
    colors: ['Verde', 'Rosa'],
    offerings: ['Frutas', 'Mel', 'Vinho'],
    ebos: ['Ebo de paz', 'Ebo de bênção'],
    taboos: ['Não falar mal', 'Não ser ingrato'],
    strengths: ['Paz', 'Bênção', 'Gratidão'],
    weaknesses: ['Suscetibilidade', 'Dependência'],
    health: ['Pescoço', 'Garganta'],
    meanings: ['Bênção', 'Paz', 'Gratidão', 'Harmonia'],
    ifaMessage: 'Ire traz paz e bênçãos,mas requer gratidão e humildade.',
  },
  {
    id: 'oshi',
    name: 'Oshi',
    portugueseName: 'Oshi',
    order: 10,
    polarity: 'masculine',
    element: 'Earth',
    planets: ['Saturno', 'Marte'],
    sephirot: ['Gevurah', 'Malkuth'],
    sign: 'Capricórnio',
    dayOfWeek: 'Sábado',
    direction: 'Sul',
    colors: ['Preto', 'Marrom'],
    offerings: ['Cachorro', 'Eti', 'Pimenta'],
    ebos: ['Ebo de proteção', 'Ebo de guerra'],
    taboos: ['Não abandonar', 'Não ser traidor'],
    strengths: ['Lealdade', 'Disciplina', 'Proteção'],
    weaknesses: ['Rigidez', 'Crueldade'],
    health: ['Ossos', 'Joelhos'],
    meanings: ['Força', 'Proteção', 'Guerra', 'Disciplina'],
    ifaMessage: 'Oshi representa a disciplina de ferro e a lealdade inabalável.',
  },
  {
    id: 'ikana',
    name: 'Ikana',
    portugueseName: 'Ikana',
    order: 11,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Saturno', 'Netuno'],
    sephirot: ['Binah', 'Hod'],
    sign: 'Aquário',
    dayOfWeek: 'Sábado',
    direction: 'Leste',
    colors: ['Azul escuro', 'Prata'],
    offerings: ['Água salgada', 'Carvão', 'Cera'],
    ebos: ['Ebo de encerramento', 'Ebo de mistério'],
    taboos: ['Não revelar segredos', 'Não desobedecer'],
    strengths: ['Mistério', 'Conhecimento oculto', 'Poder ancestral'],
    weaknesses: ['Prisão', 'Segredos perigosos'],
    health: ['Cérebro', 'Sistema nervoso'],
    meanings: ['Prisão', 'Mistério', 'Segredo', 'Cativeiro'],
    ifaMessage: 'Ikana revela prisões espirituais e os segredos que as prendem.',
  },
  {
    id: 'ma',
    name: 'Ma',
    portugueseName: 'Ma',
    order: 12,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Marte', 'Plutão'],
    sephirot: ['Gevurah', 'Chokmah'],
    sign: 'Áries',
    dayOfWeek: 'Terça-feira',
    direction: 'Nordeste',
    colors: ['Vermelho', 'Escarlate'],
    offerings: ['Sangue', 'Pimenta', 'Armas'],
    ebos: ['Ebo de guerra', 'Ebo de conquista'],
    taboos: ['Não recuar', 'Não temer'],
    strengths: ['Conquista', 'Vitória militar', 'Bravura'],
    weaknesses: ['Agressividade', 'Imprudência'],
    health: ['Cabeça', 'Nariz'],
    meanings: ['Guerra', 'Conquista', 'Vitória', 'Batalha'],
    ifaMessage: 'Ma canta o hino da batalha,prometendo vitória aos valentes.',
  },
  {
    id: 'ton',
    name: 'Ton',
    portugueseName: 'Ton',
    order: 13,
    polarity: 'masculine',
    element: 'Water',
    planets: ['Lua', 'Netuno'],
    sephirot: ['Yesod', 'Binah'],
    sign: 'Peixes',
    dayOfWeek: 'Segunda-feira',
    direction: 'Oeste',
    colors: ['Azul', 'Ciano'],
    offerings: ['Água do mar', 'Peixes', 'Sal'],
    ebos: ['Ebo de limpeza', 'Ebo de purificação'],
    taboos: ['Não poluir', 'Não mentir na água'],
    strengths: ['Purificação', 'Movimento', 'Adaptação'],
    weaknesses: ['Inundação', 'Afogamento'],
    health: ['Pés', 'Sistema imunológico'],
    meanings: ['Água', 'Movimento', 'Purificação', 'Mudança'],
    ifaMessage: 'Ton flui como água, lavando impurezas e trazendo renovação.',
  },
  {
    id: 'luon',
    name: 'Luon',
    portugueseName: 'Luon',
    order: 14,
    polarity: 'feminine',
    element: 'Earth',
    planets: ['Terra', 'Vênus'],
    sephirot: ['Malkuth', 'Netzach'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Centro',
    colors: ['Marrom', 'Verde escuro'],
    offerings: ['Raízes', 'Terra', 'Melão'],
    ebos: ['Ebo de terra', 'Ebo de fundamento'],
    taboos: ['Não desrespeitar a terra', 'Não waste food'],
    strengths: ['Fundamento', 'Praticidade', 'Conexão terrena'],
    weaknesses: ['Materialismo', 'Escassez'],
    health: ['Intestinos', 'Pele'],
    meanings: ['Terra', 'Pobreza', 'Trabalho', 'Realidade'],
    ifaMessage: 'Luon ensina que a verdadeira riqueza está no trabalho honesto da terra.',
  },
  {
    id: 'kun',
    name: 'Kun',
    portugueseName: 'Kun',
    order: 15,
    polarity: 'masculine',
    element: 'Fire',
    planets: ['Sol', 'Júpiter'],
    sephirot: ['Chokmah', 'Tiphereth'],
    sign: ' Leão',
    dayOfWeek: 'Domingo',
    direction: 'Norte',
    colors: ['Dourado', 'Amarelo'],
    offerings: ['Mel', 'Frango assado', 'Coroa de flores'],
    ebos: ['Ebo de alegria', 'Ebo de recebimento'],
    taboos: ['Não recusar presente', 'Não ser mesquinho'],
    strengths: ['Felicidade', 'Recebimento', 'Celebração'],
    weaknesses: ['Excesso', 'Superficialidade'],
    health: ['Coração', 'Estômago'],
    meanings: ['Alegria', 'Presente', 'Celebração', 'Recebimento'],
    ifaMessage: 'Kun traz alegria e boas novas,prometendo presentes e felicidade.',
  },
  {
    id: 'tuo',
    name: 'Tuo',
    portugueseName: 'Tuo',
    order: 16,
    polarity: 'feminine',
    element: 'Air',
    planets: ['Mercúrio', 'Lua'],
    sephirot: ['Hod', 'Yesod'],
    sign: 'Virgem',
    dayOfWeek: 'Quarta-feira',
    direction: 'Sul',
    colors: ['Cinza', 'Branco'],
    offerings: ['Farinha', 'Água', 'Ovelha branca'],
    ebos: ['Ebo de morte', 'Ebo de fim'],
    taboos: ['Não celebrar morte', 'Não tocar defuntos'],
    strengths: ['Transição', 'Finalização', 'Libertação'],
    weaknesses: ['Morte', 'Perda', 'Tristeza'],
    health: ['Pulmões', 'Sistema respiratório'],
    meanings: ['Morte', 'Fim', 'Transição', 'Libertação'],
    ifaMessage: 'Tuo encerra ciclos, traz fim necessário para novo começo.',
  },
];

export function getData(): MejiOgbeOdu[] {
  return MEJI_OGBE_DATA;
}
