/**
 * ════════════════════════════════════════════════════════════════════════════
 * COMMUNITY CIRCLES — index.ts (public surface)
 * ════════════════════════════════════════════════════════════════════════════
 *
 * Single entry-point for the community-circles engine family.
 * Re-exports the four engines so callers can `import { ... } from "@/lib/community-circles"`.
 *
 * Engines:
 *   - circles.ts    — circle CRUD, dissolution, audit
 *   - membership.ts — join/leave/roles/ban
 *   - feed.ts       — posts/comments/reactions/reports
 *   - governance.ts — rules/votes/flags/dissolution-vote/audit
 * ════════════════════════════════════════════════════════════════════════════
 */

// circles.ts
export {
  // Branded
  type UserId,
  type CircleId,
  type Timestamp,
  toUserId,
  toCircleId,
  toTimestamp,
  asUserId,
  asCircleId,
  // Tradition
  TRADITIONS_VALUES,
  TRADITIONS,
  isTradition,
  // Theme
  CIRCLE_THEMES_VALUES,
  CIRCLE_THEMES,
  isCircleTheme,
  THEME_TRADITION,
  type Locale,
  LOCALES,
  THEME_NAME,
  getThemeName,
  // Rule + Circle types
  type RuleSeverity,
  type RuleEnforcement,
  type Rule,
  type CircleStatus,
  type Circle,
  type CreateCircleConfig,
  type UpdateCirclePatch,
  type ListCirclesFilters,
  // Errors
  CircleNotFoundError,
  CircleValidationError,
  CircleForbiddenError,
  CircleFullError,
  CircleInvalidStateError,
  // Storage
  __resetCircleStore,
  // Core ops
  createCircle,
  getCircle,
  listCircles,
  listCirclesByMember,
  updateCircle,
  dissolveCircle,
  searchCirclesByTheme,
  assertCircleNotFull,
  __recordMemberAdded,
  __recordMemberRemoved,
  // Audit
  auditCircles,
  auditTraditionBreakdown,
  auditThemeCoverage,
  // HMAC
  setHmacSecret,
} from './circles.ts';

// membership.ts
export {
  type MemberId,
  asMemberId,
  toMemberId,
  ROLES_VALUES,
  ROLES,
  type Role,
  isRole,
  type Member,
  type ListMembersFilters,
  type JoinOptions,
  MembershipValidationError,
  MembershipNotFoundError,
  NotMemberError,
  AlreadyMemberError,
  BannedMemberError,
  __resetMembershipStore,
  setMembershipHmacSecret,
  findActiveMembership,
  joinCircle,
  leaveCircle,
  getMember,
  listMembers,
  promoteToAdmin,
  demoteAdmin,
  banMember,
  unbanMember,
  getMemberCount,
  listForUser,
  assertMemberCanPost,
  auditMembershipBreakdown,
} from './membership.ts';

// feed.ts
export {
  type PostId,
  type CommentId,
  type ReactionId,
  type ReportId,
  asPostId,
  asCommentId,
  asReactionId,
  asReportId,
  REACTION_EMOJI,
  type ReactionEmoji,
  isReactionEmoji,
  type Reaction,
  type SacredRef,
  type Post,
  type Comment,
  type PaginatedPosts,
  REPORT_REASONS,
  type ReportReason,
  isReportReason,
  type ReportContentType,
  type Report,
  type CreatePostOptions,
  type FeedFilters,
  FeedValidationError,
  PostNotFoundError,
  CommentNotFoundError,
  __resetFeedStore,
  setFeedHmacSecret,
  createPost,
  getPost,
  getCircleFeed,
  commentOnPost,
  pinPost,
  unpinPost,
  deletePost,
  reportPost,
  reportComment,
  getReport,
  reactToPost,
  unreactToPost,
  getPostReactions,
  getCommentsByPost,
  getCrossTraditionAudit,
  auditFeedByTradition,
  auditCrossTradition,
  auditReportedPosts,
} from './feed.ts';

// governance.ts
export {
  type VoteId,
  type ProposalId,
  type FlagId,
  type ResolutionId,
  asVoteId,
  asProposalId,
  asFlagId,
  asResolutionId,
  type RuleTemplateName,
  RULE_TEMPLATE_NAMES,
  RULES_TEMPLATES,
  resolveRuleTemplate,
  type ProposalType,
  PROPOSAL_KINDS,
  type VoteChoice,
  VOTE_CHOICES,
  isVoteChoice,
  type VoteStatus,
  type Vote,
  type VoteResult,
  type MemberAction,
  type PostAction,
  type AuditReport,
  RESOLUTION_ACTIONS,
  type ResolutionAction,
  type FlagStatus,
  type Flag,
  type Resolution,
  type GovernanceHealth,
  GovernanceValidationError,
  VoteNotFoundError,
  FlagNotFoundError,
  __resetGovernanceStore,
  setGovernanceHmacSecret,
  setCircleRules,
  applyRuleTemplate,
  proposeVote,
  castVote,
  tallyVote,
  getVote,
  listVotes,
  flagContent,
  resolveFlag,
  getFlag,
  listFlags,
  auditCircle,
  assertGovernanceHealthy,
  auditOpenFlags,
  auditPendingVotes,
  getBanOverrides,
  __attachFeedState,
} from './governance.ts';
