// Marma point data for Ayurvedic energy points
 
// @ts-nocheck

export interface MarmaPoint {
  id: string;
  name: string;
  nameSanskrit: string;
  location: string;
  region: string;
  category: string;
  subcategory: string;
  dosha: string[];
  effect: string;
  treatment: string;
  contraindications: string[];
  description: string;
  energeticLevel: number; // 1-7 (subtle to gross)
  triggerPoints?: string[];
}

const marmaPoints: MarmaPoint[] = [
  // HEAD & NECK REGION (10 points)
  {
    id: "marma-h1",
    name: "Adhipati",
    nameSanskrit: "अधिपति",
    location: "Crown of the head, topmost point",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Shringataka",
    dosha: ["Vata", "Pitta", "Kapha"],
    effect: "Supreme consciousness, spiritual awakening, prana access",
    treatment: "Nasya, shiroabhyanga, crown chakra work",
    contraindications: ["Severe head injury", "Acute fever"],
    description: "The king of all marma points. Located at the crown, it is the seat of divine consciousness and gateway to higher states of awareness.",
    energeticLevel: 7,
    triggerPoints: ["Sahasrara"]
  },
  {
    id: "marma-h2",
    name: "Shivagrathi",
    nameSanskrit: "शिवाग्रथि",
    location: "Forehead center, just above the eyebrows",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Shringataka",
    dosha: ["Vata", "Pitta"],
    effect: "Third eye activation, intuition, wisdom",
    treatment: "Ajna chakra meditation, third eye oiling",
    contraindications: [],
    description: "The knot of Shiva. Gateway to inner vision and spiritual insight.",
    energeticLevel: 7,
    triggerPoints: ["Ajna"]
  },
  {
    id: "marma-h3",
    name: "Hrudaya",
    nameSanskrit: "हृदय",
    location: "Cardiac region, center of chest",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Hrudaya",
    dosha: ["Kapha", "Pitta"],
    effect: "Heart function, emotional balance, love",
    treatment: "Hrudaya basti, hridaya marma massage",
    contraindications: ["Acute cardiac conditions"],
    description: "The heart marma. Governs emotional heart and physical heart function.",
    energeticLevel: 6,
    triggerPoints: ["Anahata"]
  },
  {
    id: "marma-h4",
    name: "Phana",
    nameSanskrit: "फण",
    location: "Sides of the nostrils",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Apanga",
    dosha: ["Kapha", "Vata"],
    effect: "Sinuses, sense of smell, prana intake",
    treatment: "Nasya, pranayama, netra karma",
    contraindications: [],
    description: "Nasal marma governing respiratory health and smell perception.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-h5",
    name: "Apanga",
    nameSanskrit: "अपाङ्ग",
    location: "Outer corners of the eyes",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Apanga",
    dosha: ["Pitta", "Vata"],
    effect: "Vision, eye health, liver connection",
    treatment: "Netra tarpana, akshi tarpana",
    contraindications: ["Eye infections"],
    description: "Eye corner marma related to vision and liver function.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-h6",
    name: "Nasa",
    nameSanskrit: "नासा",
    location: "Nose tip",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Apanga",
    dosha: ["Kapha", "Vata"],
    effect: "Respiration, smell, prana",
    treatment: "Nasya, anjana",
    contraindications: ["Nasal injury"],
    description: "Tip of the nose, entrance for prana and seat of Kapha.",
    energeticLevel: 2,
    triggerPoints: []
  },
  {
    id: "marma-h7",
    name: "Gala",
    nameSanskrit: "गल",
    location: "Throat region, base of throat",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Kantha",
    dosha: ["Vata", "Kapha"],
    effect: "Voice, throat health, communication",
    treatment: "Gargling, throat massage, kavala",
    contraindications: [],
    description: "Throat marma governing voice, speech, and swallowing.",
    energeticLevel: 4,
    triggerPoints: ["Vishuddha"]
  },
  {
    id: "marma-h8",
    name: "Matrika",
    nameSanskrit: "मातृका",
    location: "Four points below ears, neck sides",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Kantha",
    dosha: ["Vata"],
    effect: "Lymphatic drainage, immunity, feminine energy",
    treatment: "Neck massage, galashodhana",
    contraindications: [],
    description: "Four mother points governing lymphatic system and maternal energy.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-h9",
    name: "Krikatika",
    nameSanskrit: "कृकाटिक",
    location: "Atlanto-occipital junction, base of skull",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Kantha",
    dosha: ["Vata"],
    effect: "Cervical spine, head stability, life force",
    treatment: "Greeva basti, neck oiling",
    contraindications: ["Cervical fracture"],
    description: "Joint of skull and spine. Critical for prana flow and head movement.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-h10",
    name: "Vidhura",
    nameSanskrit: "विधुर",
    location: "Behind the ears, mastoid region",
    region: "head",
    category: "Urdhva (Upper)",
    subcategory: "Apanga",
    dosha: ["Vata", "Pitta"],
    effect: "Hearing, ear health, balance",
    treatment: "Karnapoorana, ear oiling",
    contraindications: ["Ear infection"],
    description: "Behind ear marma governing hearing and equilibrium.",
    energeticLevel: 3,
    triggerPoints: []
  },

  // UPPER LIMB REGION (12 points)
  {
    id: "marma-u1",
    name: "Talahridaya",
    nameSanskrit: "तलहृदय",
    location: "Center of the palm",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Palm",
    dosha: ["Kapha", "Vata"],
    effect: "Hand function, circulation, energy reception",
    treatment: "Abhyanga, palm massage",
    contraindications: [],
    description: "Heart of the palm. Important for receiving and channeling energy.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-u2",
    name: "Kurca",
    nameSanskrit: "कूर्च",
    location: "Root of thumb",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Palm",
    dosha: ["Vata", "Kapha"],
    effect: "Grip strength, thumb function, will power",
    treatment: "Thumb massage, mudra practice",
    contraindications: [],
    description: "The brush. Root of the thumb governing grasping and will.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-u3",
    name: "Kurca-shira",
    nameSanskrit: "कूर्चशीर्ष",
    location: "Tips of fingers",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Palm",
    dosha: ["Vata"],
    effect: "Sensory perception, fine motor skills",
    treatment: "Finger massage, reflexology",
    contraindications: [],
    description: "Tips of fingers. Highly sensitive marma points for sensory reception.",
    energeticLevel: 2,
    triggerPoints: []
  },
  {
    id: "marma-u4",
    name: "Manibandha",
    nameSanskrit: "मणिबन्ध",
    location: "Wrist joint",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Wrist",
    dosha: ["Vata"],
    effect: "Wrist mobility, circulation to hands",
    treatment: "Wrist oiling, bandaging",
    contraindications: ["Fracture"],
    description: "Wrist marma governing all hand movements and circulation.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-u5",
    name: "Indrabasti",
    nameSanskrit: "इन्द्रबस्ति",
    location: "Outer forearm, midpoint",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Forearm",
    dosha: ["Vata", "Pitta"],
    effect: "Muscular strength, arm function",
    treatment: "Forearm massage, snehana",
    contraindications: [],
    description: "Muscle of Indra. Governs strength in the upper limbs.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-u6",
    name: "Kani",
    nameSanskrit: "काणी",
    location: "Elbow joint",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Elbow",
    dosha: ["Vata"],
    effect: "Elbow mobility, arm extension",
    treatment: "Elbow oleation, karma sanyama",
    contraindications: ["Elbow fracture"],
    description: "Elbow marma. Critical for arm bending and extension.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-u7",
    name: "Kroshtu",
    nameSanskrit: "क्रोष्ठु",
    location: "Behind the elbow",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Elbow",
    dosha: ["Vata"],
    effect: "Elbow extension, nerve flow",
    treatment: "Elbow massage, basti",
    contraindications: [],
    description: "Behind elbow marma. Important for nerve and prana flow.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-u8",
    name: "Amsa",
    nameSanskrit: "अंस",
    location: "Shoulder joint top",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Shoulder",
    dosha: ["Vata", "Kapha"],
    effect: "Shoulder mobility, arm raising",
    treatment: "Shoulder massage, phal shifting",
    contraindications: ["Shoulder dislocation"],
    description: "Shoulder marma. Junction of arm and trunk.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-u9",
    name: "Amsaphalaka",
    nameSanskrit: "अंसफलक",
    location: "Shoulder blade region",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Shoulder",
    dosha: ["Vata"],
    effect: "Shoulder stability, upper back",
    treatment: "Back massage,肩部调理",
    contraindications: [],
    description: "Shoulder blade marma. Governs upper back stability.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-u10",
    name: "Parsvasandhi",
    nameSanskrit: "पार्श्वसन्धि",
    location: "Axilla, armpit",
    region: "upper",
    category: "Bahu (Upper Limb)",
    subcategory: "Shoulder",
    dosha: ["Vata", "Kapha"],
    effect: "Lymphatic drainage, arm-heart connection",
    treatment: "Axillary massage, lymphatic drainage",
    contraindications: ["Axillary lymphadenopathy"],
    description: "Axillary marma. Junction of side and arm, lymphatic hub.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-u11",
    name: "Nabhi",
    nameSanskrit: "नाभि",
    location: "Navel center",
    region: "upper",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Pitta", "Kapha"],
    effect: "Digestion, energy distribution, karma",
    treatment: "Navel oiling, nadi suddhi",
    contraindications: [],
    description: "Navel marma. Center of prana distribution and karmic storehouse.",
    energeticLevel: 6,
    triggerPoints: ["Manipura"]
  },
  {
    id: "marma-u12",
    name: "Hridaya",
    nameSanskrit: "हृदय",
    location: "Left chest, cardiac region",
    region: "upper",
    category: "Urdhva (Upper)",
    subcategory: "Hrudaya",
    dosha: ["Kapha", "Pitta"],
    effect: "Heart function, circulation, love",
    treatment: "Hrudaya basti, cardiac care",
    contraindications: ["Acute MI"],
    description: "Heart center. Physical and emotional heart seat.",
    energeticLevel: 6,
    triggerPoints: ["Anahata"]
  },

  // LOWER LIMB REGION (16 points)
  {
    id: "marma-l1",
    name: "Talahridaya (Pada)",
    nameSanskrit: "तलहृदय(पाद)",
    location: "Center of sole",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Foot",
    dosha: ["Kapha", "Vata"],
    effect: "Foot health, grounding, energy reception",
    treatment: "Foot massage, pada abhyanga",
    contraindications: [],
    description: "Heart of the foot. Gateway for earth energy and grounding.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l2",
    name: "Kurca (Pada)",
    nameSanskrit: "कूर्च(पाद)",
    location: "Root of big toe",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Foot",
    dosha: ["Vata", "Kapha"],
    effect: "Big toe function, balance, will",
    treatment: "Toe massage, yoga",
    contraindications: [],
    description: "Root of big toe. Governs balance and walking direction.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-l3",
    name: "Kurca-shira (Pada)",
    nameSanskrit: "कूर्चशीर्ष(पाद)",
    location: "Tips of toes",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Foot",
    dosha: ["Vata"],
    effect: "Sensory perception, balance",
    treatment: "Foot reflexology, toe massage",
    contraindications: [],
    description: "Tips of toes. Fine sensory points for balance.",
    energeticLevel: 2,
    triggerPoints: []
  },
  {
    id: "marma-l4",
    name: "Gulpha",
    nameSanskrit: "गुल्फ",
    location: "Ankle joint",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Ankle",
    dosha: ["Vata"],
    effect: "Ankle mobility, gait, lower leg circulation",
    treatment: "Ankle oiling, snehana",
    contraindications: ["Ankle fracture"],
    description: "Ankle marma. Critical for walking and standing.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-l5",
    name: "Indrabasti (Pada)",
    nameSanskrit: "इन्द्रबस्ति(पाद)",
    location: "Outer calf, midpoint",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Calf",
    dosha: ["Vata", "Pitta"],
    effect: "Calf strength, lower leg function",
    treatment: "Calf massage, snehana",
    contraindications: [],
    description: "Muscular strength of lower leg.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l6",
    name: "Jangha",
    nameSanskrit: "जङ्घा",
    location: "Knee joint",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Knee",
    dosha: ["Vata", "Kapha"],
    effect: "Knee mobility, bending, weight bearing",
    treatment: "Knee basti, snehana",
    contraindications: ["Knee replacement"],
    description: "Knee marma. Critical joint for sitting and walking.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l7",
    name: "Kukundara",
    nameSanskrit: "कुकुण्डर",
    location: "Inner knee region",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Knee",
    dosha: ["Vata"],
    effect: "Knee stability, inner leg flow",
    treatment: "Knee massage",
    contraindications: [],
    description: "Inner knee marma. Important for leg energy channels.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l8",
    name: "Japha",
    nameSanskrit: "जङ्घा",
    location: "Behind the knee",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Knee",
    dosha: ["Vata"],
    effect: "Knee extension, hamstring flow",
    treatment: "Posterior knee massage",
    contraindications: ["Baker's cyst"],
    description: "Behind knee marma. Vital for leg straightening.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l9",
    name: "Ani",
    nameSanskrit: "अणि",
    location: "Upper thigh, quadriceps",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Thigh",
    dosha: ["Vata", "Kapha"],
    effect: "Thigh strength, sitting, leg power",
    treatment: "Thigh massage, snehana",
    contraindications: [],
    description: "Thigh muscle marma. Strong muscular point.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l10",
    name: "Urvi",
    nameSanskrit: "ऊर्वि",
    location: "Inner thigh, saphenous vein region",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Thigh",
    dosha: ["Pitta", "Vata"],
    effect: "Inner thigh, circulation, reproductive",
    treatment: "Inner thigh massage",
    contraindications: [],
    description: "Large vein marma. Important for circulation and reproductive energy.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-l11",
    name: "Vulva",
    nameSanskrit: "वङ्क",
    location: "Groin region",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Hip",
    dosha: ["Kapha", "Vata"],
    effect: "Hip mobility, groin health",
    treatment: "Hip massage, snehana",
    contraindications: ["Inguinal hernia"],
    description: "Groin marma. Junction of thigh and trunk.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-l12",
    name: "Kukutara",
    nameSanskrit: "कुकुटार",
    location: "Buttock region, near sacrum",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Hip",
    dosha: ["Vata"],
    effect: "Sitting, sacral stability, elimination",
    treatment: "Hip massage, basti",
    contraindications: [],
    description: "Cock's seat. Important for sitting and sacral health.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-l13",
    name: "Bahula",
    nameSanskrit: "बहुल",
    location: "Outer hip, greater trochanter",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Hip",
    dosha: ["Vata", "Kapha"],
    effect: "Hip joint, lateral movement",
    treatment: "Hip massage",
    contraindications: ["Hip fracture"],
    description: "Outer hip marma. Important for hip rotation.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l14",
    name: "Pani",
    nameSanskrit: "पाणि",
    location: "Hip socket region",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Hip",
    dosha: ["Vata"],
    effect: "Hip joint, weight bearing",
    treatment: "Hip oleation",
    contraindications: ["Hip replacement"],
    description: "Hip joint marma. Weight-bearing joint.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-l15",
    name: "Vituna",
    nameSanskrit: "वितुन",
    location: "Inner ankle",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Ankle",
    dosha: ["Pitta"],
    effect: "Inner ankle, liver connection",
    treatment: "Ankle massage",
    contraindications: [],
    description: "Inner ankle marma. Related to liver energy flow.",
    energeticLevel: 3,
    triggerPoints: []
  },
  {
    id: "marma-l16",
    name: "Avarta",
    nameSanskrit: "आवर्त",
    location: "Ankle twist point",
    region: "lower",
    category: "Saktha (Lower Limb)",
    subcategory: "Ankle",
    dosha: ["Vata"],
    effect: "Ankle rotation, flexibility",
    treatment: "Ankle rotation therapy",
    contraindications: ["Sprain acute"],
    description: "Swirl marma at ankle. Governs rotational flexibility.",
    energeticLevel: 3,
    triggerPoints: []
  },

  // TRUNK & ABDOMEN REGION (8 points)
  {
    id: "marma-t1",
    name: "Nabhi",
    nameSanskrit: "नाभि",
    location: "Center of navel",
    region: "trunk",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Pitta", "Kapha"],
    effect: "Digestive fire, energy distribution, prana",
    treatment: "Navel basti, nadi work",
    contraindications: [],
    description: "Navel center. Prana distribution point and digestive fire location.",
    energeticLevel: 6,
    triggerPoints: ["Manipura"]
  },
  {
    id: "marma-t2",
    name: "Hridaya",
    nameSanskrit: "हृदय",
    location: "Heart center, sternum",
    region: "trunk",
    category: "Urdhva (Upper)",
    subcategory: "Hrudaya",
    dosha: ["Kapha", "Pitta"],
    effect: "Heart, circulation, emotions",
    treatment: "Hrudaya basti, oiling",
    contraindications: ["Cardiac emergency"],
    description: "Heart marma. Seat of emotional and physical heart.",
    energeticLevel: 6,
    triggerPoints: ["Anahata"]
  },
  {
    id: "marma-t3",
    name: "Uro-granthi",
    nameSanskrit: "उरु-ग्रन्थि",
    location: "Above the heart, sternocostal region",
    region: "trunk",
    category: "Urdhva (Upper)",
    subcategory: "Uro",
    dosha: ["Kapha"],
    effect: "Chest, lungs, breast tissue",
    treatment: "Chest oiling, uro vasti",
    contraindications: [],
    description: "Chest knot. Governing chest and lung energy.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-t4",
    name: "Stana-mula",
    nameSanskrit: "स्थानमूल",
    location: "Base of breast, 4th intercostal space",
    region: "trunk",
    category: "Urdhva (Upper)",
    subcategory: "Uro",
    dosha: ["Kapha", "Pitta"],
    effect: "Breast health, chest circulation",
    treatment: "Breast massage, oiling",
    contraindications: ["Breast infection"],
    description: "Root of breast. Important for breast and chest health.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-t5",
    name: "Stana-randhra",
    nameSanskrit: "स्थानरन्ध्र",
    location: "Center of breast, nipple region",
    region: "trunk",
    category: "Urdhva (Upper)",
    subcategory: "Uro",
    dosha: ["Kapha"],
    effect: "Breast tissue, heart connection",
    treatment: "Gentle oiling",
    contraindications: ["Nipple infection"],
    description: "Hollow of breast. Heart of chest energy.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-t6",
    name: "Apalapa",
    nameSanskrit: "अपलाप",
    location: "Sides of chest, lateral thorax",
    region: "trunk",
    category: "Urdhva (Upper)",
    subcategory: "Uro",
    dosha: ["Vata", "Kapha"],
    effect: "Lateral chest, rib cage",
    treatment: "Side chest massage",
    contraindications: [],
    description: "Sides of chest. Important for intercostal muscles.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-t7",
    name: "Aparajita",
    nameSanskrit: "अपराजिता",
    location: "Right side of sternum, liver region",
    region: "trunk",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Pitta", "Kapha"],
    effect: "Liver, gallbladder, right side",
    treatment: "Right side oiling, liver care",
    contraindications: ["Liver acute"],
    description: "Unconquered. Liver and gallbladder marma.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-t8",
    name: "Kukshi",
    nameSanskrit: "कुक्षि",
    location: "Flanks, sides of abdomen",
    region: "trunk",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Vata", "Kapha"],
    effect: "Abdomen, intestines, digestion",
    treatment: "Abdominal massage",
    contraindications: [],
    description: "Flank marma. Important for intestinal health.",
    energeticLevel: 4,
    triggerPoints: []
  },

  // BACK REGION (10 points)
  {
    id: "marma-b1",
    name: "Vrikkau",
    nameSanskrit: "वृकौ",
    location: "Kidney region, flanks",
    region: "back",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Vata", "Kapha"],
    effect: "Kidney function, adrenal, water metabolism",
    treatment: "Kidney massage, basti",
    contraindications: ["Kidney acute"],
    description: "Twin kidneys. Governing water metabolism and adrenal function.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-b2",
    name: "Vamasadhya",
    nameSanskrit: "वामसाध्य",
    location: "Left kidney region",
    region: "back",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Kapha", "Vata"],
    effect: "Left kidney, spleen, left side",
    treatment: "Left flank care",
    contraindications: ["Kidney stone acute"],
    description: "Left kidney. Governing spleen and left side.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-b3",
    name: "Kati",
    nameSanskrit: "कटि",
    location: "Lower back, lumbar region",
    region: "back",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Vata"],
    effect: "Lower back, elimination, reproductive",
    treatment: "Kati basti, lumbar oiling",
    contraindications: ["Lumbar fracture"],
    description: "Waist marma. Governing lower back and elimination.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-b4",
    name: "Kukutara (Back)",
    nameSanskrit: "कुकुटार(पृष्ठ)",
    location: "Sacral region, sitting bone",
    region: "back",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Vata"],
    effect: "Sacrum, sitting, root chakra",
    treatment: "Sacral oiling, basti",
    contraindications: [],
    description: "Sacral marma. Root of sitting and sacral energy.",
    energeticLevel: 6,
    triggerPoints: ["Muladhara"]
  },
  {
    id: "marma-b5",
    name: "Pippalanda",
    nameSanskrit: "पिप्पलान्द",
    location: "Sacrococcygeal junction",
    region: "back",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Vata"],
    effect: "Coccyx, grounding, survival energy",
    treatment: "Sacrococcygeal oiling",
    contraindications: [],
    description: "Base of spine. Grounding and survival energy.",
    energeticLevel: 6,
    triggerPoints: ["Muladhara"]
  },
  {
    id: "marma-b6",
    name: "Krikatika (Back)",
    nameSanskrit: "कृकाटिक(पृष्ठ)",
    location: "Neck base, cervical thoracic junction",
    region: "back",
    category: "Urdhva (Upper)",
    subcategory: "Kantha",
    dosha: ["Vata"],
    effect: "Neck, head support, prana flow",
    treatment: "Cervical care, neck oiling",
    contraindications: ["Cervical injury"],
    description: "Posterior neck base. Critical for head support.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-b7",
    name: "Amsa (Back)",
    nameSanskrit: "अंस(पृष्ठ)",
    location: "Shoulder blade region",
    region: "back",
    category: "Bahu (Upper Limb)",
    subcategory: "Shoulder",
    dosha: ["Vata", "Kapha"],
    effect: "Shoulder blades, upper back",
    treatment: "Back massage",
    contraindications: [],
    description: "Shoulder blade marma. Upper back stability.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-b8",
    name: "Amsaphalaka",
    nameSanskrit: "अंसफलक",
    location: "Spine of scapula",
    region: "back",
    category: "Bahu (Upper Limb)",
    subcategory: "Shoulder",
    dosha: ["Vata"],
    effect: "Shoulder stability, posture",
    treatment: "Scapular massage",
    contraindications: [],
    description: "Shoulder blade spine. Governing posture.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-b9",
    name: "Parsva",
    nameSanskrit: "पार्श्व",
    location: "Sides of torso, flanks",
    region: "back",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Vata", "Pitta"],
    effect: "Lateral body, ribcage sides",
    treatment: "Flank massage",
    contraindications: [],
    description: "Side marma. Governing lateral body movement.",
    energeticLevel: 4,
    triggerPoints: []
  },
  {
    id: "marma-b10",
    name: "Nitamba",
    nameSanskrit: "नितम्ब",
    location: "Buttocks, gluteal region",
    region: "back",
    category: "Saktha (Lower Limb)",
    subcategory: "Hip",
    dosha: ["Kapha", "Vata"],
    effect: "Glutes, sitting, lower body strength",
    treatment: "Buttock massage",
    contraindications: [],
    description: "Buttock marma. Governing sitting and lower body strength.",
    energeticLevel: 4,
    triggerPoints: []
  },

  // SPECIAL MARMAS (4 points)
  {
    id: "marma-s1",
    name: "Sira-mula",
    nameSanskrit: "शीर्षमूल",
    location: "All 96 head marmas",
    region: "special",
    category: "Urdhva (Upper)",
    subcategory: "Shringataka",
    dosha: ["Vata", "Pitta", "Kapha"],
    effect: "All head marmas, total head energy",
    treatment: "Shiroabhyanga, shirobasti",
    contraindications: ["Acute head injury"],
    description: "Root of all head vessels. Collective head marma energy.",
    energeticLevel: 7,
    triggerPoints: []
  },
  {
    id: "marma-s2",
    name: "Dhamani",
    nameSanskrit: "धमनि",
    location: "Navel to heart",
    region: "special",
    category: "Madhya (Middle)",
    subcategory: "Kati",
    dosha: ["Pitta", "Vata"],
    effect: "Umbilical circulation, prana channel",
    treatment: "Nadi suddhi, navel work",
    contraindications: [],
    description: "Great vessels. Major prana channel from navel to heart.",
    energeticLevel: 6,
    triggerPoints: ["Manipura", "Anahata"]
  },
  {
    id: "marma-s3",
    name: "Utkshepa",
    nameSanskrit: "उत्क्षेप",
    location: "Armpits (bilateral)",
    region: "special",
    category: "Bahu (Upper Limb)",
    subcategory: "Shoulder",
    dosha: ["Kapha", "Vata"],
    effect: "Axillary lymph, arm raising, breath",
    treatment: "Axillary drainage, arm stretching",
    contraindications: ["Axillary pathology"],
    description: "Raising up. Axillary marma for breath and arm raising.",
    energeticLevel: 5,
    triggerPoints: []
  },
  {
    id: "marma-s4",
    name: "Manya",
    nameSanskrit: "मन्या",
    location: "Sides of neck",
    region: "special",
    category: "Urdhva (Upper)",
    subcategory: "Kantha",
    dosha: ["Vata"],
    effect: "Neck sides, carotid, head blood flow",
    treatment: "Neck massage, lateral neck care",
    contraindications: ["Carotid disease"],
    description: "Neck side marma. Blood flow to head and brain.",
    energeticLevel: 5,
    triggerPoints: []
  }
];

export function getData(): MarmaPoint[] {
  return marmaPoints;
}

export function getMarmaById(id: string): MarmaPoint | undefined {
  return marmaPoints.find(m => m.id === id);
}

export function getMarmasByRegion(region: string): MarmaPoint[] {
  return marmaPoints.filter(m => m.region === region);
}

export function getMarmasByDosha(dosha: string): MarmaPoint[] {
  return marmaPoints.filter(m => m.dosha.includes(dosha));
}

export function getMarmasByCategory(category: string): MarmaPoint[] {
  return marmaPoints.filter(m => m.category === category);
}
