// src/lib/food/sacred-food-data.ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Food } from './food-types'

// Foods associated with sacred traditions and spiritual practices
const sacredFoods: Food[] = [
  {
    id: 'honey',
    name: 'Mel',
    description: 'Alimento sagrado na tradição bíblica. Símbolo de sabedoria e abundância espiritual.',
    energy: 'yang',
    element: 'earth',
    sefirot: ['netzah', 'hod'],
    bodySystems: ['immune'],
    properties: ['sweet', 'nourishing', 'balancing'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
   禁食: 'Não comer mel e derivados durante privações extremas',
    rituals: ['Dìa de Ayuno', 'Purificação'],
    zodiacSigns: [],
    elements: ['earth'],
    chakras: [2, 4],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    origin: 'middleEast',
    category: 'sweetener',
    kosherLevel: 4,
    spiritualLevel: 5,
    healingProperties: ['anti-inflammatory', 'antioxidant', 'energizing'],
    biblicalReferences: ['Provérbios 24:13-14', 'Salmos 119:103'],
    meditationPairing: 'Conexão com a doçura da vida',
  },
  {
    id: 'bread',
    name: 'Pão',
    description: 'Alimento fundamental em tradições sagradas. Símbolo de sustento e vida.',
    energy: 'neutral',
    element: 'earth',
    sefirot: ['chesed', 'gevurah'],
    bodySystems: ['digestive'],
    properties: ['grounding', 'sustaining', 'basic'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
   禁食: 'Pão sem fermento (matzah) durante Pessach',
    rituals: ['Eucharistia', 'Shabbat', 'Refeições sagradas'],
    zodiacSigns: [],
    elements: ['earth', 'fire'],
    chakras: [1, 3],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    origin: 'ancientNearEast',
    category: 'grain',
    kosherLevel: 3,
    spiritualLevel: 5,
    healingProperties: ['energizing', 'sustaining', 'nutritious'],
    biblicalReferences: ['João 6:35', 'Salmos 104:14-15'],
    meditationPairing: 'Gratidão pelo sustento diário',
  },
  {
    id: 'olive-oil',
    name: 'Azeite',
    description: 'Luz líquida nas tradições sagradas. Símbolo de sabedoria, paz e unção divina.',
    energy: 'yang',
    element: 'fire',
    sefirot: ['chesed', 'tiferet'],
    bodySystems: ['nervous', 'cardiovascular'],
    properties: ['illuminating', 'healing', 'nourishing'],
    seasons: ['autumn', 'winter'],
   禁食: 'Usar apenas azeite de oliva extra virgem em contextos rituais',
    rituals: ['Unção', 'Chanuká', 'Bênção'],
    zodiacSigns: ['Touro', 'Libra'],
    elements: ['fire', 'water'],
    chakras: [4, 6],
    months: [10, 11, 12, 1],
    origin: 'mediterranean',
    category: 'oil',
    kosherLevel: 4,
    spiritualLevel: 5,
    healingProperties: ['anti-inflammatory', 'heart-healthy', 'brain-nourishing'],
    biblicalReferences: ['Êxodo 27:20', 'Salmos 23:5', 'Mateus 26:12'],
    meditationPairing: 'Iluminação interior',
  },
  {
    id: 'wine',
    name: 'Vinho',
    description: 'Sangue da terra nas tradições. Símbolo de alegria, comunhão e transformação.',
    energy: 'yang',
    element: 'water',
    sefirot: ['netzah', 'yesod'],
    bodySystems: ['cardiovascular', 'nervous'],
    properties: ['transforming', 'joyful', 'communing'],
    seasons: ['autumn', 'winter'],
   禁食: 'Moderação; vinho kosher para rituais judaicos',
    rituals: ['Kiddush', 'Santa Ceia', 'Celebrações'],
    zodiacSigns: ['Escorpião', 'Sagitário'],
    elements: ['water', 'earth'],
    chakras: [4, 5],
    months: [9, 10, 11, 12],
    origin: 'mediterranean',
    category: 'beverage',
    kosherLevel: 3,
    spiritualLevel: 4,
    healingProperties: ['antioxidant', 'cardiovascular', 'relaxing'],
    biblicalReferences: ['Gênesis 14:18', 'Salmos 104:15', 'João 2:1-11'],
    meditationPairing: 'Transformação e renovação',
  },
  {
    id: 'dates',
    name: 'Tâmaras',
    description: 'Fruto do deserto, sustentação na jornada espiritual. Símbolo de fertilidade e paz.',
    energy: 'yang',
    element: 'earth',
    sefirot: ['netzah', 'malchut'],
    bodySystems: ['digestive', 'reproductive'],
    properties: ['energizing', 'sweet', 'grounding'],
    seasons: ['autumn', 'winter'],
   禁食: 'Evitar em dietas de desintoxicação rigorosa',
    rituals: ['Ramadã (breakfast)', 'Sukkot'],
    zodiacSigns: ['Leão', 'Virgem'],
    elements: ['earth', 'fire'],
    chakras: [1, 2, 4],
    months: [9, 10, 11, 12, 1],
    origin: 'middleEast',
    category: 'fruit',
    kosherLevel: 4,
    spiritualLevel: 4,
    healingProperties: ['energizing', 'fiber-rich', 'mineral-rich'],
    biblicalReferences: ['Êxodo 25:15', 'Deuteronômio 8:8'],
    meditationPairing: 'Sustento na jornada espiritual',
  },
  {
    id: 'figs',
    name: 'Figos',
    description: 'Fruta antiga de conhecimento. Símbolo de sabedoria oculta e abundância.',
    energy: 'neutral',
    element: 'earth',
    sefirot: ['chochmah', 'binah'],
    bodySystems: ['digestive', 'cardiovascular'],
    properties: ['nourishing', 'sweet', 'moistening'],
    seasons: ['summer', 'autumn'],
   禁食: 'Restrição em jejuns prolongados',
    rituals: ['Sukkot', 'Oferendas'],
    zodiacSigns: ['Virgem', 'Touro'],
    elements: ['earth', 'water'],
    chakras: [2, 4],
    months: [7, 8, 9, 10],
    origin: 'mediterranean',
    category: 'fruit',
    kosherLevel: 4,
    spiritualLevel: 4,
    healingProperties: ['digestive-aid', 'bone-health', 'anti-oxidant'],
    biblicalReferences: ['Gênesis 3:7', 'Salmos 78:47'],
    meditationPairing: 'Sabedoria oculta e introspecção',
  },
  {
    id: 'pomegranate',
    name: 'Romã',
    description: 'Fruto dos mistérios. Símbolo de sabedoria divina e plenitude espiritual.',
    energy: 'yang',
    element: 'water',
    sefirot: ['chokhmah', 'daat'],
    bodySystems: ['reproductive', 'cardiovascular'],
    properties: ['mysterious', 'abundant', 'purifying'],
    seasons: ['autumn'],
   禁食: 'Sementes podem representar desafios em jejum rigoroso',
    rituals: ['Rosh Hashaná', 'Tu Bishvat', '祭典'],
    zodiacSigns: ['Escorpião', 'Sagitário'],
    elements: ['water', 'earth'],
    chakras: [2, 4, 6],
    months: [9, 10, 11],
    origin: 'middleEast',
    category: 'fruit',
    kosherLevel: 5,
    spiritualLevel: 5,
    healingProperties: ['anti-inflammatory', 'antioxidant', 'cardiovascular'],
    biblicalReferences: ['Êxodo 28:33-34', 'Cântico dos Cânticos 4:3', 'Salmos 148:13'],
    meditationPairing: 'Mistérios divinos e plenitude',
  },
  {
    id: 'water',
    name: 'Água',
    description: 'Essência da vida, purificação espiritual. Símbolo de pureza e renovação.',
    energy: 'yin',
    element: 'water',
    sefirot: ['chochmah', 'binah', 'chesed'],
    bodySystems: ['cellular', 'digestive', 'nervous'],
    properties: ['purifying', 'refreshing', 'life-sustaining'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
   禁食: 'Ayurveda: evitar água gelada durante digestão',
    rituals: ['Mikveh', 'Batismo', 'Ablução', 'Tea ceremony'],
    zodiacSigns: ['Câncer', 'Escorpião', 'Peixes'],
    elements: ['water'],
    chakras: [1, 2, 3, 4, 5, 6, 7],
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    origin: 'universal',
    category: 'beverage',
    kosherLevel: 5,
    spiritualLevel: 5,
    healingProperties: ['hydrating', 'purifying', 'life-sustaining'],
    biblicalReferences: ['Provérbios 17:22', 'Salmos 23:2', 'João 4:14', 'Apocalipse 22:1'],
    meditationPairing: 'Fluxo contínuo de consciência',
  },
  {
    id: 'unleavened-bread',
    name: 'Matzá',
    description: 'Pão da pressa e liberdade. Símbolo de purificação e saída da escravidão.',
    energy: 'neutral',
    element: 'fire',
    sefirot: ['gevurah', 'netzah'],
    bodySystems: ['digestive'],
    properties: ['simple', 'pure', 'transforming'],
    seasons: ['spring'],
   禁食: 'Obrigatório durante Pessach - nenhum pão com fermento',
    rituals: ['Pessach (Passover)', 'Seder'],
    zodiacSigns: ['Áries'],
    elements: ['fire', 'earth'],
    chakras: [1, 3],
    months: [3, 4],
    origin: 'ancientNearEast',
    category: 'grain',
    kosherLevel: 5,
    spiritualLevel: 5,
    healingProperties: ['easy-digesting', 'energizing', 'simple'],
    biblicalReferences: ['Êxodo 12:15-20', 'Deuteronômio 16:3'],
    meditationPairing: 'Libertação e pureza',
  },
  {
    id: 'manna',
    name: 'Maná',
    description: 'Alimento sobrenatural do deserto. Símbolo de dependência divina e sustento miraculoso.',
    energy: 'neutral',
    element: 'water',
    sefirot: ['chesed', 'netzah'],
    bodySystems: ['immune', 'digestive'],
    properties: ['miraculous', 'mysterious', 'daily'],
    seasons: ['spring', 'summer'],
    '禁食': 'Não pode ser guardado para o dia seguinte',
    rituals: ['Provisão diária', 'Confiança'],
    elements: ['water', 'fire'],
    chakras: [3, 4, 6],
    months: [3, 4, 5, 6],
    origin: 'desert',
    category: 'sacred-provision',
    kosherLevel: 5,
    spiritualLevel: 5,
    healingProperties: ['energizing', 'mysterious', 'life-sustaining'],
    biblicalReferences: ['Êxodo 16:4-35', 'Salmos 78:24-25', 'João 6:31-35'],
    meditationPairing: 'Confiança na provisão divina',
  },
]

export function getData(): Food[] {
  return sacredFoods
}