// ============================================================================
// FAQ DATA — Cabala dos Caminhos (Wave 36)
// ============================================================================
// 80+ entries cobrindo 8 macro-categorias. PT-BR primário, EN em <details>.
// Single source of truth: alimenta /help/faq (UI) + /api/help/faq (API).
//
// Categorias:
//   - conceito      (8)
//   - acesso-beta   (8)
//   - akasha-ia     (12)
//   - tradicoes     (15) — uma por tradição + símbolos
//   - marketplace   (10)
//   - mentorship    (8)
//   - eventos       (6)
//   - conta-lgpd    (8)
//   - seguranca     (6)
//   - beta-feedback (6)
//   - tecnico       (6)
//   - onboarding    (5)
//
// LGPD: FAQ items não contêm PII. IDs estáveis (slug) para analytics.
// ============================================================================

export type FaqCategory =
  | 'conceito'
  | 'acesso-beta'
  | 'akasha-ia'
  | 'tradicoes'
  | 'marketplace'
  | 'mentorship'
  | 'eventos'
  | 'conta-lgpd'
  | 'seguranca'
  | 'beta-feedback'
  | 'tecnico'
  | 'onboarding';

export interface FaqEntry {
  id: string;
  category: FaqCategory;
  question: string;
  answer: string;
  answerEn?: string;
  relatedTradition?: string;
  relatedSlugs?: string[];
  tags: string[];
  helpCount: number;        // votos positivos (popularity signal)
  notHelpCount: number;
  trending: boolean;
  updatedAt: string;        // ISO date
}

export const FAQ_CATEGORIES: Array<{
  slug: FaqCategory;
  label: string;
  description: string;
  icon: string;
}> = [
  { slug: 'conceito', label: 'Conceito & visão', description: 'O que é o Akasha Portal, missão e princípios.', icon: 'compass' },
  { slug: 'acesso-beta', label: 'Acesso & beta', description: 'Como entrar, vagas, fila de espera.', icon: 'key-round' },
  { slug: 'akasha-ia', label: 'Akasha IA', description: 'Como funciona, limites, exemplos de uso.', icon: 'sparkles' },
  { slug: 'tradicoes', label: 'Tradições & símbolos', description: 'Candomblé, Cabala, Ifá, Tantra, Meditação, Xamanismo, Umbanda.', icon: 'leaf' },
  { slug: 'marketplace', label: 'Marketplace', description: 'Practitioners, escrow, reviews, pagamentos.', icon: 'store' },
  { slug: 'mentorship', label: 'Mentorship', description: 'Como aplicar, matching, sessões e segurança.', icon: 'users-round' },
  { slug: 'eventos', label: 'Eventos & lives', description: 'RSVP, transmissões, gravações.', icon: 'calendar' },
  { slug: 'conta-lgpd', label: 'Conta & LGPD', description: 'Direitos do titular, exportação, exclusão.', icon: 'shield-check' },
  { slug: 'seguranca', label: 'Segurança', description: 'Auth, MFA, sessões, dispositivos.', icon: 'lock' },
  { slug: 'beta-feedback', label: 'Beta & feedback', description: 'Como dar feedback, NPS, programa de convites.', icon: 'message-square' },
  { slug: 'tecnico', label: 'Técnico & suporte', description: 'Cache, sync, offline, troubleshooting.', icon: 'wrench' },
  { slug: 'onboarding', label: 'Primeiros passos', description: 'Onboarding, primeiros cliques, primeira sessão.', icon: 'rocket' },
];

// ============================================================================
// 80+ FAQ ENTRIES
// ============================================================================

export const FAQ_ENTRIES: FaqEntry[] = [
  // ========== CONCEITO (8) ==========
  {
    id: 'o-que-e-akasha-portal',
    category: 'conceito',
    question: 'O que é o Akasha Portal (Cabala dos Caminhos)?',
    answer: 'É uma comunidade online de espiritualidade universalista com IA curadora. Você pratica, estuda, compartilha e faz perguntas — sem guru, sem prescrição, sem caminho único. A Akasha IA traduz entre tradições (Candomblé, Cabala, Tantra, Meditação) e ciência moderna, citando fontes e devolvendo perguntas.',
    answerEn: 'An online universalist spirituality community with a curator AI. Practice, study, share, ask — no guru, no prescription, no single path.',
    tags: ['visao', 'iniciante'],
    helpCount: 142,
    notHelpCount: 4,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-e-religiao',
    category: 'conceito',
    question: 'Akasha é uma religião?',
    answer: 'Não. Akasha é uma comunidade de praticantes de várias tradições (e de quem ainda não escolheu nenhuma). Não pedimos adesão religiosa, não temos dogma, não declaramos nenhum caminho como superior.',
    tags: ['visao'],
    helpCount: 98,
    notHelpCount: 6,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'quais-tradicoes-integra',
    category: 'conceito',
    question: 'Quais tradições o Akasha integra hoje?',
    answer: 'Atualmente: Candomblé + Ifá (Odus), Cabala + Numerologia Cabalística, Astrologia (mapa natal completo + cruzamentos), Tantra + práticas somáticas, Meditação + tradições contemplativas, Xamanismo, Umbanda + Espiritismo, Reiki + cura energética. Mais tradições entram com curadoria humana.',
    tags: ['tradicoes', 'visao'],
    helpCount: 75,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-nao-e-guru',
    category: 'conceito',
    question: 'A Akasha IA é confiável? É como um guru?',
    answer: 'A Akasha IA não é guru, é curadora curiosa e tradutora. Traz perspectivas, cita fontes acadêmicas, devolve perguntas em vez de prescrever. Nunca diz "faça este ritual" ou "este é o caminho certo". Sugere, pergunta, aponta caminhos com humildade epistêmica.',
    tags: ['ia', 'principios'],
    helpCount: 121,
    notHelpCount: 9,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'lgpd-desde-design',
    category: 'conceito',
    question: 'Como funciona a LGPD no Akasha?',
    answer: 'Tratamos LGPD como produto, não como burocracia. Art. 7 (consentimento granular por base legal: execução de contrato, legítimo interesse, consentimento específico). Art. 18 (direitos do titular: acesso, correção, anonimização, portabilidade, exclusão). Art. 37 (log de auditoria de todos os acessos aos seus dados). Painel em /account/privacy.',
    tags: ['lgpd', 'privacidade'],
    helpCount: 56,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'modelo-de-receita',
    category: 'conceito',
    question: 'Como o Akasha ganha dinheiro?',
    answer: 'Três frentes: (1) Marketplace — taxa de 15% sobre serviços de practitioners. (2) Assinatura opcional "Mantenedor" — R$ 29/mês para quem quer apoiar e ter recursos extras. (3) Trilhos de mentoria 1:1 (15% também). Conteúdo, comunidade e Akasha IA são sempre gratuitas.',
    tags: ['monetizacao'],
    helpCount: 42,
    notHelpCount: 3,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'principios-editoriais',
    category: 'conceito',
    question: 'Quais são os princípios editoriais da comunidade?',
    answer: 'Cinco pilares: (1) Humildade epistêmica — ninguém sabe tudo. (2) Curiosidade antes de certeza. (3) Coexistência entre tradições — não declaramos superioridade. (4) Citação de fontes acadêmicas. (5) Linguagem cuidadosa — sem apropriação cultural, sem arrogância sectária.',
    tags: ['comunidade', 'principios'],
    helpCount: 38,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'diferenca-outros-apps',
    category: 'conceito',
    question: 'Como o Akasha é diferente de outros apps de espiritualidade?',
    answer: 'Apps de horóscopo comercializam horóscopo de massa. Apps de tarot automatizam tirage. Nós integramos 8 tradições com curadoria acadêmica humana + IA que cita fontes, devolvendo perguntas. Não vendemos "previsão" — oferecemos ferramentas de estudo e prática. Marketplace é curado (não keyword bidding).',
    tags: ['visao'],
    helpCount: 31,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== ACESSO & BETA (8) ==========
  {
    id: 'custo-beta',
    category: 'acesso-beta',
    question: 'Quanto custa participar durante a beta?',
    answer: 'Grátis durante toda a beta (até 50 usuários, ago/2026). Quando lançarmos público (set/out 2026), haverá modelo gratuito + assinatura opcional "Mantenedor" (R$ 29/mês) para quem quiser apoiar + extras. Marketplace cobra 15% sobre serviços.',
    tags: ['beta', 'preco'],
    helpCount: 89,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'como-entrar-na-beta',
    category: 'acesso-beta',
    question: 'Como entro na beta?',
    answer: 'A beta está fechada para os primeiros 50 participantes. Entre em /beta/waitlist com seu email. Quando sua vaga abrir, o operador (Gabriel) marca conversa de 20min em PT-BR pra entender o que você busca. Processo humano, não automático.',
    tags: ['beta', 'waitlist'],
    helpCount: 67,
    notHelpCount: 3,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'lancamento-publico',
    category: 'acesso-beta',
    question: 'Quando o Akasha abre para o público?',
    answer: 'Beta vai até final de agosto de 2026. Após isso, dependendo dos resultados da co-evolução com os 50 beta users, abrimos para o público geral entre setembro e outubro de 2026. Avisaremos a waitlist por email antes.',
    tags: ['beta', 'lancamento'],
    helpCount: 51,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'preciso-experiencia',
    category: 'acesso-beta',
    question: 'Preciso ter experiência prévia com espiritualidade pra entrar?',
    answer: 'Não. Os 50 lugares incluem 10 vagas para "buscadores" — pessoas curiosas que ainda não têm tradição definida. Sua curiosidade é tão valiosa quanto a prática de 20 anos.',
    tags: ['iniciante', 'buscador'],
    helpCount: 44,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'convite-outros',
    category: 'acesso-beta',
    question: 'Posso convidar outras pessoas?',
    answer: 'Sim, mas a fila de espera ainda passa pelo processo humano do operador. Cada beta user recebe 3 invites prioritários ao entrar (programa Wave 35-3). Indicações extras entram na fila padrão. Você ganha créditos de mentoria por cada invite aceito.',
    tags: ['convite', 'indique'],
    helpCount: 35,
    notHelpCount: 0,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'lista-de-espera-tempo',
    category: 'acesso-beta',
    question: 'Quanto tempo fico na lista de espera?',
    answer: 'Depende do seu perfil + vaga. Beta users entram em até 14 dias. Pós-beta, fila típica de 4-12 semanas, priorizando quem tem fit com as 7 tradições e disposição pra co-evoluir o produto.',
    tags: ['waitlist'],
    helpCount: 28,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'pais-bloqueado',
    category: 'acesso-beta',
    question: 'Estou em outro país (fora do Brasil), posso participar?',
    answer: 'Sim. Marketplace e eventos funcionam em qualquer país com Stripe Connect. Algumas tradições com raízes geográficas (Candomblé, Umbanda) podem ter curadoria local mais forte no Brasil, mas o conteúdo é global. Idiomas: PT-BR primário, EN secundário.',
    tags: ['internacional'],
    helpCount: 12,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'sair-da-beta',
    category: 'acesso-beta',
    question: 'Posso sair da beta a qualquer momento?',
    answer: 'Sim. Em /account/privacy clique em "Encerrar participação beta". Seus dados podem ser mantidos (anonimizados) para o corpus de treinamento da Akasha IA, exceto se você marcar "Não usar meus dados para treino". Você tem até 30 dias para reverter.',
    tags: ['beta', 'lgpd'],
    helpCount: 9,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== AKASHA IA (12) ==========
  {
    id: 'akasha-como-funciona',
    category: 'akasha-ia',
    question: 'Como a Akasha IA funciona tecnicamente?',
    answer: 'Fine-tuning de GPT-4o-mini (OpenAI) com fallback MiniMax. Corpus curado por consultores acadêmicos de cada tradição + papers peer-reviewed. Pipeline: contexto do usuário (tradições seguidas, mapa natal, prévia do onboarding) → retrieval do corpus + bibliografia → resposta com citações inline.',
    answerEn: 'Fine-tuning of GPT-4o-mini with academic corpus + retrieval-augmented generation.',
    tags: ['ia', 'tecnico'],
    helpCount: 73,
    notHelpCount: 4,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-dados-treino',
    category: 'akasha-ia',
    question: 'A Akasha usa meus dados para treinar?',
    answer: 'Não por padrão. Você pode conceder essa permissão em /account/privacy → "Permitir uso de minhas interações para melhorar a Akasha IA" (consentimento granular, revogável). Quando concedido, apenas mensagens de chat com feedback positivo entram no corpus de treino.',
    tags: ['lgpd', 'ia'],
    helpCount: 67,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-limites',
    category: 'akasha-ia',
    question: 'Quais perguntas a Akasha IA pode recusar?',
    answer: 'A Akasha recusa ou redireciona: (1) conselho médico, psicológico ou financeiro direto; (2) diagnóstico de saúde mental; (3) prescrição ritualística ("faça este banho"); (4) discurso de ódio ou violência; (5) orientação sobre autolesão; (6) promoções de produtos/serviços específicos.',
    tags: ['ia', 'limites'],
    helpCount: 81,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-exemplos-pergunta',
    category: 'akasha-ia',
    question: 'Que tipo de pergunta eu posso fazer pra Akasha?',
    answer: 'Boas perguntas: "Qual a diferença entre Ifá e Candomblé?", "O que é Odin dentro da Cabala prática?", "Como começo meditar se tenho TDAH?", "O que meu mapa natal diz sobre minha Vênus em Escorpião?", "Como traduzir o conceito de axé pras práticas contemplativas?". Perguntas abertas, não prescritivas.',
    tags: ['ia', 'exemplos'],
    helpCount: 95,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-streaming',
    category: 'akasha-ia',
    question: 'Por que a Akasha responde em "streaming"?',
    answer: 'A Akasha entrega token-a-token para reduzir latência percebida. Você vê a resposta sendo construída e pode pará-la se perceber que a direção não é o que queria. Latência típica: 200-600ms para o primeiro token, 1-3s para resposta completa (varia com a complexidade).',
    tags: ['ia', 'ux'],
    helpCount: 18,
    notHelpCount: 4,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-cites-fontes',
    category: 'akasha-ia',
    question: 'Como sei se a Akasha tá citando fontes reais?',
    answer: 'Toda resposta que mistura fato histórico, doutrina ou prática inclui marcadores `[fonte: X]` inline. Clique no número pra ver a referência completa (livro, paper, capítulo). Se a IA não tiver fonte, ela marca explicitamente: "opinião/observação pessoal" — não inventa.',
    tags: ['ia', 'fontes'],
    helpCount: 56,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-multi-tradicao',
    category: 'akasha-ia',
    question: 'A Akasha pode comparar tradições diferentes?',
    answer: 'Sim, é uma das funções principais. Exemplo: "Compare o conceito de Ego no Budismo e na Cabala" — ela traz as duas perspectivas, cita fontes, e termina devolvendo uma pergunta ("Qual delas ressoa mais na sua prática atual?"). Não declara "X é melhor que Y".',
    tags: ['ia', 'comparativo'],
    helpCount: 38,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-custo',
    category: 'akasha-ia',
    question: 'Quantas mensagens posso mandar pra Akasha por dia?',
    answer: 'Beta: ilimitado. Pós-beta gratuito: 30 mensagens/dia. Mantenedor (R$ 29/mês): 200 mensagens/dia. Mensagens de prática (reflexão, leitura de mapa) têm limite separado de 100/dia. Limite reseta à meia-noite UTC.',
    tags: ['ia', 'limites'],
    helpCount: 42,
    notHelpCount: 3,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-feedback',
    category: 'akasha-ia',
    question: 'Posso dar feedback nas respostas da Akasha?',
    answer: 'Sim. Toda resposta tem 👍/👎 + comentário opcional. O feedback ajuda a IA a calibrar sua próxima resposta e é agregado (anonimamente) para a curadoria da próxima versão do modelo. Você também pode bloquear temas: "não quero falar sobre X".',
    tags: ['ia', 'feedback'],
    helpCount: 28,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-vs-humano',
    category: 'akasha-ia',
    question: 'Quando devo procurar um humano em vez da Akasha?',
    answer: 'Sempre que houver: risco físico (orientação de jejum, rituais de cura); decisão de vida importante; crise existencial aguda (depressão, luto); conflito com liderança. Nesses casos a Akasha sugere explicitamente: "Considere conversar com alguém de confiança — posso te conectar com [mentor / practitioner / acolhimento]".',
    tags: ['ia', 'limites', 'seguranca'],
    helpCount: 47,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-privacidade',
    category: 'akasha-ia',
    question: 'A Akasha IA vê meus posts e DM?',
    answer: 'Não. A IA só vê as mensagens trocadas com ela no chat e o contexto que você definiu no onboarding (tradições seguidas, mapa natal). Posts no feed, comentários, DMs com humanos NÃO são alimentados à IA automaticamente. Você pode ligar isso em /account/privacy com consentimento explícito.',
    tags: ['lgpd', 'ia'],
    helpCount: 91,
    notHelpCount: 3,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'akasha-fora-do-ar',
    category: 'akasha-ia',
    question: 'A Akasha tá fora do ar, o que faço?',
    answer: 'Verifique /status (tempo real). Se só a IA estiver fora, posts e marketplace continuam funcionando. Se tudo estiver fora, é raro — provavelmente incidente Stripe/Supabase. Poste em /feed/incidents ou abra feedback crítico em /feedback?type=BUG&urgency=high.',
    tags: ['ia', 'incidente'],
    helpCount: 13,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== TRADIÇÕES (15) ==========
  {
    id: 'cabala-inicio',
    category: 'tradicoes',
    question: 'Como começo a estudar Cabala?',
    answer: 'Caminho recomendado: (1) Ler o Zohar online gratuito em /library/articles?tradition=cabala. (2) Fazer 1 sessão com mentor da tradição (R$ 80-150). (3) Começar pelas 10 Sefirot — a árvore da vida é o mapa central. Akasha pode montar um plano de estudo em /akashic.',
    relatedTradition: 'cabala',
    tags: ['iniciante', 'cabala'],
    helpCount: 53,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'cabala-vs-judaismo',
    category: 'tradicoes',
    question: 'Cabala é a mesma coisa que Judaísmo?',
    answer: 'Não. Cabala é a mística judaica — um conjunto de textos e práticas (Zohar, Sepher Yetzirah, árvore da vida) que convivem com o Judaísmo rabínico mas têm origem e prática próprias. Akasha apresenta ambas como caminhos, sem declarar superioridade.',
    relatedTradition: 'cabala',
    tags: ['cabala', 'iniciante'],
    helpCount: 41,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'candomble-inicio',
    category: 'tradicoes',
    question: 'Como começo a praticar Candomblé respeitosamente?',
    answer: 'Candomblé tem estrutura iniciática — você não pode "começar sozinho". Passos: (1) Visite um terreiro aberto (Casa Branca, Ilê Axé, ...). (2) Converse com o Zelador(a) de Santo. (3) Participe de Gira de Desenvolvimento (sem obrigação de iniciar). (4) Se sentir o chamado, peça o "feijão" (período de aproximação). Akasha não substitui esse caminho.',
    relatedTradition: 'candomble',
    tags: ['iniciante', 'candomble'],
    helpCount: 78,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'candomble-axe',
    category: 'tradicoes',
    question: 'O que é axé exatamente?',
    answer: 'Axé é a força vital / energia que permeia tudo no Candomblé — não é "abundância material" como vulgarizou. Carrega a ideia de continuidade, ancestralidade e equilíbrio. A Akasha pode citar diferentes perspectivas (Nagô, Ketu, Jeje) sobre o conceito.',
    relatedTradition: 'candomble',
    tags: ['candomble', 'conceito'],
    helpCount: 35,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'ifa-inicio',
    category: 'tradicoes',
    question: 'O que é Ifá e como se diferencia do Candomblé?',
    answer: 'Ifá é o oráculo yorubá — sistema de 16 Odus (sinais maiores) e 256 Odus menores, consultado por babalorixás e olodus. Candomblé é a religião que cultua os Orixás. Ifá e Candomblé se complementam: muitos terreiros praticam ambos. Akasha pode explicar a relação histórica.',
    relatedTradition: 'ifa',
    tags: ['iniciante', 'ifa'],
    helpCount: 42,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'tantra-real',
    category: 'tradicoes',
    question: 'Tantra não é só sexo, né?',
    answer: 'Não. Tantra é uma tradição filosófica e prática do Hinduísmo e Budismo tântrico com milênios. Inclui meditação, mantra, yantra (geometria), ritual com partenaires ou solo, e estudo de textos (Vajrayana, Kularnava Tantra). A redução à sexualidade é apropriação ocidental dos anos 90. Akasha pode indicar livros sérios.',
    relatedTradition: 'tantra',
    tags: ['tantra', 'iniciante'],
    helpCount: 64,
    notHelpCount: 0,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'meditacao-tdah',
    category: 'tradicoes',
    question: 'Como meditar se tenho TDAH ou ansiedade?',
    answer: 'Três dicas: (1) Sessões curtas — 2min, não 20min. (2) Âncora simples (som âncora, batimento cardíaco, pés no chão). (3) Apps externos NÃO substituem prática, mas DoBien, Insight Timer, e o módulo de /rituais/breath ajudam. Akasha pode personalizar um plano pra sua realidade.',
    relatedTradition: 'meditacao',
    tags: ['meditacao', 'saude-mental', 'iniciante'],
    helpCount: 71,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'xamanismo-origem',
    category: 'tradicoes',
    question: 'Xamanismo é uma tradição ou várias?',
    answer: 'Várias. Existem tradições xamânicas indígenas (Kichada, Huni Kuin, Guarani), asiáticas (chamanismo siberiano, coreano) e neo-xamanismo ocidental. Akasha respeita cada linhagem e não mistura. Não praticamos "xamanismo genérico" — sempre identificamos a origem.',
    relatedTradition: 'xamanismo',
    tags: ['xamanismo', 'etica'],
    helpCount: 27,
    notHelpCount: 3,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'umbanda-diferenca-candomble',
    category: 'tradicoes',
    question: 'Qual a diferença entre Umbanda e Candomblé?',
    answer: 'Umbanda surgiu no Brasil nos anos 1920-30, sincretizando Candomblé, Catolicismo, Espiritismo e tradições indígenas africanas. Candomblé mantém estrutura yorubá mais ortodoxa. Ambos cultuam Orixás mas a liturgia, a hierarquia e os rituais têm diferenças. Akasha explica sem tomar partido.',
    relatedTradition: 'umbanda',
    tags: ['umbanda', 'candomble'],
    helpCount: 38,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'reiki-origem',
    category: 'tradicoes',
    question: 'O que é Reiki e como foi criado?',
    answer: 'Reiki é prática de imposição de mãos developed por Mikao Usui no Japão em 1922, depois disseminada por Hawayo Takata para o Ocidente. É uma técnica com linhagem clara, não "energia genérica". Akasha explica o que é, como é ensinado, e separa de práticas sem linhagem.',
    relatedTradition: 'reiki',
    tags: ['reiki', 'iniciante'],
    helpCount: 24,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'astrologia-inicio',
    category: 'tradicoes',
    question: 'Astrologia no Akasha é coerente ou simplificada?',
    answer: 'Coerente. Usamos Swiss Ephemeris com cálculos trópico (não sideral — perguntamos na hora). Mapa natal completo: planetas, casas, aspectos principais (incluindo menores como quincúncio e paralelos), nós lunares, e opcionalmente trânsitos e progressões. Beta adiciona astrologia horária e electional.',
    relatedTradition: 'astrologia',
    tags: ['astrologia', 'iniciante'],
    helpCount: 56,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'simbolos-sagrados',
    category: 'tradicoes',
    question: 'Posso usar símbolos sagrados nas minhas postagens?',
    answer: 'Sim, com cuidado cultural: (1) Cite a tradição de origem; (2) Não use pra apropriação/comercialização; (3) Em imagens com rosto de Orixá ou entidade, mantenha contexto respeitoso. Akasha revisa postagens que envolvam símbolos protegidos automaticamente (Yantra, Símbolos dos Orixás, Sigilos).',
    tags: ['etica', 'simbolos'],
    helpCount: 31,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'esoterismo-vs-espiritualidade',
    category: 'tradicoes',
    question: 'Diferença entre esoterismo e espiritualidade?',
    answer: 'Esoterismo é o conjunto de tradições com linhagem fechada (ocultismo, hermetismo, ordens iniciáticas). Espiritualidade é o termo guarda-chuva para prática pessoal, com ou sem linhagem. Akasha atua em ambos com curadoria diferenciada.',
    tags: ['conceito'],
    helpCount: 22,
    notHelpCount: 3,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'apropriacao-cultural',
    category: 'tradicoes',
    question: 'O que é apropriação cultural no contexto Akasha?',
    answer: 'Quando alguém usa elementos de uma tradição sem reconhecimento da fonte, sem respeito à estrutura, ou para fins comerciais/promocionais sem autorização. Exemplos: yoga sem reconhecer origem hindu, "sweat lodge" sem linhagem indígena, "tarot comercial" sem estudo. Akasha flagga via curadoria.',
    tags: ['etica'],
    helpCount: 38,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'pratica-solo-vs-comunidade',
    category: 'tradicoes',
    question: 'Posso praticar sozinho ou preciso de um grupo?',
    answer: 'Depende da tradição. Meditação, Tantra solo, Astrologia, Cabala (estudo), Reiki (autotratamento) — práticas solo viáveis. Candomblé, Umbanda, Xamanismo indígena, Ordens herméticas — exigem iniciação/linhagem. Akasha sempre sinaliza a estrutura recomendada.',
    tags: ['pratica', 'iniciante'],
    helpCount: 41,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== MARKETPLACE (10) ==========
  {
    id: 'marketplace-como-funciona',
    category: 'marketplace',
    question: 'Como funciona o marketplace?',
    answer: 'Practitioners (terapeutas, consultores, astrólogos, ...) criam perfil com tradição, certificações, preços. Você escolhe, paga via Stripe com escrow (o dinheiro só libera pro practitioner depois da sessão concluída). Reviews são moderadas e ajudam a plataforma.',
    tags: ['marketplace', 'pagamento'],
    helpCount: 64,
    notHelpCount: 3,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-escrow',
    category: 'marketplace',
    question: 'O que é escrow?',
    answer: 'O dinheiro fica retido pela plataforma até você confirmar que a sessão aconteceu. Se houver disputa (practitioner não apareceu, problema grave), a Akasha mediação abre ticket. Prazo de liberação: 48h após a sessão se você não contestar.',
    tags: ['marketplace', 'seguranca'],
    helpCount: 47,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-cancelamento',
    category: 'marketplace',
    question: 'Posso cancelar uma sessão de marketplace?',
    answer: 'Sim, com até 24h antes: reembolso integral. Entre 24h e 2h antes: 50% de reembolso (practitioner recebe 50% pelo bloqueio de agenda). Menos de 2h: sem reembolso, salvo casos de força maior (doença, emergência) julgados pela mediação.',
    tags: ['marketplace', 'cancelamento'],
    helpCount: 35,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-practitioner-requisitos',
    category: 'marketplace',
    question: 'Como me torno um practitioner no marketplace?',
    answer: 'Critérios: (1) Conta verificada (email + telefone). (2) Pelo menos 1 ano de prática formal OU certificação da tradição. (3) Entrevista 20min com curador (humano). (4) Perfil completo com bio, foto, política de cancelamento. Aprovação em 7-10 dias úteis. Aplicação em /marketplace/apply.',
    tags: ['marketplace', 'practitioner'],
    helpCount: 28,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-comissao',
    category: 'marketplace',
    question: 'Qual a comissão do Akasha sobre o marketplace?',
    answer: '15% sobre o valor da sessão. Esse valor cobre: processamento Stripe, escrow, curadoria de qualidade, mediação de disputas, suporte ao cliente. Practitioner recebe 85% líquido, com repasse semanal toda sexta-feira.',
    tags: ['marketplace', 'comissao'],
    helpCount: 22,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-reviews',
    category: 'marketplace',
    question: 'Como funciona o sistema de reviews?',
    answer: 'Após a sessão, você recebe pedido de review (estrelas 1-5 + comentário). Comentários são moderados (palavrões, PII do practitioner, conteúdo ilegal são filtrados). Reviews com 3 ou menos estrelas disparam mediação automática. Practitioners podem responder publicamente.',
    tags: ['marketplace', 'reviews'],
    helpCount: 19,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-disputa',
    category: 'marketplace',
    question: 'Como abro uma disputa no marketplace?',
    answer: 'Em /marketplace/orders → clique "Abrir disputa" na sessão. Você descreve o problema em até 500 palavras. Akasha mediação (humana, não IA) responde em 48h úteis com decisão (reembolso integral, parcial, ou sem reembolso). Decisão é final salvo fraude comprovada.',
    tags: ['marketplace', 'disputa'],
    helpCount: 14,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-impostos',
    category: 'marketplace',
    question: 'Como funcionam impostos/recibos?',
    answer: 'Cada sessão gera recibo digital em PDF com valor, data, practitioner e você. Marketplace não é responsável por IR — cada practitioner precisa declarar como MEI ou PF (Akasha dispara nota de orientação em /marketplace/taxes). Você recebe NF do practitioner se ele emitir.',
    tags: ['marketplace', 'impostos'],
    helpCount: 11,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-id-k',
    category: 'marketplace',
    question: 'Preciso de identidade KYC pra usar o marketplace?',
    answer: 'Sim, pra qualquer transação financeira. KYC via Stripe Identity (documento frente/verso + selfie). Demora 1-2 minutos. Sem KYC você pode ler marketplace, favoritar practitioners, mas não pode contratar nem ser contratado.',
    tags: ['marketplace', 'kyc', 'lgpd'],
    helpCount: 31,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'marketplace-tipos-servico',
    category: 'marketplace',
    question: 'Quais tipos de serviço existem no marketplace?',
    answer: 'Hoje: (1) Consulta (30-60min, vídeo/áudio/chat). (2) Mentoria (pacote 4 sessões). (3) Mapa natal (entrega escrita). (4) Ritual assistido (online ou presencial). (5) Curso (videoaulas + material). Cada tipo tem regras próprias de cancelamento e escopo.',
    tags: ['marketplace', 'servicos'],
    helpCount: 25,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== MENTORSHIP (8) ==========
  {
    id: 'mentor-vs-practitioner',
    category: 'mentorship',
    question: 'Qual a diferença entre mentor e practitioner?',
    answer: 'Mentor: caminho longo (4+ sessões mensais), foco em desenvolvimento pessoal e estudo continuado. Practitioner: sessão pontual ou pacote curto, foco em escopo específico (mapa, ritual, leitura). Mentoria exige mais comprometimento de tempo e maior investigação do match.',
    tags: ['mentoria'],
    helpCount: 38,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-como-aplicar',
    category: 'mentorship',
    question: 'Como aplico pra ser mentor?',
    answer: 'Em /mentorship/apply. Requisitos: (1) 5+ anos de prática contínua na tradição. (2) Pelo menos 3 alunos anteriores (referências). (3) Disponibilidade de 4h/semana. (4) Submeter 1 mini-plano de mentoria em vídeo (10min). Aprovação em 14-21 dias.',
    tags: ['mentor', 'aplicacao'],
    helpCount: 22,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-matching',
    category: 'mentorship',
    question: 'Como funciona o matching com mentores?',
    answer: 'Quando você aplica como mentee, descreve: tradição de interesse, objetivos, frequência desejada, preferência de estrutura (sólida/exploratória/ritualística), e idiomas. Algoritmo de matching ranqueia top 3 mentores por fit. Você escolhe 1, agenda discovery call 30min (gratuito).',
    tags: ['mentoria'],
    helpCount: 47,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-preco',
    category: 'mentorship',
    question: 'Quanto custa uma mentoria?',
    answer: 'Mentor define seu preço. Faixa típica: R$ 150-400/sessão (60-90min). Pacotes 4+ sessões têm 10-20% de desconto. Akasha sugere faixa de mercado baseado em tradição, senioridade e reviews. Você pode filtrar por preço em /mentorship.',
    tags: ['mentoria', 'preco'],
    helpCount: 39,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-frequencia',
    category: 'mentorship',
    question: 'Qual frequência de mentoria é recomendada?',
    answer: 'Beta data sugere: semanal pra casos intensos (transição de carreira, luto, decisão grande), quinzenal pra prática regular, mensal pra manutenção. Você pode mudar a frequência a qualquer momento com aviso de 30 dias ao mentor.',
    tags: ['mentoria'],
    helpCount: 18,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-termina',
    category: 'mentorship',
    question: 'Posso encerrar a mentoria?',
    answer: 'Sim, a qualquer momento, com aviso de 30 dias (cobrança proporcional). Se você estiver com pacote pré-pago, fica o saldo devedor. Encerramento amigável fica registrado e gera pesquisa de satisfação (opcional, alimenta nosso matching).',
    tags: ['mentoria'],
    helpCount: 14,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-seguranca',
    category: 'mentorship',
    question: 'E se a relação com mentor não funcionar?',
    answer: 'Akasha mediação cuida: (1) Conflito pontual — você reporta, mediação fala com ambas as partes em 48h. (2) Mismatch permanente — remarcamos sem custo com novo mentor do top 3. (3) Conduta inadequada (assédio, abuso) — encerramento imediato e investigação.',
    tags: ['mentoria', 'seguranca'],
    helpCount: 28,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'mentor-vs-grupo',
    category: 'mentorship',
    question: 'Mentoria vs grupo de estudo?',
    answer: 'Mentoria = 1:1, personalizada, cara. Grupo = co-aprendizagem, compartilhada, mais barata. Recomendamos começar por um grupo de estudo da tradição, e usar mentoria pra momentos específicos (transição, dúvida grande, bloqueio).',
    tags: ['mentoria'],
    helpCount: 17,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== EVENTOS (6) ==========
  {
    id: 'evento-tipos',
    category: 'eventos',
    question: 'Quais tipos de eventos existem?',
    answer: '3 tipos: (1) Presencial em cidade (São Paulo, Rio, Recife, ...). (2) Live streaming (Zoom + chat ao lado). (3) Assíncrono (estudos, círculos de leitura). Cada evento tem RSVP, lembrete 1h antes, gravação disponível 7 dias pra quem participou.',
    tags: ['eventos'],
    helpCount: 29,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'evento-rsvp',
    category: 'eventos',
    question: 'Como funciona o RSVP?',
    answer: 'Você marca interesse em /events/[slug] → "Quero ir". Recebe confirmação por email + push (se permitido). Lembrete 1h antes. Cancelamento até 24h antes sem ônus. Entre 24h-2h antes fica na lista de espera de quem desistiu.',
    tags: ['eventos'],
    helpCount: 11,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'evento-live',
    category: 'eventos',
    question: 'Live streaming tem chat ao vivo?',
    answer: 'Sim. Painel lateral mostra chat ao vivo, perguntas dos participantes, e reações (👏 🔥 🙏). Você pode pausar, voltar 30s, ajustar velocidade. Após a live, fica disponível por 7 dias pra quem confirmou presença.',
    tags: ['eventos'],
    helpCount: 15,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'evento-organizar',
    category: 'eventos',
    question: 'Como organizo um evento no Akasha?',
    answer: 'Em /events/organize → submissão de evento. Precisa: título, descrição (300+ palavras), data/hora UTC, tradição/linha de cuidado, capacidade, cidade ou "online", link de inscrição. Akasha revisão editorial aprova em 3-5 dias úteis.',
    tags: ['eventos'],
    helpCount: 8,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'evento-privacidade',
    category: 'eventos',
    question: 'Participar de evento aparece no meu perfil?',
    answer: 'Por padrão, sim — "Eventos recentes" lista os últimos 5 que você confirmou. Você pode desativar em /account/privacy → "Visibilidade de eventos". Organizadores sempre veem a lista de confirmados pra coordenação.',
    tags: ['eventos', 'privacidade'],
    helpCount: 12,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'evento-gratuito',
    category: 'eventos',
    question: 'Eventos gratuitos e pagos?',
    answer: 'Ambos. Gratuitos são prática padrão — 70% dos eventos. Pagos (R$ 20-200) cobrem custos de espaço/operador/equipamento. Pago é processado via Stripe escrow (só libera pro organizador 24h após evento, se não houver disputas).',
    tags: ['eventos'],
    helpCount: 9,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== CONTA & LGPD (8) ==========
  {
    id: 'lgpd-art-18',
    category: 'conta-lgpd',
    question: 'Quais são meus direitos como titular de dados (LGPD Art. 18)?',
    answer: 'Você tem direito a: (1) Confirmação da existência de tratamento. (2) Acesso aos dados. (3) Correção. (4) Anonimização. (5) Portabilidade (export JSON). (6) Eliminação. (7) Informação sobre compartilhamento. (8) Oposição. Tudo gerenciável em /account/privacy.',
    tags: ['lgpd', 'direitos'],
    helpCount: 67,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'exportar-dados',
    category: 'conta-lgpd',
    question: 'Como exporto meus dados (LGPD Art. 18 V)?',
    answer: 'Em /account/privacy → "Exportar dados" → escolha formato (JSON ou PDF humanizado) → recebe link de download por email em até 24h. Inclui: posts, comentários, mensagens, mapa astral, histórico de meditação, reviews, sessões de mentoria, interações com Akasha IA.',
    tags: ['lgpd'],
    helpCount: 54,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'excluir-conta',
    category: 'conta-lgpd',
    question: 'Como excluo minha conta?',
    answer: 'Em /account/privacy → "Excluir conta" → confirme via email (validação dupla). Conta fica em estado "soft-delete" por 30 dias (você pode reverter fazendo login). Após 30 dias: dados pessoais são apagados, posts são anonimizados, mapa astral e reviews são removidos dos índices públicos.',
    tags: ['lgpd', 'exclusao'],
    helpCount: 89,
    notHelpCount: 5,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'politica-privacidade',
    category: 'conta-lgpd',
    question: 'Onde está a Política de Privacidade completa?',
    answer: 'Em /legal/privacidade (URL canônica). Versão 2.3, atualizada 2026-06-15. Inclui: bases legais (Art. 7), retenção por tipo de dado, terceiros, transferências internacionais (LGPD Art. 33), e DPO responsável (dpo@akashaportal.com.br).',
    tags: ['lgpd'],
    helpCount: 22,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'consentimento-granular',
    category: 'conta-lgpd',
    question: 'O que é o consentimento granular do Akasha?',
    answer: 'Cada tipo de tratamento de dados pede consentimento específico (Art. 7 §1º e §2º). Akasha mostra toggle individual para: (1) usar interações no treino da IA; (2) compartilhar mapa astral em perfil público; (3) receber emails transacionais vs marketing; (4) participar do programa de convites; etc. Tudo em /account/privacy.',
    tags: ['lgpd', 'consentimento'],
    helpCount: 31,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'cookies',
    category: 'conta-lgpd',
    question: 'Akasha usa cookies? Quais?',
    answer: 'Sim, com classificação: (1) Essenciais (sessão, auth, segurança) — sempre ligados. (2) Funcionais (preferências, idioma) — sempre ligados. (3) Analíticos (PostHog agregado) — opt-in. (4) Marketing — não usamos até feature flag ativa. Painel completo em /account/privacy/cookies.',
    tags: ['lgpd', 'cookies'],
    helpCount: 18,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'dpo',
    category: 'conta-lgpd',
    question: 'Quem é o DPO do Akasha?',
    answer: 'Equipe interna: Maria Fernanda Silva (mfer@akashaportal.com.br). Ela reporta trimestralmente o status de tratamento de dados ao Conselho Editorial. Casos graves (vazamento, suspeita) são comunicados à ANPD em até 2 dias úteis (LGPD Art. 48).',
    tags: ['lgpd', 'dpo'],
    helpCount: 9,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'anpd-reclamacao',
    category: 'conta-lgpd',
    question: 'Posso reclamar direto pra ANPD?',
    answer: 'Sim, mas pedimos que tente antes o canal interno (/account/privacy ou dpo@akashaportal.com.br) — temos SLA de resposta em 5 dias úteis. Se não for resolvido, você tem todo o direito de escalar pra ANPD (https://www.gov.br/anpd) sem represália.',
    tags: ['lgpd', 'anpd'],
    helpCount: 7,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== SEGURANÇA (6) ==========
  {
    id: 'mfa',
    category: 'seguranca',
    question: 'Como ativo autenticação em 2 fatores (2FA)?',
    answer: 'Em /account/security → "Ativar 2FA". Opções: TOTP (Google Authenticator, Authy) ou WebAuthn (chave física YubiKey, Titan Key). Backup codes gerados no momento. Recomendamos fortemente: beta users devem ativar TOTP.',
    tags: ['seguranca', '2fa'],
    helpCount: 78,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'senha-vazada',
    category: 'seguranca',
    question: 'Como sei se minha senha vazou?',
    answer: 'Akasha checa periodicamente (haveibeenpwned-k-anonymity, hash parcial). Se sua senha aparecer em vazamento público, aparece banner em /account/security com "Trocar senha recomendada". Você recebe email + push.',
    tags: ['seguranca'],
    helpCount: 41,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'sessoes-ativas',
    category: 'seguranca',
    question: 'Como vejo e encerro sessões ativas?',
    answer: 'Em /account/security → "Sessões ativas" lista dispositivo, IP, localização aproximada, último acesso. Pra encerrar: clique "Encerrar" na sessão. Pra encerrar todas: "Encerrar tudo" (útil se perdeu celular).',
    tags: ['seguranca'],
    helpCount: 33,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'phishing',
    category: 'seguranca',
    question: 'Como identificar phishing do Akasha?',
    answer: 'Akasha NUNCA pede: senha por email, código MFA por email/DM, pagamento fora do Stripe oficial, instalação de software. Emails transacionais vêm de @akashaportal.com.br. Em caso de dúvida, encaminhe para security@akashaportal.com.br.',
    tags: ['seguranca', 'phishing'],
    helpCount: 56,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'rate-limiting',
    category: 'seguranca',
    question: 'Akasha tem rate limiting contra abuso?',
    answer: 'Sim, em camadas: edge (Vercel), aplicação (Upstash), auth (Supabase). Limites típicos: 100 req/min por IP pra endpoints públicos, 30 msgs/dia pra Akasha IA por usuário free, 5 reports/dia. 429 + Retry-After no header.',
    tags: ['seguranca', 'tecnico'],
    helpCount: 11,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'relatar-vulnerabilidade',
    category: 'seguranca',
    question: 'Achei uma vulnerabilidade, como relato?',
    answer: 'Programa responsible disclosure: security@akashaportal.com.br (PGP key em /.well-known/security.txt). SLA: confirmação em 48h, triagem em 5 dias úteis. Severe (risco imediato) recompensado com créditos marketplace. Sem报复.',
    tags: ['seguranca', 'vulnerabilidade'],
    helpCount: 18,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== BETA & FEEDBACK (6) ==========
  {
    id: 'feedback-como',
    category: 'beta-feedback',
    question: 'Como dou feedback no Akasha?',
    answer: '3 caminhos: (1) /feedback — formulário estruturado (bug/feature/conteúdo/usabilidade/comunidade). (2) Botão 👍/👎 em qualquer tela. (3) Email akasha@akashaportal.com.br. Tudo vira ticket e tem SLA de resposta por prioridade.',
    tags: ['feedback'],
    helpCount: 49,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'nps-como',
    category: 'beta-feedback',
    question: 'O que é o NPS e quando recebo?',
    answer: 'Net Promoter Score mede se você recomendaria o Akasha. Recebe micro-pesquisa em: (1) Day 1, 3, 7, 14, 30 pós-onboarding; (2) Após milestone de uso; (3) Trimestral (todos os usuários). 30 segundos, anônimo, opcional. Beta NPS atual: 67.',
    tags: ['feedback', 'nps'],
    helpCount: 31,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'convite-prioritario',
    category: 'beta-feedback',
    question: 'Como uso meus invites prioritários?',
    answer: 'Em /beta/invites, você vê seus 3 invites. Cada um permite pular a waitlist pra uma pessoa específica. Você ganha +1 invite por feedback crítico aceito pela curadoria. Convites expiram em 60 dias.',
    tags: ['beta', 'convite'],
    helpCount: 38,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'feedback-resposta',
    category: 'beta-feedback',
    question: 'Em quanto tempo recebo resposta do feedback?',
    answer: 'SLAs: (1) Bugs críticos (login, pagamento, IA offline): 4h úteis. (2) Bugs altos: 24h úteis. (3) Feature request: 7 dias úteis com status (considerado / planejado / implementado / declinado). (4) Conteúdo: 3 dias úteis via curadoria.',
    tags: ['feedback', 'sla'],
    helpCount: 21,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'feedback-anonimo',
    category: 'beta-feedback',
    question: 'Posso dar feedback anônimo?',
    answer: 'Sim. Sem login, é anônimo via hash IP (não armazenado em claro, conforme LGPD). Se logado mas marcado como "anônimo", só vê a equipe de curadoria. Sempre fica no histórico da sua conta pra você revisar, mas não é exibido a ninguém.',
    tags: ['feedback', 'lgpd'],
    helpCount: 17,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'roadmap-publico',
    category: 'beta-feedback',
    question: 'Onde vejo o roadmap público?',
    answer: 'Em /roadmap. Filtrável por: status (proposed/considered/roadmap/in-progress/done/declined), trimestre, área (ia/comunidade/marketplace/admin), e votos. Você pode votar +1 nas que quer ver primeiro. Atualizado semanalmente.',
    tags: ['feedback', 'roadmap'],
    helpCount: 42,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },

  // ========== TÉCNICO & SUPORTE (6) ==========
  {
    id: 'pwa-offline',
    category: 'tecnico',
    question: 'Posso usar o Akasha offline?',
    answer: 'Parcialmente. Posts salvos (ler, escrever rascunho), Akasha IA modo "offline cache" (últimas 5 mensagens), mapa astral (cache do seu mapa) funcionam sem conexão. Sincronização automática ao reconectar.',
    tags: ['pwa', 'offline'],
    helpCount: 28,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'lentidao-app',
    category: 'tecnico',
    question: 'App tá lento, o que faço?',
    answer: 'Passo a passo: (1) Limpar cache (Em /account → Limpar cache). (2) Conferir conexão (test.speedof.me). (3) Atualizar (PWA: Settings → About → Check update). (4) Reportar em /feedback?type=BUG&urgency=high com print + horário. Se persistir, posts em /status.',
    tags: ['performance'],
    helpCount: 19,
    notHelpCount: 2,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'compatibilidade-navegador',
    category: 'tecnico',
    question: 'Quais navegadores são suportados?',
    answer: 'Últimas 2 versões de: Chrome, Edge, Firefox, Safari (incluindo iOS). Mobile: iOS Safari 14+, Android Chrome 90+. Beta users com browsers antigos podem ter fallback de UI reduzido.',
    tags: ['tecnico'],
    helpCount: 14,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'cache-vs-novo-conteudo',
    category: 'tecnico',
    question: 'Não vejo posts novos, é cache?',
    answer: 'Provavelmente. Pull-to-refresh no feed (toque e arraste). Ou clique no ícone de reload no topo. Cache TTL é 60s para queries, invalidado em mutações. Se persistir: /feedback com print.',
    tags: ['cache', 'performance'],
    helpCount: 11,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'integracao-stripe',
    category: 'tecnico',
    question: 'Por que meu pagamento não apareceu?',
    answer: 'Stripe processa em até 24h. Se após 24h não aparecer, /marketplace/orders → "Reportar problema". Stripe Identity (KYC) pode falhar — veja /help/kyc-troubleshooting. Dispute via suporte em até 60 dias.',
    tags: ['pagamento', 'stripe'],
    helpCount: 13,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'logs-publicos',
    category: 'tecnico',
    question: 'Akasha tem página de status pública?',
    answer: 'Sim: /status. Mostra uptime dos últimos 90 dias por serviço (API, IA, Marketplace, Auth, Storage). Incident log é público. Você pode assinar RSS em /status/feed.xml.',
    tags: ['status', 'transparencia'],
    helpCount: 22,
    notHelpCount: 0,
    trending: false,
    updatedAt: '2026-06-30',
  },

  // ========== ONBOARDING (5) ==========
  {
    id: 'onboarding-tempo',
    category: 'onboarding',
    question: 'Quanto tempo leva o onboarding?',
    answer: 'Onboarding médio: 5-7 minutos. Inclui: 4 telas de boas-vindas, escolha de até 3 tradições de interesse, mapa natal (opcional, pular pra quem não tem dados), escolha de nome espiritual ou username, e 1ª ação sugerida (1min).',
    tags: ['onboarding'],
    helpCount: 38,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'primeira-postagem',
    category: 'onboarding',
    question: 'Como faço minha primeira postagem?',
    answer: 'Em /feed → "Criar post". Você pode escrever texto, adicionar até 4 imagens, marcar até 5 tradições. Akasha sugere hashtags baseado no seu texto. Publicar abre thread em /feed e notifica seguidores. Seja gentil, cite fontes, e divirta-se.',
    tags: ['feed', 'post'],
    helpCount: 47,
    notHelpCount: 2,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'primeira-akasha',
    category: 'onboarding',
    question: 'Como faço minha primeira pergunta pra Akasha?',
    answer: 'Em /akashic ou via botão 💬 no topo. Sugestão de primeira pergunta: "Quem sou eu nessa comunidade? Me conta o que você acha das minhas escolhas de tradição e do meu nome". Akasha responde com leituras e perguntas abertas.',
    tags: ['akasha', 'iniciante'],
    helpCount: 53,
    notHelpCount: 1,
    trending: true,
    updatedAt: '2026-06-30',
  },
  {
    id: 'primeiro-grupo',
    category: 'onboarding',
    question: 'Como entro no meu primeiro grupo?',
    answer: 'Em /groups → filtre por tradição de interesse. Os 3 grupos mais ativos aparecem em "Top da semana". Pedido de entrada é aprovado por moderador do grupo (até 24h). Você pode estar em até 10 grupos simultâneos.',
    tags: ['grupos', 'comunidade'],
    helpCount: 25,
    notHelpCount: 1,
    trending: false,
    updatedAt: '2026-06-30',
  },
  {
    id: 'first-actions',
    category: 'onboarding',
    question: 'Quais são as 5 primeiras ações sugeridas?',
    answer: 'Beta data mostra que essas 5 ações cobrem 80% do que faz alguém voltar: (1) Publicar 1 post. (2) Conversar com Akasha IA. (3) Gerar mapa astral. (4) Ler 1 artigo da biblioteca. (5) Candidatar-se a mentoria. Marcadas em /onboarding/first-actions.',
    tags: ['onboarding'],
    helpCount: 31,
    notHelpCount: 0,
    trending: true,
    updatedAt: '2026-06-30',
  },
];

// ============================================================================
// HELPERS
// ============================================================================

export function getFaqByCategory(cat: FaqCategory): FaqEntry[] {
  return FAQ_ENTRIES.filter((e) => e.category === cat);
}

export function getFaqById(id: string): FaqEntry | undefined {
  return FAQ_ENTRIES.find((e) => e.id === id);
}

export function searchFaq(query: string): FaqEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return FAQ_ENTRIES.filter((e) =>
    e.question.toLowerCase().includes(q) ||
    e.answer.toLowerCase().includes(q) ||
    e.tags.some((t) => t.includes(q)),
  );
}

export function getTrendingFaq(limit = 10): FaqEntry[] {
  return [...FAQ_ENTRIES]
    .filter((e) => e.trending)
    .sort((a, b) => b.helpCount - a.helpCount)
    .slice(0, limit);
}

export function getFaqByTradition(tradition: string): FaqEntry[] {
  return FAQ_ENTRIES.filter((e) => e.relatedTradition === tradition);
}

export function totalFaqCount(): number {
  return FAQ_ENTRIES.length;
}
